<?php
declare(strict_types=1);
require_once __DIR__.'/_layout.php';
$pdo=obtenerConexion();docenteCabecera('Calendario','calendario','Fechas reales de tus clases, tareas y evaluaciones.');$docenteId=(int)$GLOBALS['docentePortalId'];docenteSelectorSupervision($pdo);$eventos=[];
$q=$pdo->prepare("SELECT s.fecha_inicio fecha,'Inicio de clase' tipo,CONCAT(a.nombre,' · ',s.codigo) titulo,s.horario detalle FROM capacitacion_secciones s JOIN asignaturas a ON a.id=s.asignatura_id WHERE s.docente_id=:d AND s.fecha_inicio IS NOT NULL");$q->execute(['d'=>$docenteId]);foreach($q->fetchAll()as$e)$eventos[]=$e;
$q=$pdo->prepare("SELECT c.fecha_limite fecha,'Entrega' tipo,CONCAT(c.titulo,' · ',s.codigo) titulo,a.nombre detalle FROM contenidos c JOIN capacitacion_secciones s ON s.id=c.seccion_id AND s.docente_id=c.docente_id JOIN asignaturas a ON a.id=c.asignatura_id WHERE c.docente_id=:d AND c.fecha_limite IS NOT NULL");$q->execute(['d'=>$docenteId]);foreach($q->fetchAll()as$e)$eventos[]=$e;
$q=$pdo->prepare("SELECT e.fecha_cierre fecha,'Evaluación' tipo,e.titulo,a.nombre detalle FROM evaluaciones e JOIN asignaturas a ON a.id=e.asignatura_id WHERE e.docente_id=:d AND e.fecha_cierre IS NOT NULL");$q->execute(['d'=>$docenteId]);foreach($q->fetchAll()as$e)$eventos[]=$e;
usort($eventos,static fn(array$a,array$b)=>strcmp((string)$a['fecha'],(string)$b['fecha']));
?>
<div class="card card-rounded"><div class="card-body"><div class="d-flex flex-wrap align-items-center justify-content-between gap-2 mb-4"><h2 class="h5 mb-0">Agenda académica</h2><span class="badge bg-primary"><?=count($eventos)?> evento(s)</span></div><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Fecha</th><th>Tipo</th><th>Actividad</th><th>Detalle</th></tr></thead><tbody><?php foreach($eventos as$e):?><tr><td class="text-nowrap"><strong><?=date('d/m/Y',strtotime($e['fecha']))?></strong><?php if(strlen((string)$e['fecha'])>10):?><small class="d-block"><?=date('H:i',strtotime($e['fecha']))?></small><?php endif;?></td><td><span class="badge bg-light text-dark"><?=atenea_e($e['tipo'])?></span></td><td><?=atenea_e($e['titulo'])?></td><td><?=atenea_e((string)($e['detalle']?:'Sin detalle adicional'))?></td></tr><?php endforeach;?><?php if(!$eventos):?><tr><td colspan="4" class="text-center py-5"><i class="mdi mdi-calendar-blank-outline fs-1 text-muted"></i><p class="mb-0 mt-2">No hay fechas académicas registradas.</p></td></tr><?php endif;?></tbody></table></div></div></div>
<?php docentePie();
