<?php
declare(strict_types=1);
require_once __DIR__.'/_layout.php';
require_once dirname(__DIR__,2).'/includes/academico_flujo.php';
$pdo=obtenerConexion();$docenteId=docenteSupervisadoAtenea($pdo);$seccion=docenteId($_GET['seccion']??0);if($seccion)exigirSeccionDocente($pdo,$docenteId,$seccion);docenteCabecera('Calificaciones','calificaciones','Consulta las notas generadas en tus clases y evaluaciones.');docenteSelectorSupervision($pdo);
$q=$pdo->prepare("SELECT s.id,s.codigo,a.nombre capacitacion FROM capacitacion_secciones s JOIN asignaturas a ON a.id=s.asignatura_id WHERE s.docente_id=:d AND s.estado IN('abierta','cerrada') ORDER BY a.nombre,s.codigo");$q->execute(['d'=>$docenteId]);$secciones=$q->fetchAll();
$where='c.docente_id=:d AND s.docente_id=:d2 AND ec.nota IS NOT NULL';$pa=['d'=>$docenteId,'d2'=>$docenteId];if($seccion){$where.=' AND ec.seccion_id=:s';$pa['s']=$seccion;}
$q=$pdo->prepare("SELECT ec.nota,ec.estado,ec.revisado_at,c.titulo,u.nombre,u.apellido,a.nombre capacitacion,s.codigo seccion FROM entregas_contenido ec JOIN contenidos c ON c.id=ec.contenido_id JOIN capacitacion_secciones s ON s.id=ec.seccion_id JOIN asignaturas a ON a.id=ec.asignatura_id JOIN usuarios u ON u.id=ec.estudiante_id WHERE $where ORDER BY COALESCE(ec.revisado_at,ec.updated_at) DESC LIMIT 250");$q->execute($pa);$calificaciones=$q->fetchAll();
$q=$pdo->prepare("SELECT n.nota,e.nota_maxima,e.titulo,u.nombre,u.apellido,a.nombre capacitacion,n.updated_at FROM notas n JOIN evaluaciones e ON e.id=n.evaluacion_id AND e.docente_id=n.docente_id JOIN usuarios u ON u.id=n.estudiante_id JOIN asignaturas a ON a.id=e.asignatura_id WHERE n.docente_id=:d ORDER BY n.updated_at DESC LIMIT 250");$q->execute(['d'=>$docenteId]);$evaluaciones=$q->fetchAll();
?>
<div class="card card-rounded mb-4"><div class="card-body"><form class="row g-2 align-items-end"><input type="hidden" name="docente_id" value="<?=$docenteId?>"><div class="col-md-9"><label class="form-label" for="calificacion-seccion">Sección</label><select class="form-select" id="calificacion-seccion" name="seccion"><option value="">Todas mis secciones</option><?php foreach($secciones as$s):?><option value="<?=$s['id']?>" <?=$seccion===(int)$s['id']?'selected':''?>><?=atenea_e($s['capacitacion'].' · '.$s['codigo'])?></option><?php endforeach;?></select></div><div class="col-md-3"><button class="btn btn-primary w-100">Aplicar filtro</button></div></form></div></div>
<div class="card card-rounded mb-4"><div class="card-body"><h2 class="h5">Notas de tareas</h2><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Estudiante</th><th>Tarea</th><th>Clase</th><th>Nota</th><th>Estado</th><th>Fecha</th></tr></thead><tbody><?php foreach($calificaciones as$c):?><tr><td><?=atenea_e(trim($c['nombre'].' '.$c['apellido']))?></td><td><?=atenea_e($c['titulo'])?></td><td><?=atenea_e($c['capacitacion'].' · '.$c['seccion'])?></td><td><strong><?=number_format((float)$c['nota'],2)?>/10</strong></td><td><?=atenea_e(ucfirst(str_replace('_',' ',$c['estado'])))?></td><td><?=atenea_e($c['revisado_at']?date('d/m/Y H:i',strtotime($c['revisado_at'])):'—')?></td></tr><?php endforeach;?><?php if(!$calificaciones):?><tr><td colspan="6" class="text-center py-5">No hay tareas calificadas para mostrar.</td></tr><?php endif;?></tbody></table></div></div></div>
<div class="card card-rounded"><div class="card-body"><h2 class="h5">Notas de evaluaciones</h2><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Estudiante</th><th>Evaluación</th><th>Curso</th><th>Nota</th><th>Actualización</th></tr></thead><tbody><?php foreach($evaluaciones as$c):?><tr><td><?=atenea_e(trim($c['nombre'].' '.$c['apellido']))?></td><td><?=atenea_e($c['titulo'])?></td><td><?=atenea_e($c['capacitacion'])?></td><td><strong><?=number_format((float)$c['nota'],2)?>/<?=number_format((float)$c['nota_maxima'],2)?></strong></td><td><?=date('d/m/Y H:i',strtotime($c['updated_at']))?></td></tr><?php endforeach;?><?php if(!$evaluaciones):?><tr><td colspan="5" class="text-center py-5">No hay evaluaciones calificadas para mostrar.</td></tr><?php endif;?></tbody></table></div></div></div>
<?php docentePie();
