<?php
declare(strict_types=1);
require_once __DIR__.'/_layout.php';require_once dirname(__DIR__,2).'/includes/contenido_clase.php';
$pdo=obtenerConexion();$id=docenteId($_GET['id']??0);$q=$pdo->prepare('SELECT c.*,a.nombre capacitacion,s.codigo seccion FROM contenidos c JOIN asignaturas a ON a.id=c.asignatura_id JOIN capacitacion_secciones s ON s.id=c.seccion_id WHERE c.id=:id AND c.eliminado_at IS NULL');$q->execute(['id'=>$id]);$c=$q->fetch();if(!$c||!contenidoClasePuedeAdministrar($pdo,$c,(int)$_SESSION['usuario_id'],(string)$_SESSION['usuario_rol']))denegarAccesoDocente('No puedes editar esta publicación.');
$q=$pdo->prepare("SELECT s.id,s.codigo,s.nombre,a.nombre capacitacion FROM capacitacion_secciones s JOIN asignaturas a ON a.id=s.asignatura_id JOIN docentes_asignaturas da ON da.asignatura_id=s.asignatura_id AND da.docente_id=s.docente_id AND da.estado='activo' WHERE s.docente_id=:d AND s.estado IN('abierta','cerrada') ORDER BY a.nombre,s.codigo");$q->execute(['d'=>$c['docente_id']]);$secciones=$q->fetchAll();$tipoRecurso=tipoRecursoDeContenido($c);
docenteCabecera('Editar publicación','contenidos','Actualiza el material sin perder la conversación de la clase.');
?><form class="card card-rounded" method="post" action="<?=docenteUrl('contenido_actualizar.php')?>" enctype="multipart/form-data" data-content-publication-form <?=$c['archivo_relpath']?'data-existing-file="1"':''?>><div class="card-body"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$id?>"><div class="row g-3">
<div class="col-lg-6"><label class="form-label">Clase o asignatura</label><select class="form-select" name="seccion_id" required><?php foreach($secciones as$s):?><option value="<?=$s['id']?>" <?=$c['seccion_id']==$s['id']?'selected':''?>><?=atenea_e($s['capacitacion'].' · '.$s['nombre'].' ('.$s['codigo'].')')?></option><?php endforeach;?></select></div>
<div class="col-lg-6"><label class="form-label">Sesión, unidad o tema</label><input class="form-control" name="modulo" maxlength="120" value="<?=atenea_e($c['modulo'])?>" required></div><div class="col-12"><label class="form-label">Título</label><input class="form-control" name="titulo" maxlength="190" value="<?=atenea_e($c['titulo'])?>" required></div><div class="col-12"><label class="form-label">Texto explicativo</label><textarea class="form-control" name="descripcion" maxlength="10000" rows="5"><?=atenea_e($c['descripcion'])?></textarea></div>
<div class="col-lg-4"><label class="form-label">Tipo de recurso</label><select class="form-select" name="tipo_recurso" data-resource-type><?php foreach(tiposRecursoContenidoClase() as$k=>$v):?><option value="<?=$k?>" <?=$tipoRecurso===$k?'selected':''?>><?=atenea_e($v)?></option><?php endforeach;?></select></div>
<div class="col-lg-8" data-resource-url-wrap><label class="form-label">Enlace externo</label><input class="form-control" type="url" name="recurso_url" maxlength="500" value="<?=atenea_e((string)$c['video_url'])?>"></div><div class="col-lg-8" data-resource-file-wrap><label class="form-label">Reemplazar archivo</label><input class="form-control" type="file" name="archivo"><?php if($c['archivo_nombre']):?><small class="text-muted">Actual: <?=atenea_e((string)$c['archivo_nombre'])?></small><?php endif;?></div>
<div class="col-md-6"><label class="form-label">Fecha de publicación</label><input class="form-control" type="datetime-local" name="fecha_publicacion" value="<?=atenea_e($c['fecha_publicacion']?date('Y-m-d\TH:i',strtotime($c['fecha_publicacion'])):'')?>"></div><div class="col-md-3"><label class="form-label">Estado</label><select class="form-select" name="estado"><option value="borrador" <?=$c['estado']!=='activo'?'selected':''?>>Borrador</option><option value="publicado" <?=$c['estado']==='activo'?'selected':''?>>Publicado</option></select></div><div class="col-md-3 d-flex align-items-end"><button class="btn btn-primary w-100">Guardar cambios</button></div></div><div class="mt-4"><a class="btn btn-light" href="<?=docenteUrl('contenidos.php',['seccion'=>$c['seccion_id']])?>">Cancelar</a> <a class="btn btn-outline-primary" href="<?=docenteUrl('contenido-vista.php',['id'=>$id])?>">Ver publicación</a></div></div></form><script src="<?=atenea_url('src/docente/assets/js/contenido-clase-form.js')?>" defer></script><?php docentePie();
