<?php
declare(strict_types=1);
require_once __DIR__.'/_layout.php';require_once dirname(__DIR__,2).'/includes/contenido_clase.php';
$pdo=obtenerConexion();$docenteId=docenteSupervisadoAtenea($pdo);$seccion=docenteId($_GET['seccion']??0);if($seccion)exigirSeccionDocente($pdo,$docenteId,$seccion);
$buscar=trim((string)($_GET['q']??''));$estado=in_array($_GET['estado']??'', ['borrador','activo'],true)?(string)$_GET['estado']:'';$pagina=max(1,(int)($_GET['pagina']??1));$limite=10;
docenteCabecera('Contenido de clase','contenidos','Publica materiales y conversa con estudiantes de tus clases asignadas.');docenteSelectorSupervision($pdo);
$q=$pdo->prepare("SELECT s.id,s.codigo,s.nombre seccion,a.nombre capacitacion,a.id asignatura_id FROM capacitacion_secciones s JOIN asignaturas a ON a.id=s.asignatura_id JOIN docentes_asignaturas da ON da.asignatura_id=s.asignatura_id AND da.docente_id=s.docente_id AND da.estado='activo' WHERE s.docente_id=:d AND s.estado IN('abierta','cerrada') ORDER BY a.nombre,s.codigo");$q->execute(['d'=>$docenteId]);$secciones=$q->fetchAll();
$where=["c.docente_id=:d","c.eliminado_at IS NULL","EXISTS(SELECT 1 FROM capacitacion_secciones sx JOIN docentes_asignaturas dax ON dax.asignatura_id=sx.asignatura_id AND dax.docente_id=sx.docente_id AND dax.estado='activo' WHERE sx.id=c.seccion_id AND sx.docente_id=c.docente_id)"];$params=['d'=>$docenteId];if($seccion){$where[]='c.seccion_id=:s';$params['s']=$seccion;}if($estado){$where[]='c.estado=:estado';$params['estado']=$estado;}if($buscar!==''){$where[]='(c.titulo LIKE :buscar OR c.descripcion LIKE :buscar OR c.modulo LIKE :buscar)';$params['buscar']='%'.$buscar.'%';}$filtro=implode(' AND ',$where);
$q=$pdo->prepare("SELECT COUNT(*) FROM contenidos c WHERE $filtro");$q->execute($params);$total=(int)$q->fetchColumn();$paginas=max(1,(int)ceil($total/$limite));if($pagina>$paginas)$pagina=$paginas;
$sql="SELECT c.*,a.nombre capacitacion,s.codigo seccion,s.nombre seccion_nombre,CONCAT_WS(' ',u.nombre,u.apellido) docente,(SELECT COUNT(*) FROM contenido_comentarios cc WHERE cc.contenido_id=c.id AND cc.estado='visible') comentarios FROM contenidos c JOIN asignaturas a ON a.id=c.asignatura_id JOIN capacitacion_secciones s ON s.id=c.seccion_id JOIN usuarios u ON u.id=c.docente_id WHERE $filtro ORDER BY COALESCE(c.fecha_publicacion,c.created_at) DESC,c.id DESC LIMIT :lim OFFSET :off";$q=$pdo->prepare($sql);foreach($params as$k=>$v)$q->bindValue(':'.$k,$v);$q->bindValue(':lim',$limite,PDO::PARAM_INT);$q->bindValue(':off',($pagina-1)*$limite,PDO::PARAM_INT);$q->execute();$filas=$q->fetchAll();
$videoMax=limiteArchivoAcademicoMb('video');$docMax=limiteArchivoAcademicoMb('contenido');
?>
<?php if($secciones):?>
<div class="card card-rounded mb-4"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 mb-1">Crear publicación</h2><p class="text-muted mb-0">Solo aparecerá en la clase seleccionada.</p></div><i class="mdi mdi-post-outline fs-2 text-primary"></i></div>
<form method="post" action="<?=docenteUrl('contenido_guardar.php')?>" enctype="multipart/form-data" class="row g-3" data-content-publication-form><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="docente_id" value="<?=$docenteId?>">
<div class="col-lg-6"><label class="form-label" for="contenidoSeccion">Clase o asignatura *</label><select class="form-select" id="contenidoSeccion" name="seccion_id" required><?php foreach($secciones as$s):?><option value="<?=$s['id']?>" <?=$seccion===$s['id']?'selected':''?>><?=atenea_e($s['capacitacion'].' · '.$s['seccion'].' ('.$s['codigo'].')')?></option><?php endforeach;?></select></div>
<div class="col-lg-6"><label class="form-label" for="contenidoModulo">Sesión, unidad o tema *</label><input class="form-control" id="contenidoModulo" name="modulo" maxlength="120" placeholder="Ej. Unidad 2 · Plantas medicinales" required></div>
<div class="col-12"><label class="form-label" for="contenidoTitulo">Título *</label><input class="form-control" id="contenidoTitulo" name="titulo" minlength="2" maxlength="190" required></div>
<div class="col-12"><label class="form-label" for="contenidoDescripcion">Texto explicativo</label><textarea class="form-control" id="contenidoDescripcion" name="descripcion" maxlength="10000" rows="4" placeholder="Explica el objetivo del material y las indicaciones para la clase."></textarea></div>
<div class="col-lg-4"><label class="form-label" for="contenidoTipoRecurso">Tipo de recurso *</label><select class="form-select" id="contenidoTipoRecurso" name="tipo_recurso" data-resource-type><?php foreach(tiposRecursoContenidoClase() as$k=>$v):?><option value="<?=$k?>"><?=atenea_e($v)?></option><?php endforeach;?></select></div>
<div class="col-lg-8" data-resource-url-wrap hidden><label class="form-label" for="contenidoUrl">Enlace externo</label><input class="form-control" id="contenidoUrl" type="url" name="recurso_url" maxlength="500" placeholder="https://..."><small class="text-muted">YouTube y Drive se muestran en una vista segura; otros sitios se abren en una pestaña nueva.</small></div>
<div class="col-lg-8" data-resource-file-wrap hidden><label class="form-label" for="contenidoArchivo">Archivo</label><input class="form-control" id="contenidoArchivo" type="file" name="archivo" accept=".mp4,.webm,.ogv,.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.jpg,.jpeg,.png,.webp,.txt"><small class="text-muted">Videos: máximo <?=$videoMax?> MB. Documentos: máximo <?=$docMax?> MB. El tipo MIME real será verificado.</small></div>
<div class="col-md-6"><label class="form-label" for="contenidoFecha">Fecha de publicación</label><input class="form-control" id="contenidoFecha" type="datetime-local" name="fecha_publicacion"><small class="text-muted">Déjala vacía para publicar inmediatamente.</small></div>
<div class="col-md-3"><label class="form-label" for="contenidoEstado">Estado</label><select class="form-select" id="contenidoEstado" name="estado"><option value="borrador">Borrador</option><option value="publicado">Publicado</option></select></div>
<div class="col-md-3 d-flex align-items-end"><button class="btn btn-primary w-100"><i class="mdi mdi-send me-1"></i>Guardar publicación</button></div></form></div></div>
<?php else:?><div class="card card-rounded mb-4"><div class="card-body text-center py-5"><i class="mdi mdi-book-lock-outline display-4 text-primary"></i><h2 class="h5 mt-3">Sin clases asignadas</h2><p class="text-muted mb-0">Necesitas una sección activa asignada para publicar contenido.</p></div></div><?php endif;?>

<div class="card card-rounded mb-4"><div class="card-body"><form class="row g-2 align-items-end" method="get"><input type="hidden" name="docente_id" value="<?=$docenteId?>"><div class="col-lg-5"><label class="form-label" for="buscarPublicacion">Buscar</label><input class="form-control" id="buscarPublicacion" type="search" name="q" maxlength="100" value="<?=atenea_e($buscar)?>" placeholder="Título, texto o unidad"></div><div class="col-lg-4"><label class="form-label">Clase</label><select class="form-select" name="seccion"><option value="">Todas mis clases</option><?php foreach($secciones as$s):?><option value="<?=$s['id']?>" <?=$seccion===$s['id']?'selected':''?>><?=atenea_e($s['capacitacion'].' · '.$s['codigo'])?></option><?php endforeach;?></select></div><div class="col-lg-2"><label class="form-label">Estado</label><select class="form-select" name="estado"><option value="">Todos</option><option value="activo" <?=$estado==='activo'?'selected':''?>>Publicado</option><option value="borrador" <?=$estado==='borrador'?'selected':''?>>Borrador</option></select></div><div class="col-lg-1"><button class="btn btn-outline-primary w-100" aria-label="Filtrar"><i class="mdi mdi-filter"></i></button></div></form></div></div>

<div class="d-grid gap-3" data-content-feed><?php foreach($filas as$c):?><article class="card card-rounded"><div class="card-body"><div class="d-flex flex-wrap justify-content-between gap-3"><div class="d-flex gap-3"><div class="bg-light rounded-circle d-flex align-items-center justify-content-center" style="width:48px;height:48px"><i class="mdi mdi-book-open-page-variant fs-4 text-primary"></i></div><div><div class="d-flex flex-wrap gap-2 align-items-center"><h2 class="h5 mb-0"><?=atenea_e($c['titulo'])?></h2><span class="badge <?=$c['estado']==='activo'?'bg-success':'bg-warning text-dark'?>"><?=$c['estado']==='activo'?'Publicado':'Borrador'?></span></div><p class="text-muted small mb-0"><?=atenea_e($c['docente'].' · '.$c['capacitacion'].' · '.$c['seccion'])?></p><small class="text-muted"><?=date('d/m/Y h:i A',strtotime((string)($c['fecha_publicacion']?:$c['created_at'])))?> · <?=atenea_e($c['modulo'])?></small></div></div><div class="dropdown"><button class="btn btn-light btn-sm" data-bs-toggle="dropdown" aria-label="Acciones"><i class="mdi mdi-dots-vertical"></i></button><div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item" href="<?=docenteUrl('contenido-vista.php',['id'=>$c['id']])?>">Ver como estudiante</a><a class="dropdown-item" href="<?=docenteUrl('contenido_editar.php',['id'=>$c['id']])?>">Editar</a><form method="post" action="<?=docenteUrl('contenido_estado.php')?>"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$c['id']?>"><input type="hidden" name="accion" value="<?=$c['estado']==='activo'?'borrador':'publicar'?>"><button class="dropdown-item"><?=$c['estado']==='activo'?'Pasar a borrador':'Publicar'?></button></form><form method="post" action="<?=docenteUrl('contenido_estado.php')?>" data-atenea-confirm="danger" data-atenea-confirm-title="Eliminar publicación" data-atenea-confirm-message="La publicación y su conversación dejarán de estar disponibles para la clase." data-atenea-confirm-text="Sí, eliminar"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$c['id']?>"><input type="hidden" name="accion" value="eliminar"><button class="dropdown-item text-danger" data-atenea-confirm="danger">Eliminar</button></form></div></div></div><?php if($c['descripcion']):?><p class="mt-3 mb-3"><?=nl2br(atenea_e(mb_strimwidth((string)$c['descripcion'],0,700,'…')))?></p><?php endif;?><div class="mb-3"><?php renderizarRecursoContenidoClase($c);?></div><div class="border-top pt-3 d-flex justify-content-between align-items-center"><span class="text-muted"><i class="mdi mdi-comment-outline me-1"></i><?=(int)$c['comentarios']?> comentarios</span><a class="btn btn-sm btn-outline-primary" href="<?=docenteUrl('contenido-vista.php',['id'=>$c['id']])?>">Abrir publicación</a></div></div></article><?php endforeach;?>
<?php if(!$filas):?><div class="card card-rounded"><div class="card-body text-center py-5"><i class="mdi mdi-post-outline display-4 text-primary"></i><h2 class="h5 mt-3">No hay publicaciones</h2><p class="text-muted mb-0">Crea la primera publicación o cambia los filtros de búsqueda.</p></div></div><?php endif;?></div>
<?php if($paginas>1):?><nav class="mt-4" aria-label="Páginas de publicaciones"><ul class="pagination justify-content-end"><?php for($i=1;$i<=$paginas;$i++):?><li class="page-item <?=$i===$pagina?'active':''?>"><a class="page-link" href="?<?=atenea_e(http_build_query(['docente_id'=>$docenteId,'seccion'=>$seccion,'estado'=>$estado,'q'=>$buscar,'pagina'=>$i]))?>"><?=$i?></a></li><?php endfor;?></ul></nav><?php endif;?>
<script src="<?=atenea_url('src/docente/assets/js/contenido-clase-form.js')?>" defer></script>
<?php docentePie();
