<?php
declare(strict_types=1);
require_once __DIR__.'/_layout.php';
require_once dirname(__DIR__,2).'/includes/academico_flujo.php';
$pdo=obtenerConexion();$docenteId=docenteSupervisadoAtenea($pdo);
$seccion=docenteId($_GET['seccion']??0);if($seccion)exigirSeccionDocente($pdo,$docenteId,$seccion);
docenteCabecera('Tareas','tareas','Actividades asignadas únicamente en tus secciones.');docenteSelectorSupervision($pdo);
$q=$pdo->prepare("SELECT s.id,s.codigo,a.nombre capacitacion FROM capacitacion_secciones s JOIN asignaturas a ON a.id=s.asignatura_id WHERE s.docente_id=:d AND s.estado IN('abierta','cerrada') ORDER BY a.nombre,s.codigo");$q->execute(['d'=>$docenteId]);$secciones=$q->fetchAll();
$where="c.docente_id=:d AND s.docente_id=:d2 AND c.tipo IN('actividad','evaluacion')";$pa=['d'=>$docenteId,'d2'=>$docenteId];if($seccion){$where.=' AND c.seccion_id=:s';$pa['s']=$seccion;}
$q=$pdo->prepare("SELECT c.id,c.titulo,c.modulo,c.tipo,c.estado,c.fecha_publicacion,c.fecha_limite,a.nombre capacitacion,s.codigo seccion,COUNT(ec.id) entregas,SUM(ec.estado IN('enviada','en_revision')) por_revisar FROM contenidos c JOIN capacitacion_secciones s ON s.id=c.seccion_id JOIN asignaturas a ON a.id=c.asignatura_id LEFT JOIN entregas_contenido ec ON ec.contenido_id=c.id WHERE $where GROUP BY c.id ORDER BY COALESCE(c.fecha_limite,'9999-12-31'),c.id DESC");$q->execute($pa);$tareas=$q->fetchAll();
?>
<div class="card card-rounded mb-4"><div class="card-body"><form class="row g-2 align-items-end"><input type="hidden" name="docente_id" value="<?=$docenteId?>"><div class="col-md-9"><label class="form-label" for="filtro-seccion">Sección</label><select class="form-select" id="filtro-seccion" name="seccion"><option value="">Todas mis secciones</option><?php foreach($secciones as$s):?><option value="<?=$s['id']?>" <?=$seccion===(int)$s['id']?'selected':''?>><?=atenea_e($s['capacitacion'].' · '.$s['codigo'])?></option><?php endforeach;?></select></div><div class="col-md-3"><button class="btn btn-primary w-100">Filtrar tareas</button></div></form></div></div>
<div class="card card-rounded"><div class="card-body"><div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><h2 class="h5 mb-0">Tareas de tus clases</h2><a class="btn btn-sm btn-outline-primary" href="<?=docenteUrl('contenidos.php')?>">Crear desde Contenidos</a></div><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Tarea</th><th>Clase</th><th>Fechas</th><th>Estado</th><th>Entregas</th><th>Acción</th></tr></thead><tbody><?php foreach($tareas as$t):?><tr><td><strong><?=atenea_e($t['titulo'])?></strong><small class="d-block text-muted"><?=atenea_e($t['modulo'].' · '.$t['tipo'])?></small></td><td><?=atenea_e($t['capacitacion'].' · '.$t['seccion'])?></td><td><small>Publicación: <?=atenea_e($t['fecha_publicacion']?date('d/m/Y H:i',strtotime($t['fecha_publicacion'])):'Inmediata')?></small><small class="d-block">Límite: <?=atenea_e($t['fecha_limite']?date('d/m/Y H:i',strtotime($t['fecha_limite'])):'Sin límite')?></small></td><td><?=atenea_e(ucfirst($t['estado']))?></td><td><?=(int)$t['entregas']?> <small class="d-block text-muted"><?=(int)$t['por_revisar']?> por revisar</small></td><td><a class="btn btn-sm btn-outline-primary" href="<?=docenteUrl('entregas.php',['contenido'=>$t['id']])?>">Revisar</a></td></tr><?php endforeach;?><?php if(!$tareas):?><tr><td colspan="6" class="text-center py-5"><i class="mdi mdi-clipboard-text-off-outline fs-1 text-muted"></i><p class="mb-0 mt-2">No hay tareas en las secciones seleccionadas.</p></td></tr><?php endif;?></tbody></table></div></div></div>
<?php docentePie();
