<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';
$pdo=obtenerConexion();
$id=cmsId($_GET['id']??$_POST['id']??0);
$producto=['nombre'=>'','sku'=>'','descripcion_corta'=>'','descripcion'=>'','precio'=>'0.00','stock'=>0,'stock_reservado'=>0,'stock_minimo'=>0,'disponible'=>1,'activo'=>1,'imagen_principal'=>'','categoria_id'=>null];
if($id){$q=$pdo->prepare('SELECT * FROM productos WHERE id=:id AND eliminado_at IS NULL LIMIT 1');$q->execute(['id'=>$id]);$producto=$q->fetch()?:[];if(!$producto){cmsFlash('error','Producto no encontrado.');header('Location:index.php');exit;}}
$categoriaOriginal=(int)($producto['categoria_id']??0);
$q=$pdo->prepare('SELECT id,nombre,activo FROM categorias_producto WHERE eliminado_at IS NULL AND (activo=1 OR id=:actual) ORDER BY nombre');$q->execute(['actual'=>$categoriaOriginal]);$categorias=$q->fetchAll();
$hayCategoriasActivas=(bool)$pdo->query('SELECT id FROM categorias_producto WHERE activo=1 AND eliminado_at IS NULL LIMIT 1')->fetch();
$errores=[];$nuevaImagen=null;$galeria=[];
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    $nombre=trim(strip_tags((string)($_POST['nombre']??'')));
    $sku=trim((string)($_POST['sku']??''));
    $descripcionCorta=trim(strip_tags((string)($_POST['descripcion_corta']??'')));
    $descripcion=trim(strip_tags((string)($_POST['descripcion']??'')));
    $precio=filter_var($_POST['precio']??null,FILTER_VALIDATE_FLOAT);
    $stock=filter_var($_POST['stock']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>0]]);
    $stockMinimo=filter_var($_POST['stock_minimo']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>0]]);
    $categoriaId=cmsId($_POST['categoria_id']??0);
    $disponible=isset($_POST['disponible'])?1:0;$activo=isset($_POST['activo'])?1:0;
    if(!validarTokenCsrf(isset($_POST['csrf_token'])?(string)$_POST['csrf_token']:null))$errores[]='La solicitud expiró. Intenta nuevamente.';
    if($nombre===''||mb_strlen($nombre)>180)$errores[]='El nombre es obligatorio y no puede superar 180 caracteres.';
    if($sku!==''&&mb_strlen($sku)>80)$errores[]='El SKU no puede superar 80 caracteres.';
    if($descripcionCorta===''||mb_strlen($descripcionCorta)>500||$descripcion===''||mb_strlen($descripcion)>10000)$errores[]='Completa las descripciones respetando las longitudes permitidas.';
    if($precio===false||$precio<0)$errores[]='Ingresa un precio válido.';
    if($stock===false||$stockMinimo===false)$errores[]='Ingresa valores de inventario válidos.';
    if($stock!==false&&(int)$stock<(int)($producto['stock_reservado']??0))$errores[]='El stock no puede ser menor que las unidades reservadas.';
    if(!$categoriaId)$errores[]='Selecciona una categoría. Primero debes crear una categoría si la lista está vacía.';
    else{$q=$pdo->prepare('SELECT activo FROM categorias_producto WHERE id=:id AND eliminado_at IS NULL LIMIT 1');$q->execute(['id'=>$categoriaId]);$categoriaActiva=$q->fetchColumn();if($categoriaActiva===false||(!(bool)$categoriaActiva&&$categoriaId!==$categoriaOriginal))$errores[]='La categoría seleccionada no existe o no está activa.';}
    $promocionActiva=isset($_POST['promo_activa']);
    $precioPromocional=filter_var($_POST['precio_promocional']??null,FILTER_VALIDATE_FLOAT);
    $inicio=str_replace('T',' ',trim((string)($_POST['promo_inicio']??'')));
    $fin=str_replace('T',' ',trim((string)($_POST['promo_fin']??'')));
    if($promocionActiva&&($precioPromocional===false||$precioPromocional<0||$precio===false||$precioPromocional>=$precio||!strtotime($inicio)||!strtotime($fin)||strtotime($fin)<=strtotime($inicio)))$errores[]='La promoción requiere un precio menor al normal y un período válido.';
    $imagen=(string)($producto['imagen_principal']??'');
    if(!$errores){try{$nuevaImagen=cmsSubirImagen('imagen_principal');if($nuevaImagen)$imagen=$nuevaImagen;$galeria=cmsSubirGaleria('galeria');}catch(RuntimeException$e){if($nuevaImagen)cmsEliminarImagenSiNoSeUsa($nuevaImagen);$nuevaImagen=null;$imagen=(string)($producto['imagen_principal']??'');$errores[]=$e->getMessage();}}
    if(!$errores){
        try{
            $pdo->beginTransaction();
            if($id){$q=$pdo->prepare('UPDATE productos SET categoria_id=:categoria,sku=:sku,nombre=:nombre,descripcion_corta=:corta,descripcion=:descripcion,precio=:precio,stock=:stock,stock_minimo=:minimo,disponible=:disponible,activo=:activo,imagen_principal=:imagen,actualizado_por=:admin WHERE id=:id AND eliminado_at IS NULL');$q->execute(['categoria'=>$categoriaId,'sku'=>$sku?:null,'nombre'=>$nombre,'corta'=>$descripcionCorta,'descripcion'=>$descripcion,'precio'=>$precio,'stock'=>$stock,'minimo'=>$stockMinimo,'disponible'=>$disponible,'activo'=>$activo,'imagen'=>$imagen?:null,'admin'=>$_SESSION['usuario_id'],'id'=>$id]);}
            else{$base=strtolower(trim((string)preg_replace('/[^a-z0-9]+/','-',iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$nombre)?:$nombre),'-'));$slug=mb_substr($base?:'producto',0,185).'-'.bin2hex(random_bytes(4));$q=$pdo->prepare('INSERT INTO productos(categoria_id,sku,nombre,slug,descripcion_corta,descripcion,precio,stock,stock_minimo,disponible,activo,imagen_principal,creado_por,actualizado_por) VALUES(:categoria,:sku,:nombre,:slug,:corta,:descripcion,:precio,:stock,:minimo,:disponible,:activo,:imagen,:creado,:actualizado)');$q->execute(['categoria'=>$categoriaId,'sku'=>$sku?:null,'nombre'=>$nombre,'slug'=>$slug,'corta'=>$descripcionCorta,'descripcion'=>$descripcion,'precio'=>$precio,'stock'=>$stock,'minimo'=>$stockMinimo,'disponible'=>$disponible,'activo'=>$activo,'imagen'=>$imagen?:null,'creado'=>$_SESSION['usuario_id'],'actualizado'=>$_SESSION['usuario_id']]);$id=(int)$pdo->lastInsertId();}
            foreach($galeria as$orden=>$ruta){$q=$pdo->prepare('INSERT INTO producto_imagenes(producto_id,ruta,orden) VALUES(:producto,:ruta,:orden)');$q->execute(['producto'=>$id,'ruta'=>$ruta,'orden'=>$orden]);}
            $pdo->prepare('UPDATE promociones SET activa=0,actualizado_por=:admin WHERE producto_id=:producto AND activa=1')->execute(['admin'=>$_SESSION['usuario_id'],'producto'=>$id]);
            if($promocionActiva){$porcentaje=round((1-(float)$precioPromocional/(float)$precio)*100,2);$q=$pdo->prepare('INSERT INTO promociones(producto_id,etiqueta,precio_promocional,porcentaje_descuento,fecha_inicio,fecha_fin,activa,creado_por,actualizado_por) VALUES(:producto,:etiqueta,:precio,:porcentaje,:inicio,:fin,1,:creado,:actualizado)');$q->execute(['producto'=>$id,'etiqueta'=>trim(strip_tags((string)($_POST['promo_etiqueta']??'')))?:null,'precio'=>$precioPromocional,'porcentaje'=>$porcentaje,'inicio'=>$inicio,'fin'=>$fin,'creado'=>$_SESSION['usuario_id'],'actualizado'=>$_SESSION['usuario_id']]);}
            if((int)($producto['stock']??0)!==(int)$stock){$q=$pdo->prepare("INSERT INTO inventario_movimientos(producto_id,usuario_admin_id,tipo,cantidad,stock_anterior,stock_nuevo,nota) VALUES(:producto,:admin,'ajuste',:cantidad,:anterior,:nuevo,'Ajuste desde edición de producto')");$q->execute(['producto'=>$id,'admin'=>$_SESSION['usuario_id'],'cantidad'=>(int)$stock-(int)($producto['stock']??0),'anterior'=>(int)($producto['stock']??0),'nuevo'=>(int)$stock]);}
            $pdo->commit();
            if($nuevaImagen&&!empty($producto['imagen_principal']))cmsEliminarImagenSiNoSeUsa((string)$producto['imagen_principal']);
            cmsFlash('exito','Producto guardado correctamente.');header('Location:index.php');exit;
        }catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();if($nuevaImagen)cmsEliminarImagenSiNoSeUsa($nuevaImagen);foreach($galeria as$ruta)cmsEliminarImagenSiNoSeUsa($ruta);error_log('Guardar producto Atenea: '.$e->getMessage());$errores[]='No fue posible guardar el producto. Verifica que el SKU sea único y que los datos sean válidos.';}
    }
    $producto=array_merge($producto,['nombre'=>$nombre,'sku'=>$sku,'descripcion_corta'=>$descripcionCorta,'descripcion'=>$descripcion,'precio'=>$precio===false?'':$precio,'stock'=>$stock===false?'':$stock,'stock_minimo'=>$stockMinimo===false?'':$stockMinimo,'disponible'=>$disponible,'activo'=>$activo,'categoria_id'=>$categoriaId,'imagen_principal'=>$imagen]);
}
$promocion=null;$imagenes=[];
if($id){$q=$pdo->prepare('SELECT * FROM promociones WHERE producto_id=:producto ORDER BY id DESC LIMIT 1');$q->execute(['producto'=>$id]);$promocion=$q->fetch();$q=$pdo->prepare('SELECT * FROM producto_imagenes WHERE producto_id=:producto ORDER BY orden,id');$q->execute(['producto'=>$id]);$imagenes=$q->fetchAll();}
cmsCabecera($id?'Editar producto':'Nuevo producto','productos/editar.php','Completa la información comercial, inventario, imágenes y promoción del producto.');
?>
<?php foreach($errores as$error):?><div class="alert alert-danger"><?=atenea_e($error)?></div><?php endforeach;?>
<?php if(!$hayCategoriasActivas):?><div class="alert alert-warning d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-2"><span>Primero debes crear una categoría activa para guardar productos.</span><a class="btn btn-sm btn-warning" href="<?=atenea_url('src/dashboard/categorias/editar.php')?>">Crear categoría</a></div><?php endif;?>
<form method="post" enctype="multipart/form-data" class="card card-rounded"><div class="card-body row g-3"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$id?>">
  <div class="col-md-8"><label class="form-label" for="nombreProducto">Nombre *</label><input class="form-control" id="nombreProducto" name="nombre" maxlength="180" value="<?=atenea_e((string)$producto['nombre'])?>" required></div><div class="col-md-4"><label class="form-label" for="skuProducto">SKU</label><input class="form-control" id="skuProducto" name="sku" maxlength="80" value="<?=atenea_e((string)$producto['sku'])?>"></div>
  <div class="col-md-6"><div class="d-flex justify-content-between align-items-center"><label class="form-label" for="categoriaProducto">Categoría *</label><a class="small" href="<?=atenea_url('src/dashboard/categorias/index.php')?>">Administrar categorías</a></div><select class="form-select" id="categoriaProducto" name="categoria_id" required><option value="">Selecciona una categoría</option><?php foreach($categorias as$categoria):?><option value="<?=(int)$categoria['id']?>" <?=(int)$producto['categoria_id']===(int)$categoria['id']?'selected':''?>><?=atenea_e((string)$categoria['nombre'])?><?=$categoria['activo']?'':' (inactiva actual)'?></option><?php endforeach;?></select><?php if(!$categorias):?><div class="form-text text-danger">Primero debes crear una categoría.</div><?php endif;?></div><div class="col-md-6"><label class="form-label" for="precioProducto">Precio *</label><input class="form-control" id="precioProducto" type="number" step="0.01" min="0" name="precio" value="<?=atenea_e((string)$producto['precio'])?>" required></div>
  <div class="col-12"><label class="form-label" for="descripcionCorta">Descripción corta *</label><input class="form-control" id="descripcionCorta" name="descripcion_corta" maxlength="500" value="<?=atenea_e((string)$producto['descripcion_corta'])?>" required></div><div class="col-12"><label class="form-label" for="descripcionProducto">Descripción completa *</label><textarea class="form-control" id="descripcionProducto" rows="5" name="descripcion" maxlength="10000" required><?=atenea_e((string)$producto['descripcion'])?></textarea></div>
  <div class="col-md-4"><label class="form-label" for="stockProducto">Stock</label><input class="form-control" id="stockProducto" type="number" min="<?=(int)$producto['stock_reservado']?>" name="stock" value="<?=atenea_e((string)$producto['stock'])?>"></div><div class="col-md-4"><label class="form-label" for="stockMinimo">Stock mínimo</label><input class="form-control" id="stockMinimo" type="number" min="0" name="stock_minimo" value="<?=atenea_e((string)$producto['stock_minimo'])?>"></div><div class="col-md-4 d-flex align-items-end gap-3"><div class="form-check form-switch mb-2"><input class="form-check-input" id="productoDisponible" type="checkbox" name="disponible" <?=$producto['disponible']?'checked':''?>><label class="form-check-label" for="productoDisponible">Disponible</label></div><div class="form-check form-switch mb-2"><input class="form-check-input" id="productoActivo" type="checkbox" name="activo" <?=$producto['activo']?'checked':''?>><label class="form-check-label" for="productoActivo">Activo</label></div></div>
  <div class="col-md-6"><label class="form-label" for="imagenPrincipal">Imagen principal</label><input class="form-control" id="imagenPrincipal" type="file" name="imagen_principal" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp"></div><div class="col-md-6"><label class="form-label" for="galeriaProducto">Galería</label><input class="form-control" id="galeriaProducto" type="file" name="galeria[]" multiple accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp"></div>
  <div class="col-12"><hr><h2 class="h5">Promoción</h2></div><div class="col-md-2"><div class="form-check form-switch"><input class="form-check-input" id="promocionActiva" type="checkbox" name="promo_activa" <?=$promocion&&$promocion['activa']?'checked':''?>><label class="form-check-label" for="promocionActiva">Activa</label></div></div><div class="col-md-3"><label class="visually-hidden" for="etiquetaPromocion">Etiqueta</label><input class="form-control" id="etiquetaPromocion" name="promo_etiqueta" maxlength="100" placeholder="Etiqueta" value="<?=atenea_e((string)($promocion['etiqueta']??''))?>"></div><div class="col-md-2"><label class="visually-hidden" for="precioOferta">Precio de oferta</label><input class="form-control" id="precioOferta" type="number" min="0" step="0.01" name="precio_promocional" placeholder="Precio oferta" value="<?=atenea_e((string)($promocion['precio_promocional']??''))?>"></div><div class="col-md-2"><label class="visually-hidden" for="inicioPromocion">Inicio</label><input class="form-control" id="inicioPromocion" type="datetime-local" name="promo_inicio" value="<?=$promocion?date('Y-m-d\TH:i',strtotime((string)$promocion['fecha_inicio'])):''?>"></div><div class="col-md-3"><label class="visually-hidden" for="finPromocion">Fin</label><input class="form-control" id="finPromocion" type="datetime-local" name="promo_fin" value="<?=$promocion?date('Y-m-d\TH:i',strtotime((string)$promocion['fecha_fin'])):''?>"></div>
  <?php if($imagenes):?><div class="col-12 d-flex gap-3 flex-wrap"><?php foreach($imagenes as$imagenGaleria):?><div class="text-center"><img class="preview-img d-block mb-2" src="<?=rutaImagenContenido((string)$imagenGaleria['ruta'])?>" alt="Imagen de galería"><button class="btn btn-sm btn-outline-danger" type="submit" form="borrar-imagen-<?=(int)$imagenGaleria['id']?>">Eliminar</button></div><?php endforeach;?></div><?php endif;?><div class="col-12"><a class="btn btn-light" href="index.php">Cancelar</a> <button class="btn btn-primary text-white" type="submit" <?=!$hayCategoriasActivas&&!$categoriaOriginal?'disabled':''?>>Guardar producto</button></div>
</div></form>
<?php foreach($imagenes as$imagenGaleria):?><form id="borrar-imagen-<?=(int)$imagenGaleria['id']?>" method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=(int)$imagenGaleria['id']?>"><input type="hidden" name="producto_id" value="<?=$id?>"><input type="hidden" name="accion" value="eliminar_imagen"></form><?php endforeach;?>
<?php cmsPie(); ?>
