<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';
$pdo=obtenerConexion();
$buscar=trim((string)($_GET['q']??''));
$estado=in_array($_GET['estado']??'', ['activo','inactivo','agotado','bajo'],true)?(string)$_GET['estado']:'';
$categoriaId=cmsId($_GET['categoria_id']??0);
$pagina=max(1,cmsId($_GET['pagina']??1));$porPagina=10;
$where=['p.eliminado_at IS NULL'];$parametros=[];
if($buscar!==''){$where[]='(p.nombre LIKE :buscar_nombre OR p.sku LIKE :buscar_sku)';$parametros['buscar_nombre']='%'.$buscar.'%';$parametros['buscar_sku']='%'.$buscar.'%';}
if($estado==='activo')$where[]='p.activo=1';elseif($estado==='inactivo')$where[]='p.activo=0';elseif($estado==='agotado')$where[]='p.stock<=p.stock_reservado';elseif($estado==='bajo')$where[]='p.stock<=p.stock_minimo';
if($categoriaId){$where[]='p.categoria_id=:categoria';$parametros['categoria']=$categoriaId;}
$whereSql=implode(' AND ',$where);
$q=$pdo->prepare("SELECT COUNT(*) FROM productos p WHERE {$whereSql}");$q->execute($parametros);$total=(int)$q->fetchColumn();$paginas=max(1,(int)ceil($total/$porPagina));$pagina=min($pagina,$paginas);$offset=($pagina-1)*$porPagina;
$q=$pdo->prepare("SELECT p.*,c.nombre categoria,c.activo categoria_activa FROM productos p LEFT JOIN categorias_producto c ON c.id=p.categoria_id WHERE {$whereSql} ORDER BY p.updated_at DESC,p.id DESC LIMIT :limite OFFSET :offset");foreach($parametros as$clave=>$valor)$q->bindValue($clave,$valor);$q->bindValue('limite',$porPagina,PDO::PARAM_INT);$q->bindValue('offset',$offset,PDO::PARAM_INT);$q->execute();$filas=$q->fetchAll();
$categorias=$pdo->query('SELECT id,nombre,activo FROM categorias_producto WHERE eliminado_at IS NULL ORDER BY nombre')->fetchAll();
cmsCabecera('Productos','productos/index.php','Administra catálogo, promociones e inventario con los componentes de StarAdmin.');
?>
<div class="card card-rounded"><div class="card-body">
  <div class="d-flex flex-column flex-xl-row justify-content-between align-items-xl-center gap-3 mb-4">
    <form class="row g-2 flex-grow-1" method="get"><div class="col-md-4"><label class="visually-hidden" for="buscarProducto">Buscar</label><input class="form-control" id="buscarProducto" name="q" value="<?=atenea_e($buscar)?>" placeholder="Buscar nombre o SKU"></div><div class="col-md-3"><label class="visually-hidden" for="categoriaProducto">Categoría</label><select class="form-select" id="categoriaProducto" name="categoria_id"><option value="">Todas las categorías</option><?php foreach($categorias as$categoria):?><option value="<?=(int)$categoria['id']?>" <?=$categoriaId===(int)$categoria['id']?'selected':''?>><?=atenea_e((string)$categoria['nombre'])?><?=$categoria['activo']?'':' (inactiva)'?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="visually-hidden" for="estadoProducto">Estado</label><select class="form-select" id="estadoProducto" name="estado"><option value="">Todos los estados</option><?php foreach(['activo'=>'Activos','inactivo'=>'Inactivos','agotado'=>'Agotados','bajo'=>'Bajo inventario']as$valor=>$texto):?><option value="<?=$valor?>" <?=$estado===$valor?'selected':''?>><?=$texto?></option><?php endforeach;?></select></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-outline-primary flex-grow-1">Filtrar</button><?php if($buscar!==''||$estado!==''||$categoriaId):?><a class="btn btn-light" href="index.php" aria-label="Limpiar filtros"><i class="mdi mdi-close"></i></a><?php endif;?></div></form>
    <div class="d-flex gap-2"><a class="btn btn-outline-primary" href="<?=atenea_url('src/dashboard/categorias/index.php')?>"><i class="mdi mdi-tag-multiple me-1"></i>Administrar categorías</a><a class="btn btn-primary text-white" href="editar.php"><i class="mdi mdi-plus me-1"></i>Nuevo producto</a></div>
  </div>
  <div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Producto</th><th>Categoría</th><th>Precio</th><th>Stock</th><th>Disponibilidad</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><?php foreach($filas as$f):?><tr><td><div class="d-flex align-items-center"><img class="img-sm rounded me-2" src="<?=rutaImagenContenido((string)$f['imagen_principal'],'src/website/assets/img/course-1.jpg')?>" alt="Imagen de <?=atenea_e((string)$f['nombre'])?>"><div><strong><?=atenea_e((string)$f['nombre'])?></strong><small class="d-block text-muted"><?=atenea_e((string)$f['sku'])?></small></div></div></td><td><?php if($f['categoria']):?><span><?=atenea_e((string)$f['categoria'])?></span><?php if(!$f['categoria_activa']):?><small class="d-block text-warning">Inactiva</small><?php endif;?><?php else:?><span class="text-muted">Sin categoría</span><?php endif;?></td><td>$<?=number_format((float)$f['precio'],2)?></td><td><span class="<?=$f['stock']<=$f['stock_minimo']?'text-danger fw-bold':''?>"><?=(int)$f['stock']?> <small>(reservado <?=(int)$f['stock_reservado']?>)</small></span></td><td><?=$f['disponible']?'Disponible':'No disponible'?></td><td><span class="badge badge-opacity-<?=$f['activo']?'success':'secondary'?>"><?=$f['activo']?'Activo':'Inactivo'?></span></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-primary" href="editar.php?id=<?=(int)$f['id']?>">Editar</a> <a class="btn btn-sm btn-outline-info" target="_blank" href="<?=atenea_url('src/website/product-details.php?id='.(int)$f['id'])?>">Vista previa</a> <form class="d-inline" method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=(int)$f['id']?>"><button class="btn btn-sm btn-outline-warning" name="accion" value="toggle"><?=$f['activo']?'Desactivar':'Activar'?></button> <button class="btn btn-sm btn-outline-danger" name="accion" value="eliminar" onclick="return confirm('¿Eliminar este producto?')">Eliminar</button></form></td></tr><?php endforeach;?><?php if(!$filas):?><tr><td colspan="7" class="text-center py-5 text-muted">No hay productos que coincidan con los filtros.</td></tr><?php endif;?></tbody></table></div>
  <?php if($paginas>1):$base=['q'=>$buscar,'estado'=>$estado,'categoria_id'=>$categoriaId];?><nav class="mt-4" aria-label="Paginación de productos"><ul class="pagination mb-0"><?php for($i=1;$i<=$paginas;$i++):?><li class="page-item <?=$i===$pagina?'active':''?>"><a class="page-link" href="?<?=http_build_query($base+['pagina'=>$i])?>"><?=$i?></a></li><?php endfor;?></ul></nav><?php endif;?>
</div></div>
<?php cmsPie(); ?>
