<?php declare(strict_types=1); $nombreCompleto=trim((string)$perfil['nombre'].' '.(string)$perfil['apellido']); ?>
<nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row" aria-label="Barra superior del aula virtual">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
    <div class="me-3"><button class="navbar-toggler align-self-center" type="button" data-bs-toggle="minimize" aria-label="Contraer o expandir menú"><span class="icon-menu"></span></button></div>
    <a class="navbar-brand brand-logo" href="<?=atenea_url('src/estudiantes/index.php')?>"><img src="<?=atenea_e($logo)?>" alt="Atenea"></a>
    <a class="navbar-brand brand-logo-mini" href="<?=atenea_url('src/estudiantes/index.php')?>"><img src="<?=atenea_e($logo)?>" alt="Atenea"></a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-top">
    <ul class="navbar-nav"><li class="nav-item fw-semibold d-none d-lg-block ms-0"><h1 class="welcome-text"><?=atenea_e($saludo)?>, <span class="text-black fw-bold" data-atenea-current-name><?=atenea_e((string)$perfil['nombre'])?></span></h1><h2 class="welcome-sub-text">Aula Virtual Atenea</h2></li></ul>
    <ul class="navbar-nav ms-auto align-items-center">
      <li class="nav-item"><a class="nav-link count-indicator" href="<?=atenea_url('src/comunicaciones/chat.php')?>" aria-label="Mensajes<?= $mensajesNoLeidos?' no leídos: '.$mensajesNoLeidos:'' ?>"><i class="mdi mdi-message-text-outline"></i><?php if($mensajesNoLeidos):?><span class="count bg-warning"></span><span class="student-count-label"><?=$mensajesNoLeidos?></span><?php endif;?></a></li>
      <li class="nav-item dropdown"><button class="nav-link count-indicator border-0 bg-transparent" id="StudentNotifications" type="button" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Notificaciones"><i class="icon-bell"></i><span id="ateneaNotificationDot" class="count<?=($notificacionesPortal['no_leidas']??0)?'':' d-none'?>"></span></button><div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="StudentNotifications"><div class="dropdown-divider"></div><div id="ateneaNotificationList"><?php foreach($notificacionesPortal['notificaciones']??[] as $n):?><a class="dropdown-item preview-item py-3" href="<?=atenea_e($n['action_url']?:atenea_url('src/notificaciones/index.php'))?>"><div class="preview-thumbnail"><i class="mdi mdi-bell-outline m-auto text-primary"></i></div><div class="preview-item-content"><h3 class="preview-subject fw-normal text-dark mb-1 h6"><?=atenea_e($n['title'])?></h3><p class="fw-light small-text mb-0"><?=atenea_e(mb_substr((string)$n['message'],0,120))?></p></div></a><?php endforeach;?><?php if(empty($notificacionesPortal['notificaciones'])):?><div class="dropdown-item py-3 text-muted">No hay notificaciones recientes.</div><?php endif;?></div><a class="dropdown-item text-center small py-3" href="<?=atenea_url('src/notificaciones/index.php')?>">Ver todas</a></div></li>
      <li class="nav-item dropdown user-dropdown"><button class="nav-link border-0 bg-transparent" id="StudentUserDropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false"><img class="img-xs rounded-circle" src="<?=atenea_e($avatar)?>" data-atenea-current-avatar alt="Fotografía de <?=atenea_e($nombreCompleto)?>"></button><div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="StudentUserDropdown"><div class="dropdown-header text-center"><img class="img-md rounded-circle" src="<?=atenea_e($avatar)?>" alt="Fotografía"><p class="mb-1 mt-3 fw-semibold" data-atenea-current-name><?=atenea_e($nombreCompleto)?></p><p class="fw-light text-muted mb-0">Estudiante · <?=atenea_e((string)$perfil['correo'])?></p></div><a class="dropdown-item" href="<?=atenea_url('src/estudiantes/perfil.php')?>"><i class="mdi mdi-account-outline text-primary me-2"></i>Mi perfil</a><a class="dropdown-item" href="<?=atenea_url('src/estudiantes/configuracion.php')?>"><i class="mdi mdi-cog-outline text-primary me-2"></i>Configuración</a><a class="dropdown-item" href="<?=atenea_url('index.php')?>"><i class="mdi mdi-web text-primary me-2"></i>Volver al sitio</a><a class="dropdown-item" data-atenea-confirm="logout" href="<?=atenea_url('src/login/logout.php')?>"><i class="mdi mdi-power text-primary me-2"></i>Cerrar sesión</a></div></li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-bs-toggle="offcanvas" aria-label="Abrir menú"><span class="mdi mdi-menu"></span></button>
  </div>
</nav>
