<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/auth.php';
require_once dirname(__DIR__,2).'/includes/notificaciones.php';
require_once dirname(__DIR__,2).'/includes/permissions.php';
exigirAutenticacion();$rol=(string)$_SESSION['usuario_rol'];
if($rol==='admin'){header('Location:'.atenea_url('src/dashboard/notificaciones/index.php'));exit;}
if($rol==='administracion_docente'){$modo=modoHibridoActualAtenea();if($modo==='admin'){exigirPermiso('notifications.view');header('Location:'.atenea_url('src/dashboard/notificaciones/index.php'));exit;}exigirModoHibridoAtenea('docente');exigirPermiso('academic.notifications.view');}
$pdo=obtenerConexion();$uid=(int)$_SESSION['usuario_id'];$estado=in_array($_GET['estado']??'',['pendiente','visto'],true)?(string)$_GET['estado']:'';$pagina=max(1,(int)($_GET['pagina']??1));$limite=20;$where=' WHERE user_id=:u';$pa=['u'=>$uid];if($estado!==''){$where.=' AND status=:estado';$pa['estado']=$estado;}$q=$pdo->prepare('SELECT COUNT(*) FROM admin_notices'.$where);$q->execute($pa);$total=(int)$q->fetchColumn();$q=$pdo->prepare('SELECT * FROM admin_notices'.$where.' ORDER BY created_at DESC,id DESC LIMIT :lim OFFSET :off');foreach($pa as$k=>$v)$q->bindValue(':'.$k,$v);$q->bindValue(':lim',$limite,PDO::PARAM_INT);$q->bindValue(':off',($pagina-1)*$limite,PDO::PARAM_INT);$q->execute();$filas=$q->fetchAll();
if(in_array($rol,['docente','administracion_docente'],true)){require_once dirname(__DIR__).'/docente/_layout.php';docenteCabecera('Notificaciones','notificaciones','Actividad relevante de tu cuenta y cursos.');$cerrar='docentePie';}
else{require_once dirname(__DIR__,2).'/includes/portal_estudiante_layout.php';portalEstudianteCabecera('Notificaciones','notificaciones','Actividad relevante de tu cuenta y aprendizaje.');$cerrar='portalEstudiantePie';}
?>
<div class="card card-rounded"><div class="card-body"><div class="d-flex flex-wrap justify-content-between gap-2 mb-4"><form class="d-flex gap-2" method="get"><label class="visually-hidden" for="estado-notificacion">Estado</label><select class="form-select" id="estado-notificacion" name="estado"><option value="">Todas</option><option value="pendiente" <?=$estado==='pendiente'?'selected':''?>>No leídas</option><option value="visto" <?=$estado==='visto'?'selected':''?>>Leídas</option></select><button class="btn btn-outline-primary">Filtrar</button></form><form method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="todas"><button class="btn btn-outline-secondary">Marcar todas como leídas</button></form></div>
<?php foreach($filas as$n):?><article class="border rounded p-3 mb-3 <?=$n['status']==='pendiente'?'border-primary':''?>"><div class="d-flex flex-wrap justify-content-between gap-3"><div class="flex-grow-1"><span class="badge bg-secondary"><?=atenea_e($n['category'])?></span><h2 class="h6 mt-2 mb-1"><?=atenea_e($n['title'])?></h2><p class="mb-1"><?=atenea_e($n['message'])?></p><small class="text-muted"><?=date('d/m/Y H:i',strtotime($n['created_at']))?></small><?php if($n['action_url']):?> · <a href="<?=atenea_e($n['action_url'])?>">Abrir acción relacionada</a><?php endif;?></div><?php if($n['status']==='pendiente'):?><form method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="leer"><input type="hidden" name="id" value="<?=(int)$n['id']?>"><button class="btn btn-sm btn-outline-primary">Marcar como leída</button></form><?php endif;?></div></article><?php endforeach;?>
<?php if(!$filas):?><div class="text-center py-5"><i class="bi bi-bell-slash fs-1 text-muted" aria-hidden="true"></i><h2 class="h5 mt-3">No hay notificaciones</h2><p class="text-muted mb-0">Las acciones relevantes aparecerán en este historial.</p></div><?php endif;?>
<?php $paginas=max(1,(int)ceil($total/$limite));if($paginas>1):?><nav aria-label="Páginas de notificaciones"><ul class="pagination justify-content-end"><?php for($i=1;$i<=$paginas;$i++):?><li class="page-item <?=$i===$pagina?'active':''?>"><a class="page-link" href="?<?=atenea_e(http_build_query(['estado'=>$estado,'pagina'=>$i]))?>"><?=$i?></a></li><?php endfor;?></ul></nav><?php endif;?></div></div>
<?php $cerrar();
