<?php
declare(strict_types=1);
require_once __DIR__.'/DteProviderInterface.php';
final class HaciendaDteProvider implements DteProviderInterface {
 private function asegurar(array $c):void{foreach(['usuario_hacienda','password_hacienda','certificado','certificado_secreto','sign_url','auth_url','receive_url','query_url','invalidate_url']as$k)if(trim((string)($c[$k]??''))==='')throw new RuntimeException('Configuración fiscal incompleta para el ambiente solicitado.');if(!is_file($c['certificado']))throw new RuntimeException('El certificado fiscal configurado no está disponible.');}
 public function generate(array $p,array $c):array{$this->asegurar($c);return construirJsonDteFactura($p,$c);}
 public function sign(array $d,array $c):array{$this->asegurar($c);$ch=curl_init($c['sign_url']);$payload=['nit'=>$c['nit'],'activo'=>true,'passwordPri'=>$c['certificado_secreto'],'dteJson'=>$d];curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>30,CURLOPT_HTTPHEADER=>['Content-Type: application/json'],CURLOPT_POSTFIELDS=>json_encode($payload,JSON_THROW_ON_ERROR)]);$raw=curl_exec($ch);$code=curl_getinfo($ch,CURLINFO_RESPONSE_CODE);if($raw===false||$code>=400)throw new RuntimeException('El servicio de firmado no respondió correctamente.');$r=json_decode($raw,true,512,JSON_THROW_ON_ERROR);$firmado=(string)($r['body']??$r['documento']??'');if($firmado==='')throw new RuntimeException('El firmador no devolvió un documento firmado.');$d['_documento_firmado']=$firmado;return $d;}
 public function submit(array $d,array $c):array{$this->asegurar($c);if(empty($d['_documento_firmado']))throw new RuntimeException('No se enviará un DTE sin una firma real.');$i=$d['identificacion'];$r=solicitudHacienda('POST',$c['receive_url'],['ambiente'=>$i['ambiente'],'idEnvio'=>1,'version'=>$i['version'],'tipoDte'=>$i['tipoDte'],'documento'=>$d['_documento_firmado'],'codigoGeneracion'=>$i['codigoGeneracion']],$c);$sello=(string)($r['selloRecibido']??$r['sello']??'');if($sello==='')throw new RuntimeException('Hacienda no devolvió sello de recepción.');return ['estado'=>(string)($r['estado']??'PROCESADO'),'sello'=>$sello,'observaciones'=>json_encode($r['observaciones']??[],JSON_UNESCAPED_UNICODE)];}
 public function queryStatus(string $g,array $c):array{$this->asegurar($c);return solicitudHacienda('POST',$c['query_url'],['codigoGeneracion'=>$g],$c);}
 public function invalidate(array $d,string $m,array $c):array{$this->asegurar($c);return solicitudHacienda('POST',$c['invalidate_url'],['documento'=>$d,'motivo'=>$m],$c);}
 public function getGraphicalRepresentation(array $d,array $p,array $c):string{return renderizarPdfDte($d,$p,$c,false);}
}
