<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';
exigirPermiso('audit.view');
$pdo=obtenerConexion();$pagina=max(1,(int)($_GET['page']??1));$limite=25;$where=[];$params=[];
$usuario=cmsId($_GET['usuario_id']??0);$tipo=mb_substr(trim((string)($_GET['tipo']??'')),0,100);$modulo=mb_substr(trim((string)($_GET['modulo']??'')),0,80);$resultado=in_array($_GET['resultado']??'', ['success','failure','blocked','warning'],true)?(string)$_GET['resultado']:'';$desde=(string)($_GET['desde']??'');$hasta=(string)($_GET['hasta']??'');$buscar=mb_substr(trim((string)($_GET['q']??'')),0,100);
if($usuario){$where[]='(a.actor_user_id=:actor_user OR a.target_user_id=:target_user)';$params['actor_user']=$usuario;$params['target_user']=$usuario;}if($tipo!==''){$where[]='a.event_type=:type';$params['type']=$tipo;}if($modulo!==''){$where[]='a.module=:module';$params['module']=$modulo;}if($resultado!==''){$where[]='a.result=:result';$params['result']=$resultado;}if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$desde)){$where[]='a.created_at>=:from';$params['from']=$desde.' 00:00:00';}if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$hasta)){$where[]='a.created_at<=:to';$params['to']=$hasta.' 23:59:59';}if($buscar!==''){$where[]='(a.description LIKE :description_q OR a.event_type LIKE :event_q OR a.request_id LIKE :request_q)';$valorBusqueda='%'.$buscar.'%';$params['description_q']=$valorBusqueda;$params['event_q']=$valorBusqueda;$params['request_q']=$valorBusqueda;}$filtro=$where?' WHERE '.implode(' AND ',$where):'';
$q=$pdo->prepare('SELECT COUNT(*) FROM audit_logs a'.$filtro);$q->execute($params);$total=(int)$q->fetchColumn();
$q=$pdo->prepare('SELECT a.*,CONCAT(actor.nombre," ",actor.apellido) actor_nombre,CONCAT(target.nombre," ",target.apellido) target_nombre FROM audit_logs a LEFT JOIN usuarios actor ON actor.id=a.actor_user_id LEFT JOIN usuarios target ON target.id=a.target_user_id'.$filtro.' ORDER BY a.created_at DESC,a.id DESC LIMIT '.$limite.' OFFSET '.(($pagina-1)*$limite));$q->execute($params);$eventos=$q->fetchAll();$paginas=max(1,(int)ceil($total/$limite));$tipos=$pdo->query('SELECT DISTINCT event_type FROM audit_logs ORDER BY event_type')->fetchAll(PDO::FETCH_COLUMN);$modulos=$pdo->query('SELECT DISTINCT module FROM audit_logs ORDER BY module')->fetchAll(PDO::FETCH_COLUMN);
cmsCabecera('Bitacora','bitacora/index.php','Registro inmutable de eventos significativos y acciones administrativas.');
?>
<div class="card card-rounded"><div class="card-body"><form class="row g-2 mb-4" method="get"><div class="col-lg-3"><label class="form-label">Busqueda</label><input class="form-control" name="q" value="<?= atenea_e($buscar) ?>" placeholder="Descripcion o request ID"></div><div class="col-lg-2"><label class="form-label">Usuario ID</label><input class="form-control" type="number" min="1" name="usuario_id" value="<?= $usuario?:'' ?>"></div><div class="col-lg-2"><label class="form-label">Evento</label><select class="form-select" name="tipo"><option value="">Todos</option><?php foreach($tipos as $op):?><option <?= $tipo===$op?'selected':'' ?>><?= atenea_e((string)$op) ?></option><?php endforeach;?></select></div><div class="col-lg-2"><label class="form-label">Modulo</label><select class="form-select" name="modulo"><option value="">Todos</option><?php foreach($modulos as $op):?><option <?= $modulo===$op?'selected':'' ?>><?= atenea_e((string)$op) ?></option><?php endforeach;?></select></div><div class="col-lg-3"><label class="form-label">Resultado</label><select class="form-select" name="resultado"><option value="">Todos</option><?php foreach(['success'=>'Exito','failure'=>'Fallo','blocked'=>'Bloqueado','warning'=>'Advertencia'] as $v=>$l):?><option value="<?= $v ?>" <?= $resultado===$v?'selected':'' ?>><?= $l ?></option><?php endforeach;?></select></div><div class="col-lg-3"><label class="form-label">Desde</label><input class="form-control" type="date" name="desde" value="<?= atenea_e($desde) ?>"></div><div class="col-lg-3"><label class="form-label">Hasta</label><input class="form-control" type="date" name="hasta" value="<?= atenea_e($hasta) ?>"></div><div class="col-lg-2 d-flex align-items-end"><button class="btn btn-primary w-100">Aplicar filtros</button></div></form>
<div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Fecha</th><th>Evento</th><th>Actor</th><th>Objetivo</th><th>Modulo</th><th>Resultado</th><th>Descripcion</th><th></th></tr></thead><tbody><?php foreach($eventos as $e):?><tr><td><?= date('d/m/Y H:i:s',strtotime((string)$e['created_at'])) ?></td><td><?= atenea_e((string)$e['event_type']) ?></td><td><?= atenea_e((string)($e['actor_nombre']?:'Sistema')) ?></td><td><?= atenea_e((string)($e['target_nombre']?:'-')) ?></td><td><?= atenea_e((string)$e['module']) ?></td><td><span class="badge badge-opacity-<?= $e['result']==='success'?'success':'danger' ?>"><?= atenea_e((string)$e['result']) ?></span></td><td><?= atenea_e((string)$e['description']) ?></td><td><a class="btn btn-sm btn-outline-primary" href="detalle.php?id=<?= (int)$e['id'] ?>">Detalle</a></td></tr><?php endforeach;?><?php if(!$eventos):?><tr><td colspan="8" class="text-center text-muted py-5">No hay eventos para los filtros seleccionados.</td></tr><?php endif;?></tbody></table></div>
<?php if($paginas>1):?><nav><ul class="pagination justify-content-end"><?php for($i=1;$i<=$paginas;$i++):?><li class="page-item <?= $i===$pagina?'active':'' ?>"><a class="page-link" href="?<?= http_build_query(array_merge($_GET,['page'=>$i])) ?>"><?= $i ?></a></li><?php endfor;?></ul></nav><?php endif;?></div></div><?php cmsPie(); ?>
