<?php
require_once dirname(__DIR__) . '/includes/cms.php';
$pdo=obtenerConexion();$seccionId=cmsId($_GET['seccion_id']??0);$pagina=max(1,cmsId($_GET['pagina']??1));$porPagina=20;$offset=($pagina-1)*$porPagina;$secciones=$pdo->query('SELECT id,nombre FROM secciones ORDER BY orden,id')->fetchAll();
$where=$seccionId?'WHERE e.seccion_id=:sid':'';$conteo=$pdo->prepare("SELECT COUNT(*) FROM elementos_seccion e $where");$conteo->execute($seccionId?['sid'=>$seccionId]:[]);$total=(int)$conteo->fetchColumn();$q=$pdo->prepare("SELECT e.*,s.nombre seccion_nombre FROM elementos_seccion e JOIN secciones s ON s.id=e.seccion_id $where ORDER BY s.orden,e.orden,e.id LIMIT :limite OFFSET :offset");if($seccionId)$q->bindValue('sid',$seccionId,PDO::PARAM_INT);$q->bindValue('limite',$porPagina,PDO::PARAM_INT);$q->bindValue('offset',$offset,PDO::PARAM_INT);$q->execute();$filas=$q->fetchAll();
cmsCabecera('Elementos de las secciones','elementos/index.php','Administra tarjetas, cifras, áreas y capacitaciones. Las noticias tienen un módulo editorial propio.');
?>
<div class="row"><div class="col-12 grid-margin stretch-card"><div class="card card-rounded"><div class="card-body">
<div class="row align-items-end mb-4"><div class="col-md-6"><label class="form-label">Filtrar por sección</label><form><select class="form-select" name="seccion_id" onchange="this.form.submit()"><option value="">Todas las secciones</option><?php foreach($secciones as $s):?><option value="<?=$s['id']?>" <?=$seccionId===$s['id']?'selected':''?>><?=atenea_e($s['nombre'])?></option><?php endforeach;?></select></form></div><div class="col-md-6 text-md-end mt-3 mt-md-0"><a class="btn btn-primary text-white" href="editar.php<?=$seccionId?'?seccion_id='.$seccionId:''?>"><i class="mdi mdi-plus me-1"></i>Agregar elemento</a></div></div>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Sección</th><th>Título</th><th>Estado</th><th>Orden</th><th>Imagen</th><th>Acciones</th></tr></thead><tbody>
<?php if(!$filas):?><tr><td colspan="6" class="text-center text-muted py-5">No hay elementos para mostrar.</td></tr><?php endif;?>
<?php foreach($filas as $f):?><tr><td><?=atenea_e($f['seccion_nombre'])?></td><td class="fw-semibold"><?=atenea_e($f['titulo'])?><div class="small text-muted"><?=atenea_e((string)$f['subtitulo'])?></div></td><td><span class="badge badge-opacity-<?=$f['activo']?'success':'secondary'?>"><?=$f['activo']?'Activo':'Inactivo'?></span></td><td><?=$f['orden']?></td><td><?php if($f['imagen']):?><img src="<?=rutaImagenContenido($f['imagen'])?>" alt="" style="width:60px;height:45px;object-fit:cover;border-radius:6px"><?php else:?>—<?php endif;?></td><td class="text-nowrap">
<a class="btn btn-sm btn-outline-primary" href="editar.php?id=<?=$f['id']?>"><i class="mdi mdi-pencil"></i> Editar</a>
<form class="d-inline" method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$f['id']?>"><input type="hidden" name="accion" value="toggle"><button class="btn btn-sm <?=$f['activo']?'btn-outline-warning':'btn-outline-success'?>"><i class="mdi <?=$f['activo']?'mdi-eye-off':'mdi-eye'?>"></i> <?=$f['activo']?'Desactivar':'Activar'?></button></form>
<button class="btn btn-sm btn-outline-danger" data-bs-toggle="modal" data-bs-target="#del<?=$f['id']?>"><i class="mdi mdi-delete"></i> Eliminar</button></td></tr>
<div class="modal fade" id="del<?=$f['id']?>" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="h5 modal-title">Confirmar eliminación</h2><button class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body">Esta acción no se puede deshacer. ¿Deseas eliminar este contenido?</div><div class="modal-footer"><button class="btn btn-light" data-bs-dismiss="modal">Cancelar</button><form method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$f['id']?>"><input type="hidden" name="accion" value="eliminar"><button class="btn btn-danger"><i class="mdi mdi-delete me-1"></i>Sí, eliminar</button></form></div></div></div></div>
<?php endforeach;?></tbody></table></div>
<?php $paginas=max(1,(int)ceil($total/$porPagina));if($paginas>1):?><nav class="mt-4"><ul class="pagination mb-0"><?php for($i=1;$i<=$paginas;$i++):?><li class="page-item <?=$i===$pagina?'active':''?>"><a class="page-link" href="?pagina=<?=$i?><?=$seccionId?'&seccion_id='.$seccionId:''?>"><?=$i?></a></li><?php endfor;?></ul></nav><?php endif;?>
</div></div></div></div>
<?php cmsPie(); ?>

