<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/auth.php';require_once dirname(__DIR__,2).'/includes/carrito.php';require_once dirname(__DIR__,2).'/includes/stripe_config.php';require_once dirname(__DIR__,2).'/includes/alerts.php';require_once dirname(__DIR__,2).'/includes/audit.php';require_once dirname(__DIR__,2).'/includes/notificaciones.php';require_once dirname(__DIR__,2).'/includes/errores_sistema.php';
exigirRol(['usuario']);$retorno=atenea_url('src/estudiantes/checkout.php');
if(($_SERVER['REQUEST_METHOD']??'')!=='POST'||!validarTokenCsrf((string)($_POST['csrf_token']??''))){ateneaFlash('error','Solicitud expirada','Recarga el checkout.');header('Location:'.$retorno);exit;}
$direccionId=filter_var($_POST['direccion_id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$key=(string)($_POST['checkout_key']??'');
if(empty($_POST['confirmar_direccion'])||!isset($_SESSION['checkout_key'])||!hash_equals((string)$_SESSION['checkout_key'],$key)||!preg_match('/^[a-f0-9]{64}$/',$key)){ateneaFlash('warning','Confirma la dirección','La confirmación no es válida o ya fue utilizada.');header('Location:'.$retorno);exit;}
$stripeCfg=configuracionStripe();$autoload=dirname(__DIR__,2).'/includes/stripe/vendor/autoload.php';if(!stripeConfigurado($stripeCfg)||!is_file($autoload)){ateneaFlash('error','Pago no disponible','Stripe no está configurado.');header('Location:'.$retorno);exit;}
$pdo=obtenerConexion();$pedidoId=0;$sesionStripe=null;$stripe=null;
try{
 $pdo->beginTransaction();$direccion=direccionPropia($pdo,$direccionId,(int)$_SESSION['usuario_id'],true);if(!$direccion)throw new DomainException('Selecciona una dirección propia y activa.');$r=resumenCarrito($pdo,(int)$_SESSION['usuario_id'],true);if(!$r['items'])throw new DomainException('El carrito está vacío.');
 foreach($r['items'] as$i){if(!(int)$i['activo']||!(int)$i['disponible']||$i['eliminado_at']!==null||$i['cantidad']>$i['disponible_real'])throw new DomainException('El stock cambió. Revisa el carrito.');}
 $q=$pdo->prepare('SELECT id,stripe_checkout_session_id FROM pedidos WHERE checkout_key=:k FOR UPDATE');$q->execute(['k'=>$key]);if($prev=$q->fetch())throw new DomainException('Esta confirmación ya fue procesada. Consulta Mis pedidos.');
 $numero=numeroPedido();$q=$pdo->prepare("INSERT INTO pedidos(numero,usuario_id,carrito_id,direccion_id,direccion_snapshot,subtotal,descuento,envio,impuestos,total,moneda,checkout_key,estado,payment_status) VALUES(:n,:u,:c,:d,:snap,:sub,:desc,:env,:imp,:total,:moneda,:k,'pendiente_pago','pending')");$q->execute(['n'=>$numero,'u'=>$_SESSION['usuario_id'],'c'=>$r['carrito']['id'],'d'=>$direccionId,'snap'=>json_encode(snapshotDireccion($direccion),JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),'sub'=>centavosDinero($r['subtotal']),'desc'=>centavosDinero($r['descuento']),'env'=>centavosDinero($r['envio']),'imp'=>centavosDinero($r['impuesto']),'total'=>centavosDinero($r['total']),'moneda'=>$stripeCfg['currency'],'k'=>$key]);$pedidoId=(int)$pdo->lastInsertId();
 $ins=$pdo->prepare('INSERT INTO pedido_detalles(pedido_id,producto_id,nombre_producto,sku,cantidad,precio_normal,precio_unitario,descuento_unitario,subtotal,promocion_id) VALUES(:pedido,:producto,:nombre,:sku,:cantidad,:normal,:unitario,:descuento,:subtotal,:promocion)');
 foreach($r['items'] as$i){$ins->execute(['pedido'=>$pedidoId,'producto'=>$i['id'],'nombre'=>$i['nombre'],'sku'=>$i['sku'],'cantidad'=>$i['cantidad'],'normal'=>centavosDinero($i['precio_normal_centavos']),'unitario'=>centavosDinero($i['precio_centavos']),'descuento'=>centavosDinero($i['descuento_centavos']),'subtotal'=>centavosDinero($i['linea_centavos']),'promocion'=>$i['promo_id']?:null]);$pdo->prepare('UPDATE productos SET stock_reservado=stock_reservado+:q WHERE id=:id')->execute(['q'=>$i['cantidad'],'id'=>$i['id']]);}
 $pdo->prepare("UPDATE carritos SET estado='convertido' WHERE id=:id")->execute(['id'=>$r['carrito']['id']]);registrarHistorialPedido($pdo,$pedidoId,null,'pendiente_pago','usuario',(int)$_SESSION['usuario_id'],'Pedido creado desde carrito; precio, stock y dirección validados.');crearNotificacionAtenea(['rol'=>'admin','tipo'=>'compra_nueva','categoria'=>'pedidos','nivel'=>'informacion','titulo'=>'Nueva compra pendiente','descripcion'=>'Pedido '.$numero.' creado y pendiente de pago.','url'=>atenea_url('src/dashboard/pedidos/detalle.php?id='.$pedidoId),'pedido_id'=>$pedidoId,'idempotency_key'=>'pedido:nuevo:'.$pedidoId],$pdo);$pdo->commit();unset($_SESSION['checkout_key']);
 require_once $autoload;
 $stripe=new Stripe\StripeClient($stripeCfg['secret_key']);$lineas=[];
 foreach($r['items'] as$i){
  $lineas[]=['quantity'=>(int)$i['cantidad'],'price_data'=>['currency'=>$stripeCfg['currency'],'unit_amount'=>$i['precio_centavos'],'product_data'=>['name'=>$i['nombre'],'description'=>(string)$i['descripcion_corta']]]];
 }
 if($r['envio']+$r['impuesto']>0){
  $lineas[]=['quantity'=>1,'price_data'=>['currency'=>$stripeCfg['currency'],'unit_amount'=>$r['envio']+$r['impuesto'],'product_data'=>['name'=>'Envío e impuestos']]];
 }
 $sesionStripe=$stripe->checkout->sessions->create(['mode'=>'payment','customer_email'=>(string)$_SESSION['usuario_correo'],'client_reference_id'=>(string)$pedidoId,'line_items'=>$lineas,'metadata'=>['pedido_id'=>(string)$pedidoId,'numero'=>$numero],'payment_intent_data'=>['metadata'=>['pedido_id'=>(string)$pedidoId,'numero'=>$numero]],'success_url'=>atenea_url_absoluta('src/pagos/success.php?session_id={CHECKOUT_SESSION_ID}'),'cancel_url'=>atenea_url_absoluta('src/pagos/cancel.php?pedido='.$pedidoId)],['idempotency_key'=>'checkout-pedido-'.$pedidoId]);
 $pdo->beginTransaction();$q=$pdo->prepare("UPDATE pedidos SET stripe_checkout_session_id=:s WHERE id=:id AND estado='pendiente_pago'");$q->execute(['s'=>$sesionStripe->id,'id'=>$pedidoId]);if($q->rowCount()!==1)throw new RuntimeException('No se vinculó el pago.');registrarHistorialPedido($pdo,$pedidoId,'pendiente_pago','pendiente_pago','stripe',null,'Checkout Stripe creado.');$pdo->commit();header('Location:'.$sesionStripe->url,true,303);exit;
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();if($sesionStripe&&$stripe)try{$stripe->checkout->sessions->expire($sesionStripe->id);}catch(Throwable){}if($pedidoId){try{$pdo->beginTransaction();$q=$pdo->prepare('SELECT estado,carrito_id FROM pedidos WHERE id=:id FOR UPDATE');$q->execute(['id'=>$pedidoId]);$p=$q->fetch();if($p&&$p['estado']==='pendiente_pago'){foreach($pdo->query('SELECT producto_id,cantidad FROM pedido_detalles WHERE pedido_id='.(int)$pedidoId) as$d)$pdo->prepare('UPDATE productos SET stock_reservado=GREATEST(stock_reservado-:q,0) WHERE id=:id')->execute(['q'=>$d['cantidad'],'id'=>$d['producto_id']]);$pdo->prepare("UPDATE pedidos SET estado='pago_fallido',payment_status='failed' WHERE id=:id")->execute(['id'=>$pedidoId]);if(!empty($p['carrito_id']))$pdo->prepare("UPDATE carritos SET estado='activo' WHERE id=:id")->execute(['id'=>$p['carrito_id']]);registrarHistorialPedido($pdo,$pedidoId,'pendiente_pago','pago_fallido','sistema',null,'No se pudo crear el Checkout; reserva liberada.');}$pdo->commit();}catch(Throwable){if($pdo->inTransaction())$pdo->rollBack();}}
 if(!($e instanceof DomainException))try{registrarErrorSistemaAtenea('pago','crear_checkout',$e->getMessage(),['pedido_id'=>$pedidoId?:null,'usuario_id'=>$_SESSION['usuario_id']]);}catch(Throwable){}
 ateneaFlash('warning','No fue posible iniciar el pago',$e instanceof DomainException?$e->getMessage():'Tu compra no fue cobrada. Inténtalo nuevamente.');header('Location:'.atenea_url('src/estudiantes/carrito.php'));exit;}
