<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/auth.php';
exigirRol(['usuario']);
$session=trim((string)($_GET['session_id']??''));
$q=obtenerConexion()->prepare('SELECT cp.estado,a.nombre,i.estado estado_inscripcion,s.codigo FROM capacitacion_pagos cp INNER JOIN asignaturas a ON a.id=cp.asignatura_id LEFT JOIN inscripciones_capacitacion i ON i.pago_id=cp.id LEFT JOIN capacitacion_secciones s ON s.id=i.seccion_id WHERE cp.usuario_id=:u AND cp.stripe_checkout_session_id=:session LIMIT 1');
$q->execute(['u'=>$_SESSION['usuario_id'],'session'=>$session]);$pago=$q->fetch();
$pageTitle='Estado del pago | Atenea';$pageDescription='Consulta el estado confirmado por Stripe.';require dirname(__DIR__,2).'/includes/header.php';
?><main class="main"><section class="section"><div class="container" style="max-width:760px"><div class="card shadow-sm"><div class="card-body p-5 text-center"><?php if(!$pago):?><h1 class="h3">Pago no localizado</h1><p>La referencia no pertenece a tu cuenta.</p><?php elseif($pago['estado']!=='pagado'):?><h1 class="h3">Estamos confirmando tu pago</h1><p>Regresar desde Stripe no confirma el pago. La inscripción aparecerá cuando el webhook verificado lo confirme.</p><?php elseif($pago['estado_inscripcion']==='pendiente_asignacion'):?><h1 class="h3">Pago confirmado</h1><p>Tu inscripción en <?=atenea_e($pago['nombre'])?> está pendiente de docente y sección. No debes pagar nuevamente.</p><?php else:?><h1 class="h3">Pago e inscripción confirmados</h1><p>Ya estás inscrito en <?=atenea_e($pago['nombre'])?>, sección <?=atenea_e($pago['codigo'])?>.</p><?php endif;?><a class="btn-atenea d-inline-block mt-3" href="<?=atenea_url('src/estudiantes/cursos.php')?>">Mis capacitaciones</a></div></div></div></section></main><?php require dirname(__DIR__,2).'/includes/footer.php';
