<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/cms.php';
$pdo=obtenerConexion();
$estado=in_array((string)($_GET['estado']??''),['borrador','publicado'],true)?(string)$_GET['estado']:'';
$pagina=max(1,cmsId($_GET['pagina']??1));$limite=20;$offset=($pagina-1)*$limite;
$where='WHERE deleted_at IS NULL';$params=[];
if($estado!==''){$where.=' AND estado=:estado';$params['estado']=$estado;}
$q=$pdo->prepare("SELECT COUNT(*) FROM noticias $where");$q->execute($params);$total=(int)$q->fetchColumn();
$q=$pdo->prepare("SELECT * FROM noticias $where ORDER BY COALESCE(fecha_publicacion,created_at) DESC,id DESC LIMIT :limite OFFSET :offset");
foreach($params as$k=>$v)$q->bindValue($k,$v);$q->bindValue('limite',$limite,PDO::PARAM_INT);$q->bindValue('offset',$offset,PDO::PARAM_INT);$q->execute();$noticias=$q->fetchAll();
cmsCabecera('Noticias','noticias/index.php','Crea, previsualiza y controla la publicación de noticias del sitio público.');
?>
<div class="card card-rounded"><div class="card-body"><div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><form class="d-flex gap-2"><select class="form-select" name="estado"><option value="">Todos los estados</option><option value="borrador" <?=$estado==='borrador'?'selected':''?>>Borradores</option><option value="publicado" <?=$estado==='publicado'?'selected':''?>>Publicadas</option></select><button class="btn btn-outline-secondary">Filtrar</button></form><a class="btn btn-primary text-white" href="editar.php"><i class="mdi mdi-plus"></i> Nueva noticia</a></div>
<div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Noticia</th><th>Publicación</th><th>Estado</th><th>Destacada</th><th>Acciones</th></tr></thead><tbody><?php if(!$noticias):?><tr><td colspan="5" class="text-center text-muted py-5">No hay noticias para mostrar.</td></tr><?php endif;?><?php foreach($noticias as$n):?><tr><td><div class="d-flex align-items-center gap-3"><?php if($n['imagen_portada']):?><img src="<?=rutaImagenContenido($n['imagen_portada'])?>" alt="" style="width:76px;height:52px;object-fit:cover;border-radius:8px"><?php endif;?><div><strong><?=atenea_e($n['titulo'])?></strong><div class="small text-muted">/<?=atenea_e($n['slug'])?></div></div></div></td><td><?=atenea_e($n['fecha_publicacion']?date('d/m/Y H:i',strtotime($n['fecha_publicacion'])):'Sin fecha')?></td><td><span class="badge badge-opacity-<?=$n['estado']==='publicado'&&$n['activo']?'success':'secondary'?>"><?=atenea_e(ucfirst($n['estado']))?><?=$n['activo']?'':' · Inactiva'?></span></td><td><?=$n['destacado']?'<span class="badge badge-opacity-warning">Sí</span>':'No'?></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-primary" href="editar.php?id=<?=$n['id']?>">Editar</a> <a class="btn btn-sm btn-outline-info" href="preview.php?id=<?=$n['id']?>" target="_blank" rel="noopener">Previsualizar</a><form class="d-inline" method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$n['id']?>"><input type="hidden" name="accion" value="<?=$n['estado']==='publicado'?'despublicar':'publicar'?>"><button class="btn btn-sm <?=$n['estado']==='publicado'?'btn-outline-warning':'btn-outline-success'?>"><?=$n['estado']==='publicado'?'Despublicar':'Publicar'?></button></form> <button class="btn btn-sm btn-outline-danger" data-bs-toggle="modal" data-bs-target="#delete-news-<?=$n['id']?>">Eliminar</button></td></tr><div class="modal fade" id="delete-news-<?=$n['id']?>" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="h5">Eliminar noticia</h2><button class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body">La noticia dejará de publicarse y se conservará en el historial. ¿Deseas continuar?</div><div class="modal-footer"><button class="btn btn-light" data-bs-dismiss="modal">Cancelar</button><form method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$n['id']?>"><input type="hidden" name="accion" value="eliminar"><button class="btn btn-danger">Sí, eliminar</button></form></div></div></div></div><?php endforeach;?></tbody></table></div>
<?=cmsPaginacionSimple($pagina,max(1,(int)ceil($total/$limite)),['estado'=>$estado])?>
</div></div><?php cmsPie(); ?>
