<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';require_once dirname(__DIR__,3).'/includes/comercio.php';exigirPermiso('orders.view');$pdo=obtenerConexion();
$qtxt=mb_substr(trim((string)($_GET['q']??'')),0,100);$pago=in_array($_GET['pago']??'',['paid','refunded'],true)?(string)$_GET['pago']:'';$envio=in_array($_GET['envio']??'',array_keys(estadosSeguimientoPedido()),true)?(string)$_GET['envio']:'';$pagina=max(1,(int)($_GET['pagina']??1));$limite=25;$where=["p.es_intencion_checkout=0","p.payment_status IN('paid','refunded')"];$params=[];
if($qtxt!==''){$where[]="(p.numero LIKE :q OR CONCAT_WS(' ',u.nombre,u.apellido) LIKE :q OR u.correo LIKE :q)";$params['q']='%'.$qtxt.'%';}if($pago!==''){$where[]='p.payment_status=:pago';$params['pago']=$pago;}if($envio!==''){$where[]='p.estado_pedido=:envio';$params['envio']=$envio;}$filtro=' WHERE '.implode(' AND ',$where);
$from=' FROM pedidos p JOIN usuarios u ON u.id=p.usuario_id LEFT JOIN dte_documentos d ON d.pedido_id=p.id';$q=$pdo->prepare('SELECT COUNT(*)'.$from.$filtro);$q->execute($params);$total=(int)$q->fetchColumn();
$sql="SELECT p.id,p.numero,p.total,p.moneda,p.estado,p.payment_status,p.estado_pedido,p.created_at,p.updated_at,u.nombre,u.apellido,u.correo,d.id dte_id,d.pdf_relpath,d.json_documento,(SELECT GROUP_CONCAT(CONCAT(pd.nombre_producto,' x',pd.cantidad) ORDER BY pd.id SEPARATOR ', ') FROM pedido_detalles pd WHERE pd.pedido_id=p.id) productos,(SELECT SUM(pd.cantidad) FROM pedido_detalles pd WHERE pd.pedido_id=p.id) cantidad".$from.$filtro.' ORDER BY p.created_at DESC,p.id DESC LIMIT :lim OFFSET :off';$q=$pdo->prepare($sql);foreach($params as$k=>$v)$q->bindValue(':'.$k,$v);$q->bindValue(':lim',$limite,PDO::PARAM_INT);$q->bindValue(':off',($pagina-1)*$limite,PDO::PARAM_INT);$q->execute();$pedidos=$q->fetchAll();
cmsCabecera('Pedidos','pedidos/index.php','Pago confirmado por Stripe y seguimiento logístico administrado por separado.');
?>
<div class="card card-rounded"><div class="card-body"><form class="row g-2 mb-4"><div class="col-lg-5"><label class="form-label">Buscar</label><input class="form-control" name="q" value="<?=atenea_e($qtxt)?>" placeholder="Pedido, comprador o correo"></div><div class="col-lg-3"><label class="form-label">Estado del pago</label><select class="form-select" name="pago"><option value="">Todos</option><option value="pending" <?=$pago==='pending'?'selected':''?>>Pago pendiente</option><option value="paid" <?=$pago==='paid'?'selected':''?>>Pago completado</option><option value="failed" <?=$pago==='failed'?'selected':''?>>Pago fallido</option><option value="refunded" <?=$pago==='refunded'?'selected':''?>>Reembolsado</option></select></div><div class="col-lg-3"><label class="form-label">Estado del envío</label><select class="form-select" name="envio"><option value="">Todos</option><?php foreach(estadosSeguimientoPedido()as$valor=>$label):?><option value="<?=$valor?>" <?=$envio===$valor?'selected':''?>><?=atenea_e($label)?></option><?php endforeach;?></select></div><div class="col-lg-1 d-flex align-items-end"><button class="btn btn-primary w-100">Filtrar</button></div></form>
<div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Pedido</th><th>Comprador</th><th>Producto</th><th>Cant.</th><th>Total</th><th>Pago</th><th>Envío</th><th>Compra / actualización</th><th>Documentos</th><th>Acciones</th></tr></thead><tbody><?php foreach($pedidos as$p):$pagado=$p['payment_status']==='paid';?><tr><td><strong><?=atenea_e($p['numero'])?></strong></td><td><?=atenea_e(trim($p['nombre'].' '.$p['apellido']))?><small class="d-block text-muted"><?=atenea_e($p['correo'])?></small></td><td><?=atenea_e((string)$p['productos'])?></td><td><?=(int)$p['cantidad']?></td><td>$<?=number_format((float)$p['total'],2)?> <?=atenea_e(strtoupper($p['moneda']))?></td><td><span class="badge <?=$pagado?'bg-success':($p['payment_status']==='refunded'?'bg-secondary':'bg-warning text-dark')?>"><?=$pagado?'Pago completado':($p['payment_status']==='refunded'?'Reembolsado':'Pago pendiente')?></span></td><td><span class="badge badge-opacity-<?=$p['estado_pedido']==='entregado'?'success':'primary'?>"><?=atenea_e($pagado?etiquetaSeguimientoPedido($p['estado_pedido']):'No iniciado')?></span></td><td><?=date('d/m/Y H:i',strtotime($p['created_at']))?><small class="d-block text-muted"><?=date('d/m/Y H:i',strtotime($p['updated_at']))?></small></td><td><?php if($pagado&&$p['dte_id']&&!empty($p['pdf_relpath'])&&!empty($p['json_documento'])):?><a class="btn btn-sm btn-outline-primary mb-1" href="<?=atenea_url('src/dte/documento.php?pedido='.$p['id'].'&descargar=1')?>">PDF</a> <a class="btn btn-sm btn-outline-primary mb-1" href="<?=atenea_url('src/dte/documento.php?pedido='.$p['id'].'&tipo=json&descargar=1')?>">JSON</a><?php else:?><span class="text-muted">—</span><?php endif;?></td><td><a class="btn btn-sm btn-outline-primary" href="detalle.php?id=<?=$p['id']?>">Ver / seguimiento</a></td></tr><?php endforeach;?><?php if(!$pedidos):?><tr><td colspan="10" class="text-center text-muted py-5">No hay pedidos para estos filtros.</td></tr><?php endif;?></tbody></table></div><?=cmsPaginacionSimple($pagina,(int)ceil($total/$limite),$_GET)?></div></div><?php cmsPie();
