<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';require_once dirname(__DIR__,3).'/includes/comercio.php';exigirPermiso('orders.view');$id=cmsId($_GET['id']??0);$pdo=obtenerConexion();
$q=$pdo->prepare('SELECT p.*,u.nombre,u.apellido,u.correo,c.id comprobante_id,c.codigo_generacion,c.numero comprobante_numero,c.pdf_relpath,c.json_relpath FROM pedidos p JOIN usuarios u ON u.id=p.usuario_id LEFT JOIN comprobante_documentos c ON c.pedido_id=p.id WHERE p.id=:id');$q->execute(['id'=>$id]);$p=$q->fetch();if(!$p){cmsFlash('error','Pedido no encontrado.');header('Location:index.php');exit;}
$q=$pdo->prepare('SELECT * FROM pedido_detalles WHERE pedido_id=:id');$q->execute(['id'=>$id]);$det=$q->fetchAll();$q=$pdo->prepare("SELECT h.*,CONCAT_WS(' ',u.nombre,u.apellido) responsable FROM pedido_historial h LEFT JOIN usuarios u ON u.id=h.usuario_id WHERE h.pedido_id=:id ORDER BY h.created_at");$q->execute(['id'=>$id]);$hist=$q->fetchAll();
$q=$pdo->prepare("SELECT destinatario_email,estado,intento,error_sanitizado,enviado_at,message_id,reenvio_manual,created_at FROM correo_envios WHERE pedido_id=:id AND tipo='compra_confirmada' ORDER BY id DESC LIMIT 1");$q->execute(['id'=>$id]);$correo=$q->fetch();$direccion=json_decode((string)$p['direccion_snapshot'],true)?:[];cmsCabecera('Pedido '.$p['numero'],'pedidos/index.php');
?>
<div class="row"><div class="col-lg-8"><div class="card card-rounded"><div class="card-body"><h2 class="h5">Productos</h2><div class="table-responsive"><table class="table"><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio</th><th>Descuento</th><th>Subtotal</th></tr></thead><tbody><?php foreach($det as$d):?><tr><td><?=atenea_e($d['nombre_producto'])?><small class="d-block"><?=atenea_e((string)$d['sku'])?></small></td><td><?=$d['cantidad']?></td><td>$<?=number_format((float)$d['precio_unitario'],2)?></td><td>$<?=number_format((float)$d['descuento_unitario'],2)?></td><td>$<?=number_format((float)$d['subtotal'],2)?></td></tr><?php endforeach;?></tbody></table></div><h2 class="h5 mt-4">Historial</h2><?php foreach($hist as$h):?><div class="border-bottom py-2"><strong><?=atenea_e($h['estado_anterior']?:'inicio')?> → <?=atenea_e($h['estado_nuevo'])?></strong> · <?=date('d/m/Y H:i',strtotime($h['created_at']))?><small class="d-block text-muted">Origen: <?=atenea_e($h['origen'])?> · Responsable: <?=atenea_e($h['responsable']?:'Sistema')?> · <?=atenea_e((string)$h['nota'])?></small></div><?php endforeach;?></div></div></div>
<div class="col-lg-4"><div class="card card-rounded"><div class="card-body"><h2 class="h5">Resumen</h2><p><strong>Cliente:</strong><br><?=atenea_e(trim($p['nombre'].' '.$p['apellido']))?><br><?=atenea_e($p['correo'])?></p><p><strong>Dirección:</strong><br><?=atenea_e((string)($direccion['receptor']??''))?> · <?=atenea_e((string)($direccion['telefono']??''))?><br><?=atenea_e((string)($direccion['direccion_detallada']??'No disponible'))?></p><p><strong>Pago:</strong> <?=$p['payment_status']==='paid'?'Pago completado':'Pendiente'?><br><strong>Seguimiento:</strong> <?=atenea_e(etiquetaSeguimientoPedido($p['estado_pedido']))?><br><strong>Total:</strong> $<?=number_format((float)$p['total'],2)?> <?=strtoupper($p['moneda'])?></p>
<?php if($p['comprobante_id']&&$p['payment_status']==='paid'):?><a class="btn btn-outline-primary w-100 mb-2" href="<?=atenea_url('src/comprobantes/descargar.php?pedido='.$id.'&tipo=pdf')?>">Descargar PDF</a><a class="btn btn-outline-primary w-100 mb-3" href="<?=atenea_url('src/comprobantes/descargar.php?pedido='.$id.'&tipo=json')?>">Descargar JSON</a><?php endif;?>
<h2 class="h5">Correo de compra</h2><?php if($correo):?><dl><dt>Estado</dt><dd><?=atenea_e($correo['estado'])?> (<?= (int)$correo['intento']?> intento/s)</dd><dt>Destinatario</dt><dd><?=atenea_e((string)$correo['destinatario_email'])?></dd><dt>Enviado</dt><dd><?=!empty($correo['enviado_at'])?date('d/m/Y H:i',strtotime($correo['enviado_at'])):'Aún no enviado'?></dd><?php if($correo['error_sanitizado']):?><dt>Error</dt><dd class="text-danger"><?=atenea_e($correo['error_sanitizado'])?></dd><?php endif;?></dl><?php else:?><p class="text-muted">Sin envío registrado.</p><?php endif;?>
<?php if($p['comprobante_id']&&$p['payment_status']==='paid'):?><form method="post" action="reenviar-comprobante.php" data-atenea-confirm="send" data-atenea-confirm-title="Reenviar comprobante" data-atenea-confirm-message="Se reutilizarán los documentos existentes y se registrará el reenvío manual."><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$id?>"><button class="btn btn-warning w-100 mb-3">Reenviar comprobante</button></form><?php endif;?>
<h2 class="h5">Actualizar seguimiento</h2><form method="post" action="estado.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$id?>"><select class="form-select mb-2" name="estado" required><option value="">Selecciona</option><?php foreach(['en_proceso_envio'=>'En proceso de envío','saliendo_almacen'=>'Saliendo de almacén','entregado'=>'Entregado'] as$e=>$label):?><option value="<?=$e?>"><?=atenea_e($label)?></option><?php endforeach;?></select><textarea class="form-control mb-2" name="nota" maxlength="500" placeholder="Observación"></textarea><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="confirmar_reversion_entregado" value="1" id="reversion"><label class="form-check-label" for="reversion">Confirmo la reversión especial si ya fue entregado</label></div><button class="btn btn-primary w-100">Registrar cambio</button></form></div></div></div></div><?php cmsPie();
