<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';exigirPermiso('orders.view');$pdo=obtenerConexion();
$qtxt=trim((string)($_GET['q']??''));$estado=(string)($_GET['estado']??'');$metodo=trim((string)($_GET['metodo']??''));$desde=(string)($_GET['desde']??'');$hasta=(string)($_GET['hasta']??'');
$estados=['pagado','preparando','enviado','entregado','reembolsado'];$pagina=max(1,(int)($_GET['pagina']??1));$limite=25;
$from=' FROM pedidos p JOIN usuarios u ON u.id=p.usuario_id LEFT JOIN dte_documentos d ON d.pedido_id=p.id LEFT JOIN pagos pg ON pg.pedido_id=p.id';$where=" WHERE p.es_intencion_checkout=0 AND p.payment_status IN('paid','refunded')";$pa=[];
if($qtxt!==''){$where.=' AND (p.numero LIKE :q OR CONCAT_WS(\' \',u.nombre,u.apellido) LIKE :q OR u.correo LIKE :q OR d.codigo_generacion LIKE :q OR p.stripe_checkout_session_id LIKE :q)';$pa['q']='%'.$qtxt.'%';}
if(in_array($estado,$estados,true)){$where.=' AND p.estado=:e';$pa['e']=$estado;}
if($metodo!==''){$where.=' AND (pg.proveedor=:m OR p.payment_brand=:m)';$pa['m']=mb_substr($metodo,0,30);}
if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$desde)){$where.=' AND p.created_at>=:d';$pa['d']=$desde.' 00:00:00';}
if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$hasta)){$where.=' AND p.created_at<DATE_ADD(:h,INTERVAL 1 DAY)';$pa['h']=$hasta;}
$q=$pdo->prepare('SELECT COUNT(DISTINCT p.id)'.$from.$where);$q->execute($pa);$total=(int)$q->fetchColumn();
$sql='SELECT p.*,u.nombre,u.apellido,u.correo,d.estado estado_dte,d.codigo_generacion,pg.proveedor,(SELECT COUNT(*) FROM pedido_detalles pd WHERE pd.pedido_id=p.id) lineas'.$from.$where.' GROUP BY p.id ORDER BY p.created_at DESC LIMIT :lim OFFSET :off';
$q=$pdo->prepare($sql);foreach($pa as$k=>$v)$q->bindValue(':'.$k,$v);$q->bindValue(':lim',$limite,PDO::PARAM_INT);$q->bindValue(':off',($pagina-1)*$limite,PDO::PARAM_INT);$q->execute();$pedidos=$q->fetchAll();
cmsCabecera('Pedidos','pedidos/index.php','Historial paginado de pagos, entregas y DTE.');?>
<div class="card card-rounded"><div class="card-body"><form class="row g-2 mb-4"><div class="col-lg-4"><input class="form-control" name="q" value="<?=atenea_e($qtxt)?>" placeholder="Pedido, cliente, correo o código DTE"></div><div class="col-lg-2"><select class="form-select" name="estado"><option value="">Estados</option><?php foreach($estados as$e):?><option <?=$estado===$e?'selected':''?>><?=$e?></option><?php endforeach;?></select></div><div class="col-lg-2"><input class="form-control" name="metodo" value="<?=atenea_e($metodo)?>" placeholder="Método"></div><div class="col-lg-2"><input type="date" class="form-control" name="desde" value="<?=atenea_e($desde)?>"></div><div class="col-lg-2"><input type="date" class="form-control" name="hasta" value="<?=atenea_e($hasta)?>"></div><div class="col-12"><button class="btn btn-outline-primary">Aplicar filtros</button></div></form><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Pedido</th><th>Cliente</th><th>Productos</th><th>Fecha</th><th>Total</th><th>Pago</th><th>Estado</th><th>DTE</th><th></th></tr></thead><tbody>
<?php foreach($pedidos as$p):?><tr><td><?=atenea_e($p['numero'])?></td><td><?=atenea_e(trim($p['nombre'].' '.$p['apellido']))?><small class="d-block"><?=atenea_e($p['correo'])?></small></td><td><?=(int)$p['lineas']?> líneas</td><td><?=date('d/m/Y H:i',strtotime($p['created_at']))?></td><td>$<?=number_format((float)$p['total'],2)?></td><td><?=atenea_e($p['proveedor']?:($p['payment_brand']?:$p['payment_status']))?></td><td><?=atenea_e($p['estado'])?></td><td><?=atenea_e((string)($p['estado_dte']??'—'))?></td><td><a class="btn btn-sm btn-outline-primary" href="detalle.php?id=<?=$p['id']?>">Ver</a></td></tr><?php endforeach;?>
<?php if(!$pedidos):?><tr><td colspan="9" class="text-center py-5">No hay pedidos.</td></tr><?php endif;?></tbody></table></div><?=cmsPaginacionSimple($pagina,(int)ceil($total/$limite),$_GET)?></div></div><?php cmsPie();
