<?php
declare(strict_types=1);require_once dirname(__DIR__,2).'/includes/portal_estudiante_aula.php';$pdo=obtenerConexion();$tag='c7e8_'.bin2hex(random_bytes(4));$ids=[];$ok=[];$assert=static function(bool$c,string$m)use(&$ok){if(!$c)throw new RuntimeException('FALLO: '.$m);$ok[]=$m;};
try{$activo='$activo';$clave='$clave';
 $q=$pdo->prepare("INSERT INTO usuarios(nombre,apellido,nombre_usuario,correo,password,rol,estado,email_verificado,perfil_estado,terminos_aceptados_at) VALUES('Estudiante','Aula',:n,:c,:p,'usuario','activo',1,'completo',NOW())");$q->execute(['n'=>$tag,'c'=>$tag.'@example.invalid','p'=>password_hash('Temporal123!',PASSWORD_DEFAULT)]);$u=(int)$pdo->lastInsertId();$ids['usuarios'][]=$u;
 $q=$pdo->prepare("INSERT INTO usuarios(nombre,apellido,nombre_usuario,correo,password,rol,estado,email_verificado,perfil_estado,terminos_aceptados_at) VALUES('Docente','Aula',:n,:c,:p,'docente','activo',1,'completo',NOW())");$q->execute(['n'=>'doc_'.$tag,'c'=>'doc_'.$tag.'@example.invalid','p'=>password_hash('Temporal123!',PASSWORD_DEFAULT)]);$d=(int)$pdo->lastInsertId();$ids['usuarios'][]=$d;
 $q=$pdo->prepare("INSERT INTO asignaturas(codigo,nombre,slug,descripcion,tipo,precio,estado_capacitacion,cupo_seccion,modalidad,activo,estado) VALUES(:codigo,'Curso de prueba',:slug,'Datos académicos reales de prueba','capacitacion',0,'publicada',30,'virtual',1,'activo')");$q->execute(['codigo'=>strtoupper($tag),'slug'=>$tag]);$a=(int)$pdo->lastInsertId();$ids['asignaturas'][]=$a;
 $q=$pdo->prepare("INSERT INTO capacitacion_pagos(usuario_id,asignatura_id,checkout_key,importe,estado,paid_at) VALUES(:u,:a,:k,0,'pagado',NOW())");$q->execute(['u'=>$u,'a'=>$a,'k'=>hash('sha256',$tag)]);$pago=(int)$pdo->lastInsertId();$ids['pagos'][]=$pago;
 $q=$pdo->prepare("INSERT INTO capacitacion_secciones(asignatura_id,docente_id,codigo,nombre,fecha_inicio,fecha_finalizacion,horario,estado) VALUES(:a,:d,:c,'Sección de prueba',CURDATE(),DATE_ADD(CURDATE(),INTERVAL 30 DAY),'Sábados 09:00','abierta')");$q->execute(['a'=>$a,'d'=>$d,'c'=>'SEC-'.strtoupper($tag)]);$s=(int)$pdo->lastInsertId();$ids['secciones'][]=$s;
 $q=$pdo->prepare("INSERT INTO inscripciones_capacitacion(usuario_id,asignatura_id,pago_id,seccion_id,docente_id,estado,assigned_at) VALUES(:u,:a,:p,:s,:d,'inscrito',NOW())");$q->execute(['u'=>$u,'a'=>$a,'p'=>$pago,'s'=>$s,'d'=>$d]);$i=(int)$pdo->lastInsertId();$ids['inscripciones'][]=$i;
 $q=$pdo->prepare("INSERT INTO contenidos(asignatura_id,seccion_id,docente_id,modulo,tipo,titulo,descripcion,orden,video_url,fecha_publicacion,fecha_limite,estado,activo,obligatorio,peso_progreso) VALUES(:a,:s,:d,'Unidad 1',:tipo,:titulo,'Contenido real de prueba',:orden,:video,NOW(),DATE_ADD(NOW(),INTERVAL 5 DAY),'activo',1,1,50)");foreach([['video','Video real',1,'https://www.youtube.com/watch?v=test'],['actividad','Tarea real',2,null],['evaluacion','Evaluación real',3,null]]as$c){$q->execute(['a'=>$a,'s'=>$s,'d'=>$d,'tipo'=>$c[0],'titulo'=>$c[1],'orden'=>$c[2],'video'=>$c[3]]);$ids['contenidos'][]=(int)$pdo->lastInsertId();}
 $resumen=aulaResumenEstudiante($pdo,$u);$assert(count($resumen['inscripciones'])===1&&$resumen['proxima_clase']['docente']==='Docente Aula','El inicio carga la clase y el docente asignado desde la base');$assert(count($resumen['tareas'])===2,'El inicio obtiene tareas y evaluaciones pendientes reales');$assert(count($resumen['contenidos'])===3,'El acceso rápido muestra únicamente contenidos publicados de la sección');$assert(count(aulaContenidosEstudiante($pdo,$u,['video']))===1,'La vista de videos filtra los recursos audiovisuales autorizados');$assert(count(aulaFechasEstudiante($pdo,$u))>=4,'El calendario combina clase, tareas y evaluaciones con fechas reales');
 $layout=file_get_contents(dirname(__DIR__,2).'/includes/portal_estudiante_layout.php');foreach(['index.php','clase.php','cursos.php','contenidos.php','videos.php','tareas.php','evaluaciones.php','calificaciones.php','calendario.php','certificados.php','pedidos.php','perfil.php','soporte.php']as$r){$assert(str_contains($layout,"src/estudiantes/$r"),"El menú incluye la ruta canónica $r");$assert(is_file(dirname(__DIR__,2).'/src/estudiantes/'.$r),"Existe el módulo navegable $r");}
 $assert(str_contains($layout,'data-portal-sidebar-toggle')&&str_contains($layout,'aria-expanded'),'El sidebar puede contraerse y mantiene atributos accesibles');$assert(str_contains($layout,"$activo===$clave")&&str_contains($layout,'submenu'),'La navegación conserva sección activa y submenús por categoría');$js=file_get_contents(dirname(__DIR__,2).'/src/estudiantes/assets/js/portal-navigation.js');$assert(str_contains($js,'portal-sidebar-open')&&(str_contains($js,"e.key==='Escape'")||str_contains($js,"event.key === 'Escape'")),'La navegación móvil incluye overlay y cierre por teclado');$legacy=file_get_contents(dirname(__DIR__,2).'/src/estudiantes/dashboard/index.php');$assert(str_contains($legacy,"src/estudiantes/index.php")&&!str_contains($legacy,'top-header'),'El dashboard de demostración redirige al aula canónica sin datos simulados');
 $perfil=file_get_contents(dirname(__DIR__,2).'/src/estudiantes/perfil.php');$modal=file_get_contents(dirname(__DIR__,2).'/includes/perfil_modal.php');$backend=file_get_contents(dirname(__DIR__,2).'/src/cuenta/actualizar-perfil.php');$assert(str_contains($perfil,'rutaFotoPerfil')&&str_contains($perfil,'data-atenea-current-avatar'),'El perfil carga la fotografía mediante el resolvedor compartido');$assert(str_contains($modal,'telefono')&&str_contains($modal,'direccion')&&str_contains($modal,'data-profile-ajax'),'El perfil permite editar teléfono, dirección y datos personales sin recarga');$assert(str_contains($backend,'validarTokenCsrf')&&str_contains($backend,'registrarAuditoria'),'La actualización del perfil valida CSRF y registra cambios');
 echo 'OK '.count($ok)." pruebas\n";foreach($ok as$m)echo '- '.$m."\n";
}finally{try{if(!empty($ids['contenidos'])){$marks=implode(',',array_fill(0,count($ids['contenidos']),'?'));$pdo->prepare("DELETE FROM contenidos WHERE id IN($marks)")->execute($ids['contenidos']);}if(!empty($ids['inscripciones'])){$pdo->prepare('DELETE FROM inscripciones_capacitacion WHERE id=?')->execute([$ids['inscripciones'][0]]);}if(!empty($ids['secciones']))$pdo->prepare('DELETE FROM capacitacion_secciones WHERE id=?')->execute([$ids['secciones'][0]]);if(!empty($ids['pagos']))$pdo->prepare('DELETE FROM capacitacion_pagos WHERE id=?')->execute([$ids['pagos'][0]]);if(!empty($ids['asignaturas']))$pdo->prepare('DELETE FROM asignaturas WHERE id=?')->execute([$ids['asignaturas'][0]]);if(!empty($ids['usuarios'])){$marks=implode(',',array_fill(0,count($ids['usuarios']),'?'));$pdo->prepare("DELETE FROM usuarios WHERE id IN($marks)")->execute($ids['usuarios']);}}catch(Throwable$e){fwrite(STDERR,'Limpieza: '.$e->getMessage()."\n");}}
