<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/capacitaciones.php';

$pdo=obtenerConexion();$tag='c6e3_'.bin2hex(random_bytes(4));$ok=[];$ids=['usuarios'=>[],'asignaturas'=>[],'eventos'=>[]];
$assert=function(bool $condicion,string $mensaje)use(&$ok):void{if(!$condicion)throw new RuntimeException('FALLO: '.$mensaje);$ok[]=$mensaje;};
try{
 $admin=(int)$pdo->query("SELECT id FROM usuarios WHERE rol='admin' ORDER BY id LIMIT 1")->fetchColumn();if(!$admin)throw new RuntimeException('No existe administrador para la prueba.');
 $crearUsuario=function(string $rol,int $n)use($pdo,$tag,&$ids):int{$q=$pdo->prepare("INSERT INTO usuarios(nombre,apellido,correo,password,rol,estado,email_verificado) VALUES(:n,'Integración',:c,:p,:r,'activo',1)");$q->execute(['n'=>'Tmp'.$n,'c'=>$tag.$n.'@example.invalid','p'=>password_hash(bin2hex(random_bytes(16)),PASSWORD_DEFAULT),'r'=>$rol]);$id=(int)$pdo->lastInsertId();$ids['usuarios'][]=$id;return$id;};
 $docente=$crearUsuario('docente',1);$est1=$crearUsuario('usuario',2);$est2=$crearUsuario('usuario',3);$est3=$crearUsuario('usuario',4);$docente2=$crearUsuario('docente',5);
 $crearCap=function(string $codigo,string $estado='publicada')use($pdo,$tag,$admin,&$ids):int{$q=$pdo->prepare("INSERT INTO asignaturas(codigo,nombre,slug,descripcion,descripcion_corta,descripcion_completa,tipo,precio,estado_capacitacion,cupo_seccion,activo,estado,creado_por) VALUES(:c,:n,:s,'Prueba','Prueba','Prueba','capacitacion',125.50,:e,30,1,'activo',:a)");$q->execute(['c'=>$tag.$codigo,'n'=>'Temporal '.$codigo,'s'=>$tag.'-'.strtolower($codigo),'e'=>$estado,'a'=>$admin]);$id=(int)$pdo->lastInsertId();$ids['asignaturas'][]=$id;return$id;};
 $cap1=$crearCap('A');$cap2=$crearCap('B');$cap3=$crearCap('C');
 $q=$pdo->prepare("INSERT INTO docentes_asignaturas(docente_id,asignatura_id,estado,asignado_por) VALUES(:d,:a,'activo',:admin)");$q->execute(['d'=>$docente,'a'=>$cap1,'admin'=>$admin]);$q->execute(['d'=>$docente,'a'=>$cap2,'admin'=>$admin]);
 $bloqueado=false;try{$q->execute(['d'=>$docente,'a'=>$cap3,'admin'=>$admin]);}catch(PDOException){$bloqueado=true;}$assert($bloqueado,'La base bloquea al docente con 2 capacitaciones activas');
 $assert(!docentePuedeAsumirCapacitacion($pdo,$docente,$cap3),'El backend bloquea al docente con carga máxima');
 $q=$pdo->prepare("INSERT INTO capacitacion_secciones(asignatura_id,docente_id,codigo,nombre,capacidad_maxima,cantidad_actual,estado,creada_por) VALUES(:a,:d,:c,'Sección llena',30,29,'abierta',:admin)");$q->execute(['a'=>$cap1,'d'=>$docente,'c'=>$tag.'-S29','admin'=>$admin]);$seccion29=(int)$pdo->lastInsertId();
 $crearPago=function(int $usuario,int $cap,string $evento)use($pdo,$tag,&$ids):array{$session='cs_test_'.$tag.'_'.$evento;$q=$pdo->prepare("INSERT INTO capacitacion_pagos(usuario_id,asignatura_id,checkout_key,stripe_checkout_session_id,importe,moneda,estado) VALUES(:u,:a,:k,:s,125.50,'usd','pendiente')");$q->execute(['u'=>$usuario,'a'=>$cap,'k'=>hash('sha256',$tag.$evento),'s'=>$session]);$id=(int)$pdo->lastInsertId();$eventId='evt_'.$tag.'_'.$evento;$ids['eventos'][]=$eventId;$obj=(object)['id'=>$session,'client_reference_id'=>(string)$id,'amount_total'=>12550,'currency'=>'usd','payment_status'=>'paid','payment_intent'=>'pi_'.$tag.'_'.$evento,'metadata'=>(object)['tipo'=>'capacitacion','capacitacion_pago_id'=>(string)$id]];$ev=(object)['id'=>$eventId,'type'=>'checkout.session.completed'];return[$id,$ev,$obj];};
 [$p1,$ev1,$obj1]=$crearPago($est1,$cap1,'uno');procesarWebhookCapacitacion($ev1,$obj1);$assert((int)$pdo->query('SELECT cantidad_actual FROM capacitacion_secciones WHERE id='.$seccion29)->fetchColumn()===30,'Una sección con 29 estudiantes recibe exactamente el cupo 30');
 procesarWebhookCapacitacion($ev1,$obj1);$q=$pdo->prepare('SELECT COUNT(*) FROM inscripciones_capacitacion WHERE pago_id=:p');$q->execute(['p'=>$p1]);$assert((int)$q->fetchColumn()===1,'El webhook repetido no duplica la inscripción');
 [$p2,$ev2,$obj2]=$crearPago($est2,$cap1,'dos');procesarWebhookCapacitacion($ev2,$obj2);$q=$pdo->prepare('SELECT estado,seccion_id FROM inscripciones_capacitacion WHERE pago_id=:p');$q->execute(['p'=>$p2]);$segunda=$q->fetch();$assert($segunda&&$segunda['estado']==='pendiente_asignacion'&&$segunda['seccion_id']===null,'El segundo pago no sobrepasa el último cupo y queda pendiente de una sección real');
 $q=$pdo->prepare("INSERT INTO docentes_asignaturas(docente_id,asignatura_id,estado,asignado_por) VALUES(:d,:a,'activo',:admin)");
 $capConcurrente=$crearCap('CONC');$q->execute(['d'=>$docente2,'a'=>$capConcurrente,'admin'=>$admin]);$q=$pdo->prepare("INSERT INTO capacitacion_secciones(asignatura_id,docente_id,codigo,nombre,capacidad_maxima,cantidad_actual,estado,creada_por) VALUES(:a,:d,:c,'Último cupo concurrente',30,29,'abierta',:admin)");$q->execute(['a'=>$capConcurrente,'d'=>$docente2,'c'=>$tag.'-CONC','admin'=>$admin]);$seccionConcurrente=(int)$pdo->lastInsertId();[$pc1,$ec1,$oc1]=$crearPago($est1,$capConcurrente,'conc-1');[$pc2,$ec2,$oc2]=$crearPago($est2,$capConcurrente,'conc-2');$worker=dirname(__FILE__).'/webhook_capacitacion_worker.php';$procesos=[];foreach([[$ec1->id,$pc1,$oc1->id],[$ec2->id,$pc2,$oc2->id]] as$datos){$cmd=escapeshellarg(PHP_BINARY).' '.escapeshellarg($worker).' '.escapeshellarg($datos[0]).' '.escapeshellarg((string)$datos[1]).' '.escapeshellarg($datos[2]);$procesos[]=proc_open($cmd,[1=>['pipe','w'],2=>['pipe','w']],$pipes);}foreach($procesos as$proceso){if(!is_resource($proceso)||proc_close($proceso)!==0)throw new RuntimeException('Falló un webhook concurrente.');}$q=$pdo->prepare('SELECT MAX(cantidad_actual),SUM(cantidad_actual) FROM capacitacion_secciones WHERE asignatura_id=:a');$q->execute(['a'=>$capConcurrente]);[$maxCupo,$sumaCupo]=$q->fetch(PDO::FETCH_NUM);$assert((int)$maxCupo<=30&&(int)$sumaCupo===30,'Dos webhooks simultáneos no ocupan dos veces el último cupo ni crean secciones ficticias');
 [$p3,$ev3,$obj3]=$crearPago($est3,$cap3,'sin-docente');procesarWebhookCapacitacion($ev3,$obj3);$q=$pdo->prepare('SELECT estado,seccion_id FROM inscripciones_capacitacion WHERE pago_id=:p');$q->execute(['p'=>$p3]);$pendiente=$q->fetch();$assert($pendiente&&$pendiente['estado']==='pendiente_asignacion'&&$pendiente['seccion_id']===null,'Sin docente, el pago se conserva y la inscripción queda pendiente');
 $q=$pdo->prepare("INSERT INTO capacitacion_secciones(asignatura_id,docente_id,codigo,nombre,capacidad_maxima,estado,creada_por) VALUES(:a,:d,:c,'Destino manual',30,'abierta',:admin)");$q->execute(['a'=>$cap1,'d'=>$docente,'c'=>$tag.'-DEST','admin'=>$admin]);$dest=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT id FROM inscripciones_capacitacion WHERE pago_id=:p');$q->execute(['p'=>$p2]);$ins2=(int)$q->fetchColumn();$pdo->beginTransaction();moverInscripcionCapacitacion($pdo,$ins2,$dest,$admin,'Prueba de movimiento con historial');$pdo->commit();$q=$pdo->prepare('SELECT COUNT(*) FROM inscripcion_movimientos WHERE inscripcion_id=:i AND seccion_destino_id=:s');$q->execute(['i'=>$ins2,'s'=>$dest]);$assert((int)$q->fetchColumn()===1,'El cambio manual registra historial y verifica cupo');
 $pdo->prepare("UPDATE asignaturas SET estado_capacitacion='archivada',activo=0,deleted_at=NOW() WHERE id=:id")->execute(['id'=>$cap1]);$q=$pdo->prepare('SELECT COUNT(*) FROM capacitacion_pagos WHERE asignatura_id=:a');$q->execute(['a'=>$cap1]);$assert((int)$q->fetchColumn()===2,'Archivar conserva pagos e inscripciones');
 $checkout=file_get_contents(dirname(__DIR__,2).'/src/pagos/crear-checkout-capacitacion.php');$assert(!str_contains($checkout,"\$_POST['precio']")&&!str_contains($checkout,'name="precio"'),'Checkout ignora precios del navegador y consulta la base');
 echo "OK ".count($ok)." pruebas\n";foreach($ok as$m)echo "- $m\n";
}finally{
 try{
  $pdo->beginTransaction();$like=$tag.'%@example.invalid';
  $pdo->prepare("DELETE FROM admin_notices WHERE idempotency_key LIKE 'capacitacion:%' AND (user_id IN (SELECT id FROM usuarios WHERE correo LIKE :correo) OR message LIKE :mensaje)")->execute(['correo'=>$like,'mensaje'=>'%Temporal%']);
  $pdo->prepare("DELETE FROM correo_envios WHERE idempotency_key LIKE 'capacitacion-confirmada:pago:%' AND usuario_id IN (SELECT id FROM usuarios WHERE correo LIKE :correo)")->execute(['correo'=>$like]);
  $pdo->prepare("DELETE FROM estudiantes_docentes WHERE estudiante_id IN (SELECT id FROM usuarios WHERE correo LIKE :correo1) OR docente_id IN (SELECT id FROM usuarios WHERE correo LIKE :correo2)")->execute(['correo1'=>$like,'correo2'=>$like]);
  if($ids['asignaturas']){$marks=implode(',',array_fill(0,count($ids['asignaturas']),'?'));$pdo->prepare("DELETE FROM inscripcion_movimientos WHERE inscripcion_id IN(SELECT id FROM inscripciones_capacitacion WHERE asignatura_id IN($marks))")->execute($ids['asignaturas']);$pdo->prepare("DELETE FROM capacitacion_seccion_historial WHERE seccion_id IN(SELECT id FROM capacitacion_secciones WHERE asignatura_id IN($marks))")->execute($ids['asignaturas']);$pdo->prepare("DELETE FROM inscripciones_capacitacion WHERE asignatura_id IN($marks)")->execute($ids['asignaturas']);$pdo->prepare("DELETE FROM capacitacion_secciones WHERE asignatura_id IN($marks)")->execute($ids['asignaturas']);$pdo->prepare("DELETE FROM capacitacion_pagos WHERE asignatura_id IN($marks)")->execute($ids['asignaturas']);$pdo->prepare("DELETE FROM docentes_asignaturas WHERE asignatura_id IN($marks)")->execute($ids['asignaturas']);$pdo->prepare("DELETE FROM asignaturas WHERE id IN($marks)")->execute($ids['asignaturas']);}
  if($ids['eventos']){$marks=implode(',',array_fill(0,count($ids['eventos']),'?'));$pdo->prepare("DELETE FROM stripe_eventos WHERE stripe_event_id IN($marks)")->execute($ids['eventos']);}
  if($ids['usuarios']){$marks=implode(',',array_fill(0,count($ids['usuarios']),'?'));$pdo->prepare("DELETE FROM usuarios WHERE id IN($marks)")->execute($ids['usuarios']);}
  $pdo->commit();
 }catch(Throwable$cleanup){if($pdo->inTransaction())$pdo->rollBack();fwrite(STDERR,'Limpieza: '.$cleanup->getMessage()."\n");}
}
