<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/capacitaciones.php';
$pdo=obtenerConexion();$ok=[];$assert=static function(bool$c,string$m)use(&$ok){if(!$c)throw new RuntimeException('FALLO: '.$m);$ok[]=$m;};
$col=$pdo->query("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='inscripciones_capacitacion' AND COLUMN_NAME='asignacion_limite_at'")->fetchColumn();if(!(int)$col){$pdo->exec((string)file_get_contents(dirname(__DIR__,2).'/src/database/migrations/029_asignacion_clases_docentes.sql'));}
$tag='c7e10_'.bin2hex(random_bytes(4));$ids=['usuarios'=>[],'pagos'=>[],'inscripciones'=>[],'secciones'=>[]];
try{
 $assert(strtolower(entornoAtenea('MAIL_TEST_MODE','false'))==='true','Las pruebas mantienen activo MAIL_TEST_MODE');
 $admin=(int)$pdo->query("SELECT id FROM usuarios WHERE rol='admin' AND estado='activo' AND deleted_at IS NULL ORDER BY es_superadmin DESC,id LIMIT 1")->fetchColumn();$assert($admin>0,'Existe un administrador para registrar movimientos');
 foreach([['Estudiante','Uno','usuario'],['Estudiante','Dos','usuario'],['Docente','Asignación','docente']]as$n){$q=$pdo->prepare('INSERT INTO usuarios(nombre,apellido,nombre_usuario,correo,password,rol,estado,email_verificado,perfil_estado,terminos_aceptados_at) VALUES(:nombre,:apellido,:usuario,:correo,:password,:rol,\'activo\',1,\'completo\',NOW())');$usuario=$tag.'_'.count($ids['usuarios']);$q->execute(['nombre'=>$n[0],'apellido'=>$n[1],'usuario'=>$usuario,'correo'=>$usuario.'@example.invalid','password'=>password_hash('Temporal123!',PASSWORD_DEFAULT),'rol'=>$n[2]]);$ids['usuarios'][]=(int)$pdo->lastInsertId();}
 [$estudiante1,$estudiante2,$docente]=$ids['usuarios'];$q=$pdo->prepare("INSERT INTO asignaturas(codigo,nombre,slug,descripcion,tipo,precio,estado_capacitacion,cupo_seccion,asignacion_automatica,modalidad,activo,estado) VALUES(:codigo,'Programa de asignación',:slug,'Prueba de asignación','certificacion',25,'publicada',20,1,'virtual',1,'activo')");$q->execute(['codigo'=>strtoupper($tag),'slug'=>$tag]);$asignatura=(int)$pdo->lastInsertId();
 $pdo->prepare("INSERT INTO docentes_asignaturas(docente_id,asignatura_id,estado,asignado_por) VALUES(:d,:a,'activo',:admin)")->execute(['d'=>$docente,'a'=>$asignatura,'admin'=>$admin]);
 $crearPago=function(int$estudiante)use($pdo,$asignatura,$tag,&$ids):int{$q=$pdo->prepare("INSERT INTO capacitacion_pagos(usuario_id,asignatura_id,checkout_key,importe,moneda,estado,paid_at) VALUES(:u,:a,:k,25,'usd','pagado',NOW())");$q->execute(['u'=>$estudiante,'a'=>$asignatura,'k'=>hash('sha256',$tag.'-'.$estudiante)]);$id=(int)$pdo->lastInsertId();$ids['pagos'][]=$id;return$id;};
 $pago1=$crearPago($estudiante1);$pdo->beginTransaction();$pendiente=asignarInscripcionAutomatica($pdo,$pago1);$pdo->commit();$ids['inscripciones'][]=(int)$pendiente['id'];$assert($pendiente['estado']==='pendiente_asignacion','El pago crea primero una inscripción pendiente');
 $q=$pdo->prepare('SELECT asignacion_limite_at FROM inscripciones_capacitacion WHERE id=:id');$q->execute(['id'=>$pendiente['id']]);$limite=strtotime((string)$q->fetchColumn());$assert($limite>=strtotime('+71 hours')&&$limite<=strtotime('+73 hours'),'La asignación pendiente registra un plazo máximo de 3 días');
 $q=$pdo->prepare("SELECT COUNT(*) FROM admin_notices WHERE idempotency_key LIKE :clave");$q->execute(['clave'=>'capacitacion:sin-cupo:'.$pendiente['id'].':u:%']);$assert((int)$q->fetchColumn()>0,'La falta de sección genera una alerta administrativa');
 $q=$pdo->prepare("SELECT COUNT(*) FROM correo_envios WHERE idempotency_key=:clave");$q->execute(['clave'=>'capacitacion-asignada:inscripcion:'.$pendiente['id']]);$assert((int)$q->fetchColumn()===0,'No se envía correo mientras la asignación sigue pendiente');
 $q=$pdo->prepare("INSERT INTO capacitacion_secciones(asignatura_id,docente_id,codigo,nombre,fecha_inicio,fecha_finalizacion,capacidad_maxima,horario,estado,creada_por) VALUES(:a,:d,:codigo,'Sección inicial',DATE_ADD(CURDATE(),INTERVAL 7 DAY),DATE_ADD(CURDATE(),INTERVAL 60 DAY),20,'Lunes 18:00','abierta',:admin)");$q->execute(['a'=>$asignatura,'d'=>$docente,'codigo'=>'SEC-'.strtoupper($tag),'admin'=>$admin]);$seccion1=(int)$pdo->lastInsertId();$ids['secciones'][]=$seccion1;$assert((int)$pdo->query('SELECT capacidad_maxima FROM capacitacion_secciones WHERE id='.$seccion1)->fetchColumn()===20,'Las nuevas secciones usan inicialmente un máximo de 20 estudiantes');
 $pdo->beginTransaction();$asignada=asignarInscripcionPendiente($pdo,(int)$pendiente['id']);$pdo->commit();$assert($asignada['asignada']&&$asignada['inscripcion']['estado']==='inscrito','La búsqueda automática asigna una sección real con docente');
 $q=$pdo->prepare("SELECT COUNT(*) FROM correo_envios WHERE idempotency_key=:clave");$q->execute(['clave'=>'capacitacion-asignada:inscripcion:'.$pendiente['id']]);$assert((int)$q->fetchColumn()===1,'La asignación completa encola un único correo por evento');
 $pdo->beginTransaction();asignarInscripcionPendiente($pdo,(int)$pendiente['id']);$pdo->commit();$q->execute(['clave'=>'capacitacion-asignada:inscripcion:'.$pendiente['id']]);$assert((int)$q->fetchColumn()===1,'Reintentar no duplica la asignación ni el correo');
 $pago2=$crearPago($estudiante2);$pdo->beginTransaction();$segunda=asignarInscripcionAutomatica($pdo,$pago2);$pdo->commit();$ids['inscripciones'][]=(int)$segunda['id'];$assert((int)$segunda['seccion_id']===$seccion1,'La segunda inscripción usa la sección disponible');
 $pdo->prepare('UPDATE capacitacion_secciones SET capacidad_maxima=1 WHERE id=:id')->execute(['id'=>$seccion1]);$q=$pdo->prepare('SELECT capacidad_maxima,cantidad_actual FROM capacitacion_secciones WHERE id=:id');$q->execute(['id'=>$seccion1]);$reducida=$q->fetch();$assert((int)$reducida['capacidad_maxima']===1&&(int)$reducida['cantidad_actual']===2,'Reducir capacidad no expulsa estudiantes ya inscritos');
 $q=$pdo->prepare("INSERT INTO capacitacion_secciones(asignatura_id,docente_id,codigo,nombre,capacidad_maxima,estado,creada_por) VALUES(:a,:d,:codigo,'Sección destino',20,'abierta',:admin)");$q->execute(['a'=>$asignatura,'d'=>$docente,'codigo'=>'DST-'.strtoupper($tag),'admin'=>$admin]);$seccion2=(int)$pdo->lastInsertId();$ids['secciones'][]=$seccion2;$pdo->beginTransaction();moverInscripcionCapacitacion($pdo,(int)$segunda['id'],$seccion2,$admin,'Reorganización de grupo de prueba');$pdo->commit();$q=$pdo->prepare('SELECT seccion_id FROM inscripciones_capacitacion WHERE id=:id');$q->execute(['id'=>$segunda['id']]);$assert((int)$q->fetchColumn()===$seccion2,'El administrador puede mover estudiantes entre secciones');
 $q=$pdo->prepare('SELECT COUNT(*) FROM capacitacion_seccion_historial WHERE seccion_id IN(:s1,:s2)');$q->execute(['s1'=>$seccion1,'s2'=>$seccion2]);$assert((int)$q->fetchColumn()>=3,'Las asignaciones y movimientos quedan en el historial');
 $aula=file_get_contents(dirname(__DIR__,2).'/src/estudiantes/cursos.php');$assert(str_contains($aula,'máximo de 3 días')&&str_contains($aula,'Horario')&&str_contains($aula,'Docente'),'El aula muestra plazo, sección, docente, horario y fecha');
 $adminUi=file_get_contents(dirname(__DIR__,2).'/src/dashboard/capacitaciones/secciones.php');$assert(str_contains($adminUi,'auto-asignar.php')&&str_contains($adminUi,'capacidad inicial')&&str_contains($adminUi,'docente_id')&&str_contains($adminUi,'fecha'),'La administración incluye asignación automática y filtros solicitados');
 echo 'OK '.count($ok)." pruebas\n";foreach($ok as$m)echo '- '.$m."\n";
}finally{
 try{$pdo->prepare("DELETE FROM correo_envios WHERE usuario_id IN (".implode(',',array_fill(0,count($ids['usuarios']),'?')).')')->execute($ids['usuarios']);$pdo->prepare("DELETE FROM admin_notices WHERE user_id IN (".implode(',',array_fill(0,count($ids['usuarios']),'?')).')')->execute($ids['usuarios']);foreach($ids['inscripciones']as$inscripcionId){foreach(['capacitacion:sin-cupo:'.$inscripcionId.':u:%','capacitacion:pago-confirmado:'.$inscripcionId.':u:%','capacitacion:asignada:'.$inscripcionId.':u:%']as$patron)$pdo->prepare('DELETE FROM admin_notices WHERE idempotency_key LIKE ?')->execute([$patron]);}if($ids['inscripciones']){$marks=implode(',',array_fill(0,count($ids['inscripciones']),'?'));$pdo->prepare("DELETE FROM inscripcion_movimientos WHERE inscripcion_id IN($marks)")->execute($ids['inscripciones']);$pdo->prepare("DELETE FROM inscripciones_capacitacion WHERE id IN($marks)")->execute($ids['inscripciones']);}$pdo->prepare('DELETE FROM estudiantes_docentes WHERE asignatura_id=?')->execute([$asignatura??0]);if($ids['secciones']){$marks=implode(',',array_fill(0,count($ids['secciones']),'?'));$pdo->prepare("DELETE FROM capacitacion_seccion_historial WHERE seccion_id IN($marks)")->execute($ids['secciones']);$pdo->prepare("DELETE FROM capacitacion_secciones WHERE id IN($marks)")->execute($ids['secciones']);}if($ids['pagos']){$marks=implode(',',array_fill(0,count($ids['pagos']),'?'));$pdo->prepare("DELETE FROM capacitacion_pagos WHERE id IN($marks)")->execute($ids['pagos']);}$pdo->prepare('DELETE FROM docentes_asignaturas WHERE asignatura_id=?')->execute([$asignatura??0]);$pdo->prepare('DELETE FROM asignaturas WHERE id=?')->execute([$asignatura??0]);if($ids['usuarios']){$marks=implode(',',array_fill(0,count($ids['usuarios']),'?'));$pdo->prepare("DELETE FROM usuarios WHERE id IN($marks)")->execute($ids['usuarios']);}}catch(Throwable$e){fwrite(STDERR,'Limpieza etapa 10: '.$e->getMessage()."\n");}
}
