<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/newsletter.php';
require_once dirname(__DIR__,2).'/includes/permissions.php';
$pdo=obtenerConexion();$ok=[];$assert=static function(bool$c,string$m)use(&$ok):void{if(!$c)throw new RuntimeException($m);$ok[]=$m;};
try{
 foreach(['newsletter_suscriptores','newsletter_campanas','newsletter_envios']as$t)$assert((bool)$pdo->query("SHOW TABLES LIKE '$t'")->fetchColumn(),"Existe la tabla $t");
 $columnas=array_column($pdo->query('SHOW COLUMNS FROM asignaturas')->fetchAll(),'Field');foreach(['precio_anterior','promocion_etiqueta','promocion_desde','promocion_hasta']as$c)$assert(in_array($c,$columnas,true),"Capacitaciones incorpora $c");
 $pdo->beginTransaction();$pdo->exec("UPDATE newsletter_suscriptores SET estado='inactivo'");$tag='etapa3_'.bin2hex(random_bytes(5));$uno=suscribirNewsletterAtenea(strtoupper($tag).'@EXAMPLE.INVALID','Persona Uno','website_footer','127.0.0.1',$pdo);$dos=suscribirNewsletterAtenea($tag.'2@example.invalid','Persona Dos','website_footer','127.0.0.1',$pdo);$duplicado=suscribirNewsletterAtenea($tag.'@example.invalid',null,'website_footer','127.0.0.1',$pdo);$assert($uno['estado']==='creado'&&$duplicado['estado']==='existente','Normaliza el correo e impide duplicados');
 $q=$pdo->prepare('SELECT email,estado,token_baja,origen FROM newsletter_suscriptores WHERE id=:id');$q->execute(['id'=>$uno['id']]);$s=$q->fetch();$assert($s['email']===$tag.'@example.invalid'&&$s['origen']==='website_footer'&&preg_match('/^[a-f0-9]{64}$/',$s['token_baja'])===1,'Guarda origen, estado y token seguro');
 $assert(cambiarEstadoNewsletterPorTokenAtenea($s['token_baja'],false,$pdo)&&suscriptorNewsletterPorTokenAtenea($s['token_baja'],$pdo)['estado']==='inactivo','La baja usa token y conserva el registro');$assert(cambiarEstadoNewsletterPorTokenAtenea($s['token_baja'],true,$pdo),'El suscriptor puede reactivarse con token válido');
 $admin=(int)$pdo->query("SELECT id FROM usuarios WHERE rol='admin' ORDER BY id LIMIT 1")->fetchColumn();$q=$pdo->prepare("INSERT INTO newsletter_campanas(nombre,asunto,preencabezado,contenido,texto_boton,url_destino,tipo,estado,programada_at,aprobada_at,aprobada_por,creada_por) VALUES('Prueba etapa 3','Novedad de prueba','Contenido de prueba','Contenido aprobado','Ver capacitación',:url,'capacitacion','programada',NOW(),NOW(),:admin,:admin2)");$q->execute(['url'=>atenea_url_absoluta('src/website/courses.php'),'admin'=>$admin,'admin2'=>$admin]);$campana=(int)$pdo->lastInsertId();$total=encolarDestinatariosCampanaNewsletterAtenea($campana,$pdo);$total2=encolarDestinatariosCampanaNewsletterAtenea($campana,$pdo);$assert($total===2&&$total2===2,'Cada suscriptor recibe una sola fila por campaña aunque se reencole');
 $q=$pdo->prepare('SELECT * FROM newsletter_campanas WHERE id=:id');$q->execute(['id'=>$campana]);$c=$q->fetch();$q=$pdo->prepare('SELECT * FROM newsletter_suscriptores WHERE id=:id');$q->execute(['id'=>$dos['id']]);$dest=$q->fetch();$plantilla=renderizarCampanaNewsletterAtenea($c,$dest);$assert(str_contains($plantilla['html'],'Cancelar suscripción')&&!str_contains($plantilla['html'],'C:\\xampp\\htdocs'),'La plantilla incluye baja y nunca usa rutas locales');
 $correoId=encolarCorreoAtenea($dest['email'],$dest['nombre'],$plantilla['subject'],$plantilla['html'],$plantilla['text'],['tipo'=>'newsletter_campaign','idempotency_key'=>'test-newsletter:'.$tag]);$q=$pdo->prepare('SELECT estado,es_modo_prueba FROM correo_envios WHERE id=:id');$q->execute(['id'=>$correoId]);$correo=$q->fetch();$assert(correoModoPruebaAtenea()&&$correo['estado']==='cancelado'&&(int)$correo['es_modo_prueba']===1,'MAIL_TEST_MODE bloquea la entrega real durante pruebas');
 $assert(usuarioTienePermiso('newsletter.manage',['id'=>$admin,'rol'=>'admin'])&&!in_array('newsletter.view',permisosBaseAdministradorDocenteAtenea(),true),'Administrador gestiona y administrador docente no recibe acceso automático');
 $procesador=(string)file_get_contents(dirname(__DIR__,2).'/includes/newsletter.php');$assert(str_contains($procesador,'min(50,$limite)')&&str_contains($procesador,'LIMIT {$limite}'),'La cola limita cada lote a un máximo de 50');
 $cards=(string)file_get_contents(dirname(__DIR__,2).'/src/website/courses.php');$css=(string)file_get_contents(dirname(__DIR__,2).'/src/website/assets/css/main.css');$assert(str_contains($cards,'col-xl-4 col-md-6')&&str_contains($cards,'course-price-block')&&str_contains($css,'grid-template-columns: minmax(0,1fr)'),'Las tarjetas usan tres columnas, precio legible y acciones responsive');
 $pdo->rollBack();
}finally{if($pdo->inTransaction())$pdo->rollBack();}
echo'OK '.count($ok)." pruebas\n- ".implode("\n- ",$ok)."\n";
