<?php
declare(strict_types=1);require_once dirname(__DIR__,2).'/includes/comunicacion_centro.php';$pdo=obtenerConexion();$tag='c7e4_'.bin2hex(random_bytes(4));$usuarios=[];$conversacion=0;$ok=[];$assert=static function(bool$c,string$m)use(&$ok){if(!$c)throw new RuntimeException('FALLO: '.$m);$ok[]=$m;};
try{
 $crear=function(string$rol,int$n)use($pdo,$tag,&$usuarios):int{$q=$pdo->prepare("INSERT INTO usuarios(nombre,apellido,correo,password,rol,estado,email_verificado) VALUES(:n,'Chat',:c,:p,:r,'activo',1)");$q->execute(['n'=>'Temporal'.$n,'c'=>$tag.$n.'@example.invalid','p'=>password_hash(bin2hex(random_bytes(16)),PASSWORD_DEFAULT),'r'=>$rol]);$id=(int)$pdo->lastInsertId();$usuarios[]=$id;return$id;};$admin=$crear('admin',1);$docente1=$crear('docente',2);$docente2=$crear('docente',3);$estudiante=$crear('usuario',4);$estudiante2=$crear('usuario',5);
 $assert(contactoComunicacionPermitido($pdo,$admin,$estudiante),'Administración puede contactar cuentas activas');$assert(contactoComunicacionPermitido($pdo,$docente1,$docente2),'Los docentes pueden comunicarse entre sí');$assert(!contactoComunicacionPermitido($pdo,$estudiante,$estudiante2),'Dos estudiantes sin sección común no pueden comunicarse');$assert(!contactoComunicacionPermitido($pdo,$docente1,$estudiante),'Un docente no puede contactar estudiantes ajenos a sus secciones');
 $conversacion=abrirChatIndividual($pdo,$admin,$estudiante);$clave=hash('sha256',$tag.'mensaje');$_SESSION['usuario_id']=$admin;$_SESSION['usuario_rol']='admin';$mensaje=enviarMensajeChat($pdo,$conversacion,$admin,'Mensaje inicial',null,null,$clave);$repetido=enviarMensajeChat($pdo,$conversacion,$admin,'Mensaje inicial',null,null,$clave);$assert($mensaje===$repetido,'La idempotencia evita mensajes duplicados por doble clic');
 $lista=mensajesChatAtenea($pdo,$conversacion,$admin);$assert(count($lista)===1&&$lista[0]['estado_envio']==='enviado','El mensaje comienza con estado enviado');marcarChatEntregadoAtenea($pdo,$conversacion,$estudiante);$lista=mensajesChatAtenea($pdo,$conversacion,$admin);$assert($lista[0]['estado_envio']==='entregado','La recepción por AJAX cambia el estado a entregado');marcarChatLeido($pdo,$conversacion,$estudiante);$lista=mensajesChatAtenea($pdo,$conversacion,$admin);$assert($lista[0]['estado_envio']==='leido','La apertura de la conversación cambia el estado a leído');
 $_SESSION['usuario_id']=$estudiante;$_SESSION['usuario_rol']='usuario';$respuesta=enviarMensajeChat($pdo,$conversacion,$estudiante,'Respuesta al mensaje',$mensaje,null,hash('sha256',$tag.'respuesta'));$lista=mensajesChatAtenea($pdo,$conversacion,$estudiante);$ultima=$lista[array_key_last($lista)];$assert((int)$ultima['respuesta_a_id']===$mensaje&&$ultima['respuesta_contenido']==='Mensaje inicial','Las respuestas conservan la referencia al mensaje original');eliminarMensajeChatAtenea($pdo,$respuesta,$estudiante);$q=$pdo->prepare('SELECT estado,contenido,eliminado_por FROM chat_mensajes WHERE id=:id');$q->execute(['id'=>$respuesta]);$borrado=$q->fetch();$assert($borrado['estado']==='eliminado'&&$borrado['contenido']===''&&(int)$borrado['eliminado_por']===$estudiante,'El remitente puede eliminar su mensaje reciente sin destruir el registro');
 $columnas=array_column($pdo->query('SHOW COLUMNS FROM chat_mensajes')->fetchAll(),'Field');foreach(['respuesta_a_id','idempotency_key','entregado_at','eliminado_at','eliminado_por']as$c)$assert(in_array($c,$columnas,true),'La migración de chat incorpora '.$c);$contacto=file_get_contents(dirname(__DIR__,2).'/src/website/forms/contact.php');$assert(str_contains($contacto,"'idempotency_key'=>'contacto:'")&&str_contains($contacto,'formulario_id'),'Contacto usa cola idempotente y token de un solo uso');$js=file_get_contents(dirname(__DIR__,2).'/src/website/assets/js/contact-form.js');$assert(str_contains($js,'if(sending')&&str_contains($js,'button.disabled=true'),'El frontend bloquea múltiples envíos mientras procesa');$api=file_get_contents(dirname(__DIR__,2).'/src/comunicaciones/chat-api.php');$assert(str_contains($api,'guardarAdjuntoComunicacion')&&str_contains($api,'validarTokenCsrf'),'La API protege adjuntos y acciones con validación backend y CSRF');
 echo 'OK '.count($ok)." pruebas\n";foreach($ok as$m)echo '- '.$m."\n";
}finally{try{if($usuarios){$marks=implode(',',array_fill(0,count($usuarios),'?'));$pdo->prepare("DELETE FROM admin_notices WHERE created_by IN($marks) OR user_id IN($marks)")->execute(array_merge($usuarios,$usuarios));$pdo->prepare("DELETE FROM audit_logs WHERE actor_user_id IN($marks)")->execute($usuarios);}if($conversacion)$pdo->prepare('DELETE FROM chat_conversaciones WHERE id=:id')->execute(['id'=>$conversacion]);if($usuarios){$marks=implode(',',array_fill(0,count($usuarios),'?'));$pdo->prepare("DELETE FROM usuarios WHERE id IN($marks)")->execute($usuarios);}}catch(Throwable$e){fwrite(STDERR,'Limpieza: '.$e->getMessage()."\n");}}
