<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/academico_flujo.php';
$pdo=obtenerConexion();$tag='c6e4_'.bin2hex(random_bytes(4));$ok=[];$ids=[];$pdf=null;
$assert=function(bool $condicion,string $mensaje)use(&$ok):void{if(!$condicion)throw new RuntimeException('FALLO: '.$mensaje);$ok[]=$mensaje;};
try{
 $admin=(int)$pdo->query("SELECT id FROM usuarios WHERE rol='admin' ORDER BY id LIMIT 1")->fetchColumn();if(!$admin)throw new RuntimeException('Se requiere un administrador existente.');
 $crearUsuario=function(string $rol,string $sufijo)use($pdo,$tag,&$ids):int{$q=$pdo->prepare("INSERT INTO usuarios(nombre,apellido,correo,password,rol,estado,email_verificado) VALUES(:n,'Etapa4',:c,:p,:r,'activo',1)");$q->execute(['n'=>'Temporal '.$sufijo,'c'=>$tag.$sufijo.'@example.invalid','p'=>password_hash(bin2hex(random_bytes(16)),PASSWORD_DEFAULT),'r'=>$rol]);$id=(int)$pdo->lastInsertId();$ids['usuarios'][]=$id;return$id;};
 $docente=$crearUsuario('docente','docente');$otroDocente=$crearUsuario('docente','ajeno');$estudiante=$crearUsuario('usuario','estudiante');
 $q=$pdo->prepare("INSERT INTO asignaturas(codigo,nombre,slug,descripcion,tipo,precio,duracion,estado_capacitacion,cupo_seccion,certificado_disponible,activo,estado,creado_por) VALUES(:c,:n,:s,'Integración etapa 4','capacitacion',10,'40 horas','publicada',30,1,1,'activo',:u)");$q->execute(['c'=>$tag,'n'=>'Capacitación '.$tag,'s'=>$tag,'u'=>$admin]);$cap=(int)$pdo->lastInsertId();$ids['cap']=$cap;
 $pdo->prepare("INSERT INTO docentes_asignaturas(docente_id,asignatura_id,estado,asignado_por) VALUES(:d,:a,'activo',:u)")->execute(['d'=>$docente,'a'=>$cap,'u'=>$admin]);
 $q=$pdo->prepare("INSERT INTO capacitacion_secciones(asignatura_id,docente_id,codigo,nombre,capacidad_maxima,cantidad_actual,estado,creada_por) VALUES(:a,:d,:c,'Sección temporal',30,1,'abierta',:u)");$q->execute(['a'=>$cap,'d'=>$docente,'c'=>$tag.'-S1','u'=>$admin]);$seccion=(int)$pdo->lastInsertId();$ids['seccion']=$seccion;
 $q=$pdo->prepare("INSERT INTO capacitacion_pagos(usuario_id,asignatura_id,checkout_key,importe,moneda,estado,paid_at) VALUES(:u,:a,:k,10,'usd','pagado',NOW())");$q->execute(['u'=>$estudiante,'a'=>$cap,'k'=>hash('sha256',$tag)]);$pago=(int)$pdo->lastInsertId();$ids['pago']=$pago;
 $q=$pdo->prepare("INSERT INTO inscripciones_capacitacion(usuario_id,asignatura_id,pago_id,seccion_id,docente_id,estado,asignado_por,assigned_at) VALUES(:u,:a,:p,:s,:d,'inscrito',:admin,NOW())");$q->execute(['u'=>$estudiante,'a'=>$cap,'p'=>$pago,'s'=>$seccion,'d'=>$docente,'admin'=>$admin]);$ins=(int)$pdo->lastInsertId();$ids['ins']=$ins;
 $crearContenido=function(string $tipo,string $titulo,float $peso)use($pdo,$cap,$seccion,$docente,&$ids):int{$q=$pdo->prepare("INSERT INTO contenidos(asignatura_id,seccion_id,docente_id,modulo,tipo,titulo,descripcion,estado,activo,obligatorio,peso_progreso,fecha_publicacion) VALUES(:a,:s,:d,'Unidad 1',:t,:n,'Contenido temporal','activo',1,1,:p,NOW())");$q->execute(['a'=>$cap,'s'=>$seccion,'d'=>$docente,'t'=>$tipo,'n'=>$titulo,'p'=>$peso]);$id=(int)$pdo->lastInsertId();$ids['contenidos'][]=$id;return$id;};
 $texto=$crearContenido('texto','Lectura obligatoria',40);$actividad=$crearContenido('actividad','Actividad obligatoria',60);
 $assert(docentePoseeSeccion($pdo,$docente,$seccion),'El docente asignado puede administrar su sección');$assert(!docentePoseeSeccion($pdo,$otroDocente,$seccion),'Otro docente no puede modificar una sección ajena');
 $p=progresoInscripcion($pdo,$ins);$assert($p['porcentaje']===0.0,'Abrir o existir contenido no lo marca como completado');
 $pdo->prepare('INSERT INTO progreso_contenido(inscripcion_id,contenido_id,visto_at,ultima_actividad_at) VALUES(:i,:c,NOW(),NOW())')->execute(['i'=>$ins,'c'=>$texto]);$p=progresoInscripcion($pdo,$ins);$assert($p['porcentaje']===0.0&&$p['contenidos_vistos']===1,'Visualizar registra actividad pero no aumenta el progreso');
 $pdo->prepare('UPDATE progreso_contenido SET completado_at=NOW() WHERE inscripcion_id=:i AND contenido_id=:c')->execute(['i'=>$ins,'c'=>$texto]);$p=progresoInscripcion($pdo,$ins);$assert($p['porcentaje']===40.0,'Completar explícitamente un contenido informativo aplica su peso');
 $q=$pdo->prepare("INSERT INTO entregas_contenido(contenido_id,estudiante_id,asignatura_id,seccion_id,intento,comentario,estado) VALUES(:c,:u,:a,:s,1,'Primera entrega','rechazada')");$q->execute(['c'=>$actividad,'u'=>$estudiante,'a'=>$cap,'s'=>$seccion]);$entrega1=(int)$pdo->lastInsertId();$ids['entregas'][]=$entrega1;$p=progresoInscripcion($pdo,$ins);$assert(!$p['elegible']&&$p['entregas_rechazadas']===1,'Una actividad obligatoria rechazada bloquea el certificado');
 foreach([-0.01,10.01] as$invalida){$bloqueada=false;try{$pdo->prepare('UPDATE entregas_contenido SET nota=:n WHERE id=:i')->execute(['n'=>$invalida,'i'=>$entrega1]);}catch(PDOException){$bloqueada=true;}$assert($bloqueada,'MySQL rechaza la nota fuera de rango '.$invalida);}
 $q=$pdo->prepare("INSERT INTO entregas_contenido(contenido_id,estudiante_id,asignatura_id,seccion_id,intento,comentario,estado,nota,retroalimentacion,revisado_at,revisado_por) VALUES(:c,:u,:a,:s,2,'Corrección','aprobada',8.75,'Cumple los criterios',NOW(),:d)");$q->execute(['c'=>$actividad,'u'=>$estudiante,'a'=>$cap,'s'=>$seccion,'d'=>$docente]);$entrega2=(int)$pdo->lastInsertId();$ids['entregas'][]=$entrega2;
 $pdo->prepare("INSERT INTO entrega_revisiones(entrega_id,docente_id,estado_anterior,estado_nuevo,nota_nueva,retroalimentacion) VALUES(:e,:d,'enviada','aprobada',8.75,'Cumple los criterios')")->execute(['e'=>$entrega2,'d'=>$docente]);
 $p=progresoInscripcion($pdo,$ins);$assert($p['porcentaje']===100.0&&$p['elegible']&&$p['promedio']===8.75,'La entrega aprobada completa el progreso individual y calcula promedio');
 $cert1=generarCertificadoInscripcion($pdo,$ins,$docente);$cert2=generarCertificadoInscripcion($pdo,$ins,$docente);$assert((int)$cert1['id']===(int)$cert2['id'],'La emisión repetida es idempotente y no duplica certificados');$q=$pdo->prepare('SELECT COUNT(*) FROM certificados_capacitacion WHERE inscripcion_id=:i');$q->execute(['i'=>$ins]);$assert((int)$q->fetchColumn()===1,'Existe un único certificado por inscripción');$pdf=rutaPrivadaAcademica($cert1['pdf_relpath']);$assert($pdf!==null&&str_starts_with((string)file_get_contents($pdf,false,null,0,4),'%PDF'),'El certificado se genera como PDF privado usando la plantilla oficial');
 $assert(rutaPrivadaAcademica('../.env')===null,'El resolvedor privado bloquea traversal de rutas');$assert(urlVideoAcademicoValida('https://www.youtube.com/watch?v=abc')&&!urlVideoAcademicoValida('https://example.com/video.mp4'),'Los enlaces de video se limitan a proveedores autorizados');
 echo 'OK '.count($ok)." pruebas\n";foreach($ok as$m)echo '- '.$m."\n";
}finally{
 try{$pdo->beginTransaction();if(isset($ids['ins'])){$pdo->prepare('DELETE FROM admin_notices WHERE user_id IN (SELECT id FROM usuarios WHERE correo LIKE :c)')->execute(['c'=>$tag.'%@example.invalid']);$pdo->prepare('DELETE FROM certificados_capacitacion WHERE inscripcion_id=:i')->execute(['i'=>$ids['ins']]);$pdo->prepare('DELETE FROM entrega_revisiones WHERE entrega_id IN (SELECT id FROM entregas_contenido WHERE asignatura_id=:a)')->execute(['a'=>$ids['cap']]);$pdo->prepare('DELETE FROM entrega_evidencias WHERE entrega_id IN (SELECT id FROM entregas_contenido WHERE asignatura_id=:a)')->execute(['a'=>$ids['cap']]);$pdo->prepare('DELETE FROM entregas_contenido WHERE asignatura_id=:a')->execute(['a'=>$ids['cap']]);$pdo->prepare('DELETE FROM progreso_contenido WHERE inscripcion_id=:i')->execute(['i'=>$ids['ins']]);$pdo->prepare('DELETE FROM contenidos WHERE asignatura_id=:a')->execute(['a'=>$ids['cap']]);$pdo->prepare('DELETE FROM inscripciones_capacitacion WHERE id=:i')->execute(['i'=>$ids['ins']]);}$pdo->prepare('DELETE FROM capacitacion_secciones WHERE asignatura_id=:a')->execute(['a'=>$ids['cap']]);$pdo->prepare('DELETE FROM capacitacion_pagos WHERE asignatura_id=:a')->execute(['a'=>$ids['cap']]);$pdo->prepare('DELETE FROM docentes_asignaturas WHERE asignatura_id=:a')->execute(['a'=>$ids['cap']]);$pdo->prepare('DELETE FROM asignaturas WHERE id=:a')->execute(['a'=>$ids['cap']]);if(!empty($ids['usuarios'])){$marks=implode(',',array_fill(0,count($ids['usuarios']),'?'));$pdo->prepare("DELETE FROM usuarios WHERE id IN($marks)")->execute($ids['usuarios']);}$pdo->commit();if($pdf&&is_file($pdf))unlink($pdf);}catch(Throwable$cleanup){if($pdo->inTransaction())$pdo->rollBack();fwrite(STDERR,'Limpieza: '.$cleanup->getMessage()."\n");}
}
