<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/fixtures/etapa4_roles.php';
require_once dirname(__DIR__,2).'/includes/comunicacion_centro.php';
require_once dirname(__DIR__,2).'/includes/errores_sistema.php';
$pdo=obtenerConexion();$ok=[];$assert=function(bool $condicion,string $mensaje)use(&$ok):void{if(!$condicion)throw new RuntimeException($mensaje);$ok[]=$mensaje;};
try{
 $cuentas=etapa4Preparar($pdo);
 foreach(['actor_role','active_mode','route'] as$columna){$q=$pdo->query('SHOW COLUMNS FROM audit_logs LIKE '.$pdo->quote($columna));$assert((bool)$q->fetch(),"Bitácora contiene $columna");}
 foreach(['modo_activo','ruta','accion_intentada','correlacion_id'] as$columna){$q=$pdo->query('SHOW COLUMNS FROM errores_sistema LIKE '.$pdo->quote($columna));$assert((bool)$q->fetch(),"Errores contiene $columna");}
 $assert(permisoHibridoUsuarioAtenea($cuentas['ambos']['id'],'hybrid.admin.access'),'Cuenta con ambos modos accede a Administración');$assert(permisoHibridoUsuarioAtenea($cuentas['ambos']['id'],'hybrid.docente.access'),'Cuenta con ambos modos accede a Docencia');$assert(!permisoHibridoUsuarioAtenea($cuentas['solo_docente']['id'],'hybrid.admin.access'),'Cuenta solo Docente no accede a Administración');$assert(!permisoHibridoUsuarioAtenea($cuentas['solo_admin']['id'],'hybrid.docente.access'),'Cuenta solo Administración no accede a Docencia');$assert(!permisoHibridoUsuarioAtenea($cuentas['modulo_off']['id'],'users.view'),'Módulo desactivado se deniega en backend');$assert(permisoRutaAdministrativaHibridaAtenea('/Atenea/src/dashboard/usuarios/index.php')==='users.view','Ruta directa exige permiso de módulo');
 $_SESSION['usuario_id']=$cuentas['ambos']['id'];$_SESSION['usuario_rol']='administracion_docente';$_SESSION['hybrid_mode']='admin';$_SERVER['REQUEST_URI']='/Atenea/prueba-etapa4';$_SERVER['REQUEST_METHOD']='POST';registrarAuditoria(['event_type'=>'test.hybrid.audit','module'=>'tests','entity_type'=>'user','entity_id'=>$cuentas['ambos']['id'],'action'=>'verify','result'=>'success','description'=>'Verificación segura de contexto híbrido.']);$q=$pdo->prepare("SELECT actor_role,active_mode,route,request_id FROM audit_logs WHERE actor_user_id=:id AND event_type='test.hybrid.audit' ORDER BY id DESC LIMIT 1");$q->execute(['id'=>$cuentas['ambos']['id']]);$audit=$q->fetch();$assert($audit&&$audit['actor_role']==='administracion_docente'&&$audit['active_mode']==='admin','Bitácora guarda rol y modo activo');$assert((bool)preg_match('/^[a-f0-9]{32}$/',(string)$audit['request_id']),'Bitácora guarda correlación válida');
 $mensajeError='Intento de permiso etapa cuatro';for($i=0;$i<3;$i++)$errorId=registrarErrorSistemaAtenea('sistema','permissions',$mensajeError,['usuario_id'=>$cuentas['ambos']['id'],'accion'=>'open_users','ruta'=>'/src/dashboard/usuarios/index.php'],'advertencia',$pdo);$q=$pdo->prepare('SELECT ocurrencias,modo_activo,ruta,accion_intentada,correlacion_id FROM errores_sistema WHERE id=:id');$q->execute(['id'=>$errorId]);$error=$q->fetch();$assert((int)$error['ocurrencias']>=3&&$error['modo_activo']==='admin','Intentos repetidos conservan contexto y ocurrencias');$assert((bool)$error['correlacion_id'],'Error queda relacionado por correlación');$seguro=sanitizarContextoErrorAtenea(['password'=>'no-debe-verse','stripe_key'=>'no-debe-verse']);$assert($seguro['password']==='[oculto]'&&$seguro['stripe_key']==='[oculto]','Errores ocultan contraseñas y secretos');
 $_SESSION['usuario_id']=$cuentas['admin']['id'];$_SESSION['usuario_rol']='admin';unset($_SESSION['hybrid_mode']);$conversacion=abrirChatIndividual($pdo,$cuentas['admin']['id'],$cuentas['ambos']['id']);$clave=hash('sha256','etapa4-'.$cuentas['admin']['id'].'-'.microtime(true));$mensajeId=enviarMensajeChat($pdo,$conversacion,$cuentas['admin']['id'],'Mensaje administrativo importante',null,null,$clave);$repetido=enviarMensajeChat($pdo,$conversacion,$cuentas['admin']['id'],'Mensaje administrativo importante',null,null,$clave);$assert($mensajeId===$repetido,'Idempotencia evita mensajes duplicados');$q=$pdo->prepare('SELECT COUNT(*) FROM chat_mensajes WHERE conversacion_id=:c AND idempotency_key=:k');$q->execute(['c'=>$conversacion,'k'=>$clave]);$assert((int)$q->fetchColumn()===1,'La acción crea un solo mensaje interno');$q=$pdo->prepare("SELECT COUNT(*) FROM admin_notices WHERE user_id=:u AND type='chat_nuevo'");$q->execute(['u'=>$cuentas['ambos']['id']]);$assert((int)$q->fetchColumn()===1,'El mensaje crea una notificación no duplicada');$q=$pdo->prepare('SELECT COUNT(*) FROM correo_envios WHERE evento_id=:evento');$q->execute(['evento'=>'hybrid-chat:'.$mensajeId]);$assert((int)$q->fetchColumn()<=1,'El mensaje genera como máximo un correo');$assert(!chatParticipa($pdo,$conversacion,$cuentas['estudiante']['id']),'Otros usuarios no acceden a la conversación');
 $q=$pdo->prepare('SELECT estado FROM usuarios WHERE id=:id');$q->execute(['id'=>$cuentas['suspendido']['id']]);$assert($q->fetchColumn()==='inactivo','La cuenta suspendida permanece bloqueada');$assert(str_contains(file_get_contents(dirname(__DIR__,2).'/src/comunicaciones/assets/chat-modern.js'),'15000'),'El polling del chat se ejecuta cada 15 segundos');
 echo 'OK '.count($ok)." pruebas\n";foreach($ok as$mensaje)echo "- $mensaje\n";
}finally{$_SESSION=[];etapa4Limpiar($pdo);}
