<?php
require_once dirname(__DIR__) . '/_bootstrap.php';$pdo=obtenerConexion();$id=cmsId($_GET['id']??$_POST['id']??0);
$f=['id'=>0,'clave'=>'','nombre'=>'','titulo'=>'','subtitulo'=>'','descripcion'=>'','imagen'=>'','boton_texto'=>'','boton_url'=>'','activo'=>1,'orden'=>0];
if($id){$q=$pdo->prepare('SELECT * FROM secciones WHERE id=:id');$q->execute(['id'=>$id]);$f=$q->fetch()?:$f;if(!$f['id']){cmsFlash('error','La sección no existe.');header('Location: index.php');exit;}}
$errores=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!validarTokenCsrf($_POST['csrf_token']??null))$errores[]='El token de seguridad no es válido.';
 $clave=strtolower(trim((string)($_POST['clave']??'')));$nombre=trim((string)($_POST['nombre']??''));$titulo=trim((string)($_POST['titulo']??''));$subtitulo=trim((string)($_POST['subtitulo']??''));$descripcion=trim((string)($_POST['descripcion']??''));$botonTexto=trim((string)($_POST['boton_texto']??''));$botonUrl=trim((string)($_POST['boton_url']??''));$orden=(int)($_POST['orden']??0);$activo=isset($_POST['activo'])?1:0;
 if(!preg_match('/^[a-z0-9_-]{2,100}$/',$clave))$errores[]='La clave debe usar letras minúsculas, números, guion o guion bajo.';
 if($nombre===''||mb_strlen($nombre)>150)$errores[]='El nombre es obligatorio y admite hasta 150 caracteres.';
 if(mb_strlen($titulo)>255||mb_strlen($subtitulo)>255||mb_strlen($descripcion)>5000||mb_strlen($botonTexto)>100)$errores[]='Uno de los textos supera la longitud permitida.';
 if(!cmsUrlValida($botonUrl))$errores[]='La URL del botón no es válida.';
 $imagen=$f['imagen'];try{$nueva=cmsSubirImagen('imagen');if($nueva)$imagen=$nueva;}catch(RuntimeException $e){$errores[]=$e->getMessage();}
 if(!$errores){try{$pdo->beginTransaction();if($id){$q=$pdo->prepare('UPDATE secciones SET clave=:clave,nombre=:nombre,titulo=:titulo,subtitulo=:subtitulo,descripcion=:descripcion,imagen=:imagen,boton_texto=:boton_texto,boton_url=:boton_url,activo=:activo,orden=:orden WHERE id=:id');$datos=compact('clave','nombre','titulo','subtitulo','descripcion','imagen','activo','orden');$datos['boton_texto']=$botonTexto;$datos['boton_url']=$botonUrl;$datos['id']=$id;$q->execute($datos);}else{$q=$pdo->prepare('INSERT INTO secciones(clave,nombre,titulo,subtitulo,descripcion,imagen,boton_texto,boton_url,activo,orden) VALUES(:clave,:nombre,:titulo,:subtitulo,:descripcion,:imagen,:boton_texto,:boton_url,:activo,:orden)');$datos=compact('clave','nombre','titulo','subtitulo','descripcion','imagen','activo','orden');$datos['boton_texto']=$botonTexto;$datos['boton_url']=$botonUrl;$q->execute($datos);}$pdo->commit();if($id&&$imagen!==$f['imagen'])cmsEliminarImagenSiNoSeUsa($f['imagen']);cmsFlash('exito','La sección se guardó correctamente.');header('Location: index.php');exit;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log($e->getMessage());$errores[]='No fue posible guardar. Verifica que la clave no esté repetida.';}}
 $f=array_merge($f,compact('clave','nombre','titulo','subtitulo','descripcion','imagen','activo','orden'));$f['boton_texto']=$botonTexto;$f['boton_url']=$botonUrl;
}
cmsCabecera($id?'Editar sección':'Agregar sección','secciones/index.php');?>
<?php foreach($errores as $e):?><div class="alert alert-danger"><?=atenea_e($e)?></div><?php endforeach;?>
<form method="post" enctype="multipart/form-data" class="card"><div class="card-body row g-3"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$id?>">
<div class="col-md-6"><label class="form-label">Clave</label><input class="form-control" name="clave" maxlength="100" value="<?=atenea_e($f['clave'])?>" required></div><div class="col-md-6"><label class="form-label">Nombre</label><input class="form-control" name="nombre" maxlength="150" value="<?=atenea_e($f['nombre'])?>" required></div>
<div class="col-12"><label class="form-label">Título</label><input class="form-control" name="titulo" maxlength="255" value="<?=atenea_e((string)$f['titulo'])?>"></div><div class="col-12"><label class="form-label">Subtítulo</label><input class="form-control" name="subtitulo" maxlength="255" value="<?=atenea_e((string)$f['subtitulo'])?>"></div><div class="col-12"><label class="form-label">Descripción</label><textarea class="form-control" rows="5" name="descripcion"><?=atenea_e((string)$f['descripcion'])?></textarea></div>
<div class="col-md-6"><label class="form-label">Texto del botón</label><input class="form-control" name="boton_texto" maxlength="100" value="<?=atenea_e((string)$f['boton_texto'])?>"></div><div class="col-md-6"><label class="form-label">URL del botón</label><input class="form-control" name="boton_url" maxlength="500" value="<?=atenea_e((string)$f['boton_url'])?>" placeholder="src/website/about.php o https://..."></div>
<div class="col-md-6"><label class="form-label">Imagen JPG, PNG o WEBP</label><input class="form-control" type="file" name="imagen" accept=".jpg,.jpeg,.png,.webp"></div><div class="col-md-3"><label class="form-label">Orden</label><input class="form-control" type="number" name="orden" value="<?=(int)$f['orden']?>"></div><div class="col-md-3 d-flex align-items-end"><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="activo" <?=$f['activo']?'checked':''?>><label class="form-check-label">Activa</label></div></div>
<?php if($f['imagen']):?><div class="col-12"><p>Imagen actual</p><img class="preview-img" src="<?=rutaImagenContenido($f['imagen'])?>" alt=""></div><?php endif;?>
<div class="col-12"><a class="btn btn-secondary" href="index.php">Volver</a> <button class="btn btn-atenea">Guardar cambios</button></div></div></form><?php cmsPie();?>
