<?php
require_once dirname(__DIR__) . '/_bootstrap.php';
$pdo=obtenerConexion();$pagina=max(1,cmsId($_GET['pagina']??1));$porPagina=10;$total=(int)$pdo->query('SELECT COUNT(*) FROM secciones')->fetchColumn();$offset=($pagina-1)*$porPagina;
$q=$pdo->prepare('SELECT * FROM secciones ORDER BY orden,id LIMIT :limite OFFSET :offset');$q->bindValue('limite',$porPagina,PDO::PARAM_INT);$q->bindValue('offset',$offset,PDO::PARAM_INT);$q->execute();$filas=$q->fetchAll();
cmsCabecera('Secciones de la página de inicio','secciones/index.php');?>
<div class="mb-3"><a class="btn btn-atenea" href="editar.php">Agregar sección</a></div>
<div class="card"><div class="card-body"><div class="table-responsive"><table class="table"><thead><tr><th>Nombre</th><th>Título</th><th>Estado</th><th>Orden</th><th>Actualización</th><th>Acciones</th></tr></thead><tbody>
<?php if(!$filas):?><tr><td colspan="6" class="text-center py-5">No hay secciones registradas.</td></tr><?php endif;?>
<?php foreach($filas as $f):?><tr><td><?=atenea_e($f['nombre'])?><div class="small text-muted"><?=atenea_e($f['clave'])?></div></td><td><?=atenea_e((string)$f['titulo'])?></td><td><span class="badge bg-<?=$f['activo']?'success':'secondary'?>"><?=$f['activo']?'Activa':'Inactiva'?></span></td><td><?=$f['orden']?></td><td><?=atenea_e($f['updated_at'])?></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-primary" href="editar.php?id=<?=$f['id']?>">Editar</a> <a class="btn btn-sm btn-outline-dark" href="../elementos/index.php?seccion_id=<?=$f['id']?>">Elementos</a> <form class="d-inline" method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$f['id']?>"><input type="hidden" name="accion" value="toggle"><button class="btn btn-sm btn-outline-warning"><?=$f['activo']?'Desactivar':'Activar'?></button></form> <button class="btn btn-sm btn-outline-danger" data-bs-toggle="modal" data-bs-target="#eliminar<?=$f['id']?>">Eliminar</button></td></tr>
<div class="modal fade" id="eliminar<?=$f['id']?>" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h2 class="h5 modal-title">Eliminar sección</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">Se eliminará “<?=atenea_e($f['nombre'])?>” y todos sus elementos relacionados. Esta acción no se puede deshacer.</div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button><form method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$f['id']?>"><input type="hidden" name="accion" value="eliminar"><button class="btn btn-danger">Eliminar</button></form></div></div></div></div>
<?php endforeach;?></tbody></table></div>
<?php $paginas=max(1,(int)ceil($total/$porPagina));if($paginas>1):?><nav><ul class="pagination"><?php for($i=1;$i<=$paginas;$i++):?><li class="page-item <?=$i===$pagina?'active':''?>"><a class="page-link" href="?pagina=<?=$i?>"><?=$i?></a></li><?php endfor?></ul></nav><?php endif;?>
</div></div><?php cmsPie();?>
