<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/cms.php';
require_once dirname(__DIR__, 3) . '/includes/mailer.php';
exigirPermiso('mail.manage');
$pdo = obtenerConexion();
$estados = ['pendiente','procesando','enviado','fallido','cancelado'];
$estado = in_array((string)($_GET['estado'] ?? ''), $estados, true) ? (string)$_GET['estado'] : '';
$tipo = mb_substr(trim(strip_tags((string)($_GET['tipo'] ?? ''))), 0, 80);
$where=[];$params=[];
if($estado!==''){$where[]='estado=:estado';$params['estado']=$estado;}
if($tipo!==''){$where[]='tipo=:tipo';$params['tipo']=$tipo;}
$q=$pdo->prepare('SELECT id,tipo,asunto,destinatario_enmascarado,evento_id,estado,intento,max_intentos,agrupados,error_sanitizado,cancelado_motivo,enviado_at,created_at FROM correo_envios'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY id DESC LIMIT 250');$q->execute($params);$correos=$q->fetchAll();
$resumen=$pdo->query('SELECT estado,COUNT(*) total FROM correo_envios GROUP BY estado')->fetchAll(PDO::FETCH_KEY_PAIR);
$destinoPrueba=correoDestinatarioPruebaAtenea();
cmsCabecera('Cola e historial de correos','comunicaciones/correos.php','Control de entregas, reintentos, duplicados y pruebas autorizadas.');
?>
<div class="row g-4 mb-4"><div class="col-lg-8"><div class="card card-rounded h-100"><div class="card-body"><h2 class="h5">Estado de la cola</h2><p><?php foreach($estados as$e):?><span class="badge bg-secondary me-2"><?=atenea_e(ucfirst($e))?>: <?=(int)($resumen[$e]??0)?></span><?php endforeach;?></p><div class="alert <?=correoModoPruebaAtenea()?'alert-warning':'alert-success'?> mb-0"><strong>Modo de pruebas:</strong> <?=correoModoPruebaAtenea()?'activo; los correos ordinarios se guardan y cancelan sin salir por SMTP.':'inactivo; el procesador puede realizar entregas reales.'?></div></div></div></div>
<div class="col-lg-4"><div class="card card-rounded h-100"><div class="card-body"><h2 class="h5">Probar un solo correo</h2><p class="small text-muted">Solo se admite la dirección configurada en MAIL_TEST_RECIPIENT. Esta acción nunca usa la base de usuarios.</p><?php if($destinoPrueba===''):?><div class="alert alert-warning">Configura una dirección autorizada antes de realizar la prueba.</div><?php else:?><form method="post" action="correo-accion.php" data-atenea-confirm="send" data-atenea-confirm-title="Confirmar correo de prueba" data-atenea-confirm-message="Se intentará enviar un único correo a la dirección autorizada."><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="probar"><label class="form-label" for="correo_prueba">Dirección autorizada</label><input class="form-control" id="correo_prueba" type="email" name="correo" maxlength="190" required><label class="form-label mt-3" for="confirmacion">Escribe ENVIAR PRUEBA</label><input class="form-control" id="confirmacion" name="confirmacion" maxlength="20" pattern="ENVIAR PRUEBA" required><div class="form-check mt-3"><input class="form-check-input" id="aceptar" type="checkbox" name="aceptar" value="1" required><label class="form-check-label" for="aceptar">Confirmo el envío real de un solo mensaje.</label></div><button class="btn btn-primary mt-3">Enviar prueba autorizada</button></form><?php endif;?></div></div></div></div>
<div class="card card-rounded"><div class="card-body"><form class="row g-2 mb-4" method="get"><div class="col-md-4"><label class="form-label">Estado</label><select class="form-select" name="estado"><option value="">Todos</option><?php foreach($estados as$e):?><option value="<?=$e?>" <?=$estado===$e?'selected':''?>><?=atenea_e(ucfirst($e))?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Tipo exacto</label><input class="form-control" name="tipo" maxlength="80" value="<?=atenea_e($tipo)?>"></div><div class="col-md-4 d-flex align-items-end"><button class="btn btn-outline-primary">Filtrar historial</button></div></form><div class="table-responsive"><table class="table"><thead><tr><th>Evento</th><th>Destinatario</th><th>Estado</th><th>Intentos</th><th>Fecha</th></tr></thead><tbody><?php foreach($correos as$c):?><tr><td><strong><?=atenea_e($c['tipo'])?></strong><small class="d-block text-muted"><?=atenea_e((string)$c['asunto'])?></small><small class="d-block">ID: <?=atenea_e((string)$c['evento_id'])?><?=$c['agrupados']>1?' · '.(int)$c['agrupados'].' agrupados':''?></small></td><td><?=atenea_e($c['destinatario_enmascarado'])?></td><td><span class="badge bg-secondary"><?=atenea_e($c['estado'])?></span><?php if($c['error_sanitizado']||$c['cancelado_motivo']):?><small class="d-block text-muted"><?=atenea_e((string)($c['error_sanitizado']?:$c['cancelado_motivo']))?></small><?php endif;?></td><td><?=(int)$c['intento']?> / <?=(int)$c['max_intentos']?></td><td><?=atenea_e((string)($c['enviado_at']?:$c['created_at']))?></td></tr><?php endforeach;?><?php if(!$correos):?><tr><td colspan="5" class="text-center py-4">No hay correos para este filtro.</td></tr><?php endif;?></tbody></table></div></div></div>
<?php cmsPie();
