ALTER TABLE `public_users`
  ADD COLUMN IF NOT EXISTS `PROFILE_PHOTO` VARCHAR(255) NULL AFTER `PHONE_NUMBER`;

ALTER TABLE `public_users`
  ADD COLUMN IF NOT EXISTS `BIRTHDATE` DATE NULL AFTER `PROFILE_PHOTO`;

ALTER TABLE `public_users`
  ADD COLUMN IF NOT EXISTS `GOOGLE_ID` VARCHAR(191) NULL AFTER `BIRTHDATE`;

ALTER TABLE `public_users`
  ADD COLUMN IF NOT EXISTS `GOOGLE_EMAIL` VARCHAR(150) NULL AFTER `GOOGLE_ID`;

ALTER TABLE `public_users`
  ADD COLUMN IF NOT EXISTS `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `public_users`
  ADD COLUMN IF NOT EXISTS `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
