<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/auth.php';
require_once dirname(__DIR__,2).'/includes/portal_estudiante.php';
require_once dirname(__DIR__,2).'/includes/alerts.php';
$token=(string)($_GET['token']??$_SESSION['assisted_token_return']??'');unset($_SESSION['assisted_token_return']);
$valido=false;if(preg_match('/^[a-f0-9]{64}$/',$token)){try{$q=obtenerConexion()->prepare('SELECT id FROM assisted_password_resets WHERE recovery_token_hash=:hash AND verified_at IS NOT NULL AND token_used_at IS NULL AND cancelled_at IS NULL AND token_expires_at>NOW() LIMIT 1');$q->execute(['hash'=>hash('sha256',$token)]);$valido=(bool)$q->fetchColumn();}catch(Throwable $e){error_log('Validacion recuperacion asistida: '.$e->getMessage());}}
$errores=is_array($_SESSION['assisted_reset_errors']??null)?$_SESSION['assisted_reset_errors']:[];unset($_SESSION['assisted_reset_errors']);$logo=atenea_url(obtenerConfiguracionPortalEstudiante('portal_logo'));
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Recuperacion asistida | Atenea</title><link rel="icon" type="image/png" href="<?= $logo ?>"><link rel="stylesheet" href="<?= atenea_url('src/estudiantes/dashboard_estudiantes/dashboard/assets/vendors/css/vendor.bundle.base.css') ?>"><link rel="stylesheet" href="<?= atenea_url('src/estudiantes/dashboard_estudiantes/dashboard/assets/css/style.css') ?>"><link rel="stylesheet" href="<?= atenea_url('src/login/auth.css') ?>"><?php ateneaAlertasHead();?></head><body><div class="wrapper"><section class="login-content"><div class="row m-0 align-items-center bg-white min-vh-100"><div class="col-md-6 py-4"><div class="row justify-content-center"><div class="col-md-10 col-xl-8"><div class="card card-transparent shadow-none auth-card"><div class="card-body"><a href="<?= atenea_url('index.php') ?>" class="navbar-brand atenea-auth-logo d-flex justify-content-center mb-3"><img src="<?= $logo ?>" alt="Atenea"></a><h1 class="h2 text-center">Crear nueva contrasena</h1>
<?php if(!$valido):?><div class="alert alert-warning">Este enlace no es valido, ya fue utilizado o expiro.</div><a class="btn btn-primary w-100" href="<?= atenea_url('src/login/forgot-password.php') ?>">Usar recuperacion normal</a><?php else:?><p class="text-center">Usa al menos 12 caracteres con mayusculas, minusculas, numeros y simbolos. El administrador no puede ver esta contrasena.</p><?php if($errores):?><div class="alert alert-danger"><ul class="mb-0"><?php foreach($errores as $error):?><li><?= atenea_e((string)$error) ?></li><?php endforeach;?></ul></div><?php endif;?><form method="post" action="<?= atenea_url('src/auth/restablecer-asistido.php') ?>" data-atenea-loading><input type="hidden" name="csrf_token" value="<?= atenea_e(obtenerTokenCsrf()) ?>"><input type="hidden" name="token" value="<?= atenea_e($token) ?>"><div class="form-group"><label class="form-label" for="password">Nueva contrasena</label><input class="form-control" type="password" id="password" name="password" minlength="12" maxlength="255" autocomplete="new-password" required></div><div class="form-group"><label class="form-label" for="confirmar_password">Confirmar contrasena</label><input class="form-control" type="password" id="confirmar_password" name="confirmar_password" minlength="12" maxlength="255" autocomplete="new-password" required></div><button class="btn btn-primary w-100">Guardar nueva contrasena</button></form><?php endif;?></div></div></div></div></div><div class="col-md-6 d-md-block d-none bg-primary p-0 vh-100 overflow-hidden"><img src="<?= recursoPortalEstudiante('login_imagen_lateral','src/estudiantes/dashboard_estudiantes/dashboard/assets/images/dashboard/darkBG.png') ?>" class="img-fluid gradient-main animated-scaleX" alt="Seguridad de cuenta"></div></div></section></div><script src="<?= atenea_url('src/estudiantes/dashboard_estudiantes/dashboard/assets/vendors/js/vendor.bundle.base.js') ?>"></script><script src="<?=atenea_url('src/website/assets/js/security-ui.js')?>"></script><?php ateneaAlertasScripts($errores?['type'=>'error','title'=>'Revisa la contrasena','message'=>implode("\n",array_map('strval',$errores))]:null);?></body></html>
