<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/includes/auth.php';
require_once dirname(__DIR__, 2) . '/includes/portal_estudiante.php';
if (usuarioAutenticado()) redirigirPorRol();
$mensaje = (string) ($_SESSION['mensaje_auth'] ?? '');
$correo = (string) ($_SESSION['login_correo'] ?? '');
unset($_SESSION['mensaje_auth'], $_SESSION['login_correo']);
$google = require dirname(__DIR__, 2) . '/config/google.php';
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= atenea_e(obtenerConfiguracionPortalEstudiante('login_titulo')) ?> | Atenea</title><link rel="icon" href="<?= atenea_url('img/atenea-logo.png') ?>"><link rel="stylesheet" href="<?= atenea_url('src/estudiantes/assets/css/core/libs.min.css') ?>"><link rel="stylesheet" href="<?= atenea_url('src/estudiantes/assets/css/hope-ui.min.css') ?>"></head>
<body><div id="loading"><div class="loader simple-loader"><div class="loader-body"></div></div></div><div class="wrapper"><section class="login-content"><div class="row m-0 align-items-center bg-white vh-100"><div class="col-md-6"><div class="row justify-content-center"><div class="col-md-10"><div class="card card-transparent shadow-none auth-card"><div class="card-body">
<a href="<?= atenea_url() ?>" class="navbar-brand d-flex justify-content-center mb-3"><img src="<?= atenea_url(obtenerConfiguracionPortalEstudiante('portal_logo')) ?>" style="max-height:85px" alt="Atenea"></a><h2 class="mb-2 text-center"><?= atenea_e(obtenerConfiguracionPortalEstudiante('login_titulo')) ?></h2><p class="text-center"><?= atenea_e(obtenerConfiguracionPortalEstudiante('login_subtitulo')) ?></p>
<?php if ($mensaje !== ''): ?><div class="alert alert-danger"><?= atenea_e($mensaje) ?></div><?php endif; ?>
<form method="post" action="<?= atenea_url('src/auth/procesar_login.php') ?>"><input type="hidden" name="csrf_token" value="<?= atenea_e(obtenerTokenCsrf()) ?>"><div class="form-group"><label class="form-label" for="correo">Correo electrónico</label><input class="form-control" type="email" id="correo" name="correo" value="<?= atenea_e($correo) ?>" maxlength="190" autocomplete="username" required></div><div class="form-group"><label class="form-label" for="password">Contraseña</label><input class="form-control" type="password" id="password" name="password" maxlength="255" autocomplete="current-password" required></div><div class="d-flex justify-content-between"><label><input type="checkbox" name="recordar" value="1"> Recordarme</label><span class="text-muted">¿Olvidaste tu contraseña?</span></div><div class="d-flex justify-content-center mt-3"><button class="btn btn-primary" type="submit"><?= atenea_e(obtenerConfiguracionPortalEstudiante('login_texto_boton')) ?></button></div><p class="text-center my-3">O continúa con</p><div class="text-center"><?php if ($google['client_id'] !== ''): ?><div id="google-button"></div><?php else: ?><button class="btn btn-outline-primary" type="button" disabled>Continuar con Google</button><small class="d-block text-muted mt-2">Google pendiente de configuración</small><?php endif; ?></div><p class="mt-3 text-center">¿Aún no tienes una cuenta? <a href="<?= atenea_url('src/login/sign-up.php') ?>">Regístrate</a></p></form>
</div></div></div></div><div class="sign-bg"></div></div><div class="col-md-6 d-md-block d-none bg-primary p-0 vh-100 overflow-hidden"><img src="<?= atenea_url(obtenerConfiguracionPortalEstudiante('login_imagen_lateral')) ?>" class="img-fluid gradient-main animated-scaleX" alt="Acceso Atenea"></div></div></section></div>
<script src="<?= atenea_url('src/estudiantes/assets/js/core/libs.min.js') ?>"></script>
<?php if ($google['client_id'] !== ''): ?><script src="https://accounts.google.com/gsi/client" async defer></script><script>window.onload=()=>{google.accounts.id.initialize({client_id:<?= json_encode($google['client_id']) ?>,callback:r=>{const f=document.createElement('form');f.method='post';f.action=<?= json_encode(atenea_url('src/auth/google.php')) ?>;for(const[n,v]of Object.entries({credential:r.credential,csrf_token:<?= json_encode(obtenerTokenCsrf()) ?>})){const i=document.createElement('input');i.type='hidden';i.name=n;i.value=v;f.appendChild(i)}document.body.appendChild(f);f.submit()}});google.accounts.id.renderButton(document.getElementById('google-button'),{theme:'outline',size:'large',text:'continue_with'})};</script><?php endif; ?>
<script src="<?= atenea_url('src/estudiantes/assets/js/hope-ui.js') ?>" defer></script></body></html>
