<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/portal_estudiante_layout.php';
require_once dirname(__DIR__,2).'/includes/carrito.php';
$portal=portalEstudianteCabecera('Mi carrito','carrito','Revisa cantidades, disponibilidad y totales antes de continuar.');$r=resumenCarrito(obtenerConexion(),(int)$_SESSION['usuario_id']);
?>
<div class="row g-4"><div class="col-lg-8"><div class="card"><div class="card-body"><h2 class="h4 mb-4">Carrito de compras</h2>
<?php if(!$r['items']):?><div class="text-center py-5"><i class="bi bi-cart-x display-4 text-muted"></i><p class="mt-3 text-muted">Tu carrito está vacío.</p><a class="btn btn-primary" href="<?=atenea_url('src/website/pricing.php')?>">Ver productos</a></div><?php endif;?>
<?php foreach($r['items'] as $i):?><div class="row align-items-center border-bottom py-3 g-2"><div class="col-md-5"><strong><?=atenea_e($i['nombre'])?></strong><small class="d-block text-muted">$<?=centavosDinero($i['precio_centavos'])?> por unidad · <?=intval($i['disponible_real'])?> disponibles</small></div><div class="col-md-4"><form class="d-flex gap-2" method="post" action="<?=atenea_url('src/carrito/accion.php')?>"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="actualizar"><input type="hidden" name="producto_id" value="<?=$i['id']?>"><input class="form-control" type="number" name="cantidad" min="1" max="<?=max(1,(int)$i['disponible_real'])?>" value="<?=$i['cantidad']?>" aria-label="Cantidad"><button class="btn btn-outline-primary">Actualizar</button></form></div><div class="col-md-2 text-end"><strong>$<?=centavosDinero($i['linea_centavos'])?></strong></div><div class="col-md-1"><form method="post" action="<?=atenea_url('src/carrito/accion.php')?>"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="eliminar"><input type="hidden" name="producto_id" value="<?=$i['id']?>"><button class="btn btn-sm btn-outline-danger" aria-label="Eliminar"><i class="bi bi-trash"></i></button></form></div></div><?php endforeach;?>
<?php if($r['items']):?><form class="mt-3" method="post" action="<?=atenea_url('src/carrito/accion.php')?>" data-atenea-confirm="vaciar-carrito"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="vaciar"><button class="btn btn-light">Vaciar carrito</button></form><?php endif;?></div></div></div>
<div class="col-lg-4"><div class="card"><div class="card-body"><h2 class="h5">Resumen</h2><div class="d-flex justify-content-between"><span>Subtotal</span><span>$<?=centavosDinero($r['subtotal'])?></span></div><div class="d-flex justify-content-between"><span>Descuento</span><span>-$<?=centavosDinero($r['descuento'])?></span></div><div class="d-flex justify-content-between"><span>Envío</span><span>$<?=centavosDinero($r['envio'])?></span></div><div class="d-flex justify-content-between"><span>Impuestos</span><span>$<?=centavosDinero($r['impuesto'])?></span></div><hr><div class="d-flex justify-content-between h5"><span>Total</span><span>$<?=centavosDinero($r['total'])?></span></div><?php if($r['items']):?><a class="btn btn-primary w-100" href="<?=atenea_url('src/estudiantes/checkout.php')?>">Continuar con dirección</a><?php endif;?></div></div></div></div>
<?php portalEstudiantePie();
