<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/portal_estudiante_layout.php';
require_once dirname(__DIR__,2).'/includes/academico_flujo.php';
$portal=portalEstudianteCabecera('Certificados','certificados','Genera y descarga tus certificados académicos.');$pdo=obtenerConexion();$usuario=(int)$portal['perfil']['id'];
$q=$pdo->prepare("SELECT i.id,i.estado,a.nombre capacitacion,a.duracion,a.certificado_disponible,s.codigo seccion,c.id certificado_id,c.numero,c.emitido_at,c.estado certificado_estado FROM inscripciones_capacitacion i JOIN asignaturas a ON a.id=i.asignatura_id LEFT JOIN capacitacion_secciones s ON s.id=i.seccion_id LEFT JOIN certificados_capacitacion c ON c.inscripcion_id=i.id WHERE i.usuario_id=:u AND i.estado IN('inscrito','finalizado') ORDER BY i.created_at DESC");$q->execute(['u'=>$usuario]);$filas=$q->fetchAll();
?>
<div class="row"><div class="col-12"><div class="card"><div class="card-header"><h1 class="card-title">Mis certificados</h1></div><div class="card-body"><div class="row g-4"><?php foreach($filas as$f):$p=progresoInscripcion($pdo,(int)$f['id']);?><div class="col-lg-6"><article class="border rounded p-4 h-100"><div class="d-flex gap-3"><i class="bi bi-award fs-1 text-warning"></i><div class="flex-grow-1"><h2 class="h5"><?=atenea_e($f['capacitacion'])?></h2><p class="text-muted mb-2">Sección <?=atenea_e((string)$f['seccion'])?> · Progreso <?=$p['porcentaje']?>%</p><?php if($f['certificado_id']&&$f['certificado_estado']==='emitido'):?><p class="small mb-2">Número: <strong><?=atenea_e($f['numero'])?></strong><br>Emitido: <?=atenea_e((string)$f['emitido_at'])?></p><a class="btn btn-success" href="<?=atenea_url('src/academico/archivo.php?tipo=certificado&id='.(int)$f['certificado_id'])?>"><i class="bi bi-download"></i> Descargar PDF</a><?php elseif(!(int)$f['certificado_disponible']):?><span class="badge bg-secondary">Esta capacitación no ofrece certificado</span><?php elseif($p['elegible']):?><form method="post" action="certificado-generar.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="inscripcion_id" value="<?=$f['id']?>"><button class="btn btn-warning">Generar certificado individual</button></form><?php else:?><div class="alert alert-light border mb-0">Faltan contenidos o actividades obligatorias por aprobar. Un contenido abierto no cuenta como completado.</div><?php endif;?></div></div></article></div><?php endforeach;?><?php if(!$filas):?><div class="col-12 text-center py-5"><i class="bi bi-award display-3 text-warning"></i><h2 class="h4 mt-3">Aún no tienes capacitaciones con certificado</h2></div><?php endif;?></div></div></div></div></div>
<?php portalEstudiantePie();
