<?php
declare(strict_types=1);require_once dirname(__DIR__,2).'/includes/portal_estudiante_layout.php';require_once dirname(__DIR__,2).'/includes/academico_flujo.php';
exigirPerfilCompleto();$id=filter_var($_GET['id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$pdo=obtenerConexion();
$q=$pdo->prepare("SELECT c.*,a.nombre capacitacion,s.codigo seccion,i.id inscripcion_id FROM contenidos c JOIN asignaturas a ON a.id=c.asignatura_id JOIN capacitacion_secciones s ON s.id=c.seccion_id JOIN inscripciones_capacitacion i ON i.seccion_id=c.seccion_id AND i.asignatura_id=c.asignatura_id WHERE c.id=:id AND i.usuario_id=:u AND i.estado IN('inscrito','finalizado') AND c.estado='activo' AND c.activo=1 AND (c.fecha_publicacion IS NULL OR c.fecha_publicacion<=NOW())");$q->execute(['id'=>$id,'u'=>$_SESSION['usuario_id']]);$c=$q->fetch();if(!$c)mostrarPaginaErrorAtenea(403);
$pdo->prepare('INSERT INTO progreso_contenido(inscripcion_id,contenido_id,visto_at,ultima_actividad_at) VALUES(:i,:c,NOW(),NOW()) ON DUPLICATE KEY UPDATE visto_at=COALESCE(visto_at,NOW()),ultima_actividad_at=NOW()')->execute(['i'=>$c['inscripcion_id'],'c'=>$id]);$q=$pdo->prepare('SELECT * FROM entregas_contenido WHERE contenido_id=:c AND estudiante_id=:u ORDER BY intento DESC');$q->execute(['c'=>$id,'u'=>$_SESSION['usuario_id']]);$entregas=$q->fetchAll();$ultima=$entregas[0]??null;$puedeEntregar=in_array($c['tipo'],['actividad','evaluacion'],true)&&(!$ultima||in_array($ultima['estado'],['rechazada','requiere_correccion'],true));$activo=match($c['tipo']){'video'=>'videos','actividad'=>'tareas','evaluacion'=>'evaluaciones',default=>'contenidos'};$portal=portalEstudianteCabecera($c['titulo'],$activo,$c['capacitacion'].' · '.$c['seccion']);
?>
<div class="card"><div class="card-body"><span class="badge bg-primary"><?=atenea_e($c['modulo'])?></span> <span class="badge bg-secondary"><?=atenea_e(ucfirst($c['tipo']))?></span><h1 class="h3 mt-3"><?=atenea_e($c['titulo'])?></h1><p><?=nl2br(atenea_e((string)$c['descripcion']))?></p><?php if($c['video_url']):?><p><a class="btn btn-outline-primary" target="_blank" rel="noopener noreferrer" href="<?=atenea_e($c['video_url'])?>">Abrir video autorizado</a></p><?php endif;?><?php if($c['archivo_relpath']):?><p><a class="btn btn-outline-secondary" href="<?=atenea_url('src/academico/archivo.php?tipo=contenido&id='.(int)$c['id'])?>"><?=$c['tipo']==='video'?'Reproducir video privado':'Descargar recurso'?></a></p><?php endif;?>
<?php if(!in_array($c['tipo'],['actividad','evaluacion'],true)):?><form method="post" action="<?=atenea_url('src/estudiantes/contenido-accion.php')?>"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="completar"><input type="hidden" name="contenido_id" value="<?=$id?>"><button class="btn btn-success">Marcar como estudiado</button></form><?php elseif($puedeEntregar):?><hr><h2 class="h5">Enviar entrega</h2><form method="post" action="<?=atenea_url('src/estudiantes/contenido-accion.php')?>" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="entregar"><input type="hidden" name="contenido_id" value="<?=$id?>"><div class="mb-3"><label class="form-label" for="comentario">Comentario o explicación</label><textarea class="form-control" id="comentario" name="comentario" maxlength="5000" rows="4" required></textarea></div><div class="mb-3"><label class="form-label" for="resultado">Resultado de la práctica</label><textarea class="form-control" id="resultado" name="resultado" maxlength="10000" rows="4"></textarea></div><div class="mb-3"><label class="form-label" for="evidencias">Evidencias (máximo 5, 10 MB cada una)</label><input class="form-control" id="evidencias" type="file" name="evidencias[]" multiple accept=".pdf,.doc,.docx,.jpg,.jpeg,.png,.webp"></div><button class="btn btn-primary">Enviar para revisión</button></form><?php elseif($ultima):?><div class="alert alert-info">Última entrega: <?=atenea_e(ucfirst(str_replace('_',' ',$ultima['estado'])))?><?php if($ultima['nota']!==null):?> · Nota <?=number_format((float)$ultima['nota'],2)?>/10<?php endif;?><br><?=nl2br(atenea_e((string)$ultima['retroalimentacion']))?></div><?php endif;?>
<?php if($entregas):?><hr><h2 class="h5">Historial de intentos</h2><?php foreach($entregas as$e):?><div class="border rounded p-3 mb-2">Intento <?=(int)$e['intento']?> · <?=atenea_e(ucfirst(str_replace('_',' ',$e['estado'])))?> · <?=date('d/m/Y H:i',strtotime($e['enviado_at']))?><?php if($e['nota']!==null):?> · <?=number_format((float)$e['nota'],2)?>/10<?php endif;?></div><?php endforeach;?><?php endif;?></div></div><?php portalEstudiantePie();
