<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/portal_estudiante_layout.php';require_once dirname(__DIR__,2).'/includes/contenido_clase.php';
$portal=portalEstudianteCabecera('Contenido de clase','contenidos','Publicaciones y recursos de tus clases activas.');$pdo=obtenerConexion();$usuario=(int)$portal['perfil']['id'];$asignatura=filter_var($_GET['asignatura']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$buscar=trim((string)($_GET['q']??''));$pagina=max(1,(int)($_GET['pagina']??1));$limite=9;
$q=$pdo->prepare("SELECT DISTINCT a.id,a.nombre FROM inscripciones_capacitacion i JOIN asignaturas a ON a.id=i.asignatura_id WHERE i.usuario_id=:u AND i.estado IN('inscrito','finalizado') ORDER BY a.nombre");$q->execute(['u'=>$usuario]);$clases=$q->fetchAll();
$where=["i.usuario_id=:u","i.estado IN('inscrito','finalizado')","c.estado='activo'","c.activo=1","c.eliminado_at IS NULL","(c.fecha_publicacion IS NULL OR c.fecha_publicacion<=NOW())"];$params=['u'=>$usuario];if($asignatura){$where[]='c.asignatura_id=:a';$params['a']=$asignatura;}if($buscar!==''){$where[]='(c.titulo LIKE :buscar OR c.descripcion LIKE :buscar OR c.modulo LIKE :buscar)';$params['buscar']='%'.$buscar.'%';}$filtro=implode(' AND ',$where);
$from=' FROM inscripciones_capacitacion i JOIN contenidos c ON c.seccion_id=i.seccion_id AND c.asignatura_id=i.asignatura_id JOIN asignaturas a ON a.id=c.asignatura_id JOIN capacitacion_secciones s ON s.id=c.seccion_id JOIN usuarios d ON d.id=c.docente_id';$q=$pdo->prepare('SELECT COUNT(*)'.$from.' WHERE '.$filtro);$q->execute($params);$total=(int)$q->fetchColumn();$paginas=max(1,(int)ceil($total/$limite));if($pagina>$paginas)$pagina=$paginas;
$q=$pdo->prepare("SELECT c.*,a.nombre capacitacion,s.codigo seccion,CONCAT_WS(' ',d.nombre,d.apellido) docente,d.foto docente_foto,(SELECT COUNT(*) FROM contenido_comentarios cc WHERE cc.contenido_id=c.id AND cc.estado='visible') comentarios".$from.' WHERE '.$filtro.' ORDER BY COALESCE(c.fecha_publicacion,c.created_at) DESC,c.id DESC LIMIT :lim OFFSET :off');foreach($params as$k=>$v)$q->bindValue(':'.$k,$v);$q->bindValue(':lim',$limite,PDO::PARAM_INT);$q->bindValue(':off',($pagina-1)*$limite,PDO::PARAM_INT);$q->execute();$contenidos=$q->fetchAll();
?><div class="card mb-4"><div class="card-body"><form class="row g-2 align-items-end"><div class="col-lg-6"><label class="form-label">Buscar publicaciones</label><input class="form-control" type="search" name="q" maxlength="100" value="<?=atenea_e($buscar)?>" placeholder="Título, explicación o unidad"></div><div class="col-lg-4"><label class="form-label">Clase</label><select class="form-select" name="asignatura"><option value="">Todas mis clases</option><?php foreach($clases as$clase):?><option value="<?=$clase['id']?>" <?=$asignatura==$clase['id']?'selected':''?>><?=atenea_e($clase['nombre'])?></option><?php endforeach;?></select></div><div class="col-lg-2"><button class="btn btn-primary w-100">Filtrar</button></div></form></div></div>
<div class="row g-4"><?php foreach($contenidos as$c):?><div class="col-lg-6"><article class="card h-100"><div class="card-body d-flex flex-column"><div class="d-flex gap-3"><img src="<?=atenea_e(urlAvatarAtenea($c['docente_foto']))?>" class="rounded-circle" width="44" height="44" alt=""><div><h2 class="h5 mb-1"><?=atenea_e($c['titulo'])?></h2><p class="small text-muted mb-0"><?=atenea_e($c['docente'].' · '.$c['capacitacion'].' · '.$c['seccion'])?></p><small class="text-muted"><?=date('d/m/Y h:i A',strtotime((string)($c['fecha_publicacion']?:$c['created_at'])))?></small></div></div><p class="mt-3"><?=nl2br(atenea_e(mb_strimwidth((string)$c['descripcion'],0,360,'…')))?></p><div class="mt-auto pt-3 border-top d-flex justify-content-between align-items-center"><span class="text-muted"><i class="bi bi-chat-dots me-1"></i><?=(int)$c['comentarios']?></span><a class="btn btn-outline-primary btn-sm" href="<?=atenea_url('src/estudiantes/contenido.php?id='.(int)$c['id'])?>">Abrir publicación</a></div></div></article></div><?php endforeach;?><?php if(!$contenidos):?><div class="col-12"><div class="card"><div class="aula-empty"><i class="bi bi-journal-x"></i><h2 class="h5 mt-3">No hay publicaciones disponibles</h2><p class="text-muted mb-0">Las publicaciones de tus clases aparecerán aquí.</p></div></div></div><?php endif;?></div>
<?php if($paginas>1):?><nav class="mt-4"><ul class="pagination justify-content-end"><?php for($i=1;$i<=$paginas;$i++):?><li class="page-item <?=$i===$pagina?'active':''?>"><a class="page-link" href="?<?=atenea_e(http_build_query(['asignatura'=>$asignatura,'q'=>$buscar,'pagina'=>$i]))?>"><?=$i?></a></li><?php endfor;?></ul></nav><?php endif;?><?php portalEstudiantePie();
