<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/portal_estudiante_layout.php';
$portal=portalEstudianteCabecera('Facturas y comprobantes','facturas','Documentos fiscales y comprobantes vinculados únicamente a tus compras.');
$pdo=obtenerConexion();$usuario=(int)$portal['perfil']['id'];
$q=$pdo->prepare("SELECT p.id,p.numero,p.total,p.moneda,p.estado,p.created_at,d.codigo_generacion,d.numero_control,d.estado estado_dte,d.emitido_at FROM pedidos p LEFT JOIN dte_documentos d ON d.pedido_id=p.id WHERE p.usuario_id=:u ORDER BY p.created_at DESC,p.id DESC");
$q->execute(['u'=>$usuario]);$documentos=$q->fetchAll();
?>
<div class="card"><div class="card-body"><div class="table-responsive"><table class="table align-middle aula-responsive-table"><thead><tr><th>Compra</th><th>Fecha</th><th>Total</th><th>Estado</th><th>Documento fiscal</th><th>Acciones</th></tr></thead><tbody><?php foreach($documentos as $d):?><tr><td data-label="Compra"><strong><?=atenea_e((string)$d['numero'])?></strong></td><td data-label="Fecha"><?=date('d/m/Y H:i',strtotime((string)$d['created_at']))?></td><td data-label="Total">$<?=number_format((float)$d['total'],2)?> <?=atenea_e(strtoupper((string)$d['moneda']))?></td><td data-label="Estado"><span class="badge <?=claseEstadoPedido((string)$d['estado'])?>"><?=atenea_e(estadoPedidoEstudiante((string)$d['estado']))?></span></td><td data-label="Documento fiscal"><?php if($d['codigo_generacion']):?><strong><?=atenea_e((string)$d['numero_control'])?></strong><small class="d-block text-muted"><?=atenea_e((string)$d['estado_dte'])?> · <?=date('d/m/Y',strtotime((string)($d['emitido_at']?:$d['created_at'])))?></small><?php else:?><span class="text-muted">No disponible todavía</span><?php endif;?></td><td data-label="Acciones"><a class="btn btn-sm btn-outline-secondary" href="<?=atenea_url('src/estudiantes/comprobante.php?pedido='.(int)$d['id'])?>">Comprobante</a><?php if($d['codigo_generacion']):?> <a class="btn btn-sm btn-outline-primary" href="<?=atenea_url('src/dte/documento.php?pedido='.(int)$d['id'])?>">Ver factura</a> <a class="btn btn-sm btn-outline-primary" href="<?=atenea_url('src/dte/documento.php?pedido='.(int)$d['id'].'&tipo=json&descargar=1')?>">JSON</a><?php endif;?></td></tr><?php endforeach;?><?php if(!$documentos):?><tr><td colspan="6"><div class="aula-empty"><i class="bi bi-receipt"></i><p class="mt-2 mb-0">Todavía no tienes compras ni facturas registradas.</p></div></td></tr><?php endif;?></tbody></table></div></div></div>
<?php portalEstudiantePie();
