<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/auth.php';
exigirRol(['usuario']);
$completar = isset($_GET['completar']) && $_GET['completar'] === '1';
require_once dirname(__DIR__,2).'/includes/portal_estudiante_layout.php';
$portal=portalEstudianteCabecera('Mi perfil','perfil','Administra tus datos personales, dirección y seguridad.',true);
$perfil=$portal['perfil'];
?>
<?php if($completar&&!datosPerfilCompletos($perfil)): $errores=is_array($_SESSION['google_perfil_errores']??null)?$_SESSION['google_perfil_errores']:[];$datos=is_array($_SESSION['google_perfil_datos']??null)?$_SESSION['google_perfil_datos']:[];unset($_SESSION['google_perfil_errores'],$_SESSION['google_perfil_datos']);$departamentos=obtenerDepartamentos();$valor=static fn(string $k,string $fallback=''):string=>(string)($datos[$k]??$perfil[$k]??$fallback);?>
<div class="row"><div class="col-xl-9 mx-auto"><div class="card"><div class="card-body p-4 p-lg-5"><div class="mb-4"><span class="badge bg-warning text-dark mb-2">Perfil pendiente</span><h1 class="h3">Completa tu registro con Google</h1><p class="text-muted mb-0">Google proporcionó únicamente tu identidad básica. Confirma los datos restantes para habilitar el portal académico.</p></div><?php if($errores):?><div class="alert alert-danger" role="alert"><strong>Revisa el formulario.</strong><ul class="mb-0 mt-2"><?php foreach($errores as$error):?><li><?=atenea_e((string)$error)?></li><?php endforeach;?></ul></div><?php endif;?>
<form method="post" action="<?=atenea_url('src/auth/completar-perfil-google.php')?>" class="row g-3" data-google-profile-form><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>">
<div class="col-md-6"><label class="form-label" for="gp_nombre">Nombres</label><input class="form-control" id="gp_nombre" name="nombre" maxlength="100" value="<?=atenea_e($valor('nombre'))?>" required></div><div class="col-md-6"><label class="form-label" for="gp_apellido">Apellidos</label><input class="form-control" id="gp_apellido" name="apellido" maxlength="100" value="<?=atenea_e($valor('apellido'))?>" required></div>
<div class="col-md-6"><label class="form-label" for="gp_fecha">Fecha de nacimiento</label><input class="form-control" type="date" id="gp_fecha" name="fecha_nacimiento" max="<?=date('Y-m-d')?>" value="<?=atenea_e($valor('fecha_nacimiento'))?>" required></div><div class="col-md-6"><label class="form-label" for="gp_dui">DUI</label><input class="form-control" id="gp_dui" name="dui" inputmode="numeric" maxlength="10" pattern="\d{8}-\d" placeholder="00000000-0" value="<?=atenea_e($valor('dui'))?>" required><div class="form-text">Formato 00000000-0.</div></div>
<div class="col-md-4"><label class="form-label" for="gp_codigo">Prefijo telefónico</label><select class="form-select" id="gp_codigo" name="codigo_telefono" required><?php $codigo=$valor('codigo_telefono','+503');foreach(['+503'=>'El Salvador +503','+502'=>'Guatemala +502','+504'=>'Honduras +504','+505'=>'Nicaragua +505','+506'=>'Costa Rica +506','+507'=>'Panamá +507','+52'=>'México +52','+1'=>'EE. UU./Canadá +1']as$k=>$v):?><option value="<?=$k?>" <?=$codigo===$k?'selected':''?>><?=atenea_e($v)?></option><?php endforeach;?></select></div><div class="col-md-8"><label class="form-label" for="gp_telefono">Teléfono</label><input class="form-control" id="gp_telefono" name="telefono" inputmode="numeric" maxlength="15" pattern="\d{7,15}" value="<?=atenea_e($valor('telefono'))?>" required></div>
<div class="col-md-4"><label class="form-label" for="gp_departamento">Departamento</label><select class="form-select" id="gp_departamento" name="departamento_id" required><option value="">Seleccione…</option><?php foreach($departamentos as$d):?><option value="<?=$d['id']?>" <?=(int)$valor('departamento_id')===(int)$d['id']?'selected':''?>><?=atenea_e((string)$d['nombre'])?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label" for="gp_municipio">Municipio</label><select class="form-select" id="gp_municipio" name="municipio_id" data-selected="<?=(int)$valor('municipio_id')?>" required disabled><option value="">Seleccione…</option></select></div><div class="col-md-4"><label class="form-label" for="gp_distrito">Distrito</label><select class="form-select" id="gp_distrito" name="distrito_id" data-selected="<?=(int)$valor('distrito_id')?>" required disabled><option value="">Seleccione…</option></select></div>
<div class="col-12"><label class="form-label" for="gp_direccion">Dirección completa</label><textarea class="form-control" id="gp_direccion" name="direccion" rows="3" minlength="8" maxlength="500" required><?=atenea_e($valor('direccion'))?></textarea></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" id="gp_terminos" name="terminos" value="1" required><label class="form-check-label" for="gp_terminos">Acepto los términos y condiciones y confirmo que los datos son correctos.</label></div></div><div class="col-12 d-flex justify-content-end"><button class="btn btn-primary" type="submit">Guardar y habilitar mi cuenta</button></div></form></div></div></div></div>
<script>window.ATENEA_GOOGLE_PROFILE={endpoint:<?=json_encode(atenea_url('src/api/ubicaciones.php'),JSON_UNESCAPED_SLASHES)?>};</script><script src="<?=atenea_url('src/website/assets/js/google-profile.js')?>"></script>
<?php else:?>
<div class="row"><div class="col-lg-8 mx-auto"><div class="card"><div class="card-body p-4"><div class="d-flex flex-column flex-md-row align-items-center gap-4"><img src="<?=atenea_e(rutaFotoPerfil($perfil))?>" class="avatar avatar-100 avatar-rounded" data-atenea-current-avatar alt="Foto de perfil"><div class="flex-grow-1 text-center text-md-start"><h1 class="h3 mb-1" data-atenea-current-name><?=atenea_e(trim((string)$perfil['nombre'].' '.(string)$perfil['apellido']))?></h1><p class="text-muted mb-2"><?=atenea_e((string)$perfil['correo'])?> · <?=atenea_e(etiquetaRol((string)$perfil['rol']))?></p><p>Actualiza tus datos, fotografía, dirección, correo y contraseña desde un único perfil seguro.</p><button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#modalPerfil">Abrir mi perfil</button></div></div></div></div></div></div>
<?php endif;?>
<?php portalEstudiantePie(); ?>
