<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/portal_estudiante_layout.php';
$portal=portalEstudianteCabecera('Récord académico','record','Resumen real de matrículas, progreso y resultados de tu cuenta.');
$pdo=obtenerConexion();$usuario=(int)$portal['perfil']['id'];
$q=$pdo->prepare("SELECT i.id,i.estado,i.created_at,i.finalizacion_confirmada_at,a.codigo,a.nombre,COALESCE(s.nombre,'Por asignar') seccion,CONCAT_WS(' ',d.nombre,d.apellido) docente,(SELECT COUNT(*) FROM contenidos c WHERE c.asignatura_id=i.asignatura_id AND c.seccion_id=i.seccion_id AND c.estado='activo' AND c.activo=1 AND c.eliminado_at IS NULL) contenidos,(SELECT COUNT(DISTINCT e.contenido_id) FROM entregas_contenido e WHERE e.estudiante_id=i.usuario_id AND e.asignatura_id=i.asignatura_id AND e.seccion_id=i.seccion_id AND e.estado='aprobada') completados,(SELECT AVG(e.nota) FROM entregas_contenido e WHERE e.estudiante_id=i.usuario_id AND e.asignatura_id=i.asignatura_id AND e.seccion_id=i.seccion_id AND e.nota IS NOT NULL) promedio FROM inscripciones_capacitacion i JOIN asignaturas a ON a.id=i.asignatura_id LEFT JOIN capacitacion_secciones s ON s.id=i.seccion_id LEFT JOIN usuarios d ON d.id=i.docente_id WHERE i.usuario_id=:u ORDER BY i.created_at DESC,i.id DESC");
$q->execute(['u'=>$usuario]);$registros=$q->fetchAll();
?>
<div class="row g-4"><?php foreach($registros as $r):$porcentaje=(int)$r['contenidos']>0?min(100,(int)round(((int)$r['completados']/(int)$r['contenidos'])*100)):0;?><div class="col-xl-6"><article class="card h-100"><div class="card-body"><div class="d-flex flex-wrap justify-content-between gap-2"><span class="badge bg-primary"><?=atenea_e((string)$r['codigo'])?></span><span class="badge bg-<?=$r['estado']==='finalizado'?'success':($r['estado']==='retirado'?'secondary':'warning')?>"><?=atenea_e(ucfirst(str_replace('_',' ',(string)$r['estado'])))?></span></div><h2 class="h4 mt-3 mb-1"><?=atenea_e((string)$r['nombre'])?></h2><p class="text-muted"><?=atenea_e((string)($r['docente']?:'Docente por asignar'))?> · <?=atenea_e((string)$r['seccion'])?></p><div class="d-flex justify-content-between small mb-1"><span>Progreso registrado</span><strong><?=$porcentaje?>%</strong></div><div class="progress mb-3" role="progressbar" aria-label="Progreso" aria-valuenow="<?=$porcentaje?>" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar" style="width:<?=$porcentaje?>%"></div></div><dl class="row mb-0"><dt class="col-7">Actividades completadas</dt><dd class="col-5 text-end"><?=(int)$r['completados']?> / <?=(int)$r['contenidos']?></dd><dt class="col-7">Promedio calificado</dt><dd class="col-5 text-end"><?=$r['promedio']!==null?number_format((float)$r['promedio'],2).'/10':'Sin notas'?></dd><dt class="col-7">Fecha de matrícula</dt><dd class="col-5 text-end"><?=date('d/m/Y',strtotime((string)$r['created_at']))?></dd></dl></div></article></div><?php endforeach;?><?php if(!$registros):?><div class="col-12"><div class="card"><div class="aula-empty"><i class="bi bi-bar-chart"></i><h2 class="h5 mt-3">Todavía no tienes historial académico</h2><p class="mb-0">Tu récord se construirá con las matrículas y resultados registrados en Atenea.</p></div></div></div><?php endif;?></div>
<?php portalEstudiantePie();
