-- Ejecutar en la base de datos `atenea`
-- Perfil de facturacion del usuario + snapshot de compra para checkout/DTE

ALTER TABLE `public_users`
    ADD COLUMN IF NOT EXISTS `BIRTHDATE` DATE NULL AFTER `PHONE_NUMBER`,
    ADD COLUMN IF NOT EXISTS `PROFILE_PHOTO` VARCHAR(255) NULL AFTER `BIRTHDATE`,
    ADD COLUMN IF NOT EXISTS `GOOGLE_ID` VARCHAR(191) NULL AFTER `PROFILE_PHOTO`,
    ADD COLUMN IF NOT EXISTS `GOOGLE_EMAIL` VARCHAR(150) NULL AFTER `GOOGLE_ID`,
    ADD COLUMN IF NOT EXISTS `BILLING_NAME` VARCHAR(150) NULL AFTER `GOOGLE_EMAIL`,
    ADD COLUMN IF NOT EXISTS `BILLING_EMAIL` VARCHAR(150) NULL AFTER `BILLING_NAME`,
    ADD COLUMN IF NOT EXISTS `TIPO_DOCUMENTO` VARCHAR(10) NULL AFTER `BILLING_EMAIL`,
    ADD COLUMN IF NOT EXISTS `NUMERO_DOCUMENTO` VARCHAR(25) NULL AFTER `TIPO_DOCUMENTO`,
    ADD COLUMN IF NOT EXISTS `BILLING_DEPARTAMENTO` VARCHAR(100) NULL AFTER `NUMERO_DOCUMENTO`,
    ADD COLUMN IF NOT EXISTS `BILLING_MUNICIPIO` VARCHAR(100) NULL AFTER `BILLING_DEPARTAMENTO`,
    ADD COLUMN IF NOT EXISTS `BILLING_DISTRITO` VARCHAR(100) NULL AFTER `BILLING_MUNICIPIO`,
    ADD COLUMN IF NOT EXISTS `BILLING_DIRECCION` TEXT NULL AFTER `BILLING_DISTRITO`,
    ADD COLUMN IF NOT EXISTS `BILLING_NRC` VARCHAR(20) NULL AFTER `BILLING_DIRECCION`,
    ADD COLUMN IF NOT EXISTS `BILLING_PROFILE_COMPLETED` TINYINT(1) NOT NULL DEFAULT 0 AFTER `BILLING_NRC`;

ALTER TABLE `ordenes`
    ADD COLUMN IF NOT EXISTS `billing_tipo_documento` VARCHAR(10) NOT NULL DEFAULT '' AFTER `billing_address`,
    ADD COLUMN IF NOT EXISTS `billing_numero_documento` VARCHAR(25) NOT NULL DEFAULT '' AFTER `billing_tipo_documento`,
    ADD COLUMN IF NOT EXISTS `billing_telefono` VARCHAR(20) NULL AFTER `billing_numero_documento`,
    ADD COLUMN IF NOT EXISTS `billing_departamento` VARCHAR(100) NULL AFTER `billing_telefono`,
    ADD COLUMN IF NOT EXISTS `billing_municipio` VARCHAR(100) NULL AFTER `billing_departamento`,
    ADD COLUMN IF NOT EXISTS `billing_distrito` VARCHAR(100) NULL AFTER `billing_municipio`,
    ADD COLUMN IF NOT EXISTS `billing_nrc` VARCHAR(20) NULL AFTER `billing_distrito`;
