<?php
declare(strict_types=1);
$q=$pdo->prepare('SELECT h.*,CONCAT_WS(" ",a.nombre,a.apellido) administrador FROM usuario_permisos_historial h JOIN usuarios a ON a.id=h.cambiado_por WHERE h.usuario_id=:id ORDER BY h.created_at DESC,h.id DESC LIMIT 20');$q->execute(['id'=>$id]);$historialPermisos=$q->fetchAll();$ultimoPermiso=$historialPermisos[0]??null;
$q=$pdo->prepare('SELECT id,nivel,mensaje,modulo,modo_activo,estado,correlacion_id,ultima_ocurrencia_at FROM errores_sistema WHERE usuario_id=:id ORDER BY ultima_ocurrencia_at DESC,id DESC LIMIT 10');$q->execute(['id'=>$id]);$erroresHibridos=$q->fetchAll();
$q=$pdo->prepare("SELECT id,title,message,level,status,created_at FROM admin_notices WHERE user_id=:id AND status IN('pendiente','visto') ORDER BY created_at DESC,id DESC LIMIT 10");$q->execute(['id'=>$id]);$notificacionesHibridas=$q->fetchAll();
?>
<section class="card card-rounded mt-4" id="control-hibrido"><div class="card-body">
 <div class="d-flex flex-wrap justify-content-between gap-3"><div><h2 class="h4">Supervisión de la cuenta híbrida</h2><p class="text-muted mb-0">Sesiones, comunicación, cambios de permisos, errores y notificaciones.</p></div><form method="post" action="<?=atenea_url('src/comunicaciones/chat-abrir.php')?>"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="contacto_id" value="<?=$id?>"><button class="btn btn-outline-primary"><i class="mdi mdi-message-text-outline me-1"></i>Mensaje directo</button></form></div>
 <div class="row g-3 my-2"><div class="col-md-4"><div class="border rounded p-3 h-100"><small class="text-muted">Último cambio de permisos</small><strong class="d-block mt-1"><?=$ultimoPermiso?date('d/m/Y H:i',strtotime((string)$ultimoPermiso['created_at'])):'Sin cambios'?></strong><span class="small"><?=atenea_e((string)($ultimoPermiso['administrador']??'No disponible'))?></span></div></div><div class="col-md-4"><div class="border rounded p-3 h-100"><small class="text-muted">Sesión y actividad</small><strong class="d-block mt-1"><?=atenea_e($usuario['estado']==='activo'?'Cuenta activa':'Cuenta suspendida')?></strong><span class="small">Último acceso: <?=$usuario['ultimo_acceso']?date('d/m/Y H:i',strtotime((string)$usuario['ultimo_acceso'])):'sin registro'?></span></div></div><div class="col-md-4"><div class="border rounded p-3 h-100"><small class="text-muted">Pendientes relacionados</small><strong class="d-block mt-1"><?=count($notificacionesHibridas)?> notificaciones</strong><span class="small"><?=count($erroresHibridos)?> errores recientes</span></div></div></div>
 <div class="accordion" id="supervisionHibrida"><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button" data-bs-toggle="collapse" data-bs-target="#sesionesHibridas">Sesiones y seguridad</button></h3><div id="sesionesHibridas" class="accordion-collapse collapse show" data-bs-parent="#supervisionHibrida"><div class="accordion-body"><p>El sistema registra último acceso y última actividad. No existe una tabla de dispositivos individuales; la revocación incrementa la versión de sesión y cierra todas las sesiones activas.</p><?php if($esSuperadminActor&&!$esPropia):?><form method="post" action="accion.php" class="row g-2 align-items-end"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="revocar_sesiones"><input type="hidden" name="id" value="<?=$id?>"><div class="col-md-8"><label class="form-label" for="passwordRevocar">Confirma tu contraseña administrativa</label><input class="form-control" id="passwordRevocar" type="password" name="admin_password" autocomplete="current-password" required></div><div class="col-md-4"><button class="btn btn-outline-danger w-100" data-atenea-confirm="deactivate" data-atenea-confirm-title="Revocar sesiones" data-atenea-confirm-message="La cuenta deberá iniciar sesión nuevamente.">Revocar sesiones activas</button></div></form><?php endif;?></div></div></div>
 <div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#eventosHibridos">Cambios, errores y notificaciones</button></h3><div id="eventosHibridos" class="accordion-collapse collapse" data-bs-parent="#supervisionHibrida"><div class="accordion-body"><h4 class="h6">Cambios recientes de permisos</h4><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Fecha</th><th>Permiso</th><th>Cambio</th><th>Administrador</th></tr></thead><tbody><?php foreach($historialPermisos as$cambio):?><tr><td><?=date('d/m/Y H:i',strtotime((string)$cambio['created_at']))?></td><td><?=atenea_e((string)$cambio['permiso'])?></td><td><?=(int)$cambio['valor_anterior']?> → <?=(int)$cambio['valor_nuevo']?></td><td><?=atenea_e((string)$cambio['administrador'])?></td></tr><?php endforeach;?><?php if(!$historialPermisos):?><tr><td colspan="4" class="text-muted">Sin cambios registrados.</td></tr><?php endif;?></tbody></table></div><h4 class="h6 mt-4">Errores relacionados</h4><?php foreach($erroresHibridos as$error):?><div class="border rounded p-2 mb-2"><a href="<?=atenea_url('src/dashboard/errores/detalle.php?id='.(int)$error['id'])?>"><strong><?=atenea_e((string)$error['modulo'])?></strong></a> · <?=atenea_e((string)$error['nivel'])?> · <?=atenea_e((string)($error['modo_activo']?:'sin modo'))?><span class="d-block small"><?=atenea_e((string)$error['mensaje'])?> · <?=atenea_e((string)$error['correlacion_id'])?></span></div><?php endforeach;?><?php if(!$erroresHibridos):?><p class="text-muted">Sin errores relacionados.</p><?php endif;?><h4 class="h6 mt-4">Notificaciones pendientes</h4><?php foreach($notificacionesHibridas as$notificacion):?><div class="border rounded p-2 mb-2"><strong><?=atenea_e((string)$notificacion['title'])?></strong> · <?=atenea_e((string)$notificacion['status'])?><span class="d-block small"><?=atenea_e((string)$notificacion['message'])?></span></div><?php endforeach;?><?php if(!$notificacionesHibridas):?><p class="text-muted mb-0">Sin notificaciones pendientes.</p><?php endif;?></div></div></div></div>
</div></section>
