<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/cms.php';
require_once dirname(__DIR__, 3) . '/includes/admin_users.php';
exigirPermiso('users.view');

$id = cmsId($_GET['id'] ?? 0);
$usuario = $id ? adminUsuarioPorId($id) : null;
if (!$usuario) { cmsFlash('error', 'La cuenta solicitada no existe.'); header('Location: index.php'); exit; }
$pdo = obtenerConexion();
$comprasPagina = max(1, (int)($_GET['compras_page'] ?? 1));
$auditPagina = max(1, (int)($_GET['audit_page'] ?? 1));
$limite = 10;
$q=$pdo->prepare('SELECT COUNT(*) FROM pedidos WHERE usuario_id=:id');$q->execute(['id'=>$id]);$comprasTotal=(int)$q->fetchColumn();
$q=$pdo->prepare('SELECT p.id,p.numero,p.total,p.moneda,p.estado,p.payment_brand,p.payment_last4,p.paid_at,p.created_at,GROUP_CONCAT(CONCAT(pd.nombre_producto," x",pd.cantidad) SEPARATOR ", ") productos FROM pedidos p LEFT JOIN pedido_detalles pd ON pd.pedido_id=p.id WHERE p.usuario_id=:id GROUP BY p.id ORDER BY p.created_at DESC LIMIT '.$limite.' OFFSET '.(($comprasPagina-1)*$limite));$q->execute(['id'=>$id]);$compras=$q->fetchAll();
$q=$pdo->prepare('SELECT COUNT(*) FROM audit_logs WHERE target_user_id=:target_id OR actor_user_id=:actor_id');$q->execute(['target_id'=>$id,'actor_id'=>$id]);$auditTotal=(int)$q->fetchColumn();
$q=$pdo->prepare('SELECT id,event_type,module,action,result,description,created_at,actor_user_id,target_user_id FROM audit_logs WHERE target_user_id=:target_id OR actor_user_id=:actor_id ORDER BY created_at DESC,id DESC LIMIT '.$limite.' OFFSET '.(($auditPagina-1)*$limite));$q->execute(['target_id'=>$id,'actor_id'=>$id]);$actividad=$q->fetchAll();
$q=$pdo->prepare('SELECT n.*,CONCAT(a.nombre," ",a.apellido) creador FROM admin_notices n JOIN usuarios a ON a.id=n.created_by WHERE n.user_id=:id ORDER BY n.created_at DESC LIMIT 50');$q->execute(['id'=>$id]);$avisos=$q->fetchAll();
$revelado = usuarioTienePermiso('users.view_sensitive') && (int)($_SESSION['sensitive_reveal_user_id']??0)===$id && (int)($_SESSION['sensitive_reveal_until']??0)>=time();
$esPropia = $id === (int)($_SESSION['usuario_id']??0);
$administradores = cantidadAdministradoresActivos($pdo);
cmsCabecera('Detalle de cuenta', 'usuarios/detalle.php', 'Perfil administrativo con acceso controlado, historial y acciones auditadas.');
?>
<div class="d-flex flex-wrap gap-3 align-items-center mb-4"><img class="rounded-circle" style="width:72px;height:72px;object-fit:cover" src="<?= atenea_e(rutaFotoPerfil($usuario)) ?>" alt="Foto de <?= atenea_e((string)$usuario['nombre']) ?>"><div><h2 class="h4 mb-1"><?= atenea_e(trim((string)$usuario['nombre'].' '.(string)$usuario['apellido'])) ?></h2><span class="badge badge-opacity-primary"><?= atenea_e(etiquetaRol((string)$usuario['rol'])) ?></span> <span class="badge badge-opacity-<?= $usuario['estado']==='activo'&&!$usuario['deleted_at']?'success':'secondary' ?>"><?= $usuario['deleted_at']?'Periodo de gracia':atenea_e(ucfirst((string)$usuario['estado'])) ?></span></div><div class="ms-auto"><?php if(!$usuario['deleted_at']&&usuarioTienePermiso('users.edit')):?><a class="btn btn-outline-primary" href="editar.php?id=<?= $id ?>">Editar datos permitidos</a><?php endif;?> <a class="btn btn-light" href="index.php">Volver</a></div></div>
<ul class="nav nav-tabs" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#perfil">Perfil</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#actividad">Actividad</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#compras">Compras</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#formacion">Formacion</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#avisos">Avisos</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#seguridad">Seguridad</button></li></ul>
<div class="tab-content card card-rounded border-top-0"><div class="tab-pane fade show active p-4" id="perfil">
 <div class="row g-4"><div class="col-lg-6"><h3 class="h5">Informacion general</h3><dl class="row"><dt class="col-sm-5">Correo</dt><dd class="col-sm-7"><?= atenea_e((string)$usuario['correo']) ?></dd><dt class="col-sm-5">Registro</dt><dd class="col-sm-7"><?= date('d/m/Y H:i',strtotime((string)$usuario['created_at'])) ?></dd><dt class="col-sm-5">Ultimo acceso</dt><dd class="col-sm-7"><?= $usuario['ultimo_acceso']?date('d/m/Y H:i',strtotime((string)$usuario['ultimo_acceso'])):'Sin registro' ?></dd><dt class="col-sm-5">Ultima actividad</dt><dd class="col-sm-7"><?= $usuario['last_activity_at']?date('d/m/Y H:i',strtotime((string)$usuario['last_activity_at'])):'Sin registro' ?></dd><dt class="col-sm-5">Google</dt><dd class="col-sm-7"><?= $usuario['google_id']?'Vinculada':'No vinculada' ?></dd></dl></div>
 <div class="col-lg-6"><h3 class="h5">Datos personales</h3><dl class="row"><dt class="col-sm-5">Telefono</dt><dd class="col-sm-7"><?= atenea_e(trim((string)$usuario['codigo_telefono'].' '.(string)$usuario['telefono'])?:'No registrado') ?></dd><dt class="col-sm-5">Nacimiento</dt><dd class="col-sm-7"><?= atenea_e((string)($usuario['fecha_nacimiento']?:'No registrada')) ?></dd><dt class="col-sm-5">DUI</dt><dd class="col-sm-7"><?= atenea_e($revelado?(string)$usuario['dui']:duiEnmascarado($usuario['dui'])) ?> <?php if(!$revelado&&usuarioTienePermiso('users.view_sensitive')):?><form class="d-inline" method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?= atenea_e(obtenerTokenCsrf()) ?>"><input type="hidden" name="accion" value="revelar_sensible"><input type="hidden" name="id" value="<?= $id ?>"><button class="btn btn-link btn-sm p-0">Revelar 5 min</button></form><?php endif;?></dd><dt class="col-sm-5">Direccion</dt><dd class="col-sm-7"><?= usuarioTienePermiso('users.view_sensitive')?atenea_e(trim((string)$usuario['direccion'].', '.(string)$usuario['distrito'].', '.(string)$usuario['municipio'].', '.(string)$usuario['departamento'],', ')):'Restringida' ?></dd></dl></div></div>
</div><div class="tab-pane fade p-4" id="actividad"><h3 class="h5">Actividad y bitacora administrativa</h3><?php require __DIR__.'/_tabla_auditoria.php'; ?></div>
<div class="tab-pane fade p-4" id="compras"><h3 class="h5">Pedidos</h3><div class="table-responsive"><table class="table"><thead><tr><th>Pedido</th><th>Productos</th><th>Total</th><th>Estado</th><th>Metodo</th><th>Fecha</th></tr></thead><tbody><?php foreach($compras as $compra):?><tr><td><?= atenea_e((string)$compra['numero']) ?></td><td><?= atenea_e((string)$compra['productos']) ?></td><td><?= number_format((float)$compra['total'],2).' '.atenea_e(strtoupper((string)$compra['moneda'])) ?></td><td><?= atenea_e((string)$compra['estado']) ?></td><td><?= $compra['payment_last4']?atenea_e(ucfirst((string)$compra['payment_brand']).' terminada en '.$compra['payment_last4']):'No disponible' ?></td><td><?= date('d/m/Y H:i',strtotime((string)$compra['created_at'])) ?></td></tr><?php endforeach;?><?php if(!$compras):?><tr><td colspan="6" class="text-center text-muted">Sin pedidos.</td></tr><?php endif;?></tbody></table></div><?php $comprasPaginas=max(1,(int)ceil($comprasTotal/$limite));if($comprasPaginas>1):?><nav aria-label="Paginas de compras"><ul class="pagination justify-content-end"><?php for($p=1;$p<=$comprasPaginas;$p++):?><li class="page-item <?= $p===$comprasPagina?'active':'' ?>"><a class="page-link" href="?id=<?= $id ?>&compras_page=<?= $p ?>#compras"><?= $p ?></a></li><?php endfor;?></ul></nav><?php endif;?></div>
<div class="tab-pane fade p-4" id="formacion"><div class="alert alert-info mb-0">El esquema actual no contiene tablas de matriculas, capacitaciones asignadas ni certificaciones. Esta seccion no inventa registros academicos y queda lista para enlazar la fuente real cuando exista.</div></div>
<div class="tab-pane fade p-4" id="avisos"><div class="row g-4"><div class="col-lg-7"><h3 class="h5">Historial de avisos</h3><?php foreach($avisos as $aviso):?><div class="border rounded p-3 mb-2"><div class="d-flex justify-content-between"><strong><?= atenea_e((string)$aviso['title']) ?></strong><span class="badge badge-opacity-primary"><?= atenea_e((string)$aviso['status']) ?></span></div><p class="mb-1"><?= nl2br(atenea_e((string)$aviso['message'])) ?></p><small class="text-muted"><?= date('d/m/Y H:i',strtotime((string)$aviso['created_at'])) ?> por <?= atenea_e((string)$aviso['creador']) ?></small></div><?php endforeach;?><?php if(!$avisos):?><p class="text-muted">Sin avisos.</p><?php endif;?></div><div class="col-lg-5"><h3 class="h5">Crear aviso</h3><form method="post" action="accion.php" data-atenea-loading><input type="hidden" name="csrf_token" value="<?= atenea_e(obtenerTokenCsrf()) ?>"><input type="hidden" name="accion" value="crear_aviso"><input type="hidden" name="id" value="<?= $id ?>"><div class="mb-2"><label class="form-label">Tipo</label><select class="form-select" name="tipo"><option value="correccion">Correccion</option><option value="documentacion">Documentacion</option><option value="seguridad">Seguridad</option><option value="general">General</option></select></div><div class="mb-2"><label class="form-label">Titulo</label><input class="form-control" name="titulo" maxlength="180" required></div><div class="mb-2"><label class="form-label">Mensaje</label><textarea class="form-control" name="mensaje" maxlength="2000" rows="5" required></textarea></div><div class="row g-2"><div class="col-6"><label class="form-label">Prioridad</label><select class="form-select" name="prioridad"><option value="normal">Normal</option><option value="alta">Alta</option><option value="urgente">Urgente</option></select></div><div class="col-6"><label class="form-label">Fecha limite</label><input class="form-control" type="date" name="fecha_limite"></div></div><div class="mt-2"><label class="form-label">Seccion a corregir</label><input class="form-control" name="seccion" maxlength="100"></div><button class="btn btn-primary mt-3" <?= usuarioTienePermiso('users.send_notice')?'':'disabled' ?>>Enviar aviso</button></form></div></div></div>
<div class="tab-pane fade p-4" id="seguridad"><div class="row g-4"><div class="col-lg-6"><h3 class="h5">Cambiar rol</h3><form method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?= atenea_e(obtenerTokenCsrf()) ?>"><input type="hidden" name="accion" value="cambiar_rol"><input type="hidden" name="id" value="<?= $id ?>"><select class="form-select mb-2" name="rol" <?= $esPropia?'disabled':'' ?>><?php foreach(rolesAdministrablesAtenea() as $rol):?><option value="<?= $rol ?>" <?= $usuario['rol']===$rol?'selected':'' ?>><?= atenea_e(etiquetaRol($rol)) ?></option><?php endforeach;?></select><label class="form-label">Confirma tu contrasena administrativa</label><input class="form-control" type="password" name="admin_password" autocomplete="current-password"><button class="btn btn-primary mt-2" data-atenea-confirm="role" data-atenea-confirm-title="Confirmar cambio de rol" data-atenea-confirm-message="Se invalidaran las sesiones anteriores y los permisos cambiaran de inmediato." <?= $esPropia?'disabled':'' ?>>Cambiar rol</button></form><small class="text-muted"><?= $esPropia?'No puedes cambiar tu propio rol.':'La reautenticacion se conserva durante 10 minutos.' ?></small><hr><h3 class="h5">Activacion</h3><form method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?= atenea_e(obtenerTokenCsrf()) ?>"><input type="hidden" name="accion" value="cambiar_estado"><input type="hidden" name="id" value="<?= $id ?>"><input type="hidden" name="estado" value="<?= $usuario['estado']==='activo'?'inactivo':'activo' ?>"><label class="form-label">Motivo</label><input class="form-control" name="motivo" maxlength="300" required><label class="form-label mt-2">Confirma tu contrasena</label><input class="form-control" type="password" name="admin_password"><button class="btn <?= $usuario['estado']==='activo'?'btn-outline-danger':'btn-success' ?> mt-2" data-atenea-confirm="<?= $usuario['estado']==='activo'?'deactivate':'state' ?>"><?= $usuario['estado']==='activo'?'Desactivar cuenta':'Activar cuenta' ?></button></form></div>
<div class="col-lg-6"><h3 class="h5">Recuperacion asistida</h3><form method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?= atenea_e(obtenerTokenCsrf()) ?>"><input type="hidden" name="accion" value="iniciar_recuperacion"><input type="hidden" name="id" value="<?= $id ?>"><label class="form-label">Confirma tu contrasena administrativa</label><input class="form-control" type="password" name="admin_password" autocomplete="current-password"><button class="btn btn-outline-primary mt-2">Enviar codigo al correo registrado</button></form><form class="mt-3" method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?= atenea_e(obtenerTokenCsrf()) ?>"><input type="hidden" name="accion" value="verificar_recuperacion"><input type="hidden" name="id" value="<?= $id ?>"><label class="form-label">Codigo comunicado por el usuario</label><input class="form-control text-uppercase" name="codigo" minlength="8" maxlength="8" autocomplete="one-time-code" required><button class="btn btn-success mt-2">Verificar y enviar enlace seguro</button></form></div>
<div class="col-12"><hr><h3 class="h5">Ciclo de vida</h3><?php if($usuario['deleted_at']):?><p>Eliminacion logica solicitada. Gracia hasta <?= atenea_e((string)$usuario['deletion_scheduled_at']) ?>.</p><form method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?= atenea_e(obtenerTokenCsrf()) ?>"><input type="hidden" name="accion" value="restaurar"><input type="hidden" name="id" value="<?= $id ?>"><label class="form-label">Confirma tu contrasena</label><input class="form-control" type="password" name="admin_password" style="max-width:420px"><button class="btn btn-success mt-2">Restaurar cuenta</button></form><?php else:?><form method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?= atenea_e(obtenerTokenCsrf()) ?>"><input type="hidden" name="accion" value="eliminar_logico"><input type="hidden" name="id" value="<?= $id ?>"><label class="form-label">Motivo obligatorio</label><textarea class="form-control" name="motivo" maxlength="500" required></textarea><label class="form-label mt-2">Confirma tu contrasena</label><input class="form-control" type="password" name="admin_password"><button class="btn btn-danger mt-2" data-atenea-confirm="delete" data-atenea-confirm-title="Solicitar eliminacion de cuenta" data-atenea-confirm-message="La cuenta se desactivara, las sesiones se invalidaran y comenzara un periodo de gracia. No se borraran pedidos ni registros legales.">Solicitar eliminacion logica</button></form><?php endif;?></div></div></div></div>
<script>document.addEventListener('DOMContentLoaded',function(){if(!location.hash)return;var trigger=document.querySelector('[data-bs-target="'+location.hash.replace(/[^#a-z0-9_-]/gi,'')+'"]');if(trigger&&window.bootstrap&&window.bootstrap.Tab)new bootstrap.Tab(trigger).show();});</script>
<?php cmsPie(); ?>
