<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';exigirPermiso('users.view');
$roles=rolesAdministrablesAtenea();$rol=in_array($_GET['rol']??'',$roles,true)?(string)$_GET['rol']:'';$estado=in_array($_GET['estado']??'',['activo','inactivo','eliminado'],true)?(string)$_GET['estado']:'';$busqueda=mb_substr(trim((string)($_GET['q']??'')),0,100);$pagina=max(1,(int)($_GET['page']??1));$porPagina=20;$where=[];$params=[];
if($rol!==''){$where[]='rol=:rol';$params['rol']=$rol;}if($estado==='eliminado')$where[]='deleted_at IS NOT NULL';elseif($estado!==''){$where[]='estado=:estado AND deleted_at IS NULL';$params['estado']=$estado;}else$where[]='deleted_at IS NULL';
if($busqueda!==''){$like='%'.$busqueda.'%';$where[]="(nombre LIKE :nombre OR apellido LIKE :apellido OR correo LIKE :correo OR nombre_usuario LIKE :usuario OR telefono LIKE :telefono OR dui LIKE :dui".(ctype_digit($busqueda)?' OR id=:id':'').')';foreach(['nombre','apellido','correo','usuario','telefono','dui']as$campo)$params[$campo]=$like;if(ctype_digit($busqueda))$params['id']=(int)$busqueda;}
$filtro=' WHERE '.implode(' AND ',$where);$pdo=obtenerConexion();$q=$pdo->prepare('SELECT COUNT(*) FROM usuarios'.$filtro);$q->execute($params);$total=(int)$q->fetchColumn();$offset=($pagina-1)*$porPagina;
$q=$pdo->prepare('SELECT id,nombre,apellido,nombre_usuario,correo,telefono,dui,rol,es_superadmin,estado,created_at,ultimo_acceso,last_activity_at,deleted_at,foto FROM usuarios'.$filtro.' ORDER BY created_at DESC,id DESC LIMIT '.$porPagina.' OFFSET '.$offset);$q->execute($params);$usuarios=$q->fetchAll();$paginas=max(1,(int)ceil($total/$porPagina));
cmsCabecera('Usuarios','usuarios/index.php','Consulta todas las cuentas registradas con filtros, búsqueda y paginación.');
?>
<div class="card card-rounded"><div class="card-body"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><span class="text-muted"><?=number_format($total)?> cuentas encontradas</span><?php if(usuarioTienePermiso('users.change_role')):?><a class="btn btn-primary" href="crear.php"><i class="mdi mdi-account-plus-outline"></i> Crear usuario</a><?php endif;?></div>
<form class="row g-2 mb-4" method="get"><div class="col-lg-5"><label class="form-label" for="q">Buscar</label><input class="form-control" id="q" name="q" value="<?=atenea_e($busqueda)?>" placeholder="Nombre, apellido, correo, teléfono, DUI o ID"></div><div class="col-lg-3"><label class="form-label" for="rol">Rol</label><select class="form-select" id="rol" name="rol"><option value="">Todos</option><option value="admin" <?=$rol==='admin'?'selected':''?>>Administradores</option><option value="administrador_docente" <?=$rol==='administrador_docente'?'selected':''?>>Administradores docentes</option><option value="docente" <?=$rol==='docente'?'selected':''?>>Docentes</option><option value="usuario" <?=$rol==='usuario'?'selected':''?>>Estudiantes / usuarios</option></select></div><div class="col-lg-2"><label class="form-label" for="estado">Estado</label><select class="form-select" id="estado" name="estado"><option value="">Todos</option><option value="activo" <?=$estado==='activo'?'selected':''?>>Activos</option><option value="inactivo" <?=$estado==='inactivo'?'selected':''?>>Inactivos</option><option value="eliminado" <?=$estado==='eliminado'?'selected':''?>>Eliminados</option></select></div><div class="col-lg-2 d-flex align-items-end gap-1"><button class="btn btn-primary flex-grow-1">Filtrar</button><a class="btn btn-light" href="index.php" aria-label="Limpiar filtros"><i class="mdi mdi-close"></i></a></div></form>
<div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Nombre completo</th><th>Correo</th><th>Rol</th><th>Estado</th><th>Registro</th><th>Último acceso</th><th>Acciones</th></tr></thead><tbody><?php foreach($usuarios as$usuario):?><tr><td><div class="d-flex align-items-center"><img class="img-sm rounded-circle me-3" src="<?=atenea_e(rutaFotoPerfil($usuario))?>" alt=""><div><strong><?=atenea_e(trim($usuario['nombre'].' '.$usuario['apellido']))?></strong><small class="d-block text-muted">ID <?=(int)$usuario['id']?><?=trim((string)$usuario['telefono'])!==''?' · '.atenea_e($usuario['telefono']):''?></small></div></div></td><td><?=atenea_e($usuario['correo'])?></td><td><?=atenea_e(etiquetaRol($usuario['rol']))?><?=(int)$usuario['es_superadmin']===1?' / SuperAdmin':''?></td><td><span class="badge badge-opacity-<?=$usuario['deleted_at']?'danger':($usuario['estado']==='activo'?'success':'secondary')?>"><?=$usuario['deleted_at']?'Eliminado':atenea_e(ucfirst($usuario['estado']))?></span></td><td><?=date('d/m/Y H:i',strtotime($usuario['created_at']))?></td><td><?=$usuario['ultimo_acceso']?date('d/m/Y H:i',strtotime($usuario['ultimo_acceso'])):'Sin registro'?></td><td><a class="btn btn-sm btn-outline-primary" href="detalle.php?id=<?=(int)$usuario['id']?>">Ver detalle</a></td></tr><?php endforeach;?><?php if(!$usuarios):?><tr><td colspan="7" class="text-center text-muted py-5">No hay cuentas para este filtro.</td></tr><?php endif;?></tbody></table></div>
<?php if($paginas>1):?><nav><ul class="pagination justify-content-end mb-0"><?php for($i=max(1,$pagina-2);$i<=min($paginas,$pagina+2);$i++):?><li class="page-item <?=$i===$pagina?'active':''?>"><a class="page-link" href="?<?=atenea_e(http_build_query(['rol'=>$rol,'estado'=>$estado,'q'=>$busqueda,'page'=>$i]))?>"><?=$i?></a></li><?php endfor;?></ul></nav><?php endif;?></div></div><?php cmsPie();
