<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';
exigirPermiso('system_errors.manage');
$pdo=obtenerConexion();
$estado=in_array($_GET['estado']??'', ['nuevo','revisando','resuelto'],true)?(string)$_GET['estado']:'';
$nivel=in_array($_GET['nivel']??'', ['advertencia','error','critico'],true)?(string)$_GET['nivel']:'';
$soloHibridos=in_array(($_GET['rol']??''),['administracion_docente','administrador_docente'],true);
$pagina=max(1,(int)($_GET['pagina']??1));$limite=25;$where=[];$params=[];
if($estado!==''){$where[]='e.estado=:estado';$params['estado']=$estado;}
if($nivel!==''){$where[]='e.nivel=:nivel';$params['nivel']=$nivel;}
if($soloHibridos)$where[]="u.rol IN('administracion_docente','administrador_docente')";
$filtro=$where?' WHERE '.implode(' AND ',$where):'';
$q=$pdo->prepare('SELECT COUNT(*) FROM errores_sistema e LEFT JOIN usuarios u ON u.id=e.usuario_id'.$filtro);$q->execute($params);$total=(int)$q->fetchColumn();
$q=$pdo->prepare('SELECT e.*,CONCAT_WS(" ",u.nombre,u.apellido) usuario,u.rol FROM errores_sistema e LEFT JOIN usuarios u ON u.id=e.usuario_id'.$filtro.' ORDER BY e.ultima_ocurrencia_at DESC,e.id DESC LIMIT :limite OFFSET :offset');
foreach($params as$clave=>$valor)$q->bindValue(':'.$clave,$valor);$q->bindValue(':limite',$limite,PDO::PARAM_INT);$q->bindValue(':offset',($pagina-1)*$limite,PDO::PARAM_INT);$q->execute();$filas=$q->fetchAll();
cmsCabecera('Errores operativos','errores/index.php','Errores sanitizados relacionados con usuarios, módulos y correlaciones.');
?>
<div class="card card-rounded"><div class="card-body">
<form class="row g-2 mb-4"><div class="col-md-3"><label class="form-label" for="errorEstado">Estado</label><select class="form-select" id="errorEstado" name="estado"><option value="">Todos</option><?php foreach(['nuevo','revisando','resuelto'] as$opcion):?><option value="<?=$opcion?>" <?=$estado===$opcion?'selected':''?>><?=atenea_e($opcion==='revisando'?'Revisado':ucfirst($opcion))?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label" for="errorNivel">Nivel</label><select class="form-select" id="errorNivel" name="nivel"><option value="">Todos</option><?php foreach(['advertencia','error','critico'] as$opcion):?><option value="<?=$opcion?>" <?=$nivel===$opcion?'selected':''?>><?=atenea_e(ucfirst($opcion))?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label" for="errorRol">Cuenta</label><select class="form-select" id="errorRol" name="rol"><option value="">Todos los usuarios</option><option value="administracion_docente" <?=$soloHibridos?'selected':''?>>Administración_Docente</option></select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-outline-primary w-100">Filtrar</button></div></form>
<div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Fecha / usuario</th><th>Módulo y acción</th><th>Mensaje</th><th>Nivel</th><th>Estado</th><th></th></tr></thead><tbody><?php foreach($filas as$error):?><tr><td class="text-nowrap"><?=date('d/m/Y H:i',strtotime((string)$error['ultima_ocurrencia_at']))?><small class="d-block text-muted"><?=atenea_e($error['usuario']?:'Sistema')?><?=!empty($error['rol'])?' · '.atenea_e(etiquetaRol((string)$error['rol'])):''?></small></td><td><?=atenea_e((string)$error['modulo'])?><small class="d-block text-muted"><?=atenea_e((string)($error['accion_intentada']?:'No indicada'))?> · <?=atenea_e((string)($error['modo_activo']?:'sin modo'))?></small></td><td><?=atenea_e((string)$error['mensaje'])?><small class="d-block text-muted">Correlación: <?=atenea_e((string)($error['correlacion_id']?:'no disponible'))?> · <?=(int)$error['ocurrencias']?> ocurrencia(s)</small></td><td><span class="badge badge-opacity-<?=$error['nivel']==='critico'?'danger':($error['nivel']==='advertencia'?'warning':'primary')?>"><?=atenea_e((string)$error['nivel'])?></span></td><td><?=atenea_e((string)$error['estado'])?></td><td><a class="btn btn-sm btn-outline-primary" href="detalle.php?id=<?=(int)$error['id']?>">Revisar</a></td></tr><?php endforeach;?><?php if(!$filas):?><tr><td colspan="6" class="text-center py-5 text-muted">No hay errores para estos filtros.</td></tr><?php endif;?></tbody></table></div>
<?php $paginas=max(1,(int)ceil($total/$limite));if($paginas>1):?><nav aria-label="Paginación de errores"><ul class="pagination justify-content-end"><?php for($i=1;$i<=$paginas;$i++):?><li class="page-item <?=$i===$pagina?'active':''?>"><a class="page-link" href="?<?=atenea_e(http_build_query(['estado'=>$estado,'nivel'=>$nivel,'rol'=>$soloHibridos?'administracion_docente':'','pagina'=>$i]))?>"><?=$i?></a></li><?php endfor;?></ul></nav><?php endif;?>
</div></div><?php cmsPie();
