<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/cms.php';
require_once dirname(__DIR__, 3) . '/includes/navbar_contenido.php';
$pdo=obtenerConexion(); $id=cmsId($_GET['id']??$_POST['id']??0); $tipos=tiposContenidoNavbarAtenea();
$f=['id'=>0,'padre_id'=>null,'texto'=>'','slug'=>'','icono'=>'','url'=>'','orden'=>0,'activo'=>1,'nueva_pestana'=>0,'visibilidad'=>'publica','roles_json'=>null,'tipo_contenido'=>'enlace_interno','contenido_html'=>'','contenido_json'=>null];
if($id){$q=$pdo->prepare('SELECT * FROM menu_sitio WHERE id=:id AND eliminado_at IS NULL');$q->execute(['id'=>$id]);$f=$q->fetch()?:$f;if(!(int)$f['id']){cmsFlash('error','La sección no existe o está en la papelera.');header('Location:index.php');exit;}}
$contenido=datosContenidoNavbarAtenea($f['contenido_json']??null); $roles=datosContenidoNavbarAtenea($f['roles_json']??null); $errores=[];
$padres=$pdo->prepare('SELECT id,texto,padre_id FROM menu_sitio WHERE eliminado_at IS NULL AND id<>:id ORDER BY orden,id');$padres->execute(['id'=>$id]);$padres=$padres->fetchAll();
$bloques=$pdo->query('SELECT id,nombre,clave FROM secciones WHERE activo=1 ORDER BY orden,id')->fetchAll();
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
 try{
  if(!validarTokenCsrf((string)($_POST['csrf_token']??'')))throw new DomainException('La sesión del formulario venció. Recarga la página.');
  $texto=trim(strip_tags((string)($_POST['texto']??'')));$slug=slugNavbarAtenea((string)((($_POST['slug']??'')?:$texto)));$icono=trim((string)($_POST['icono']??''));$tipo=(string)($_POST['tipo_contenido']??'');$url=trim((string)($_POST['url']??''));$padreId=cmsId($_POST['padre_id']??0)?:null;$orden=max(-9999,min(9999,(int)($_POST['orden']??0)));$activo=isset($_POST['activo'])?1:0;$nueva=isset($_POST['nueva_pestana'])?1:0;$visibilidad=(string)($_POST['visibilidad']??'publica');
  $roles=array_values(array_intersect(['admin','usuario','docente','administracion_docente'],array_map('strval',(array)($_POST['roles']??[]))));if($roles)$visibilidad='autenticada';
  if($texto===''||mb_strlen($texto)>100)throw new DomainException('El nombre es obligatorio y admite hasta 100 caracteres.');if($slug===''||mb_strlen($slug)>190)throw new DomainException('Define un identificador válido para la sección.');if(!isset($tipos[$tipo]))throw new DomainException('Selecciona un tipo de contenido permitido.');if(!iconoNavbarValidoAtenea($icono))throw new DomainException('El icono debe usar una clase Bootstrap Icons, por ejemplo: bi bi-leaf.');if(!in_array($visibilidad,['publica','autenticada'],true))throw new DomainException('La visibilidad seleccionada no es válida.');
  if($padreId){$q=$pdo->prepare('SELECT padre_id FROM menu_sitio WHERE id=:id AND eliminado_at IS NULL');$q->execute(['id'=>$padreId]);if($q->fetchColumn()===false)throw new DomainException('El menú superior seleccionado no existe.');$cursor=$padreId;for($nivel=0;$nivel<20&&$cursor;$nivel++){if($cursor===$id)throw new DomainException('Una sección no puede depender de sí misma ni de uno de sus submenús.');$q=$pdo->prepare('SELECT padre_id FROM menu_sitio WHERE id=:id');$q->execute(['id'=>$cursor]);$cursor=(int)$q->fetchColumn();}}
  $q=$pdo->prepare('SELECT id FROM menu_sitio WHERE slug=:slug AND id<>:id LIMIT 1');$q->execute(['slug'=>$slug,'id'=>$id]);if($q->fetch())throw new DomainException('Ya existe otra sección con ese identificador.');
  $esEnlace=in_array($tipo,['enlace_interno','enlace_externo'],true);if($esEnlace){if($url===''||!cmsUrlValida($url))throw new DomainException('La URL no es segura o válida.');if($tipo==='enlace_externo'&&!preg_match('#^https?://#i',$url))throw new DomainException('Un enlace externo debe comenzar con https:// o http://.');if($tipo==='enlace_interno'&&preg_match('#^https?://#i',$url))throw new DomainException('Para una URL completa selecciona Enlace externo.');}else{$url='src/website/seccion.php?slug='.rawurlencode($slug);}
  $html=(string)($_POST['contenido_html']??'');if(contieneCodigoProhibidoNavbarAtenea($html))throw new DomainException('El contenido contiene PHP, JavaScript, formularios o atributos no permitidos.');$html=sanitizarHtmlNavbarAtenea($html);
  $datos=['titulo'=>mb_substr(trim(strip_tags((string)($_POST['contenido_titulo']??$texto))),0,220),'resumen'=>mb_substr(trim(strip_tags((string)($_POST['contenido_resumen']??''))),0,1000),'imagen'=>$contenido['imagen']??null,'galeria'=>array_values(array_filter((array)($contenido['galeria']??[]))),'video_url'=>trim((string)($_POST['video_url']??'')),'archivo'=>$contenido['archivo']??null,'campos'=>array_values(array_intersect(['nombre','correo','telefono','asunto','mensaje'],array_map('strval',(array)($_POST['campos']??[])))),'bloque_id'=>cmsId($_POST['bloque_id']??0)?:null];
  if($datos['video_url']!==''&&(!filter_var($datos['video_url'],FILTER_VALIDATE_URL)||!preg_match('#^https://(?:www\.)?(?:youtube\.com|youtu\.be|vimeo\.com)/#i',$datos['video_url'])))throw new DomainException('El video debe ser una URL HTTPS válida de YouTube o Vimeo.');
  if($tipo==='formulario'&&!$datos['campos'])throw new DomainException('Selecciona al menos un campo para el formulario.');
  if($imagen=cmsSubirImagen('imagen'))$datos['imagen']=$imagen;if($galeria=cmsSubirGaleria('galeria'))$datos['galeria']=array_slice(array_merge($datos['galeria'],$galeria),0,20);if($archivo=cmsSubirArchivoContenido('archivo'))$datos['archivo']=$archivo;
  $params=['padre'=>$padreId,'texto'=>$texto,'slug'=>$slug,'icono'=>$icono?:null,'url'=>$url,'nueva'=>$nueva,'visibilidad'=>$visibilidad,'roles'=>$roles?json_encode($roles,JSON_THROW_ON_ERROR):null,'tipo'=>$tipo,'html'=>$html?:null,'contenido'=>json_encode($datos,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),'activo'=>$activo,'orden'=>$orden];
  if($id){$params['id']=$id;$sql='UPDATE menu_sitio SET padre_id=:padre,texto=:texto,slug=:slug,icono=:icono,url=:url,nueva_pestana=:nueva,visibilidad=:visibilidad,roles_json=:roles,tipo_contenido=:tipo,contenido_html=:html,contenido_json=:contenido,activo=:activo,orden=:orden WHERE id=:id AND eliminado_at IS NULL';}else{$sql='INSERT INTO menu_sitio(padre_id,texto,slug,icono,url,nueva_pestana,visibilidad,roles_json,tipo_contenido,contenido_html,contenido_json,activo,orden) VALUES(:padre,:texto,:slug,:icono,:url,:nueva,:visibilidad,:roles,:tipo,:html,:contenido,:activo,:orden)';}
  $pdo->prepare($sql)->execute($params);$guardado=$id?:((int)$pdo->lastInsertId());cmsFlash('exito','Sección guardada como borrador. Revísala en la vista previa antes de publicar.');header('Location:index.php?guardado='.$guardado);exit;
 }catch(Throwable$e){$errores[]=$e instanceof DomainException?$e->getMessage():'No fue posible guardar la sección.';}
 $f=array_merge($f,['padre_id'=>$padreId??null,'texto'=>$texto??'','slug'=>$slug??'','icono'=>$icono??'','url'=>$url??'','orden'=>$orden??0,'activo'=>$activo??0,'nueva_pestana'=>$nueva??0,'visibilidad'=>$visibilidad??'publica','tipo_contenido'=>$tipo??'enlace_interno','contenido_html'=>$html??'']);$contenido=$datos??$contenido;
}
cmsCabecera($id?'Editar sección de navegación':'Nueva sección de navegación','navbar/editar.php','Configura visibilidad, submenús y contenido sin insertar código ejecutable.');
?>
<?php foreach($errores as$e):?><div class="alert alert-danger" role="alert"><?=atenea_e($e)?></div><?php endforeach;?>
<form method="post" enctype="multipart/form-data" class="card card-rounded" data-navbar-editor><div class="card-body row g-3">
<input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$id?>">
<div class="col-md-6"><label class="form-label" for="texto">Nombre visible *</label><input class="form-control" id="texto" name="texto" maxlength="100" value="<?=atenea_e((string)$f['texto'])?>" required></div><div class="col-md-3"><label class="form-label" for="slug">Identificador</label><input class="form-control" id="slug" name="slug" maxlength="190" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value="<?=atenea_e((string)$f['slug'])?>" placeholder="se-genera-del-nombre"></div><div class="col-md-3"><label class="form-label" for="icono">Icono</label><input class="form-control" id="icono" name="icono" maxlength="100" pattern="bi bi-[a-z0-9-]+" value="<?=atenea_e((string)$f['icono'])?>" placeholder="bi bi-leaf"><div class="form-text">Bootstrap Icons.</div></div>
<div class="col-md-4"><label class="form-label" for="padre_id">Menú superior</label><select class="form-select" id="padre_id" name="padre_id"><option value="">Sección principal</option><?php foreach($padres as$p):?><option value="<?=$p['id']?>" <?=(int)$f['padre_id']===(int)$p['id']?'selected':''?>><?=atenea_e($p['texto'])?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label" for="tipo_contenido">Tipo de contenido *</label><select class="form-select" id="tipo_contenido" name="tipo_contenido" required><?php foreach($tipos as$valor=>$etiqueta):?><option value="<?=$valor?>" <?=$f['tipo_contenido']===$valor?'selected':''?>><?=atenea_e($etiqueta)?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label" for="orden">Orden</label><input class="form-control" id="orden" type="number" min="-9999" max="9999" name="orden" value="<?=(int)$f['orden']?>"></div><div class="col-md-2"><label class="form-label" for="visibilidad">Acceso</label><select class="form-select" id="visibilidad" name="visibilidad"><option value="publica" <?=$f['visibilidad']==='publica'?'selected':''?>>Pública</option><option value="autenticada" <?=$f['visibilidad']==='autenticada'?'selected':''?>>Requiere sesión</option></select></div>
<div class="col-12" data-url-field><label class="form-label" for="url">URL *</label><input class="form-control" id="url" name="url" maxlength="500" value="<?=atenea_e((string)$f['url'])?>"><div class="form-text">Para contenido administrado, Atenea genera la URL automáticamente.</div></div>
<fieldset class="col-12"><legend class="h6">Roles autorizados</legend><div class="d-flex flex-wrap gap-4"><?php foreach(['admin'=>'Administrador','usuario'=>'Estudiante o usuario','docente'=>'Docente','administracion_docente'=>'Administración_Docente'] as$r=>$label):?><label class="form-check"><input class="form-check-input" type="checkbox" name="roles[]" value="<?=$r?>" <?=in_array($r,$roles,true)?'checked':''?>><span class="form-check-label"><?=$label?></span></label><?php endforeach;?></div><div class="form-text">Sin selección: cualquier persona que cumpla la condición de acceso.</div></fieldset>
<div class="col-md-4"><label class="form-check form-switch"><input class="form-check-input" type="checkbox" name="activo" <?=$f['activo']?'checked':''?>><span class="form-check-label">Activa</span></label></div><div class="col-md-4"><label class="form-check form-switch"><input class="form-check-input" type="checkbox" name="nueva_pestana" <?=$f['nueva_pestana']?'checked':''?>><span class="form-check-label">Abrir en nueva pestaña</span></label></div>
<div class="col-12"><hr><h2 class="h5">Contenido de la sección</h2><p class="text-muted">Estos campos se utilizan en los tipos de contenido administrado.</p></div><div class="col-md-7"><label class="form-label" for="contenido_titulo">Título</label><input class="form-control" id="contenido_titulo" name="contenido_titulo" maxlength="220" value="<?=atenea_e((string)($contenido['titulo']??$f['texto']))?>"></div><div class="col-12"><label class="form-label" for="contenido_resumen">Resumen</label><textarea class="form-control" id="contenido_resumen" name="contenido_resumen" maxlength="1000" rows="3"><?=atenea_e((string)($contenido['resumen']??''))?></textarea></div><div class="col-12"><label class="form-label" for="contenido_html">Texto enriquecido permitido</label><textarea class="form-control" id="contenido_html" name="contenido_html" maxlength="100000" rows="10"><?=atenea_e((string)$f['contenido_html'])?></textarea><div class="form-text">Se permiten títulos, párrafos, listas, enlaces, énfasis e imágenes. PHP, JavaScript y formularios incrustados se rechazan.</div></div>
<div class="col-md-6"><label class="form-label" for="imagen">Imagen principal</label><input class="form-control" id="imagen" type="file" name="imagen" accept=".jpg,.jpeg,.png,.webp"><?php if(!empty($contenido['imagen'])):?><img class="preview-img mt-2" src="<?=rutaImagenContenido($contenido['imagen'])?>" alt="Imagen actual"><?php endif;?></div><div class="col-md-6"><label class="form-label" for="galeria">Galería (máximo 20)</label><input class="form-control" id="galeria" type="file" name="galeria[]" accept=".jpg,.jpeg,.png,.webp" multiple></div>
<div class="col-md-6"><label class="form-label" for="video_url">Video de YouTube o Vimeo</label><input class="form-control" id="video_url" type="url" name="video_url" maxlength="500" value="<?=atenea_e((string)($contenido['video_url']??''))?>" placeholder="https://www.youtube.com/watch?v=..."></div><div class="col-md-6"><label class="form-label" for="archivo">Archivo descargable</label><input class="form-control" id="archivo" type="file" name="archivo" accept=".pdf,.doc,.docx,.xls,.xlsx,.txt"><div class="form-text">Máximo 12 MB.</div></div>
<fieldset class="col-md-7"><legend class="h6">Campos del formulario</legend><div class="d-flex flex-wrap gap-3"><?php foreach(['nombre'=>'Nombre','correo'=>'Correo','telefono'=>'Teléfono','asunto'=>'Asunto','mensaje'=>'Mensaje'] as$campo=>$label):?><label class="form-check"><input class="form-check-input" type="checkbox" name="campos[]" value="<?=$campo?>" <?=in_array($campo,(array)($contenido['campos']??[]),true)?'checked':''?>><span class="form-check-label"><?=$label?></span></label><?php endforeach;?></div></fieldset><div class="col-md-5"><label class="form-label" for="bloque_id">Bloque reutilizable</label><select class="form-select" id="bloque_id" name="bloque_id"><option value="">Selecciona una sección existente</option><?php foreach($bloques as$b):?><option value="<?=$b['id']?>" <?=(int)($contenido['bloque_id']??0)===(int)$b['id']?'selected':''?>><?=atenea_e($b['nombre'].' · '.$b['clave'])?></option><?php endforeach;?></select></div>
<div class="col-12 d-flex flex-wrap gap-2"><a class="btn btn-light" href="index.php">Volver</a><?php if($id):?><a class="btn btn-outline-info" target="_blank" rel="noopener" href="preview.php?id=<?=$id?>">Vista previa</a><?php endif;?><button class="btn btn-primary text-white" type="submit"><i class="mdi mdi-content-save me-1"></i>Guardar borrador</button></div></div></form>
<script>(function(){const t=document.getElementById('tipo_contenido'),u=document.querySelector('[data-url-field]'),s=document.getElementById('slug'),n=document.getElementById('texto');function sync(){u.hidden=!['enlace_interno','enlace_externo'].includes(t.value)}t.addEventListener('change',sync);n.addEventListener('blur',()=>{if(!s.value)s.value=n.value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')});sync()})();</script>
<?php cmsPie(); ?>
