<?php
require_once dirname(__DIR__) . '/includes/cms.php';
$pdo=obtenerConexion();$filas=$pdo->query('SELECT * FROM menu_sitio ORDER BY orden,id')->fetchAll();
cmsCabecera('Navbar y menú','navbar/index.php','Administra los enlaces públicos; el acceso de sesión permanece protegido.');
?>
<div class="row"><div class="col-12 grid-margin stretch-card"><div class="card card-rounded"><div class="card-body">
<div class="d-flex flex-column flex-sm-row justify-content-between align-items-sm-center mb-4"><div><h2 class="card-title card-title-dash mb-1">Enlaces de navegación</h2><p class="text-muted mb-0">“Iniciar sesión” y el menú del usuario no pueden eliminarse desde este módulo.</p></div><a class="btn btn-primary text-white mt-3 mt-sm-0" href="editar.php"><i class="mdi mdi-plus me-1"></i>Agregar enlace</a></div>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Texto</th><th>URL</th><th>Orden</th><th>Estado</th><th>Nueva pestaña</th><th>Acciones</th></tr></thead><tbody>
<?php if(!$filas):?><tr><td colspan="6" class="text-center text-muted py-5">No hay enlaces registrados.</td></tr><?php endif;?>
<?php foreach($filas as $f):?><tr><td class="fw-semibold"><?=atenea_e($f['texto'])?></td><td><code><?=atenea_e($f['url'])?></code></td><td><?=$f['orden']?></td><td><span class="badge badge-opacity-<?=$f['activo']?'success':'secondary'?>"><?=$f['activo']?'Activo':'Inactivo'?></span></td><td><?=$f['nueva_pestana']?'Sí':'No'?></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-primary" href="editar.php?id=<?=$f['id']?>"><i class="mdi mdi-pencil"></i> Editar</a> <form class="d-inline" method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$f['id']?>"><input type="hidden" name="accion" value="toggle"><button class="btn btn-sm <?=$f['activo']?'btn-outline-warning':'btn-outline-success'?>"><i class="mdi <?=$f['activo']?'mdi-eye-off':'mdi-eye'?>"></i> <?=$f['activo']?'Desactivar':'Activar'?></button></form> <button class="btn btn-sm btn-outline-danger" data-bs-toggle="modal" data-bs-target="#delMenu<?=$f['id']?>"><i class="mdi mdi-delete"></i> Eliminar</button></td></tr>
<div class="modal fade" id="delMenu<?=$f['id']?>" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="h5 modal-title">Confirmar eliminación</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">Esta acción no se puede deshacer. ¿Deseas eliminar este contenido?</div><div class="modal-footer"><button class="btn btn-light" data-bs-dismiss="modal">Cancelar</button><form method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$f['id']?>"><input type="hidden" name="accion" value="eliminar"><button class="btn btn-danger"><i class="mdi mdi-delete me-1"></i>Sí, eliminar</button></form></div></div></div></div>
<?php endforeach;?></tbody></table></div></div></div></div></div>
<?php cmsPie(); ?>

