<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/cms.php';
require_once dirname(__DIR__,3) . '/includes/navbar_contenido.php';
$pdo=obtenerConexion();$filas=$pdo->query('SELECT m.*,p.texto padre_texto FROM menu_sitio m LEFT JOIN menu_sitio p ON p.id=m.padre_id WHERE m.eliminado_at IS NULL ORDER BY COALESCE(m.padre_id,m.id),m.padre_id IS NOT NULL,m.orden,m.id')->fetchAll();$tipos=tiposContenidoNavbarAtenea();$formulariosNuevos=(int)$pdo->query("SELECT COUNT(*) FROM menu_formulario_envios WHERE estado='nuevo'")->fetchColumn();
$publicado=publicacionWebsiteActual($pdo);$borrador=$pdo->query("SELECT updated_at FROM website_publicaciones WHERE estado='borrador' ORDER BY id DESC LIMIT 1")->fetchColumn();
cmsCabecera('Navbar y contenido dinámico','navbar/index.php','Crea secciones, submenús y contenido con visibilidad controlada por sesión y roles.');
?>
<div class="card card-rounded mb-3"><div class="card-body d-flex flex-wrap align-items-center gap-2"><span class="badge bg-warning text-dark">Borrador: <?=atenea_e((string)($borrador?:'sin cambios'))?></span><span class="badge bg-success">Publicado: <?=atenea_e((string)($publicado['publicado_at']??'sin publicar'))?></span><a class="btn btn-sm btn-outline-info ms-auto" href="<?=atenea_url('src/dashboard/website/editor.php?modulo=navbar')?>"><i class="mdi mdi-monitor-eye me-1"></i>Vista previa del sitio</a><a class="btn btn-sm btn-outline-primary" href="formularios.php"><i class="mdi mdi-form-select me-1"></i>Respuestas<?php if($formulariosNuevos):?> <span class="badge bg-danger"><?=$formulariosNuevos?></span><?php endif;?></a><a class="btn btn-sm btn-outline-secondary" href="papelera.php"><i class="mdi mdi-delete-restore me-1"></i>Papelera</a><a class="btn btn-sm btn-primary text-white" href="editar.php"><i class="mdi mdi-plus me-1"></i>Nueva sección</a></div></div>
<div class="card card-rounded"><div class="card-body"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Sección</th><th>Tipo</th><th>Acceso</th><th>Orden</th><th>Estado</th><th>Destino</th><th>Acciones</th></tr></thead><tbody>
<?php if(!$filas):?><tr><td colspan="7" class="text-center text-muted py-5">No hay secciones configuradas.</td></tr><?php endif;?>
<?php foreach($filas as$f):$roles=datosContenidoNavbarAtenea($f['roles_json']);?><tr><td><div class="fw-semibold"><?php if($f['padre_id']):?><span class="text-muted me-1">↳</span><?php endif;?><?php if($f['icono']):?><i class="<?=atenea_e($f['icono'])?> me-1"></i><?php endif;?><?=atenea_e($f['texto'])?></div><small class="text-muted"><?=atenea_e($f['padre_texto']?'Submenú de '.$f['padre_texto']:'Sección principal')?> · <?=atenea_e($f['slug'])?></small></td><td><?=atenea_e($tipos[$f['tipo_contenido']]??$f['tipo_contenido'])?></td><td><span class="badge badge-opacity-<?=$f['visibilidad']==='publica'?'success':'warning'?>"><?=$f['visibilidad']==='publica'?'Pública':'Con sesión'?></span><?php if($roles):?><small class="d-block mt-1"><?=atenea_e(implode(', ',$roles))?></small><?php endif;?></td><td><?=(int)$f['orden']?></td><td><span class="badge badge-opacity-<?=$f['activo']?'success':'secondary'?>"><?=$f['activo']?'Activa':'Inactiva'?></span></td><td><small><?=$f['nueva_pestana']?'Nueva pestaña':'Misma pestaña'?></small></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-primary" href="editar.php?id=<?=$f['id']?>">Editar</a> <?php if(!in_array($f['tipo_contenido'],['enlace_interno','enlace_externo'],true)):?><a class="btn btn-sm btn-outline-info" target="_blank" rel="noopener" href="preview.php?id=<?=$f['id']?>">Previsualizar</a> <?php endif;?><form class="d-inline" method="post" action="accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$f['id']?>"><input type="hidden" name="accion" value="toggle"><button class="btn btn-sm <?=$f['activo']?'btn-outline-warning':'btn-outline-success'?>"><?=$f['activo']?'Desactivar':'Activar'?></button></form> <form class="d-inline" method="post" action="accion.php" data-atenea-confirm="papelera" data-atenea-danger="true" data-atenea-confirm-title="¿Mover a la papelera?" data-atenea-confirm-message="La sección y sus submenús dejarán de estar disponibles, pero podrás restaurarlos."><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$f['id']?>"><input type="hidden" name="accion" value="eliminar"><button class="btn btn-sm btn-outline-danger">Eliminar</button></form></td></tr><?php endforeach;?></tbody></table></div>
<div class="alert alert-info mt-3 mb-0"><i class="mdi mdi-information-outline me-1"></i>Los cambios se guardan en el borrador. Usa <strong>Editor y vista previa</strong> para revisarlos y publicar la versión completa del website.</div></div></div>
<?php cmsPie(); ?>
