<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/session.php';
require_once dirname(__DIR__,2).'/includes/mail_config.php';
require_once dirname(__DIR__,2).'/includes/contenido.php';
$correoCfg=configuracionCorreoAtenea();$sitio=obtenerConfiguracionSitio();$captchaDisponible=trim((string)($correoCfg['recaptcha_site_key']??''))!==''&&trim((string)($correoCfg['recaptcha_secret_key']??''))!=='';$contactoDisponible=configuracionContactoCompleta($correoCfg)&&$captchaDisponible&&is_file(dirname(__DIR__,2).'/includes/mail/vendor/autoload.php');
$flash=is_array($_SESSION['contacto_flash']??null)?$_SESSION['contacto_flash']:[];$datos=is_array($_SESSION['contacto_datos']??null)?$_SESSION['contacto_datos']:[];$errores=is_array($_SESSION['contacto_errores']??null)?$_SESSION['contacto_errores']:[];unset($_SESSION['contacto_flash'],$_SESSION['contacto_datos'],$_SESSION['contacto_errores']);
$formularios=array_filter(is_array($_SESSION['contacto_formularios']??null)?$_SESSION['contacto_formularios']:[],static fn($t)=>is_int($t)&&$t>=time()-1200);$formularioId=bin2hex(random_bytes(16));$formularios[$formularioId]=time();$_SESSION['contacto_formularios']=array_slice($formularios,-10,null,true);
$pageTitle='Contacto | Atenea';$pageDescription='Comunícate con Atenea Escuela de Naturopatía Holística.';$pageClass='contact-page';$activePage='contacto';require dirname(__DIR__,2).'/includes/header.php';
?>
<main class="main contact-modern"><div class="page-title"><div class="heading"><div class="container"><div class="row justify-content-center text-center"><div class="col-lg-8"><span class="contact-eyebrow">Hablemos</span><h1>¿Cómo podemos ayudarte?</h1><p class="mb-0">Nuestro equipo puede orientarte sobre capacitaciones, productos, eventos y procesos académicos.</p></div></div></div></div><nav class="breadcrumbs"><div class="container"><ol><li><a href="<?=atenea_url('index.php')?>">Inicio</a></li><li class="current" aria-current="page">Contacto</li></ol></div></nav></div>
<section class="section"><div class="container"><div class="row g-5 align-items-start"><div class="col-lg-5"><aside class="contact-information"><div><span class="contact-kicker">Información de contacto</span><h2>Estamos cerca de ti</h2><p>Elige el medio que prefieras. Respondemos cada solicitud desde nuestro centro de comunicaciones.</p></div><div class="contact-info-grid">
<div class="contact-info-card"><i class="bi bi-envelope" aria-hidden="true"></i><div><h3>Correo</h3><a href="mailto:<?=atenea_e((string)($sitio['correo']??'info@atenea.edu.sv'))?>"><?=atenea_e((string)($sitio['correo']??'info@atenea.edu.sv'))?></a></div></div>
<div class="contact-info-card"><i class="bi bi-telephone" aria-hidden="true"></i><div><h3>Teléfono</h3><p><?=atenea_e(trim((string)($sitio['telefono']??''))?:'Disponible por nuestros canales digitales')?></p></div></div>
<div class="contact-info-card"><i class="bi bi-geo-alt" aria-hidden="true"></i><div><h3>Ubicación</h3><p><?=atenea_e((string)($sitio['direccion']??'El Salvador'))?></p></div></div>
<div class="contact-info-card"><i class="bi bi-clock" aria-hidden="true"></i><div><h3>Horario</h3><p>Lunes a viernes<br>8:00 a. m. – 5:00 p. m.</p></div></div></div><div class="contact-response-note"><i class="bi bi-chat-heart" aria-hidden="true"></i><span><strong>Respuesta personalizada</strong> Revisaremos tu consulta y te responderemos por el correo indicado.</span></div></aside></div>
<div class="col-lg-7"><div class="contact-form-card"><div class="contact-form-heading"><span class="contact-kicker">Envíanos un mensaje</span><h2>Cuéntanos en qué podemos orientarte</h2><p>Los campos marcados con * son obligatorios.</p></div>
<?php if($flash):?><div class="contact-result is-<?=($flash['tipo']??'')==='exito'?'success':'error'?>" role="<?=($flash['tipo']??'')==='exito'?'status':'alert'?>"><i class="bi <?=($flash['tipo']??'')==='exito'?'bi-check-circle':'bi-exclamation-circle'?>"></i><span><?=atenea_e((string)($flash['mensaje']??''))?></span></div><?php endif;?>
<?php if(!$contactoDisponible):?><div class="contact-result is-error" role="alert"><i class="bi bi-tools"></i><span>El formulario está temporalmente fuera de servicio. Puedes escribirnos directamente al correo indicado.</span></div><?php endif;?>
<form id="contact-form" action="<?=atenea_url('src/website/forms/contact.php')?>" method="post" class="atenea-contact-form" novalidate data-contact-ajax><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="formulario_id" value="<?=atenea_e($formularioId)?>"><div class="contact-honeypot" aria-hidden="true"><label for="website">No completar</label><input id="website" name="website" tabindex="-1" autocomplete="off"></div><div class="row g-4">
<?php $campos=[['name','Nombre completo','text',100,true,'Escribe tu nombre.'],['email','Correo electrónico','email',190,true,'nombre@correo.com'],['phone','Teléfono','tel',30,false,'Opcional'],['subject','Asunto','text',150,true,'¿Sobre qué deseas consultar?']];foreach($campos as[$nombre,$label,$tipo,$max,$req,$placeholder]):?><div class="<?=$nombre==='subject'?'col-12':'col-md-6'?>"><label class="form-label" for="contact-<?=$nombre?>"><?=$label?><?=$req?' *':''?></label><input class="form-control" id="contact-<?=$nombre?>" type="<?=$tipo?>" name="<?=$nombre?>" maxlength="<?=$max?>" value="<?=atenea_e((string)($datos[$nombre]??''))?>" placeholder="<?=atenea_e($placeholder)?>" <?=$req?'required':''?> aria-describedby="error-<?=$nombre?>"><div class="contact-field-error" id="error-<?=$nombre?>" data-error-for="<?=$nombre?>" aria-live="polite"><?=atenea_e((string)($errores[$nombre]??''))?></div></div><?php endforeach;?>
<div class="col-12"><label class="form-label" for="contact-message">Mensaje *</label><textarea class="form-control" id="contact-message" name="message" rows="9" maxlength="5000" required placeholder="Incluye la información necesaria para poder orientarte mejor." aria-describedby="error-message"><?=atenea_e((string)($datos['message']??''))?></textarea><div class="d-flex justify-content-between"><div class="contact-field-error" id="error-message" data-error-for="message" aria-live="polite"><?=atenea_e((string)($errores['message']??''))?></div><small class="contact-character-count" data-message-count>0 / 5000</small></div></div>
<div class="col-12"><div class="g-recaptcha" data-sitekey="<?=atenea_e((string)($correoCfg['recaptcha_site_key']??''))?>"></div><div class="contact-field-error" data-error-for="captcha" aria-live="polite"><?=atenea_e((string)($errores['captcha']??''))?></div></div>
<div class="col-12"><div class="contact-result" data-contact-result hidden aria-live="polite"></div><button class="contact-submit" type="submit" <?=$contactoDisponible?'':'disabled'?>><span data-submit-label><i class="bi bi-send" aria-hidden="true"></i> Enviar mensaje</span><span data-submit-loading hidden><span class="spinner-border spinner-border-sm" aria-hidden="true"></span> Enviando…</span></button><p class="contact-privacy"><i class="bi bi-shield-check" aria-hidden="true"></i> Protegemos tus datos y evitamos envíos duplicados.</p></div></div></form></div></div></div></div></section></main>
<?php if($captchaDisponible):?><script src="https://www.google.com/recaptcha/api.js" async defer></script><?php endif;?><script src="<?=atenea_url('src/website/assets/js/contact-form.js')?>" defer></script><?php require dirname(__DIR__,2).'/includes/footer.php';?>
