<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/auth.php';
require_once dirname(__DIR__,2).'/includes/contenido.php';
require_once dirname(__DIR__,2).'/includes/navbar_contenido.php';
require_once dirname(__DIR__,2).'/includes/noticias.php';
require_once dirname(__DIR__,2).'/includes/comercio.php';
require_once dirname(__DIR__,2).'/includes/capacitaciones.php';
$previewToken=(string)($_GET['preview_token']??'');$esPreview=false;if($previewToken!==''){if(!validarTokenPreviewWebsite(obtenerConexion(),$previewToken))mostrarPaginaErrorAtenea(403);$GLOBALS['ATENEA_WEBSITE_PREVIEW']=true;$esPreview=true;header('Cache-Control: private, no-store');header("Content-Security-Policy: frame-ancestors 'self'");}
$slug=slugNavbarAtenea((string)($_GET['slug']??''));$item=null;foreach(filasEstadoWebsite('menu_sitio')as$f)if(($f['slug']??'')===$slug){$item=$f;break;}
if(!$item||(!$esPreview&&((int)($item['activo']??0)!==1||!empty($item['eliminado_at']))))mostrarPaginaErrorAtenea(404);
$usuario=obtenerUsuarioActual();if(!$esPreview&&($item['visibilidad']??'publica')==='autenticada'&&!$usuario){$_SESSION['url_retorno']=(string)($_SERVER['REQUEST_URI']??'');$_SESSION['mensaje_auth']='Inicia sesión para acceder a esta sección.';header('Location:'.atenea_url('src/login/sign-in.php'));exit;}$roles=datosContenidoNavbarAtenea($item['roles_json']??null);if(!$esPreview&&$roles&&(!$usuario||!in_array($usuario['rol'],$roles,true)))mostrarPaginaErrorAtenea(403);
$datos=datosContenidoNavbarAtenea($item['contenido_json']??null);$tipo=(string)($item['tipo_contenido']??'pagina_informativa');$titulo=(string)($datos['titulo']??$item['texto']);$resumen=(string)($datos['resumen']??'');$html=sanitizarHtmlNavbarAtenea((string)($item['contenido_html']??''));
$pageTitle=$titulo.' | Atenea';$pageDescription=$resumen?:$titulo;$pageClass='dynamic-section-page';$activePage='navbar-'.$slug;require dirname(__DIR__,2).'/includes/header.php';
?>
<main class="main"><div class="page-title"><div class="heading"><div class="container"><div class="row justify-content-center text-center"><div class="col-lg-9"><?php if($esPreview):?><span class="badge bg-warning text-dark mb-3">Vista previa del borrador</span><?php endif;?><h1><?php if(!empty($item['icono'])):?><i class="<?=atenea_e($item['icono'])?>" aria-hidden="true"></i> <?php endif;?><?=atenea_e($titulo)?></h1><?php if($resumen):?><p class="mb-0"><?=atenea_e($resumen)?></p><?php endif;?></div></div></div></div><nav class="breadcrumbs"><div class="container"><ol><li><a href="<?=atenea_url('index.php')?>">Inicio</a></li><li class="current" aria-current="page"><?=atenea_e($item['texto'])?></li></ol></div></nav></div>
<?php if(!empty($datos['imagen'])):?><section class="section pb-0"><div class="container"><img class="img-fluid rounded-4 w-100 dynamic-hero-image" src="<?=rutaImagenContenido($datos['imagen'])?>" alt="<?=atenea_e($titulo)?>"></div></section><?php endif;?>
<?php if($html):?><section class="section"><div class="container"><article class="dynamic-rich-content mx-auto"><?=$html?></article></div></section><?php endif;?>
<?php if($tipo==='galeria'||$tipo==='imagenes'):?><section class="section light-background"><div class="container"><div class="row g-4"><?php foreach((array)($datos['galeria']??[])as$i=>$imagen):?><div class="col-sm-6 col-lg-4"><a href="<?=rutaImagenContenido($imagen)?>" class="glightbox"><img class="img-fluid rounded-3 dynamic-gallery-image" src="<?=rutaImagenContenido($imagen)?>" alt="<?=atenea_e($titulo.' · imagen '.($i+1))?>" loading="lazy"></a></div><?php endforeach;?><?php if(empty($datos['galeria'])):?><div class="col-12"><div class="alert alert-info text-center">Aún no hay imágenes en esta sección.</div></div><?php endif;?></div></div></section><?php endif;?>
<?php if($tipo==='video'&&!empty($datos['video_url'])):$video=(string)$datos['video_url'];$embed='';if(preg_match('~(?:youtube\.com/watch\?v=|youtu\.be/)([A-Za-z0-9_-]{6,20})~',$video,$m))$embed='https://www.youtube-nocookie.com/embed/'.$m[1];elseif(preg_match('~vimeo\.com/(\d{5,15})~',$video,$m))$embed='https://player.vimeo.com/video/'.$m[1];?><section class="section"><div class="container"><?php if($embed):?><div class="ratio ratio-16x9 dynamic-video"><iframe src="<?=atenea_e($embed)?>" title="<?=atenea_e($titulo)?>" loading="lazy" allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div><?php endif;?></div></section><?php endif;?>
<?php if($tipo==='archivo_descargable'&&!empty($datos['archivo'])):?><section class="section"><div class="container text-center"><a class="btn btn-primary btn-lg" href="<?=atenea_url($datos['archivo'])?>" download><i class="bi bi-download me-2"></i>Descargar archivo</a></div></section><?php endif;?>
<?php if($tipo==='noticias'):$items=obtenerNoticiasPublicadas(12);?><section class="section"><div class="container"><div class="row gy-4"><?php foreach($items as$n):?><div class="col-md-6 col-lg-4"><article class="card h-100"><img class="card-img-top dynamic-card-image" src="<?=rutaImagenContenido($n['imagen_portada'],'src/website/assets/img/events-item-1.jpg')?>" alt="<?=atenea_e($n['titulo'])?>"><div class="card-body"><h2 class="h5"><?=atenea_e($n['titulo'])?></h2><p><?=atenea_e($n['resumen'])?></p><a href="<?=urlNoticia($n)?>">Leer noticia <i class="bi bi-arrow-right"></i></a></div></article></div><?php endforeach;?><?php if(!$items):?><div class="col-12 text-center text-muted py-5">No hay noticias publicadas.</div><?php endif;?></div></div></section><?php endif;?>
<?php if($tipo==='productos'):$items=catalogoProductos();?><section class="section"><div class="container"><div class="row gy-4"><?php foreach($items as$p):$precio=$p['precio_calculado'];?><div class="col-md-6 col-lg-4"><article class="card h-100"><img class="card-img-top dynamic-card-image" src="<?=imagenProducto($p['imagen_principal'])?>" alt="<?=atenea_e($p['nombre'])?>"><div class="card-body d-flex flex-column"><h2 class="h5"><?=atenea_e($p['nombre'])?></h2><p><?=atenea_e($p['descripcion_corta'])?></p><strong class="text-success mb-3">$<?=number_format($precio['final'],2)?> USD</strong><a class="mt-auto" href="<?=atenea_url('src/website/product-details.php?id='.(int)$p['id'])?>">Ver producto <i class="bi bi-arrow-right"></i></a></div></article></div><?php endforeach;?><?php if(!$items):?><div class="col-12 text-center text-muted py-5">No hay productos disponibles.</div><?php endif;?></div></div></section><?php endif;?>
<?php if($tipo==='capacitaciones'):$items=capacitacionesPublicasWebsite();?><section class="section"><div class="container"><div class="row gy-4"><?php foreach($items as$c):?><div class="col-md-6 col-lg-4"><article class="card h-100"><img class="card-img-top dynamic-card-image" src="<?=rutaImagenContenido($c['imagen'],'src/website/assets/img/course-1.jpg')?>" alt="<?=atenea_e($c['nombre'])?>"><div class="card-body d-flex flex-column"><h2 class="h5"><?=atenea_e($c['nombre'])?></h2><p><?=atenea_e($c['descripcion_corta'])?></p><a class="mt-auto" href="<?=atenea_url('src/website/capacitacion.php?slug='.rawurlencode($c['slug']))?>">Ver capacitación <i class="bi bi-arrow-right"></i></a></div></article></div><?php endforeach;?><?php if(!$items):?><div class="col-12 text-center text-muted py-5">No hay capacitaciones publicadas.</div><?php endif;?></div></div></section><?php endif;?>
<?php if($tipo==='formulario'):$campos=(array)($datos['campos']??[]);?><section class="section"><div class="container"><form class="php-email-form dynamic-form mx-auto" method="post" action="<?=atenea_url('src/website/forms/seccion.php')?>"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="seccion_id" value="<?=(int)$item['id']?>"><input class="d-none" tabindex="-1" autocomplete="off" name="sitio_web" aria-hidden="true"><?php foreach($campos as$campo):$label=['nombre'=>'Nombre','correo'=>'Correo electrónico','telefono'=>'Teléfono','asunto'=>'Asunto','mensaje'=>'Mensaje'][$campo]??null;if(!$label)continue;?><div class="mb-3"><label class="form-label" for="campo-<?=$campo?>"><?=$label?></label><?php if($campo==='mensaje'):?><textarea class="form-control" id="campo-<?=$campo?>" name="<?=$campo?>" maxlength="3000" rows="6" required></textarea><?php else:?><input class="form-control" id="campo-<?=$campo?>" type="<?=$campo==='correo'?'email':($campo==='telefono'?'tel':'text')?>" name="<?=$campo?>" maxlength="<?=$campo==='asunto'?200:160?>" required><?php endif;?></div><?php endforeach;?><button class="btn btn-primary" type="submit">Enviar formulario</button></form></div></section><?php endif;?>
<?php if($tipo==='bloques_reutilizables'&&!empty($datos['bloque_id'])):$bloque=null;foreach(filasEstadoWebsite('secciones')as$s)if((int)$s['id']===(int)$datos['bloque_id']){$bloque=$s;break;}if($bloque):?><section class="section light-background"><div class="container"><div class="section-title"><h2><?=atenea_e((string)$bloque['titulo'])?></h2><p><?=atenea_e((string)$bloque['subtitulo'])?></p></div><div class="row gy-4"><?php foreach(filasEstadoWebsite('elementos_seccion')as$e)if((int)$e['seccion_id']===(int)$bloque['id']&&(int)$e['activo']===1):?><div class="col-md-6 col-lg-4"><article class="card h-100"><div class="card-body"><?php if($e['icono']):?><i class="<?=atenea_e($e['icono'])?> fs-2"></i><?php endif;?><h3 class="h5 mt-2"><?=atenea_e($e['titulo'])?></h3><p><?=atenea_e((string)$e['descripcion'])?></p><?php if($e['enlace']):?><a href="<?=atenea_e(urlContenidoSegura($e['enlace']))?>"><?=atenea_e((string)($e['texto_boton']?:'Ver más'))?></a><?php endif;?></div></article></div><?php endif;?></div></div></section><?php endif;endif;?>
</main><?php require dirname(__DIR__,2).'/includes/footer.php'; ?>
