<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';
require_once dirname(__DIR__,3).'/includes/academico_flujo.php';
exigirPermiso('academic.supervise');
$pdo=obtenerConexion();$asignatura=cmsId($_GET['asignatura']??0);$seccion=cmsId($_GET['seccion']??0);$estado=trim((string)($_GET['estado']??''));$permitidos=['','inscrito','finalizado','pendiente_asignacion'];if(!in_array($estado,$permitidos,true))$estado='';$where='1=1';$params=[];if($asignatura){$where.=' AND i.asignatura_id=:a';$params['a']=$asignatura;}if($seccion){$where.=' AND i.seccion_id=:s';$params['s']=$seccion;}if($estado){$where.=' AND i.estado=:e';$params['e']=$estado;}
$q=$pdo->prepare("SELECT i.id,i.estado,i.finalizacion_confirmada_at,u.nombre,u.apellido,u.correo,a.nombre capacitacion,a.certificado_disponible,s.codigo seccion,CONCAT(d.nombre,' ',d.apellido) docente,cc.id certificado_id FROM inscripciones_capacitacion i JOIN usuarios u ON u.id=i.usuario_id JOIN asignaturas a ON a.id=i.asignatura_id LEFT JOIN capacitacion_secciones s ON s.id=i.seccion_id LEFT JOIN usuarios d ON d.id=s.docente_id LEFT JOIN certificados_capacitacion cc ON cc.inscripcion_id=i.id AND cc.estado='emitido' WHERE $where ORDER BY a.nombre,s.codigo,u.apellido,u.nombre LIMIT 500");$q->execute($params);$inscripciones=$q->fetchAll();
$capacitaciones=$pdo->query("SELECT id,nombre FROM asignaturas WHERE deleted_at IS NULL ORDER BY nombre")->fetchAll();$secciones=$pdo->query("SELECT s.id,s.codigo,a.nombre FROM capacitacion_secciones s JOIN asignaturas a ON a.id=s.asignatura_id ORDER BY a.nombre,s.codigo")->fetchAll();
$contenidos=$pdo->query("SELECT c.titulo,c.tipo,c.activo,c.obligatorio,a.nombre capacitacion,s.codigo seccion,CONCAT(u.nombre,' ',u.apellido) docente FROM contenidos c JOIN asignaturas a ON a.id=c.asignatura_id LEFT JOIN capacitacion_secciones s ON s.id=c.seccion_id JOIN usuarios u ON u.id=c.docente_id WHERE c.seccion_id IS NOT NULL ORDER BY c.created_at DESC LIMIT 100")->fetchAll();
$entregas=$pdo->query("SELECT e.id,e.estado,e.nota,e.retroalimentacion,c.titulo,CONCAT(al.nombre,' ',al.apellido) estudiante,CONCAT(doc.nombre,' ',doc.apellido) revisor,(SELECT COUNT(*) FROM entrega_revisiones r WHERE r.entrega_id=e.id) revisiones,(SELECT GROUP_CONCAT(ev.id ORDER BY ev.id) FROM entrega_evidencias ev WHERE ev.entrega_id=e.id) evidencias FROM entregas_contenido e JOIN contenidos c ON c.id=e.contenido_id JOIN usuarios al ON al.id=e.estudiante_id LEFT JOIN usuarios doc ON doc.id=e.revisado_por ORDER BY e.enviado_at DESC LIMIT 100")->fetchAll();
cmsCabecera('Seguimiento académico','academico/seguimiento.php','Contenidos, entregas, notas, progreso y certificados de todas las secciones.');?>
<div class="card card-rounded mb-4"><div class="card-body"><form class="row g-2" method="get"><div class="col-md-4"><select class="form-select" name="asignatura"><option value="">Todas las capacitaciones</option><?php foreach($capacitaciones as$a):?><option value="<?=$a['id']?>" <?=$asignatura===(int)$a['id']?'selected':''?>><?=atenea_e($a['nombre'])?></option><?php endforeach;?></select></div><div class="col-md-4"><select class="form-select" name="seccion"><option value="">Todas las secciones</option><?php foreach($secciones as$s):?><option value="<?=$s['id']?>" <?=$seccion===(int)$s['id']?'selected':''?>><?=atenea_e($s['nombre'].' · '.$s['codigo'])?></option><?php endforeach;?></select></div><div class="col-md-2"><select class="form-select" name="estado"><option value="">Todos los estados</option><?php foreach(array_slice($permitidos,1) as$e):?><option value="<?=$e?>" <?=$estado===$e?'selected':''?>><?=atenea_e(ucfirst(str_replace('_',' ',$e)))?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Filtrar</button></div></form></div></div>
<div class="card card-rounded mb-4"><div class="card-body"><h2 class="h5">Progreso individual</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Estudiante</th><th>Capacitación</th><th>Docente</th><th>Progreso</th><th>Entregas / nota</th><th>Certificado</th></tr></thead><tbody><?php foreach($inscripciones as$f):$p=progresoInscripcion($pdo,(int)$f['id']);?><tr><td><?=atenea_e(trim($f['nombre'].' '.$f['apellido']))?><small class="d-block text-muted"><?=atenea_e($f['correo'])?></small></td><td><?=atenea_e($f['capacitacion'])?><small class="d-block"><?=atenea_e((string)($f['seccion']?:'Sin asignar'))?></small></td><td><?=atenea_e((string)($f['docente']?:'Pendiente'))?></td><td><div class="progress" style="min-width:120px"><div class="progress-bar" style="width:<?=$p['porcentaje']?>%"><?=$p['porcentaje']?>%</div></div><small>Vistos <?=$p['contenidos_vistos']?> · última <?=atenea_e((string)$p['ultima_actividad'])?></small></td><td>Aprobadas <?=$p['entregas_aprobadas']?> · pendientes <?=$p['entregas_pendientes']?> · rechazadas <?=$p['entregas_rechazadas']?><br><strong>Promedio: <?=$p['promedio']===null?'—':number_format($p['promedio'],2)?></strong></td><td><?php if($f['certificado_id']):?><a class="btn btn-sm btn-outline-success" href="<?=atenea_url('src/academico/archivo.php?tipo=certificado&id='.(int)$f['certificado_id'])?>">Descargar</a><?php elseif($p['elegible']&&(int)$f['certificado_disponible']===1):?><form method="post" action="finalizacion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="inscripcion_id" value="<?=$f['id']?>"><button class="btn btn-sm btn-success">Confirmar y emitir</button></form><?php else:?><span class="text-muted">No elegible</span><?php endif;?></td></tr><?php endforeach;?><?php if(!$inscripciones):?><tr><td colspan="6" class="text-center py-4">No hay inscripciones para los filtros seleccionados.</td></tr><?php endif;?></tbody></table></div></div></div>
<div class="row"><div class="col-xl-6"><div class="card card-rounded mb-4"><div class="card-body"><h2 class="h5">Contenidos recientes</h2><div class="table-responsive"><table class="table"><thead><tr><th>Contenido</th><th>Sección</th><th>Docente</th><th>Estado</th></tr></thead><tbody><?php foreach($contenidos as$c):?><tr><td><?=atenea_e($c['titulo'])?><small class="d-block"><?=atenea_e($c['tipo'])?><?=$c['obligatorio']?' · obligatorio':''?></small></td><td><?=atenea_e($c['capacitacion'].' · '.$c['seccion'])?></td><td><?=atenea_e($c['docente'])?></td><td><?=$c['activo']?'<span class="badge bg-success">Activo</span>':'<span class="badge bg-secondary">Inactivo</span>'?></td></tr><?php endforeach;?></tbody></table></div></div></div></div><div class="col-xl-6"><div class="card card-rounded mb-4"><div class="card-body"><h2 class="h5">Entregas y revisiones recientes</h2><div class="table-responsive"><table class="table"><thead><tr><th>Estudiante / contenido</th><th>Estado</th><th>Nota</th><th>Historial y evidencias</th></tr></thead><tbody><?php foreach($entregas as$e):?><tr><td><?=atenea_e($e['estudiante'])?><small class="d-block"><?=atenea_e($e['titulo'])?></small></td><td><?=atenea_e(str_replace('_',' ',$e['estado']))?></td><td><?=$e['nota']===null?'—':number_format((float)$e['nota'],2)?></td><td><?=$e['revisiones']?> revisión(es)<small class="d-block"><?=atenea_e((string)($e['revisor']?:'Sin revisor'))?></small><?php if($e['retroalimentacion']):?><small class="d-block"><?=atenea_e(mb_strimwidth($e['retroalimentacion'],0,100,'…'))?></small><?php endif;?><?php foreach(array_filter(explode(',',(string)$e['evidencias'])) as$ev):?><a class="btn btn-xs btn-outline-secondary me-1 mt-1" href="<?=atenea_url('src/academico/archivo.php?tipo=evidencia&id='.(int)$ev)?>">Evidencia <?=$ev?></a><?php endforeach;?></td></tr><?php endforeach;?></tbody></table></div></div></div></div></div>
<?php cmsPie();
