<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';
if(($_SERVER['REQUEST_METHOD']??'')!=='POST'||!validarTokenCsrf((string)($_POST['csrf_token']??''))){http_response_code(400);exit;}
$id=cmsId($_POST['id']??0);$accion=(string)($_POST['accion']??'');$pdo=obtenerConexion();
try{
 $pdo->beginTransaction();$q=$pdo->prepare('SELECT * FROM asignaturas WHERE id=:id AND deleted_at IS NULL FOR UPDATE');$q->execute(['id'=>$id]);$a=$q->fetch();if(!$a)throw new DomainException('La capacitación no existe.');
 if($accion==='toggle'){$nuevo=(int)!$a['activo'];$pdo->prepare('UPDATE asignaturas SET activo=:activo,estado=:estado WHERE id=:id')->execute(['activo'=>$nuevo,'estado'=>$nuevo?'activo':'inactivo','id'=>$id]);$mensaje='Estado actualizado.';}
 elseif($accion==='duplicar'){$sufijo=substr(bin2hex(random_bytes(4)),0,8);$q=$pdo->prepare("INSERT INTO asignaturas(codigo,nombre,slug,descripcion,descripcion_corta,descripcion_completa,imagen,tipo,nivel,precio,precio_anterior,promocion_etiqueta,promocion_desde,promocion_hasta,duracion,fecha_inicio,fecha_finalizacion,estado_capacitacion,cupo_seccion,requisitos,objetivos,modalidad,certificado_disponible,orden,activo,estado,creado_por) SELECT CONCAT(LEFT(codigo,31),'-COP-',:codigo_s),CONCAT(nombre,' (copia)'),CONCAT(LEFT(slug,180),'-',:slug_s),descripcion,descripcion_corta,descripcion_completa,imagen,tipo,nivel,precio,precio_anterior,promocion_etiqueta,promocion_desde,promocion_hasta,duracion,fecha_inicio,fecha_finalizacion,'borrador',cupo_seccion,requisitos,objetivos,modalidad,certificado_disponible,orden+1,0,'inactivo',:admin FROM asignaturas WHERE id=:id");$q->execute(['codigo_s'=>$sufijo,'slug_s'=>$sufijo,'admin'=>$_SESSION['usuario_id'],'id'=>$id]);$mensaje='Capacitación duplicada como borrador, sin docentes ni estudiantes.';}
 elseif($accion==='eliminar'){$pdo->prepare("UPDATE asignaturas SET estado_capacitacion='archivada',activo=0,estado='inactivo',deleted_at=NOW(),eliminado_por=:admin WHERE id=:id")->execute(['admin'=>$_SESSION['usuario_id'],'id'=>$id]);$pdo->prepare("UPDATE capacitacion_secciones SET estado='inactiva' WHERE asignatura_id=:id AND estado='abierta'")->execute(['id'=>$id]);$mensaje='Capacitación archivada; pagos, inscripciones, entregas y progreso se conservaron.';}
 else throw new DomainException('Acción inválida.');
 registrarAuditoria(['actor_user_id'=>$_SESSION['usuario_id'],'event_type'=>'training.'.$accion,'module'=>'academic','entity_type'=>'training','entity_id'=>$id,'action'=>$accion,'result'=>'success','description'=>$mensaje],$pdo);$pdo->commit();cmsFlash('exito',$mensaje);
}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();cmsFlash('error',$e instanceof DomainException?$e->getMessage():'No fue posible completar la acción.');}
header('Location:index.php');
