<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';
$pdo=obtenerConexion();$capId=cmsId($_GET['capacitacion_id']??0);$seccionId=cmsId($_GET['seccion_id']??0);$docenteId=cmsId($_GET['docente_id']??0);$estado=in_array($_GET['estado']??'', ['pendiente_asignacion','inscrito','retirado','finalizado'],true)?(string)$_GET['estado']:'';$fecha=trim((string)($_GET['fecha']??''));if($fecha!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$fecha))$fecha='';$buscar=trim((string)($_GET['q']??''));
$where=['1=1'];$params=[];if($capId){$where[]='i.asignatura_id=:a';$params['a']=$capId;}if($seccionId){$where[]='i.seccion_id=:s';$params['s']=$seccionId;}if($docenteId){$where[]='i.docente_id=:d';$params['d']=$docenteId;}if($estado){$where[]='i.estado=:estado';$params['estado']=$estado;}if($fecha){$where[]='DATE(i.created_at)=:fecha';$params['fecha']=$fecha;}if($buscar!==''){$where[]='(u.nombre LIKE :q1 OR u.apellido LIKE :q2 OR u.correo LIKE :q3)';$params['q1']=$params['q2']=$params['q3']='%'.$buscar.'%';}
$q=$pdo->prepare("SELECT i.*,a.nombre capacitacion,u.nombre,u.apellido,u.correo,s.codigo seccion,CONCAT_WS(' ',d.nombre,d.apellido) docente FROM inscripciones_capacitacion i JOIN asignaturas a ON a.id=i.asignatura_id JOIN usuarios u ON u.id=i.usuario_id LEFT JOIN capacitacion_secciones s ON s.id=i.seccion_id LEFT JOIN usuarios d ON d.id=i.docente_id WHERE ".implode(' AND ',$where)." ORDER BY FIELD(i.estado,'pendiente_asignacion','inscrito','finalizado','retirado'),i.asignacion_limite_at,a.nombre,u.apellido,u.nombre LIMIT 1000");$q->execute($params);$filas=$q->fetchAll();
$caps=$pdo->query("SELECT id,nombre FROM asignaturas WHERE deleted_at IS NULL ORDER BY nombre")->fetchAll();$docentes=$pdo->query("SELECT id,CONCAT_WS(' ',nombre,apellido) nombre FROM usuarios WHERE rol IN('docente','administracion_docente','administrador_docente') AND estado='activo' AND deleted_at IS NULL ORDER BY nombre,apellido")->fetchAll();$secciones=$pdo->query("SELECT id,asignatura_id,codigo,cantidad_actual,capacidad_maxima FROM capacitacion_secciones WHERE estado='abierta' AND cantidad_actual<capacidad_maxima ORDER BY codigo")->fetchAll();
cmsCabecera('Asignaciones académicas','capacitaciones/inscripciones.php','Revisa pagos confirmados, pendientes, docentes, secciones y movimientos manuales.');
?>
<section class="card card-rounded mb-4"><div class="card-body"><form class="row g-3"><div class="col-lg-3"><label class="form-label">Estudiante</label><input class="form-control" name="q" value="<?=atenea_e($buscar)?>" placeholder="Nombre o correo"></div><div class="col-lg-3"><label class="form-label">Capacitación</label><select class="form-select" name="capacitacion_id"><option value="">Todas</option><?php foreach($caps as$c):?><option value="<?=$c['id']?>" <?=$capId===$c['id']?'selected':''?>><?=atenea_e($c['nombre'])?></option><?php endforeach;?></select></div><div class="col-md-4 col-lg-2"><label class="form-label">Docente</label><select class="form-select" name="docente_id"><option value="">Todos</option><?php foreach($docentes as$d):?><option value="<?=$d['id']?>" <?=$docenteId===$d['id']?'selected':''?>><?=atenea_e($d['nombre'])?></option><?php endforeach;?></select></div><div class="col-md-4 col-lg-2"><label class="form-label">Estado</label><select class="form-select" name="estado"><option value="">Todos</option><?php foreach(['pendiente_asignacion','inscrito','finalizado','retirado']as$v):?><option value="<?=$v?>" <?=$estado===$v?'selected':''?>><?=atenea_e(ucfirst(str_replace('_',' ',$v)))?></option><?php endforeach;?></select></div><div class="col-md-4 col-lg-2"><label class="form-label">Fecha de pago</label><input class="form-control" type="date" name="fecha" value="<?=atenea_e($fecha)?>"></div><div class="col-12"><button class="btn btn-primary">Aplicar filtros</button> <a class="btn btn-light" href="inscripciones.php">Limpiar</a></div></form></div></section>
<div class="d-flex justify-content-end mb-3"><form method="post" action="auto-asignar.php" data-atenea-confirm="assign"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="capacitacion_id" value="<?=$capId?>"><button class="btn btn-success">Ejecutar asignación automática<?=$capId?' para el curso filtrado':''?></button></form></div>
<section class="card card-rounded"><div class="card-body"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Estudiante</th><th>Capacitación</th><th>Sección y docente</th><th>Estado</th><th>Asignar o mover</th></tr></thead><tbody><?php foreach($filas as$f):?><tr><td><strong><?=atenea_e(trim($f['nombre'].' '.$f['apellido']))?></strong><small class="d-block text-muted"><?=atenea_e($f['correo'])?></small><small>Pago confirmado: <?=date('d/m/Y H:i',strtotime($f['created_at']))?></small></td><td><?=atenea_e($f['capacitacion'])?></td><td><?=atenea_e($f['seccion']?:'Sin sección')?><small class="d-block text-muted"><?=atenea_e($f['docente']?:'Sin docente')?></small></td><td><span class="badge <?=$f['estado']==='pendiente_asignacion'?'bg-warning text-dark':($f['estado']==='inscrito'?'bg-success':'bg-secondary')?>"><?=atenea_e(ucfirst(str_replace('_',' ',$f['estado'])))?></span><?php if($f['estado']==='pendiente_asignacion'):?><small class="d-block mt-1 <?=$f['asignacion_limite_at']&&strtotime($f['asignacion_limite_at'])<time()?'text-danger':'text-muted'?>">Plazo: <?=atenea_e($f['asignacion_limite_at']?date('d/m/Y H:i',strtotime($f['asignacion_limite_at'])):'hasta 3 días')?></small><?php endif;?></td><td><form class="d-flex flex-column flex-xl-row gap-2" method="post" action="inscripcion-accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="inscripcion_id" value="<?=$f['id']?>"><select class="form-select form-select-sm" name="seccion_id" required><option value="">Selecciona destino</option><?php foreach($secciones as$s):if($s['asignatura_id']!=$f['asignatura_id']||$s['id']==$f['seccion_id'])continue;?><option value="<?=$s['id']?>"><?=atenea_e($s['codigo'])?> · <?=$s['cantidad_actual']?>/<?=$s['capacidad_maxima']?></option><?php endforeach;?></select><input class="form-control form-control-sm" name="motivo" maxlength="500" placeholder="Motivo obligatorio" required><button class="btn btn-sm btn-outline-primary">Guardar</button></form></td></tr><?php endforeach;?><?php if(!$filas):?><tr><td colspan="5" class="text-center text-muted py-5">No hay asignaciones para los filtros seleccionados.</td></tr><?php endif;?></tbody></table></div></div></section>
<?php cmsPie();
