<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';
require_once dirname(__DIR__,3).'/includes/capacitaciones.php';
$pdo=obtenerConexion();$capId=cmsId($_GET['capacitacion_id']??0);$docenteId=cmsId($_GET['docente_id']??0);$estado=in_array($_GET['estado']??'', ['abierta','cerrada','finalizada','inactiva'],true)?(string)$_GET['estado']:'';$fecha=trim((string)($_GET['fecha']??''));if($fecha!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$fecha))$fecha='';
$caps=$pdo->query("SELECT id,nombre FROM asignaturas WHERE deleted_at IS NULL ORDER BY nombre")->fetchAll();$docentes=$pdo->query("SELECT id,CONCAT_WS(' ',nombre,apellido) nombre FROM usuarios WHERE rol IN('docente','administracion_docente') AND estado='activo' AND deleted_at IS NULL ORDER BY nombre,apellido")->fetchAll();
$where=['1=1'];$params=[];if($capId){$where[]='s.asignatura_id=:cap';$params['cap']=$capId;}if($docenteId){$where[]='s.docente_id=:docente';$params['docente']=$docenteId;}if($estado!==''){$where[]='s.estado=:estado';$params['estado']=$estado;}if($fecha!==''){$where[]='s.fecha_inicio=:fecha';$params['fecha']=$fecha;}
$q=$pdo->prepare("SELECT s.*,a.nombre capacitacion,CONCAT_WS(' ',u.nombre,u.apellido) docente,GREATEST(s.capacidad_maxima-s.cantidad_actual,0) cupos FROM capacitacion_secciones s JOIN asignaturas a ON a.id=s.asignatura_id JOIN usuarios u ON u.id=s.docente_id WHERE ".implode(' AND ',$where).' ORDER BY COALESCE(s.fecha_inicio,\'9999-12-31\'),a.nombre,s.codigo');$q->execute($params);$secciones=$q->fetchAll();
$elegibles=[];if($capId){$q=$pdo->prepare("SELECT u.id,CONCAT_WS(' ',u.nombre,u.apellido) nombre FROM docentes_asignaturas da JOIN usuarios u ON u.id=da.docente_id WHERE da.asignatura_id=:a AND da.estado='activo' AND u.estado='activo' AND u.deleted_at IS NULL ORDER BY u.nombre,u.apellido");$q->execute(['a'=>$capId]);$elegibles=$q->fetchAll();}
cmsCabecera('Administración de secciones','capacitaciones/secciones.php','Crea, filtra y actualiza secciones reales, docentes, horarios, cupos y fechas.');
?>
<section class="card card-rounded mb-4"><div class="card-body"><form class="row g-3 align-items-end"><div class="col-lg-3"><label class="form-label" for="filtroCapacitacion">Capacitación</label><select class="form-select" id="filtroCapacitacion" name="capacitacion_id"><option value="">Todas</option><?php foreach($caps as$c):?><option value="<?=$c['id']?>" <?=$capId===$c['id']?'selected':''?>><?=atenea_e($c['nombre'])?></option><?php endforeach;?></select></div><div class="col-lg-3"><label class="form-label" for="filtroDocente">Docente</label><select class="form-select" id="filtroDocente" name="docente_id"><option value="">Todos</option><?php foreach($docentes as$d):?><option value="<?=$d['id']?>" <?=$docenteId===$d['id']?'selected':''?>><?=atenea_e($d['nombre'])?></option><?php endforeach;?></select></div><div class="col-md-3 col-lg-2"><label class="form-label" for="filtroEstado">Estado</label><select class="form-select" id="filtroEstado" name="estado"><option value="">Todos</option><?php foreach(['abierta','cerrada','finalizada','inactiva']as$v):?><option value="<?=$v?>" <?=$estado===$v?'selected':''?>><?=ucfirst($v)?></option><?php endforeach;?></select></div><div class="col-md-3 col-lg-2"><label class="form-label" for="filtroFecha">Inicio</label><input class="form-control" id="filtroFecha" type="date" name="fecha" value="<?=atenea_e($fecha)?>"></div><div class="col-md-6 col-lg-2"><button class="btn btn-primary w-100">Filtrar</button></div></form></div></section>
<?php if($capId):?><section class="card card-rounded mb-4"><div class="card-body"><div class="d-flex flex-wrap justify-content-between gap-2"><div><h2 class="h5">Crear sección</h2><p class="text-muted small">La capacidad inicial recomendada y predeterminada es de 20 estudiantes.</p></div><form method="post" action="auto-asignar.php" data-atenea-confirm="assign" data-atenea-confirm-title="Ejecutar asignación automática" data-atenea-confirm-message="Se intentará asignar cada inscripción pendiente únicamente a secciones abiertas con docente y cupo."><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="capacitacion_id" value="<?=$capId?>"><button class="btn btn-outline-success">Asignar pendientes automáticamente</button></form></div><?php if(!$elegibles):?><div class="alert alert-warning">Autoriza al menos un docente antes de crear una sección. Atenea no creará secciones sin docente.</div><?php else:?><form class="row g-3" method="post" action="seccion-accion.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="crear"><input type="hidden" name="capacitacion_id" value="<?=$capId?>"><div class="col-md-3"><label class="form-label">Código</label><input class="form-control" name="codigo" maxlength="80" required></div><div class="col-md-4"><label class="form-label">Nombre</label><input class="form-control" name="nombre" maxlength="180" required></div><div class="col-md-3"><label class="form-label">Docente</label><select class="form-select" name="docente_id" required><?php foreach($elegibles as$d):?><option value="<?=$d['id']?>"><?=atenea_e($d['nombre'])?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label">Capacidad</label><input class="form-control" type="number" name="capacidad" min="1" max="30" value="20" required></div><div class="col-md-3"><label class="form-label">Fecha de inicio</label><input class="form-control" type="date" name="fecha_inicio"></div><div class="col-md-3"><label class="form-label">Fecha final</label><input class="form-control" type="date" name="fecha_finalizacion"></div><div class="col-md-4"><label class="form-label">Horario</label><input class="form-control" name="horario" maxlength="255"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-success w-100">Crear sección</button></div></form><?php endif;?></div></section><?php else:?><div class="alert alert-info">Selecciona una capacitación para crear secciones o ejecutar la asignación automática.</div><?php endif;?>
<section class="card card-rounded"><div class="card-body"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Sección</th><th>Docente</th><th>Cupos</th><th>Fechas y horario</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><?php foreach($secciones as$s):?><tr><td><strong><?=atenea_e($s['codigo'])?></strong><small class="d-block"><?=atenea_e($s['nombre'])?></small><small class="text-muted"><?=atenea_e($s['capacitacion'])?></small></td><td><?=atenea_e($s['docente'])?></td><td><strong><?=$s['cantidad_actual']?> / <?=$s['capacidad_maxima']?></strong><small class="d-block <?=$s['cupos']?'text-success':'text-danger'?>"><?=$s['cupos']?> disponibles</small><?php if($s['cantidad_actual']>$s['capacidad_maxima']):?><span class="badge bg-warning text-dark">Capacidad debajo del grupo actual</span><?php endif;?></td><td><?=atenea_e($s['fecha_inicio']?date('d/m/Y',strtotime($s['fecha_inicio'])):'Sin fecha')?><?php if($s['fecha_finalizacion']):?> – <?=date('d/m/Y',strtotime($s['fecha_finalizacion']))?><?php endif;?><small class="d-block text-muted"><?=atenea_e($s['horario']?:'Horario por definir')?></small></td><td><span class="badge <?=$s['estado']==='abierta'?'bg-success':'bg-secondary'?>"><?=atenea_e(ucfirst($s['estado']))?></span></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-primary" href="seccion-detalle.php?id=<?=$s['id']?>">Editar y ver estudiantes</a></td></tr><?php endforeach;?><?php if(!$secciones):?><tr><td colspan="6" class="text-center text-muted py-5">No existen secciones para los filtros seleccionados.</td></tr><?php endif;?></tbody></table></div></div></section>
<?php cmsPie();
