<?php
require_once __DIR__.'/../_auth_guard.php';
require_once dirname(__DIR__, 4) . '/includes/notificaciones.php';
$usuarioNav=obtenerUsuarioActual()??[];$perfilNav=obtenerPerfilUsuario((int)$usuarioNav['id'])?:$usuarioNav;$fotoNav=rutaFotoPerfil($perfilNav);$nombreNav=trim(($usuarioNav['nombre']??'').' '.($usuarioNav['apellido']??''));$logoNav=rutaImagenContenido((obtenerConfiguracionSitio()['logo']??'img/atenea-logo.png'),'img/atenea-logo.png');$modoNav=modoHibridoActualAtenea();$notificacionesNav=usuarioTienePermiso($modoNav==='admin'?'notifications.view':'academic.notifications.view');$resumenNav=$notificacionesNav?notificacionesAdminResumen((int)$usuarioNav['id']):['no_leidas'=>0];
?>
<nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row">
 <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start"><div class="me-3"><button class="navbar-toggler align-self-center" type="button" data-bs-toggle="minimize"><span class="icon-menu"></span></button></div><a class="navbar-brand brand-logo" href="<?=atenea_url('src/administador_docente/dashboard/index.php')?>"><img src="<?=atenea_e($logoNav)?>" alt="Atenea"></a><a class="navbar-brand brand-logo-mini" href="<?=atenea_url('src/administador_docente/dashboard/index.php')?>"><img src="<?=atenea_e($logoNav)?>" alt="Atenea"></a></div>
 <div class="navbar-menu-wrapper d-flex align-items-top"><ul class="navbar-nav"><li class="nav-item fw-semibold d-none d-lg-block ms-0"><h1 class="welcome-text">Administración_Docente: <span class="text-black fw-bold" data-atenea-current-name><?=atenea_e($nombreNav)?></span></h1><h3 class="welcome-sub-text">Contexto separado y permisos individuales</h3></li></ul><ul class="navbar-nav ms-auto align-items-center"><li class="nav-item d-flex"><?php renderizarSelectorModoHibridoAtenea();?></li>
 <?php if($notificacionesNav):?><li class="nav-item"><a class="nav-link count-indicator" href="<?=atenea_url($modoNav==='admin'?'src/dashboard/notificaciones/index.php':'src/notificaciones/index.php')?>" aria-label="Notificaciones"><i class="icon-bell"></i><?php if(($resumenNav['no_leidas']??0)>0):?><span class="count"></span><?php endif;?></a></li><?php endif;?>
 <li class="nav-item dropdown user-dropdown"><button class="nav-link border-0 bg-transparent" id="HybridUserDropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false"><img class="img-xs rounded-circle" src="<?=atenea_e($fotoNav)?>" data-atenea-current-avatar alt="Fotografía de <?=atenea_e($nombreNav)?>"></button><div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="HybridUserDropdown"><div class="dropdown-header text-center"><img class="img-md rounded-circle" src="<?=atenea_e($fotoNav)?>" alt="Fotografía"><p class="mb-1 mt-3 fw-semibold"><?=atenea_e($nombreNav)?></p><p class="fw-light text-muted mb-0">Administración_Docente · <?=atenea_e($modoNav?:'sin modo')?></p></div><a class="dropdown-item" href="<?=atenea_url('index.php')?>"><i class="mdi mdi-web text-primary me-2"></i>Volver al sitio</a><a class="dropdown-item" data-atenea-confirm="logout" href="<?=atenea_url('src/login/logout.php')?>"><i class="mdi mdi-power text-primary me-2"></i>Cerrar sesión</a></div></li></ul><button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-bs-toggle="offcanvas"><span class="mdi mdi-menu"></span></button></div>
</nav>
