<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/cuenta.php';require_once dirname(__DIR__,2).'/includes/audit.php';require_once dirname(__DIR__,2).'/includes/json_response.php';exigirAutenticacion();$retorno=cuentaRetornoSeguro($_POST['retorno']??null);$json=solicitudEsJsonAtenea();
function responderActualizacionPerfil(bool $ok,string $mensaje,string $retorno,array $errores=[],?array $perfil=null,int $estado=200):never{if(solicitudEsJsonAtenea()){if(!$ok)responderJsonErrorAtenea('PROFILE_VALIDATION',$mensaje,$estado,$errores);responderJsonExitoAtenea(['mensaje'=>$mensaje,'perfil'=>$perfil]);}cuentaFlash($errores,$ok?$mensaje:'');header('Location: '.$retorno);exit;}
if(($_SERVER['REQUEST_METHOD']??'')!=='POST'||!validarTokenCsrf((string)($_POST['csrf_token']??'')))responderActualizacionPerfil(false,'La solicitud expiró. Intenta nuevamente.',$retorno,['general'=>'La sesión del formulario venció.'],null,419);
$id=(int)$_SESSION['usuario_id'];$perfil=obtenerPerfilUsuario($id);if(!$perfil){limpiarAutenticacionSesionAtenea();responderActualizacionPerfil(false,'La cuenta ya no está disponible.',$retorno,[],null,401);}
$nombre=trim(strip_tags((string)($_POST['nombre']??$perfil['nombre'])));$apellido=trim(strip_tags((string)($_POST['apellido']??$perfil['apellido'])));$fechaEntrada=trim((string)($_POST['fecha_nacimiento']??$perfil['fecha_nacimiento']??''));$fecha=$fechaEntrada===''?'':(normalizarFechaNacimiento($fechaEntrada)??$fechaEntrada);$duiEntrada=trim((string)($_POST['dui']??$perfil['dui']??''));$dui=normalizarDui($duiEntrada);$codigo=normalizarCodigoTelefono((string)($_POST['codigo_telefono']??$perfil['codigo_telefono']??''));$telefono=normalizarTelefono((string)($_POST['telefono']??$perfil['telefono']??''));$departamento=filter_var($_POST['departamento_id']??$perfil['departamento_id']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$municipio=filter_var($_POST['municipio_id']??$perfil['municipio_id']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$distrito=filter_var($_POST['distrito_id']??$perfil['distrito_id']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$direccion=trim(strip_tags((string)($_POST['direccion']??$perfil['direccion']??'')));$restaurar=($_POST['restaurar_foto']??'')==='1';$errores=[];$requiereDatos=$perfil['rol']==='usuario';
if($nombre===''||mb_strlen($nombre)>100)$errores['nombre']='Ingresa un nombre válido.';if($apellido===''||mb_strlen($apellido)>100)$errores['apellido']='Ingresa apellidos válidos.';if(($fecha!==''&&!fechaNacimientoValida($fecha))||($requiereDatos&&$fecha===''))$errores['fecha_nacimiento']='Debes tener al menos 18 años para registrarte.';if(($duiEntrada!==''&&$dui==='')||($requiereDatos&&!$dui))$errores['dui']='Usa el formato 00000000-0.';if((($telefono!==''||$codigo!=='')&&!telefonoValido($codigo,$telefono))||($requiereDatos&&$telefono===''))$errores['telefono']='Ingresa un teléfono válido.';if(mb_strlen($direccion)>500)$errores['direccion']='La dirección no puede superar 500 caracteres.';
try{$pdo=obtenerConexion();if(($departamento||$municipio||$distrito)&&!ubicacionValida($pdo,$departamento,$municipio,$distrito))$errores['ubicacion']='Selecciona una ubicación válida.';if($requiereDatos&&(!$departamento||!$municipio||!$distrito))$errores['ubicacion']='La ubicación es obligatoria para estudiantes.';if($dui){$q=$pdo->prepare('SELECT id FROM usuarios WHERE dui=:dui AND id<>:id LIMIT 1');$q->execute(['dui'=>$dui,'id'=>$id]);if($q->fetch())$errores['dui']='Ese DUI ya está registrado.';}if($errores)responderActualizacionPerfil(false,'Revisa los campos señalados.',$retorno,$errores,null,422);
 $foto=(string)($perfil['foto']??'');if($restaurar)$foto='';elseif(isset($_FILES['foto']))$foto=guardarFotoPerfil($_FILES['foto'],$perfil['foto']??null);
 $nuevos=['nombre'=>$nombre,'apellido'=>$apellido,'fecha_nacimiento'=>$fecha?:null,'dui'=>$dui?:null,'codigo_telefono'=>$codigo?:null,'telefono'=>$telefono?:null,'departamento_id'=>$departamento?:null,'municipio_id'=>$municipio?:null,'distrito_id'=>$distrito?:null,'direccion'=>$direccion?:null,'foto'=>$foto?:null];$campos=[];foreach($nuevos as$campo=>$valor)if((string)($perfil[$campo]??'')!==(string)($valor??''))$campos[]=$campo;
 if($campos){$pdo->beginTransaction();$q=$pdo->prepare('UPDATE usuarios SET nombre=:nombre,apellido=:apellido,fecha_nacimiento=:fecha_nacimiento,dui=:dui,codigo_telefono=:codigo_telefono,telefono=:telefono,departamento_id=:departamento_id,municipio_id=:municipio_id,distrito_id=:distrito_id,direccion=:direccion,foto=:foto,last_activity_at=NOW() WHERE id=:id');$q->execute($nuevos+['id'=>$id]);registrarCambioCuenta($pdo,$id,$restaurar?'restaurar_avatar':'actualizacion_perfil',$campos);registrarAuditoria(['actor_user_id'=>$id,'target_user_id'=>$id,'event_type'=>'user.profile_updated','module'=>'account','entity_type'=>'user','entity_id'=>$id,'action'=>'update','result'=>'success','description'=>'El usuario actualizó campos permitidos de su perfil.','metadata'=>['changed_fields'=>$campos,'role_unchanged'=>true]],$pdo);$pdo->commit();if($foto!==(string)($perfil['foto']??''))eliminarFotoPerfilLocal($perfil['foto']??null);}
 $actualizado=obtenerPerfilUsuario($id);if(!$actualizado)throw new RuntimeException('Perfil no disponible.');$_SESSION['usuario_nombre']=(string)$actualizado['nombre'];$_SESSION['usuario_apellido']=(string)$actualizado['apellido'];$_SESSION['usuario_foto']=$actualizado['foto']?:null;$_SESSION['usuario_perfil_completo']=datosPerfilCompletos($actualizado);if($campos)notificarCambioCuenta($actualizado,$campos);$respuesta=['nombre'=>$actualizado['nombre'],'apellido'=>$actualizado['apellido'],'nombre_completo'=>trim($actualizado['nombre'].' '.$actualizado['apellido']),'telefono'=>$actualizado['telefono'],'direccion'=>$actualizado['direccion'],'avatar'=>rutaFotoPerfil($actualizado),'avatar_predeterminado'=>urlAvatarAtenea(null),'rol'=>etiquetaRol((string)$actualizado['rol'])];responderActualizacionPerfil(true,$campos?'Tu perfil se actualizó correctamente.':'No había cambios por guardar.',$retorno,[],$respuesta);
}catch(Throwable$e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();if(isset($foto)&&$foto!==(string)($perfil['foto']??'')&&$foto!=='')eliminarFotoPerfilLocal($foto);if(!$e instanceof RuntimeException)error_log('Actualizar cuenta Atenea: '.$e->getMessage());$mensaje=$e instanceof RuntimeException?$e->getMessage():'No fue posible actualizar el perfil.';responderActualizacionPerfil(false,$mensaje,$retorno,['general'=>$mensaje],null,$e instanceof RuntimeException?422:500);}
