<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/cuenta.php';require_once dirname(__DIR__,2).'/includes/audit.php';exigirAutenticacion();$retorno=cuentaRetornoSeguro($_POST['retorno']??null);
if(($_SERVER['REQUEST_METHOD']??'')!=='POST'||!validarTokenCsrf(isset($_POST['csrf_token'])?(string)$_POST['csrf_token']:null)){cuentaFlash(['codigo'=>'La solicitud expiró.']);header('Location: '.$retorno);exit;}
$id=filter_var($_POST['verificacion_id']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$codigo=strtoupper(trim((string)($_POST['codigo']??'')));$usuarioId=(int)$_SESSION['usuario_id'];
try{$pdo=obtenerConexion();$pdo->beginTransaction();$q=$pdo->prepare('SELECT * FROM verificaciones_cuenta WHERE id=:id AND usuario_id=:usuario AND usado_at IS NULL LIMIT 1 FOR UPDATE');$q->execute(['id'=>$id,'usuario'=>$usuarioId]);$v=$q->fetch();
if(!$v||strtotime((string)$v['expira_at'])<time()||(int)$v['intentos']>=(int)$v['max_intentos'])throw new RuntimeException('vencido');
if(!hash_equals((string)$v['codigo_hash'],hash('sha256',$codigo))){$intentos=(int)$v['intentos']+1;$pdo->prepare('UPDATE verificaciones_cuenta SET intentos=:intentos,usado_at=IF(:intentos2>=max_intentos,NOW(),usado_at) WHERE id=:id')->execute(['intentos'=>$intentos,'intentos2'=>$intentos,'id'=>$id]);$pdo->commit();cuentaFlash(['codigo'=>'Código incorrecto. Intento '.$intentos.' de '.(int)$v['max_intentos'].'.'], '', ['id'=>$id,'tipo'=>$v['tipo']]);header('Location: '.$retorno);exit;}
$datos=json_decode((string)$v['datos_pendientes'],true,16,JSON_THROW_ON_ERROR);$perfil=obtenerPerfilUsuario($usuarioId);if(!$perfil)throw new RuntimeException('usuario');$campos=[];
if($v['tipo']==='cambio_password'){$pdo->prepare("UPDATE usuarios SET password=:password,proveedor=IF(google_id IS NULL,'local','mixto'),session_version=session_version+1,last_activity_at=NOW() WHERE id=:id")->execute(['password'=>$datos['password_hash'],'id'=>$usuarioId]);$campos=['contraseña'];$pdo->prepare('UPDATE password_reset_tokens SET used_at=NOW() WHERE user_id=:id AND used_at IS NULL')->execute(['id'=>$usuarioId]);}
elseif($v['tipo']==='cambio_correo'){$q=$pdo->prepare('SELECT id FROM usuarios WHERE correo=:correo AND id<>:id');$q->execute(['correo'=>$datos['correo_nuevo'],'id'=>$usuarioId]);if($q->fetch())throw new RuntimeException('duplicado');$pdo->prepare('UPDATE usuarios SET correo=:correo,email_verificado=1,session_version=session_version+1 WHERE id=:id')->execute(['correo'=>$datos['correo_nuevo'],'id'=>$usuarioId]);$campos=['correo electrónico'];}
elseif($v['tipo']==='vincular_google'){$q=$pdo->prepare('SELECT id FROM usuarios WHERE google_id=:google AND id<>:id');$q->execute(['google'=>$datos['google_id'],'id'=>$usuarioId]);if($q->fetch())throw new RuntimeException('google duplicado');$pdo->prepare("UPDATE usuarios SET google_id=:google,proveedor=IF(password IS NULL,'google','mixto'),email_verificado=1 WHERE id=:id")->execute(['google'=>$datos['google_id'],'id'=>$usuarioId]);$campos=['vinculación con Google'];}
elseif($v['tipo']==='desvincular_google'){if(empty($perfil['password']))throw new RuntimeException('sin acceso local');$pdo->prepare("UPDATE usuarios SET google_id=NULL,proveedor='local' WHERE id=:id")->execute(['id'=>$usuarioId]);$campos=['desvinculación de Google'];}
else throw new RuntimeException('tipo');
$pdo->prepare('UPDATE verificaciones_cuenta SET usado_at=NOW() WHERE id=:id')->execute(['id'=>$id]);$pdo->prepare('UPDATE verificaciones_cuenta SET usado_at=NOW() WHERE usuario_id=:usuario AND tipo=:tipo AND usado_at IS NULL')->execute(['usuario'=>$usuarioId,'tipo'=>$v['tipo']]);registrarCambioCuenta($pdo,$usuarioId,(string)$v['tipo'],$campos);if(!registrarAuditoria(['actor_user_id'=>$usuarioId,'target_user_id'=>$usuarioId,'event_type'=>'account.'.(string)$v['tipo'],'module'=>'account','entity_type'=>'user','entity_id'=>$usuarioId,'action'=>'confirm_change','result'=>'success','description'=>'El usuario confirmo un cambio sensible mediante codigo de un solo uso.','metadata'=>['changed_fields'=>$campos]],$pdo))throw new RuntimeException('auditoria');$pdo->commit();$actualizado=obtenerPerfilUsuario($usuarioId);if(!$actualizado)throw new RuntimeException('actualizado');iniciarSesionUsuario($actualizado);notificarCambioCuenta($actualizado,$campos);if($v['tipo']==='cambio_correo')notificarCambioCuenta($actualizado,$campos,(string)$datos['correo_anterior']);cuentaFlash([],'El cambio se confirmó correctamente.');
}catch(Throwable$e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();error_log('Confirmar cambio cuenta: '.$e->getMessage());cuentaFlash(['codigo'=>'El código venció, fue utilizado o el cambio ya no es válido.']);}
header('Location: '.$retorno);exit;
