<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/auth.php';require_once dirname(__DIR__,2).'/includes/contenido_clase.php';require_once dirname(__DIR__,2).'/includes/audit.php';
exigirAutenticacion();if(($_SERVER['REQUEST_METHOD']??'')!=='POST'||!validarTokenCsrf((string)($_POST['csrf_token']??''))){http_response_code(400);exit;}
$pdo=obtenerConexion();$actor=(int)$_SESSION['usuario_id'];$rol=(string)$_SESSION['usuario_rol'];$accion=(string)($_POST['accion']??'');$contenidoId=filter_var($_POST['contenido_id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$comentarioId=filter_var($_POST['comentario_id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$parentId=filter_var($_POST['parent_id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$retorno=(string)($_POST['retorno']??'');
$retornoValido=urlRetornoInternaSegura($retorno);
try{$pdo->beginTransaction();
 if(in_array($accion,['crear','responder'],true)){$q=$pdo->prepare('SELECT * FROM contenidos WHERE id=:id AND eliminado_at IS NULL FOR UPDATE');$q->execute(['id'=>$contenidoId]);$contenido=$q->fetch();if(!$contenido)throw new DomainException('La publicación no existe.');$administra=contenidoClasePuedeAdministrar($pdo,$contenido,$actor,$rol);if($rol==='usuario'){if($accion!=='crear'||!contenidoClasePuedeVerEstudiante($pdo,$contenidoId,$actor))throw new DomainException('No puedes comentar en esta publicación.');$parentId=0;}elseif(!$administra||$accion!=='responder'||!$parentId)throw new DomainException('Solo el docente de la clase puede responder.');
  $cuerpo=textoPlanoContenido($_POST['cuerpo']??'',CONTENIDO_COMENTARIO_MAX,true);if(mb_strlen($cuerpo)<CONTENIDO_COMENTARIO_MIN)throw new DomainException('El comentario debe tener al menos dos caracteres.');$ultimo=(int)($_SESSION['contenido_comentario_ultimo']??0);if($ultimo>time()-CONTENIDO_COMENTARIO_ESPERA)throw new DomainException('Espera unos segundos antes de volver a publicar.');
  if($parentId){$q=$pdo->prepare('SELECT * FROM contenido_comentarios WHERE id=:id AND contenido_id=:c AND parent_id IS NULL AND estado=\'visible\' FOR UPDATE');$q->execute(['id'=>$parentId,'c'=>$contenidoId]);$padre=$q->fetch();if(!$padre)throw new DomainException('La duda que intentas responder no está disponible.');}
  $q=$pdo->prepare("SELECT id FROM contenido_comentarios WHERE contenido_id=:c AND usuario_id=:u AND cuerpo=:cuerpo AND created_at>=DATE_SUB(NOW(),INTERVAL 60 SECOND) LIMIT 1");$q->execute(['c'=>$contenidoId,'u'=>$actor,'cuerpo'=>$cuerpo]);if($q->fetch())throw new DomainException('Ese comentario ya fue enviado recientemente.');
  $q=$pdo->prepare('INSERT INTO contenido_comentarios(contenido_id,usuario_id,parent_id,cuerpo) VALUES(:c,:u,:p,:cuerpo)');$q->execute(['c'=>$contenidoId,'u'=>$actor,'p'=>$parentId?:null,'cuerpo'=>$cuerpo]);$nuevoId=(int)$pdo->lastInsertId();
  if($rol==='usuario')crearNotificacionAtenea(['usuario_id'=>(int)$contenido['docente_id'],'created_by'=>$actor,'tipo'=>'contenido_comentario','categoria'=>'academico','nivel'=>'informacion','titulo'=>'Nueva duda en una publicación','descripcion'=>$contenido['titulo'],'url'=>atenea_url('src/docente/contenido-vista.php?id='.$contenidoId),'idempotency_key'=>'contenido-comentario:'.$nuevoId],$pdo);
  else crearNotificacionAtenea(['usuario_id'=>(int)$padre['usuario_id'],'created_by'=>$actor,'tipo'=>'contenido_respuesta','categoria'=>'academico','nivel'=>'informacion','titulo'=>'Tu docente respondió una duda','descripcion'=>$contenido['titulo'],'url'=>atenea_url('src/estudiantes/contenido.php?id='.$contenidoId.'#conversacion'),'idempotency_key'=>'contenido-respuesta:'.$nuevoId],$pdo);
  registrarAuditoria(['actor_user_id'=>$actor,'event_type'=>'academic.content_comment.created','module'=>'academic','entity_type'=>'content_comment','entity_id'=>$nuevoId,'action'=>$accion,'result'=>'success','description'=>'Mensaje agregado a la conversación de una publicación.'],$pdo);$_SESSION['contenido_comentario_ultimo']=time();$mensaje=$rol==='usuario'?'Comentario publicado.':'Respuesta enviada.';
 }else{$q=$pdo->prepare('SELECT cc.*,c.docente_id,c.seccion_id,c.asignatura_id,c.titulo FROM contenido_comentarios cc JOIN contenidos c ON c.id=cc.contenido_id WHERE cc.id=:id FOR UPDATE');$q->execute(['id'=>$comentarioId]);$comentario=$q->fetch();if(!$comentario)throw new DomainException('El comentario no existe.');$contenidoId=(int)$comentario['contenido_id'];$propio=(int)$comentario['usuario_id']===$actor;$administra=contenidoClasePuedeAdministrar($pdo,$comentario,$actor,$rol);
  if($accion==='editar'){if(!$propio||$comentario['estado']!=='visible')throw new DomainException('Solo puedes editar tus comentarios visibles.');$cuerpo=textoPlanoContenido($_POST['cuerpo']??'',CONTENIDO_COMENTARIO_MAX,true);if(mb_strlen($cuerpo)<2)throw new DomainException('El comentario es demasiado corto.');$pdo->prepare('UPDATE contenido_comentarios SET cuerpo=:c,editado_at=NOW() WHERE id=:id')->execute(['c'=>$cuerpo,'id'=>$comentarioId]);$mensaje='Comentario actualizado.';}
  elseif($accion==='eliminar'){if(!$propio&&$rol!=='admin')throw new DomainException('No puedes eliminar este comentario.');$pdo->prepare("UPDATE contenido_comentarios SET cuerpo='Comentario eliminado',estado='eliminado',editado_at=NOW() WHERE id=:id")->execute(['id'=>$comentarioId]);$mensaje='Comentario eliminado.';}
  elseif($accion==='ocultar'){if(!$administra)throw new DomainException('Solo el docente de la clase puede moderar comentarios.');$pdo->prepare("UPDATE contenido_comentarios SET estado='oculto',moderado_por=:u,moderado_at=NOW() WHERE id=:id")->execute(['u'=>$actor,'id'=>$comentarioId]);$mensaje='Comentario ocultado.';}
  else throw new DomainException('Acción no válida.');
 }
 $pdo->commit();$_SESSION[$rol==='usuario'?'portal_flash':'docente_flash']=['tipo'=>'success','mensaje'=>$mensaje];
}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();error_log('Conversación contenido: '.$e->getMessage());$_SESSION[$rol==='usuario'?'portal_flash':'docente_flash']=['tipo'=>'danger','mensaje'=>$e instanceof DomainException?$e->getMessage():'No fue posible procesar el comentario.'];}
$rutaPredeterminada=$rol==='usuario'?atenea_url('src/estudiantes/contenido.php?id='.$contenidoId):atenea_url('src/docente/contenido-vista.php?id='.$contenidoId);
header('Location:'.($retornoValido?$retorno:$rutaPredeterminada).'#conversacion');
exit;
