<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';
require_once dirname(__DIR__,3).'/includes/capacitaciones.php';
if(($_SERVER['REQUEST_METHOD']??'')!=='POST'||!validarTokenCsrf((string)($_POST['csrf_token']??''))){mostrarPaginaErrorAtenea(419);}
$accion=(string)($_POST['accion']??'');$capId=cmsId($_POST['capacitacion_id']??0);$seccionId=cmsId($_POST['seccion_id']??0);$pdo=obtenerConexion();
try{
 $pdo->beginTransaction();$q=$pdo->prepare('SELECT id FROM asignaturas WHERE id=:id AND deleted_at IS NULL FOR UPDATE');$q->execute(['id'=>$capId]);if(!$q->fetchColumn())throw new DomainException('La capacitación no existe.');
 if($accion==='crear'){
  $docente=cmsId($_POST['docente_id']??0);$codigo=strtoupper(trim((string)($_POST['codigo']??'')));$nombre=trim((string)($_POST['nombre']??''));$capacidad=(int)($_POST['capacidad']??20);$inicio=trim((string)($_POST['fecha_inicio']??''))?:null;$fin=trim((string)($_POST['fecha_finalizacion']??''))?:null;$horario=trim((string)($_POST['horario']??''))?:null;
  if($codigo===''||mb_strlen($codigo)>80||$nombre===''||mb_strlen($nombre)>180||$capacidad<1||$capacidad>30||($inicio&&$fin&&$fin<$inicio))throw new DomainException('Revisa código, nombre, fechas y capacidad.');
  validarDocenteSeccion($pdo,$docente,$capId);$q=$pdo->prepare("INSERT INTO capacitacion_secciones(asignatura_id,docente_id,codigo,nombre,fecha_inicio,fecha_finalizacion,capacidad_maxima,horario,estado,creada_por) VALUES(:a,:d,:codigo,:nombre,:inicio,:fin,:capacidad,:horario,'abierta',:admin)");$q->execute(['a'=>$capId,'d'=>$docente,'codigo'=>$codigo,'nombre'=>$nombre,'inicio'=>$inicio,'fin'=>$fin,'capacidad'=>$capacidad,'horario'=>$horario,'admin'=>$_SESSION['usuario_id']]);$seccionId=(int)$pdo->lastInsertId();$nueva=['docente_id'=>$docente,'codigo'=>$codigo,'nombre'=>$nombre,'fecha_inicio'=>$inicio,'fecha_finalizacion'=>$fin,'capacidad_maxima'=>$capacidad,'horario'=>$horario,'estado'=>'abierta'];registrarHistorialSeccionCapacitacion($pdo,$seccionId,'creada',null,$nueva,(int)$_SESSION['usuario_id'],'Creación administrativa');$mensaje='Sección creada con capacidad inicial de '.$capacidad.'.';
 }else{
  $q=$pdo->prepare('SELECT * FROM capacitacion_secciones WHERE id=:id AND asignatura_id=:a FOR UPDATE');$q->execute(['id'=>$seccionId,'a'=>$capId]);$anterior=$q->fetch();if(!$anterior)throw new DomainException('La sección no existe.');
  if(in_array($accion,['cerrar','abrir'],true)){$nuevoEstado=$accion==='cerrar'?'cerrada':'abierta';$pdo->prepare('UPDATE capacitacion_secciones SET estado=:estado WHERE id=:id')->execute(['estado'=>$nuevoEstado,'id'=>$seccionId]);registrarHistorialSeccionCapacitacion($pdo,$seccionId,$accion==='cerrar'?'cerrada':'abierta',$anterior,array_merge($anterior,['estado'=>$nuevoEstado]),(int)$_SESSION['usuario_id'],'Cambio de estado');$mensaje='Estado de la sección actualizado.';}
  elseif($accion==='docente'){$docente=cmsId($_POST['docente_id']??0);validarDocenteSeccion($pdo,$docente,$capId);actualizarDocenteSeccion($pdo,$anterior,$docente,(int)$_SESSION['usuario_id']);$mensaje='Docente actualizado y estudiantes conservados.';}
  elseif($accion==='editar'){
   $docente=cmsId($_POST['docente_id']??0);$nombre=trim((string)($_POST['nombre']??''));$capacidad=(int)($_POST['capacidad']??0);$inicio=trim((string)($_POST['fecha_inicio']??''))?:null;$fin=trim((string)($_POST['fecha_finalizacion']??''))?:null;$horario=trim((string)($_POST['horario']??''))?:null;$estadoNuevo=in_array($_POST['estado']??'', ['abierta','cerrada','finalizada','inactiva'],true)?(string)$_POST['estado']:'cerrada';$motivo=trim((string)($_POST['motivo']??''));
   if($nombre===''||mb_strlen($nombre)>180||$capacidad<1||$capacidad>30||($inicio&&$fin&&$fin<$inicio)||$motivo===''||mb_strlen($motivo)>500)throw new DomainException('Completa correctamente nombre, capacidad, fechas y motivo.');validarDocenteSeccion($pdo,$docente,$capId);
   $pdo->prepare('UPDATE capacitacion_secciones SET nombre=:nombre,fecha_inicio=:inicio,fecha_finalizacion=:fin,capacidad_maxima=:capacidad,horario=:horario,estado=:estado WHERE id=:id')->execute(['nombre'=>$nombre,'inicio'=>$inicio,'fin'=>$fin,'capacidad'=>$capacidad,'horario'=>$horario,'estado'=>$estadoNuevo,'id'=>$seccionId]);if((int)$anterior['docente_id']!==$docente)actualizarDocenteSeccion($pdo,$anterior,$docente,(int)$_SESSION['usuario_id']);
   $nueva=array_merge($anterior,['docente_id'=>$docente,'nombre'=>$nombre,'fecha_inicio'=>$inicio,'fecha_finalizacion'=>$fin,'capacidad_maxima'=>$capacidad,'horario'=>$horario,'estado'=>$estadoNuevo]);registrarHistorialSeccionCapacitacion($pdo,$seccionId,'editada',$anterior,$nueva,(int)$_SESSION['usuario_id'],$motivo);$mensaje=$capacidad<(int)$anterior['cantidad_actual']?'Cambios guardados. La capacidad quedó debajo del número actual; ningún estudiante fue expulsado.':'Cambios de la sección guardados.';
  }else throw new DomainException('La acción solicitada no es válida.');
 }
 registrarAuditoria(['actor_user_id'=>$_SESSION['usuario_id'],'event_type'=>'section.'.$accion,'module'=>'academic','entity_type'=>'training_section','entity_id'=>$seccionId,'action'=>$accion,'result'=>'success','description'=>$mensaje],$pdo);$pdo->commit();cmsFlash('exito',$mensaje);
}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();cmsFlash('error',$e instanceof DomainException?$e->getMessage():'No fue posible actualizar la sección.');}
$destino=$accion==='editar'&&$seccionId?'seccion-detalle.php?id='.$seccionId:'secciones.php?capacitacion_id='.$capId;header('Location:'.$destino);exit;

function validarDocenteSeccion(PDO $pdo,int $docente,int $capacitacion): void
{
 $q=$pdo->prepare("SELECT 1 FROM docentes_asignaturas da JOIN usuarios u ON u.id=da.docente_id WHERE da.docente_id=:d AND da.asignatura_id=:a AND da.estado='activo' AND u.rol='docente' AND u.estado='activo' AND u.deleted_at IS NULL");$q->execute(['d'=>$docente,'a'=>$capacitacion]);if(!$q->fetchColumn())throw new DomainException('El docente no está autorizado para esta capacitación.');
}
function actualizarDocenteSeccion(PDO $pdo,array $seccion,int $docente,int $admin): void
{
 if((int)$seccion['docente_id']===$docente)return;$seccionId=(int)$seccion['id'];$capId=(int)$seccion['asignatura_id'];$pdo->prepare("INSERT INTO inscripcion_movimientos(inscripcion_id,seccion_origen_id,seccion_destino_id,docente_origen_id,docente_destino_id,motivo,realizado_por) SELECT id,seccion_id,seccion_id,docente_id,:nuevo,'Cambio administrativo de docente de la sección',:admin FROM inscripciones_capacitacion WHERE seccion_id=:seccion AND estado IN('inscrito','finalizado')")->execute(['nuevo'=>$docente,'admin'=>$admin,'seccion'=>$seccionId]);$pdo->prepare('UPDATE capacitacion_secciones SET docente_id=:d WHERE id=:id')->execute(['d'=>$docente,'id'=>$seccionId]);$pdo->prepare('UPDATE inscripciones_capacitacion SET docente_id=:d,asignado_por=:admin,metodo_asignacion=\'manual\',assigned_at=NOW() WHERE seccion_id=:s')->execute(['d'=>$docente,'admin'=>$admin,'s'=>$seccionId]);$pdo->prepare("UPDATE estudiantes_docentes SET estado='retirado' WHERE asignatura_id=:a AND docente_id=:d AND estudiante_id IN(SELECT usuario_id FROM inscripciones_capacitacion WHERE seccion_id=:s)")->execute(['a'=>$capId,'d'=>$seccion['docente_id'],'s'=>$seccionId]);$pdo->prepare("INSERT INTO estudiantes_docentes(estudiante_id,docente_id,asignatura_id,estado,matriculado_por) SELECT usuario_id,:d,asignatura_id,'activo',:admin FROM inscripciones_capacitacion WHERE seccion_id=:s ON DUPLICATE KEY UPDATE estado='activo',matriculado_por=VALUES(matriculado_por)")->execute(['d'=>$docente,'admin'=>$admin,'s'=>$seccionId]);registrarHistorialSeccionCapacitacion($pdo,$seccionId,'docente_cambiado',['docente_id'=>$seccion['docente_id']],['docente_id'=>$docente],$admin,'Cambio administrativo de docente');
}
