<?php
declare(strict_types=1);
require_once __DIR__.'/cuenta.php';require_once __DIR__.'/audit.php';require_once __DIR__.'/auth_remember.php';

function validarEliminacionPropiaAtenea(PDO $pdo,array $usuario): void
{
    if(($usuario['estado']??'')!=='activo'||!empty($usuario['deleted_at']))throw new DomainException('La cuenta ya no está disponible.');
    if(($usuario['rol']??'')==='admin'){$q=$pdo->query("SELECT COUNT(*) FROM usuarios WHERE rol='admin' AND estado='activo' AND deleted_at IS NULL");if((int)$q->fetchColumn()<=1)throw new DomainException('El último administrador activo no puede eliminar su cuenta.');if(!empty($usuario['es_superadmin'])){$q=$pdo->query("SELECT COUNT(*) FROM usuarios WHERE rol='admin' AND es_superadmin=1 AND estado='activo' AND deleted_at IS NULL");if((int)$q->fetchColumn()<=1)throw new DomainException('El último Superadministrador activo no puede eliminar su cuenta.');}}
}

function programarEliminacionCuentaAtenea(PDO $pdo,int $usuarioId): array
{
    $pdo->beginTransaction();try{$q=$pdo->prepare('SELECT * FROM usuarios WHERE id=:id FOR UPDATE');$q->execute(['id'=>$usuarioId]);$usuario=$q->fetch();if(!$usuario)throw new DomainException('La cuenta no existe.');validarEliminacionPropiaAtenea($pdo,$usuario);$efectiva=(new DateTimeImmutable('now',new DateTimeZone('America/El_Salvador')))->modify('+60 days')->format('Y-m-d H:i:s');$motivo='Eliminación solicitada por el titular de la cuenta.';$pdo->prepare("UPDATE usuarios SET estado='inactivo',deleted_at=NOW(),deleted_by=NULL,deletion_reason=:motivo,deletion_scheduled_at=:efectiva,session_version=session_version+1 WHERE id=:id")->execute(['motivo'=>$motivo,'efectiva'=>$efectiva,'id'=>$usuarioId]);$q=$pdo->prepare("INSERT INTO user_deletions(user_id,requested_by,reason,email_hash,request_ip_hash,status,effective_at) VALUES(:u,:u2,:motivo,:email,:ip,'periodo_gracia',:efectiva)");$q->execute(['u'=>$usuarioId,'u2'=>$usuarioId,'motivo'=>$motivo,'email'=>hash('sha256',strtolower((string)$usuario['correo'])),'ip'=>cuentaIpHash(),'efectiva'=>$efectiva]);$deletionId=(int)$pdo->lastInsertId();revocarTokensRecuerdoUsuarioAtenea($pdo,$usuarioId);if(!registrarAuditoria(['actor_user_id'=>$usuarioId,'target_user_id'=>$usuarioId,'event_type'=>'user.self_deletion_scheduled','module'=>'account','entity_type'=>'user_deletion','entity_id'=>$deletionId,'action'=>'schedule_deletion','result'=>'success','description'=>'El titular programó la eliminación y anonimización de su cuenta en 60 días.','metadata'=>['effective_at'=>$efectiva,'legal_relations_preserved'=>true]],$pdo))throw new RuntimeException('No fue posible registrar la solicitud.');$pdo->commit();return ['id'=>$deletionId,'efectiva_at'=>$efectiva,'usuario'=>$usuario];}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
}

function anonimizarCuentaVencidaAtenea(PDO $pdo,int $eliminacionId): bool
{
    $foto=null;$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT d.*,u.* FROM user_deletions d JOIN usuarios u ON u.id=d.user_id WHERE d.id=:id AND d.status='periodo_gracia' AND d.effective_at<=NOW() FOR UPDATE");$q->execute(['id'=>$eliminacionId]);$fila=$q->fetch();if(!$fila){$pdo->rollBack();return false;}if(!empty($fila['retention_hold'])||!empty($fila['under_investigation'])){$pdo->rollBack();return false;}$usuarioId=(int)$fila['user_id'];$foto=$fila['foto']??null;$anonCorreo='anonimizado+'.$usuarioId.'.'.substr(hash('sha256',(string)$fila['correo'].$eliminacionId),0,16).'@invalid.local';$anonUsuario='anonimizado-'.$usuarioId.'-'.substr(hash('sha256',(string)$eliminacionId),0,8);$pdo->prepare("UPDATE direcciones_usuario SET receptor='Datos anonimizados',telefono='00000000',etiqueta_personalizada=NULL,direccion_detallada='Datos anonimizados',referencias=NULL,predeterminada=0,activa=0 WHERE usuario_id=:id")->execute(['id'=>$usuarioId]);$pdo->prepare("UPDATE correo_envios SET destinatario_email=:correo,destinatario_nombre='Datos anonimizados' WHERE usuario_id=:id")->execute(['correo'=>$anonCorreo,'id'=>$usuarioId]);$pdo->prepare("UPDATE usuarios SET nombre='Usuario',apellido='anonimizado',nombre_usuario=:usuario,correo=:correo,password=NULL,google_id=NULL,proveedor='local',email_verificado=0,foto=NULL,fecha_nacimiento=NULL,dui=NULL,codigo_telefono=NULL,telefono=NULL,departamento_id=NULL,municipio_id=NULL,distrito_id=NULL,direccion=NULL,anonymized_at=NOW(),session_version=session_version+1 WHERE id=:id")->execute(['usuario'=>$anonUsuario,'correo'=>$anonCorreo,'id'=>$usuarioId]);$pdo->prepare("UPDATE user_deletions SET status='anonimizada',anonymized_at=NOW() WHERE id=:id")->execute(['id'=>$eliminacionId]);registrarAuditoria(['target_user_id'=>$usuarioId,'event_type'=>'user.anonymized_after_retention','module'=>'account_lifecycle','entity_type'=>'user_deletion','entity_id'=>$eliminacionId,'action'=>'anonymize','result'=>'success','description'=>'Los datos personales de una cuenta eliminada fueron anonimizados tras 60 días; se conservaron relaciones legales e históricas.'],$pdo);$pdo->commit();if($foto)eliminarFotoPerfilLocal((string)$foto);return true;}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
}

