<?php
declare(strict_types=1);
require_once __DIR__.'/conexion.php';require_once __DIR__.'/config.php';require_once __DIR__.'/contenido.php';
function precioProducto(array $p,?array $promo=null):array{$normal=round((float)$p['precio'],2);$final=$normal;$valida=false;if($promo&&$promo['activa']&&(string)$promo['fecha_inicio']<=date('Y-m-d H:i:s')&&(string)$promo['fecha_fin']>=date('Y-m-d H:i:s')&&(float)$promo['precio_promocional']<$normal){$final=round((float)$promo['precio_promocional'],2);$valida=true;}return ['normal'=>$normal,'final'=>$final,'descuento'=>round($normal-$final,2),'promocion_valida'=>$valida,'promocion'=>$valida?$promo:null];}
function promocionVigente(PDO $pdo,int $productoId):?array{$q=$pdo->prepare('SELECT * FROM promociones WHERE producto_id=:id AND activa=1 AND fecha_inicio<=NOW() AND fecha_fin>=NOW() ORDER BY precio_promocional,id LIMIT 1');$q->execute(['id'=>$productoId]);$r=$q->fetch();return is_array($r)?$r:null;}
function catalogoProductos():array{$pdo=obtenerConexion();$estado=estadoFuenteWebsite($pdo);$categorias=[];foreach($estado['categorias_producto']??[] as$c)if((int)($c['activo']??0)===1&&empty($c['eliminado_at']))$categorias[(int)$c['id']]=$c['nombre'];$filas=[];foreach($estado['productos']??[] as$p){if((int)($p['activo']??0)!==1||!empty($p['eliminado_at']))continue;$p['categoria']=$categorias[(int)($p['categoria_id']??0)]??null;$p['precio_calculado']=precioProducto($p,promocionVigente($pdo,(int)$p['id']));$filas[]=$p;}usort($filas,static fn($a,$b)=>strcmp((string)($b['created_at']??''),(string)($a['created_at']??'')));return$filas;}
function productoPublico(int $id):?array{foreach(catalogoProductos() as$p)if((int)$p['id']===$id)return$p;return null;}
function galeriaProductoPublica(int $productoId):array{$filas=[];foreach(filasEstadoWebsite('producto_imagenes') as$f)if((int)($f['producto_id']??0)===$productoId)$filas[]=$f;usort($filas,static fn($a,$b)=>[(int)($a['orden']??0),(int)($a['id']??0)]<=>[(int)($b['orden']??0),(int)($b['id']??0)]);return array_values(array_filter(array_column($filas,'ruta')));}
function numeroPedido():string{return 'AT-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(4)));}
function registrarHistorialPedido(PDO $pdo,int $pedidoId,?string $anterior,string $nuevo,string $origen,?int $usuario=null,?string $nota=null):void{$q=$pdo->prepare('INSERT INTO pedido_historial(pedido_id,estado_anterior,estado_nuevo,origen,usuario_id,nota)VALUES(:p,:a,:n,:o,:u,:nota)');$q->execute(['p'=>$pedidoId,'a'=>$anterior,'n'=>$nuevo,'o'=>$origen,'u'=>$usuario,'nota'=>$nota]);}
function imagenProducto(?string $ruta):string{return rutaImagenContenido($ruta,'src/website/assets/img/course-1.jpg');}
