<?php
declare(strict_types=1);

require_once __DIR__.'/comprobantes.php';
require_once __DIR__.'/mailer.php';

function pagoCapacitacionCompletoAtenea(PDO $pdo,int $pagoId): ?array
{
    $q=$pdo->prepare("SELECT cp.*,a.codigo codigo_curso,a.nombre curso,a.descripcion_corta,u.nombre,u.apellido,u.correo,u.telefono,u.dui,i.id inscripcion_id,i.estado estado_inscripcion,s.codigo seccion FROM capacitacion_pagos cp JOIN asignaturas a ON a.id=cp.asignatura_id JOIN usuarios u ON u.id=cp.usuario_id LEFT JOIN inscripciones_capacitacion i ON i.pago_id=cp.id LEFT JOIN capacitacion_secciones s ON s.id=i.seccion_id WHERE cp.id=:id LIMIT 1");
    $q->execute(['id'=>$pagoId]);$p=$q->fetch();return $p?:null;
}

function generarComprobantesCapacitacionAtenea(int $pagoId): array
{
    $pdo=obtenerConexion();$lock='atenea:comprobante:capacitacion:'.$pagoId;
    $q=$pdo->prepare('SELECT GET_LOCK(:l,10)');$q->execute(['l'=>$lock]);if((int)$q->fetchColumn()!==1)throw new RuntimeException('No fue posible bloquear el comprobante académico.');
    try{
        $q=$pdo->prepare('SELECT * FROM capacitacion_comprobante_documentos WHERE pago_id=:id');$q->execute(['id'=>$pagoId]);if($d=$q->fetch())return$d;
        $p=pagoCapacitacionCompletoAtenea($pdo,$pagoId);if(!$p||$p['estado']!=='pagado'||!$p['paid_at'])throw new RuntimeException('El comprobante requiere un pago confirmado.');
        $numero='AT-C-'.date('Ymd',strtotime((string)$p['paid_at'])).'-'.str_pad((string)$pagoId,6,'0',STR_PAD_LEFT);$codigo=uuidComprobanteAtenea();$emisor=emisorComprobanteAtenea($pdo);$fecha=new DateTimeImmutable((string)$p['paid_at']);
        $jsonData=['documento'=>['tipo'=>'comprobante_interno_capacitacion','version'=>1,'numero'=>$numero,'codigo_generacion'=>$codigo,'fecha_emision'=>$fecha->format('Y-m-d'),'hora_emision'=>$fecha->format('H:i:s'),'moneda'=>strtoupper((string)$p['moneda']),'valido_fiscalmente'=>false],'emisor'=>$emisor,'receptor'=>['id_usuario'=>(int)$p['usuario_id'],'nombre'=>trim($p['nombre'].' '.$p['apellido']),'correo'=>$p['correo'],'telefono'=>$p['telefono']?:null,'dui'=>$p['dui']?:null],'pago'=>['estado'=>'pagado','metodo'=>'stripe','fecha_confirmacion'=>$p['paid_at'],'checkout_session_id'=>$p['stripe_checkout_session_id'],'payment_intent_id'=>pagoStripeOcultoAtenea($p['stripe_payment_intent_id'])],'capacitacion'=>['pago_id'=>$pagoId,'inscripcion_id'=>$p['inscripcion_id']?(int)$p['inscripcion_id']:null,'codigo'=>$p['codigo_curso']?:null,'nombre'=>$p['curso'],'estado_inscripcion'=>$p['estado_inscripcion']==='pendiente_asignacion'?'activa_seccion_por_asignar':'activa','seccion'=>$p['seccion']?:null],'totales'=>['subtotal'=>round((float)$p['importe'],2),'descuento'=>0.0,'envio'=>0.0,'total'=>round((float)$p['importe'],2)]];
        $json=json_encode($jsonData,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR);
        require_once ATENEA_ROOT.'/vendor/autoload.php';$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$logo=ATENEA_ROOT.'/img/atenea-logo-pdf.jpg';$logoUri=is_file($logo)?'data:image/jpeg;base64,'.base64_encode((string)file_get_contents($logo)):'';
        $html='<!doctype html><html lang="es"><head><meta charset="utf-8"><style>@page{margin:30px}body{font-family:DejaVu Sans,sans-serif;color:#252821;font-size:10px}.head{border-bottom:3px solid #b8943e;padding-bottom:14px}.logo{width:115px}.title{color:#173f35;font-size:21px}.warn{margin:14px 0;padding:9px;text-align:center;background:#fff8df;border:1px solid #b8943e;font-weight:bold}.box{border:1px solid #d8d5ca;padding:12px;margin:10px 0}.label{color:#6a6d66;font-size:8px}.total{background:#173f35;color:white;padding:12px;font-size:16px;text-align:right}.foot{position:fixed;bottom:-15px;text-align:center;color:#666;font-size:8px}</style></head><body><table width="100%" class="head"><tr><td>'.($logoUri?'<img class="logo" src="'.$logoUri.'">':'').'<br><strong>'.$e($emisor['nombre']).'</strong></td><td align="right"><div class="title">COMPROBANTE DE CAPACITACIÓN</div><strong>'.$e($numero).'</strong><br>'.$e($codigo).'</td></tr></table><div class="warn">DOCUMENTO INTERNO NO FISCAL · NO VÁLIDO FISCALMENTE</div><div class="box"><span class="label">COMPRADOR</span><br><strong>'.$e(trim($p['nombre'].' '.$p['apellido'])).'</strong><br>'.$e($p['correo']).'<br><br><span class="label">PAGO</span><br>Pago completado · Stripe · '.$e($fecha->format('d/m/Y H:i')).'<br>Payment Intent: '.$e(pagoStripeOcultoAtenea($p['stripe_payment_intent_id'])).'</div><div class="box"><span class="label">CAPACITACIÓN ADQUIRIDA</span><br><h2>'.$e($p['curso']).'</h2>Código: '.$e($p['codigo_curso']?:'No registrado').'<br>Inscripción: Activa'.($p['estado_inscripcion']==='pendiente_asignacion'?' · sección por asignar':'').'</div><div class="total">TOTAL PAGADO: $'.number_format((float)$p['importe'],2).' '.strtoupper((string)$p['moneda']).'</div><div class="foot">Documento interno generado por Atenea. No constituye un DTE ni una factura fiscal certificada.</div></body></html>';
        $dompdf=new Dompdf\Dompdf(['isRemoteEnabled'=>false]);$dompdf->loadHtml($html,'UTF-8');$dompdf->setPaper('letter');$dompdf->render();$pdf=$dompdf->output();if(!str_starts_with($pdf,'%PDF-'))throw new RuntimeException('No se produjo un PDF binario válido.');
        $base=rutaBaseComprobantesAtenea();$relDir=(int)$p['usuario_id'].'/capacitaciones/'.$pagoId;$dir=$base.DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$relDir);if(!is_dir($dir)&&!mkdir($dir,0700,true)&&!is_dir($dir))throw new RuntimeException('No se creó el directorio privado.');$safe=preg_replace('/[^A-Z0-9-]/i','-',$numero);$pdfRel=$relDir.'/factura_'.$safe.'.pdf';$jsonRel=$relDir.'/factura_'.$safe.'.json';$pdfPath=$base.DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$pdfRel);$jsonPath=$base.DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$jsonRel);if(file_put_contents($pdfPath,$pdf,LOCK_EX)!==strlen($pdf)||file_put_contents($jsonPath,$json,LOCK_EX)!==strlen($json))throw new RuntimeException('No se guardaron documentos completos.');
        $q=$pdo->prepare('INSERT INTO capacitacion_comprobante_documentos(pago_id,usuario_id,numero,codigo_generacion,pdf_relpath,json_relpath,pdf_sha256,json_sha256,generado_at) VALUES(:p,:u,:n,:c,:pdf,:json,:ph,:jh,NOW())');$q->execute(['p'=>$pagoId,'u'=>$p['usuario_id'],'n'=>$numero,'c'=>$codigo,'pdf'=>$pdfRel,'json'=>$jsonRel,'ph'=>hash('sha256',$pdf),'jh'=>hash('sha256',$json)]);$q=$pdo->prepare('SELECT * FROM capacitacion_comprobante_documentos WHERE pago_id=:id');$q->execute(['id'=>$pagoId]);return$q->fetch();
    }finally{try{$q=$pdo->prepare('SELECT RELEASE_LOCK(:l)');$q->execute(['l'=>$lock]);}catch(Throwable){}}
}

function rutaDocumentoCapacitacionAtenea(array $d,string $tipo): ?string
{
    $campo=$tipo==='json'?'json_relpath':'pdf_relpath';$base=rutaBaseComprobantesAtenea();$root=realpath($base);$ruta=realpath($base.DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,(string)$d[$campo]));return $root&&$ruta&&str_starts_with(strtolower($ruta),strtolower($root.DIRECTORY_SEPARATOR))&&is_file($ruta)&&filesize($ruta)>0?$ruta:null;
}

function enviarConfirmacionCompraCapacitacionAtenea(int $pagoId): bool
{
    $pdo=obtenerConexion();$p=pagoCapacitacionCompletoAtenea($pdo,$pagoId);if(!$p||$p['estado']!=='pagado'||!filter_var($p['correo'],FILTER_VALIDATE_EMAIL))return false;$d=generarComprobantesCapacitacionAtenea($pagoId);$pdf=rutaDocumentoCapacitacionAtenea($d,'pdf');$json=rutaDocumentoCapacitacionAtenea($d,'json');if(!$pdf||!$json)return false;$nombre=trim($p['nombre'].' '.$p['apellido']);$url=atenea_url_absoluta('src/estudiantes/cursos.php');
    $asunto='Compra confirmada en Atenea — Capacitación #'.$pagoId;$html='<!doctype html><html><body style="margin:0;background:#f4f4f1;font-family:Arial,sans-serif;color:#252821"><div style="display:none">Tu pago fue confirmado y tus documentos ya están disponibles.</div><table width="100%"><tr><td align="center" style="padding:32px"><table width="620" style="max-width:100%;background:#fff;border-radius:12px;overflow:hidden"><tr><td style="background:#173f35;color:#fff;padding:25px"><h1 style="margin:0">¡Pago completado!</h1></td></tr><tr><td style="padding:30px"><p>Hola, '.htmlspecialchars($nombre,ENT_QUOTES,'UTF-8').':</p><p>Tu compra de <strong>'.htmlspecialchars((string)$p['curso'],ENT_QUOTES,'UTF-8').'</strong> fue confirmada correctamente.</p><p style="font-size:20px;color:#173f35"><strong>Total pagado: $'.number_format((float)$p['importe'],2).' USD</strong></p><p>Pago: <strong>Completado</strong><br>Inscripción: <strong>Activa</strong></p><p>Adjuntamos tu comprobante PDF y los datos JSON.</p><p><a href="'.htmlspecialchars($url,ENT_QUOTES,'UTF-8').'" style="display:inline-block;background:#b8943e;color:#fff;padding:12px 20px;border-radius:6px;text-decoration:none">Ir a mi capacitación</a></p></td></tr><tr><td style="padding:18px;text-align:center;color:#666;background:#faf9f5">Atenea Escuela de Naturopatía Holística</td></tr></table></td></tr></table></body></html>';$texto="Hola, {$nombre}:\n\nTu pago fue confirmado.\nCapacitación: {$p['curso']}\nTotal pagado: $".number_format((float)$p['importe'],2)." USD\nPago: Completado\nInscripción: Activa\n\nSe adjuntan PDF y JSON.\n{$url}";
    $id=encolarCorreoAtenea((string)$p['correo'],$nombre,$asunto,$html,$texto,['tipo'=>'compra_capacitacion_confirmada','usuario_id'=>(int)$p['usuario_id'],'idempotency_key'=>'compra-confirmada:capacitacion:'.$pagoId,'attachments'=>[['path'=>$pdf,'name'=>'Comprobante_'.$d['numero'].'.pdf','type'=>'application/pdf'],['path'=>$json,'name'=>'Compra_'.$d['numero'].'.json','type'=>'application/json']]]);if(!$id)return false;$estado=procesarCorreoEnColaAtenea($id);return in_array($estado,['enviado','omitido','cancelado'],true);
}
