<?php
declare(strict_types=1);

require_once __DIR__.'/auth.php';
require_once __DIR__.'/portal_estudiante.php';
require_once __DIR__.'/contenido.php';
require_once __DIR__.'/perfil_modal.php';
require_once __DIR__.'/alerts.php';
require_once __DIR__.'/audit.php';
require_once __DIR__.'/carrito.php';
require_once __DIR__.'/notificaciones.php';
require_once __DIR__.'/personalizacion_visual.php';

function datosPortalEstudiante(int $usuarioId): array
{
    $pdo=obtenerConexion();$q=$pdo->prepare("SELECT COUNT(*) pedidos,COALESCE(SUM(estado='pagado'),0) pagados,COALESCE(SUM(CASE WHEN estado='pagado' THEN total ELSE 0 END),0) invertido FROM pedidos WHERE usuario_id=:u");$q->execute(['u'=>$usuarioId]);$resumen=$q->fetch()?:['pedidos'=>0,'pagados'=>0,'invertido'=>0];
    $q=$pdo->prepare('SELECT id,numero,total,moneda,estado,created_at FROM pedidos WHERE usuario_id=:u ORDER BY created_at DESC LIMIT 8');$q->execute(['u'=>$usuarioId]);$pedidos=$q->fetchAll();
    $q=$pdo->prepare("SELECT COUNT(*) FROM admin_notices WHERE user_id=:u AND status='pendiente'");$q->execute(['u'=>$usuarioId]);$avisos=(int)$q->fetchColumn();
    $q=$pdo->prepare("SELECT COUNT(*) FROM inscripciones_capacitacion WHERE usuario_id=:u AND estado IN('pendiente_asignacion','inscrito','finalizado')");$q->execute(['u'=>$usuarioId]);$capacitaciones=(int)$q->fetchColumn();
    $q=$pdo->prepare("SELECT COUNT(*) FROM certificados_capacitacion WHERE estudiante_id=:u AND estado='emitido'");$q->execute(['u'=>$usuarioId]);$certificados=(int)$q->fetchColumn();
    return['resumen'=>$resumen,'pedidos'=>$pedidos,'capacitaciones'=>$capacitaciones,'certificados'=>$certificados,'avisos_pendientes'=>$avisos];
}

function estadoPedidoEstudiante(string $estado): string{return match($estado){'pagado'=>'Pagado','pendiente_pago'=>'Pendiente de pago','preparando'=>'Preparando','enviado'=>'Enviado','entregado'=>'Entregado','pago_fallido'=>'Pago fallido','cancelado'=>'Cancelado','reembolsado'=>'Reembolsado',default=>ucfirst(str_replace('_',' ',$estado))};}
function claseEstadoPedido(string $estado): string{return match($estado){'pagado','entregado'=>'bg-success','pago_fallido','cancelado'=>'bg-danger','reembolsado'=>'bg-info','enviado'=>'bg-primary',default=>'bg-warning'};}

function portalEstudianteCabecera(string $titulo,string $activo='inicio',string $descripcion='',bool $permitirIncompleto=false): array
{
    $permitirIncompleto?exigirRol(['usuario']):exigirPerfilCompleto();$perfil=obtenerPerfilUsuario((int)$_SESSION['usuario_id']);if(!$perfil){header('Location: '.atenea_url('src/login/logout.php'));exit;}
    $datos=datosPortalEstudiante((int)$perfil['id']);$cantidadCarrito=cantidadCarrito(obtenerConexion(),(int)$perfil['id']);$notificacionesPortal=notificacionesUsuarioResumen((int)$perfil['id'],1);$logo=logoPersonalizacionVisualAtenea('estudiantes',obtenerConfiguracionPortalEstudiante('portal_logo'));$avatar=rutaFotoPerfil($perfil);$hora=(int)date('G');$saludo=$hora<12?'Buenos días':($hora<18?'Buenas tardes':'Buenas noches');
    $enlace=static fn(string $clave):string=>'nav-link'.($activo===$clave?' active':'');$aprendizaje=in_array($activo,['cursos','contenidos','videos','tareas','evaluaciones','calificaciones','calendario'],true);$comunicacion=in_array($activo,['comunicaciones','notificaciones','avisos','soporte'],true);$cuenta=in_array($activo,['certificados','pedidos','carrito','direcciones','perfil'],true);
    $GLOBALS['portal_estudiante_flash']=is_array($_SESSION['portal_flash']??null)?$_SESSION['portal_flash']:null;unset($_SESSION['portal_flash']);
?>
<!doctype html><html lang="es" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=atenea_e($titulo)?> | Atenea</title><meta name="description" content="<?=atenea_e($descripcion?:'Aula virtual de Atenea')?>"><link rel="shortcut icon" href="<?=atenea_e($logo)?>"><link rel="stylesheet" href="<?=atenea_url('src/estudiantes/assets/css/core/libs.min.css')?>"><link rel="stylesheet" href="<?=atenea_url('src/estudiantes/assets/vendor/aos/dist/aos.css')?>"><link rel="stylesheet" href="<?=atenea_url('src/estudiantes/assets/vendor/flatpickr/dist/flatpickr.min.css')?>"><link rel="stylesheet" href="<?=atenea_url('src/estudiantes/assets/css/hope-ui.min.css?v=4.0.0')?>"><link rel="stylesheet" href="<?=atenea_url('src/estudiantes/assets/css/custom.min.css?v=4.0.0')?>"><link rel="stylesheet" href="<?=atenea_url('src/estudiantes/assets/css/dark.min.css')?>"><link rel="stylesheet" href="<?=atenea_url('src/estudiantes/assets/css/customizer.min.css')?>"><link rel="stylesheet" href="<?=atenea_url('src/estudiantes/assets/css/rtl.min.css')?>"><link rel="stylesheet" href="<?=atenea_url('src/estudiantes/assets/css/atenea-branding.css')?>"><link rel="stylesheet" href="<?=atenea_url('src/website/assets/css/cart.css')?>"><link rel="stylesheet" href="<?=atenea_url('src/website/assets/css/perfil-modal.css')?>"><link rel="stylesheet" href="<?=atenea_url('src/website/assets/css/security-ui.css')?>"><?php ateneaAlertasHead();?></head><body class="atenea-aula">
<aside class="sidebar sidebar-default sidebar-white sidebar-base navs-rounded-all" id="portalSidebar" aria-label="Navegación del aula virtual"><div class="sidebar-header d-flex align-items-center justify-content-between"><a href="<?=atenea_url('src/estudiantes/index.php')?>" class="navbar-brand atenea-portal-logo"><img src="<?=atenea_e($logo)?>" class="img-fluid" alt="Atenea Escuela de Naturopatía Holística"></a><button class="portal-sidebar-close d-lg-none" type="button" data-portal-sidebar-toggle aria-label="Cerrar menú"><i class="bi bi-x-lg"></i></button></div><div class="sidebar-body pt-0 data-scrollbar"><div class="sidebar-list"><ul class="navbar-nav iq-main-menu" id="sidebar-menu">
<li class="nav-item static-item"><span class="nav-link static-item disabled"><span class="default-icon">Aula virtual</span></span></li><li class="nav-item"><a class="<?=$enlace('inicio')?>" href="<?=atenea_url('src/estudiantes/index.php')?>"><i class="icon"><i class="bi bi-house-door"></i></i><span class="item-name">Inicio</span></a></li><li class="nav-item"><a class="<?=$enlace('clase')?>" href="<?=atenea_url('src/estudiantes/clase.php')?>"><i class="icon"><i class="bi bi-people"></i></i><span class="item-name">Mi clase</span></a></li>
<li class="nav-item"><a class="nav-link <?=$aprendizaje?'':'collapsed'?>" data-bs-toggle="collapse" href="#menuAprendizaje" aria-expanded="<?=$aprendizaje?'true':'false'?>" aria-controls="menuAprendizaje"><i class="icon"><i class="bi bi-mortarboard"></i></i><span class="item-name">Aprendizaje</span><i class="bi bi-chevron-down ms-auto submenu-arrow"></i></a><ul class="nav collapse submenu <?=$aprendizaje?'show':''?>" id="menuAprendizaje"><li><a class="<?=$enlace('cursos')?>" href="<?=atenea_url('src/estudiantes/cursos.php')?>">Capacitaciones</a></li><li><a class="<?=$enlace('contenidos')?>" href="<?=atenea_url('src/estudiantes/contenidos.php')?>">Contenidos</a></li><li><a class="<?=$enlace('videos')?>" href="<?=atenea_url('src/estudiantes/videos.php')?>">Videos</a></li><li><a class="<?=$enlace('tareas')?>" href="<?=atenea_url('src/estudiantes/tareas.php')?>">Tareas</a></li><li><a class="<?=$enlace('evaluaciones')?>" href="<?=atenea_url('src/estudiantes/evaluaciones.php')?>">Evaluaciones</a></li><li><a class="<?=$enlace('calificaciones')?>" href="<?=atenea_url('src/estudiantes/calificaciones.php')?>">Calificaciones</a></li><li><a class="<?=$enlace('calendario')?>" href="<?=atenea_url('src/estudiantes/calendario.php')?>">Calendario</a></li></ul></li>
<li class="nav-item"><a class="nav-link <?=$comunicacion?'':'collapsed'?>" data-bs-toggle="collapse" href="#menuComunicacion" aria-expanded="<?=$comunicacion?'true':'false'?>" aria-controls="menuComunicacion"><i class="icon"><i class="bi bi-chat-square-text"></i></i><span class="item-name">Comunicación</span><i class="bi bi-chevron-down ms-auto submenu-arrow"></i></a><ul class="nav collapse submenu <?=$comunicacion?'show':''?>" id="menuComunicacion"><li><a class="<?=$enlace('comunicaciones')?>" href="<?=atenea_url('src/comunicaciones/chat.php')?>">Mensajes</a></li><li><a class="<?=$enlace('notificaciones')?>" href="<?=atenea_url('src/notificaciones/index.php')?>">Notificaciones<span class="badge bg-danger ms-auto" data-atenea-notification-count <?=$notificacionesPortal['no_leidas']?'':'hidden'?>><?=(int)$notificacionesPortal['no_leidas']?></span></a></li><li><a class="<?=$enlace('avisos')?>" href="<?=atenea_url('src/estudiantes/avisos.php')?>">Avisos<?php if($datos['avisos_pendientes']):?><span class="badge bg-danger ms-auto"><?=(int)$datos['avisos_pendientes']?></span><?php endif;?></a></li><li><a class="<?=$enlace('soporte')?>" href="<?=atenea_url('src/estudiantes/soporte.php')?>">Soporte</a></li></ul></li>
<li class="nav-item"><a class="nav-link <?=$cuenta?'':'collapsed'?>" data-bs-toggle="collapse" href="#menuCuenta" aria-expanded="<?=$cuenta?'true':'false'?>" aria-controls="menuCuenta"><i class="icon"><i class="bi bi-person-circle"></i></i><span class="item-name">Mi cuenta</span><i class="bi bi-chevron-down ms-auto submenu-arrow"></i></a><ul class="nav collapse submenu <?=$cuenta?'show':''?>" id="menuCuenta"><li><a class="<?=$enlace('certificados')?>" href="<?=atenea_url('src/estudiantes/certificados.php')?>">Certificados</a></li><li><a class="<?=$enlace('pedidos')?>" href="<?=atenea_url('src/estudiantes/pedidos.php')?>">Compras y pagos</a></li><li><a class="<?=$enlace('carrito')?>" href="<?=atenea_url('src/carrito/index.php')?>">Carrito<?php if($cantidadCarrito):?><span class="badge bg-danger ms-auto"><?=$cantidadCarrito?></span><?php endif;?></a></li><li><a class="<?=$enlace('direcciones')?>" href="<?=atenea_url('src/estudiantes/direcciones.php')?>">Direcciones</a></li><li><a class="<?=$enlace('perfil')?>" href="<?=atenea_url('src/estudiantes/perfil.php')?>">Perfil</a></li></ul></li>
<li><hr class="hr-horizontal"></li><li class="nav-item"><a class="nav-link" href="<?=atenea_url('index.php')?>"><i class="icon"><i class="bi bi-globe"></i></i><span class="item-name">Volver al sitio</span></a></li><li class="nav-item"><a class="nav-link" data-atenea-confirm="logout" href="<?=atenea_url('src/login/logout.php')?>"><i class="icon"><i class="bi bi-box-arrow-right"></i></i><span class="item-name">Cerrar sesión</span></a></li></ul></div></div></aside><button class="portal-sidebar-overlay" type="button" data-portal-sidebar-toggle aria-label="Cerrar navegación" tabindex="-1"></button>
<main class="main-content"><nav class="nav navbar navbar-light iq-navbar"><div class="container-fluid navbar-inner"><button class="portal-menu-button" type="button" data-portal-sidebar-toggle aria-controls="portalSidebar" aria-expanded="true" aria-label="Mostrar u ocultar menú"><i class="bi bi-list"></i></button><a href="<?=atenea_url('src/estudiantes/index.php')?>" class="navbar-brand d-lg-none atenea-portal-logo-mobile"><img src="<?=atenea_e($logo)?>" alt="Atenea"></a><div class="ms-auto d-flex align-items-center"><a class="nav-link position-relative me-3" href="<?=atenea_url('src/notificaciones/index.php')?>" aria-label="Abrir notificaciones"><i class="bi bi-bell fs-5"></i><span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" data-atenea-notification-count <?=$notificacionesPortal['no_leidas']?'':'hidden'?>><?=(int)$notificacionesPortal['no_leidas']?></span></a><div class="dropdown"><a class="py-0 nav-link d-flex align-items-center" href="#" id="menuPerfilEstudiante" role="button" data-bs-toggle="dropdown" aria-expanded="false"><img src="<?=atenea_e($avatar)?>" class="img-fluid avatar avatar-50 avatar-rounded" data-atenea-current-avatar alt="Foto de <?=atenea_e((string)$perfil['nombre'])?>"><div class="caption ms-3 d-none d-md-block"><h6 class="mb-0 caption-title" data-atenea-current-name><?=atenea_e(trim((string)$perfil['nombre'].' '.(string)$perfil['apellido']))?></h6><p class="mb-0 caption-sub-title"><?=atenea_e(etiquetaRol((string)$perfil['rol']))?></p></div></a><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="<?=atenea_url('src/estudiantes/perfil.php')?>">Mi perfil</a></li><li><a class="dropdown-item" href="<?=atenea_url('index.php')?>">Volver al sitio</a></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item" data-atenea-confirm="logout" href="<?=atenea_url('src/login/logout.php')?>">Cerrar sesión</a></li></ul></div></div></div></nav>
<div class="iq-navbar-header"><div class="container-fluid iq-container"><div class="row"><div class="col-12"><nav aria-label="Ruta de navegación"><ol class="breadcrumb portal-breadcrumb"><li class="breadcrumb-item"><a href="<?=atenea_url('src/estudiantes/index.php')?>">Aula virtual</a></li><li class="breadcrumb-item active" aria-current="page"><?=atenea_e($titulo)?></li></ol></nav><h1><?=atenea_e($saludo)?>, <?=atenea_e((string)$perfil['nombre'])?></h1><p><?=atenea_e($descripcion?:obtenerConfiguracionPortalEstudiante('panel_texto_bienvenida'))?></p></div></div></div><div class="iq-header-img"><img src="<?=atenea_url('src/estudiantes/assets/images/dashboard/top-header.png')?>" alt="" class="theme-color-default-img img-fluid w-100 h-100 animated-scaleX"></div></div><div class="container-fluid content-inner mt-n5 py-0">
<?php return['perfil'=>$perfil,'datos'=>$datos];}

function portalEstudiantePie(): void
{?>
</div><footer class="footer"><div class="footer-body text-center"><?=atenea_e(obtenerConfiguracionPortalEstudiante('texto_pie_pagina'))?> &copy; <?=date('Y')?></div></footer></main><?php renderizarModalPerfil('estudiantes');renderizarControlSesionAtenea();?><script src="<?=atenea_url('src/estudiantes/assets/js/core/libs.min.js')?>"></script><script src="<?=atenea_url('src/estudiantes/assets/js/core/external.min.js')?>"></script><script src="<?=atenea_url('src/estudiantes/assets/vendor/aos/dist/aos.js')?>"></script><script src="<?=atenea_url('src/estudiantes/assets/vendor/flatpickr/dist/flatpickr.min.js')?>"></script><script src="<?=atenea_url('src/estudiantes/assets/js/hope-ui.js')?>" defer></script><script src="<?=atenea_url('src/estudiantes/assets/js/portal-navigation.js')?>" defer></script><script src="<?=atenea_url('src/website/assets/js/perfil-modal.js')?>"></script><script src="<?=atenea_url('src/website/assets/js/security-ui.js')?>"></script><?php ateneaAlertasScripts($GLOBALS['portal_estudiante_flash']??null);?></body></html><?php }
