<?php
declare(strict_types=1);require_once __DIR__.'/conexion.php';require_once __DIR__.'/session.php';require_once __DIR__.'/audit.php';

function tablasVersionadasWebsite():array{return['configuracion_sitio','menu_sitio','secciones','elementos_seccion','noticias','asignaturas','categorias_producto','productos','producto_imagenes'];}
function capturarEstadoWebsite(?PDO $pdo=null):array{$pdo??=obtenerConexion();$estado=[];foreach(tablasVersionadasWebsite() as$t){try{$estado[$t]=$pdo->query("SELECT * FROM `$t` ORDER BY 1")->fetchAll();}catch(Throwable){$estado[$t]=[];}}return$estado;}
function jsonEstadoWebsite(array $estado):string{return json_encode($estado,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function publicacionWebsiteActual(?PDO $pdo=null):?array{$pdo??=obtenerConexion();$q=$pdo->query("SELECT * FROM website_publicaciones WHERE estado='publicado' ORDER BY publicado_at DESC,id DESC LIMIT 1");return$q->fetch()?:null;}
function estadoPublicadoWebsite(?PDO $pdo=null):array{$p=publicacionWebsiteActual($pdo);return$p?json_decode($p['contenido_json'],true,512,JSON_THROW_ON_ERROR):capturarEstadoWebsite($pdo);}
function estadoFuenteWebsite(?PDO $pdo=null):array{return !empty($GLOBALS['ATENEA_WEBSITE_PREVIEW'])?capturarEstadoWebsite($pdo):estadoPublicadoWebsite($pdo);}

function inicializarVersionadoWebsite(PDO $pdo,int $admin):void{if(publicacionWebsiteActual($pdo))return;$json=jsonEstadoWebsite(capturarEstadoWebsite($pdo));$q=$pdo->prepare("INSERT INTO website_publicaciones(estado,contenido_json,comentario,creado_por,publicado_por,publicado_at) VALUES('publicado',:j,'Versión inicial antes de habilitar borradores',:a,:a2,NOW()),('borrador',:j2,'Borrador inicial',:a3,NULL,NULL)");$q->execute(['j'=>$json,'a'=>$admin,'a2'=>$admin,'j2'=>$json,'a3'=>$admin]);}
function guardarSnapshotBorradorWebsite(PDO $pdo,array $estado,int $admin,string $comentario='Cambios guardados desde el CMS'):void{$json=jsonEstadoWebsite($estado);$q=$pdo->query("SELECT id FROM website_publicaciones WHERE estado='borrador' ORDER BY id DESC LIMIT 1");$id=(int)$q->fetchColumn();if($id)$pdo->prepare('UPDATE website_publicaciones SET contenido_json=:j,comentario=:c,creado_por=:a WHERE id=:id')->execute(['j'=>$json,'c'=>mb_substr($comentario,0,500),'a'=>$admin,'id'=>$id]);else$pdo->prepare("INSERT INTO website_publicaciones(estado,contenido_json,comentario,creado_por) VALUES('borrador',:j,:c,:a)")->execute(['j'=>$json,'c'=>mb_substr($comentario,0,500),'a'=>$admin]);}
function registrarVersionWebsite(PDO $pdo,int $admin,string $seccion,array $antes,array $despues,string $estado='borrador',?string $comentario=null):int{$q=$pdo->prepare('INSERT INTO website_versiones(administrador_id,seccion_modificada,datos_anteriores,datos_nuevos,estado,comentario) VALUES(:a,:s,:an,:nu,:e,:c)');$q->execute(['a'=>$admin,'s'=>mb_substr($seccion,0,120),'an'=>jsonEstadoWebsite($antes),'nu'=>jsonEstadoWebsite($despues),'e'=>$estado,'c'=>$comentario?mb_substr($comentario,0,500):null]);return(int)$pdo->lastInsertId();}

function registrarCapturaAutomaticaCms():void
{
 if(($_SERVER['REQUEST_METHOD']??'')!=='POST'||($_SESSION['usuario_rol']??'')!=='admin')return;$ruta=str_replace('\\','/',(string)($_SERVER['SCRIPT_NAME']??''));if(!preg_match('~/src/dashboard/(secciones|elementos|configuracion|navbar|noticias|capacitaciones|productos|categorias)/~',$ruta,$m))return;$antes=capturarEstadoWebsite();$admin=(int)$_SESSION['usuario_id'];register_shutdown_function(static function()use($antes,$admin,$m){try{$pdo=obtenerConexion();$despues=capturarEstadoWebsite($pdo);if(hash_equals(hash('sha256',jsonEstadoWebsite($antes)),hash('sha256',jsonEstadoWebsite($despues))))return;$pdo->beginTransaction();guardarSnapshotBorradorWebsite($pdo,$despues,$admin,'Guardado automático en '.$m[1]);registrarVersionWebsite($pdo,$admin,$m[1],$antes,$despues,'borrador','Cambio guardado como borrador');$pdo->commit();}catch(Throwable$e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();error_log('Versionado CMS: '.$e->getMessage());}});
}

function upsertFilasWebsite(PDO $pdo,string $tabla,array $filas):void
{
 if(!$filas)return;$columnas=array_column($pdo->query("SHOW COLUMNS FROM `$tabla`")->fetchAll(),'Field');foreach($filas as$f){$datos=array_intersect_key($f,array_flip($columnas));if(!$datos)continue;$cols=array_keys($datos);$sql="INSERT INTO `$tabla` (`".implode('`,`',$cols).'`) VALUES ('.implode(',',array_map(fn($c)=>':'.$c,$cols)).') ON DUPLICATE KEY UPDATE '.implode(',',array_map(fn($c)=>"`$c`=VALUES(`$c`)",array_filter($cols,fn($c)=>$c!=='id')));$pdo->prepare($sql)->execute($datos);}
}
function aplicarEstadoWebsite(PDO $pdo,array $estado):void
{
 $pdo->beginTransaction();try{foreach(['configuracion_sitio','menu_sitio','secciones','categorias_producto','productos','asignaturas','noticias','elementos_seccion','producto_imagenes'] as$t)upsertFilasWebsite($pdo,$t,$estado[$t]??[]);foreach(['menu_sitio','secciones','elementos_seccion','noticias','asignaturas','categorias_producto','productos'] as$t){$ids=array_values(array_filter(array_map(fn($r)=>(int)($r['id']??0),$estado[$t]??[])));if(!$ids)continue;$marks=implode(',',array_fill(0,count($ids),'?'));$col=$t==='noticias'?'activo':'activo';$pdo->prepare("UPDATE `$t` SET `$col`=0 WHERE id NOT IN($marks)")->execute($ids);}$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
}

function publicarWebsite(PDO $pdo,int $admin,string $comentario=''):int{$actual=capturarEstadoWebsite($pdo);$antes=estadoPublicadoWebsite($pdo);$pdo->beginTransaction();try{$pdo->exec("UPDATE website_publicaciones SET estado='archivado' WHERE estado='publicado'");$q=$pdo->prepare("INSERT INTO website_publicaciones(estado,contenido_json,comentario,creado_por,publicado_por,publicado_at) VALUES('publicado',:j,:c,:a,:a2,NOW())");$q->execute(['j'=>jsonEstadoWebsite($actual),'c'=>mb_substr($comentario?:'Publicación manual',0,500),'a'=>$admin,'a2'=>$admin]);$id=(int)$pdo->lastInsertId();guardarSnapshotBorradorWebsite($pdo,$actual,$admin,'Sincronizado después de publicar');registrarVersionWebsite($pdo,$admin,'website',$antes,$actual,'publicado',$comentario?:'Publicación manual');registrarAuditoria(['actor_user_id'=>$admin,'event_type'=>'website.published','module'=>'website','entity_type'=>'website_publication','entity_id'=>$id,'action'=>'publish','description'=>'El borrador del website fue publicado.'],$pdo);$pdo->commit();return$id;}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
function descartarBorradorWebsite(PDO $pdo,int $admin):void{$antes=capturarEstadoWebsite($pdo);$publicado=estadoPublicadoWebsite($pdo);aplicarEstadoWebsite($pdo,$publicado);$pdo->beginTransaction();try{guardarSnapshotBorradorWebsite($pdo,$publicado,$admin,'Borrador descartado');registrarVersionWebsite($pdo,$admin,'website',$antes,$publicado,'descartado','Se descartó el borrador');registrarAuditoria(['actor_user_id'=>$admin,'event_type'=>'website.draft.discarded','module'=>'website','action'=>'discard','description'=>'El borrador fue descartado y se restauró la publicación vigente.'],$pdo);$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
function restaurarVersionWebsite(PDO $pdo,int $versionId,int $admin):void{$q=$pdo->prepare('SELECT * FROM website_versiones WHERE id=:id');$q->execute(['id'=>$versionId]);$v=$q->fetch();if(!$v)throw new DomainException('La versión no existe.');$antes=capturarEstadoWebsite($pdo);$restaurado=json_decode($v['datos_nuevos'],true,512,JSON_THROW_ON_ERROR);aplicarEstadoWebsite($pdo,$restaurado);$pdo->beginTransaction();try{guardarSnapshotBorradorWebsite($pdo,$restaurado,$admin,'Restauración de versión '.$versionId);registrarVersionWebsite($pdo,$admin,'website',$antes,$restaurado,'restaurado','Restaurada desde versión '.$versionId);registrarAuditoria(['actor_user_id'=>$admin,'event_type'=>'website.version.restored','module'=>'website','entity_type'=>'website_version','entity_id'=>$versionId,'action'=>'restore','description'=>'Se restauró una versión anterior como borrador.'],$pdo);$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}

function crearTokenPreviewWebsite(PDO $pdo,int $admin):string{$token=bin2hex(random_bytes(32));$hash=hash('sha256',$token);$sesion=hash('sha256',session_id());$pdo->prepare('DELETE FROM website_preview_tokens WHERE expira_at<NOW() OR revocado_at IS NOT NULL')->execute();$pdo->prepare('INSERT INTO website_preview_tokens(token_hash,administrador_id,session_hash,expira_at) VALUES(:t,:a,:s,DATE_ADD(NOW(),INTERVAL 30 MINUTE))')->execute(['t'=>$hash,'a'=>$admin,'s'=>$sesion]);return$token;}
function validarTokenPreviewWebsite(PDO $pdo,string $token):bool{if(!preg_match('/^[a-f0-9]{64}$/',$token)||($_SESSION['usuario_rol']??'')!=='admin')return false;$q=$pdo->prepare('SELECT id,administrador_id,session_hash FROM website_preview_tokens WHERE token_hash=:t AND expira_at>NOW() AND revocado_at IS NULL LIMIT 1');$q->execute(['t'=>hash('sha256',$token)]);$r=$q->fetch();if(!$r||(int)$r['administrador_id']!==(int)$_SESSION['usuario_id']||!hash_equals($r['session_hash'],hash('sha256',session_id())))return false;$pdo->prepare('UPDATE website_preview_tokens SET ultimo_uso_at=NOW() WHERE id=:id')->execute(['id'=>$r['id']]);return true;}

function filasEstadoWebsite(string $tabla):array{$e=estadoFuenteWebsite();return is_array($e[$tabla]??null)?$e[$tabla]:[];}
