<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';
require_once dirname(__DIR__,3).'/includes/database_backups.php';
exigirPermiso('backups.view');
$pdo=obtenerConexion();$pagina=max(1,(int)($_GET['pagina']??1));$limite=20;$total=(int)$pdo->query('SELECT COUNT(*) FROM respaldos_base_datos')->fetchColumn();$paginas=max(1,(int)ceil($total/$limite));$pagina=min($pagina,$paginas);
$q=$pdo->query('SELECT r.*,CONCAT(u.nombre," ",u.apellido) creador,CONCAT(ur.nombre," ",ur.apellido) restaurador FROM respaldos_base_datos r LEFT JOIN usuarios u ON u.id=r.creado_por LEFT JOIN usuarios ur ON ur.id=r.restaurado_por ORDER BY r.created_at DESC,r.id DESC LIMIT '.$limite.' OFFSET '.(($pagina-1)*$limite));$respaldos=$q->fetchAll();$superadmin=respaldoEsSuperadmin();
$estados=['creando'=>['Creando','info'],'disponible'=>['Disponible','success'],'restaurando'=>['Restaurando','warning'],'restaurado'=>['Restaurado','primary'],'fallido'=>['Fallido','danger'],'eliminado'=>['Eliminado','secondary']];
cmsCabecera('Copias de seguridad','backups/index.php','Genera, descarga y administra copias privadas de la base de datos.');
?>
<div class="row g-3 mb-4">
  <div class="col-lg-8"><div class="card card-rounded h-100"><div class="card-body d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3"><div><h2 class="h5 mb-1">Protección de la base de datos</h2><p class="text-muted mb-0">La copia contiene estructura y datos persistentes. Tokens, sesiones y estados temporales se crean vacíos.</p></div><form method="post" action="accion.php" data-atenea-loading data-atenea-loading-title="Creando copia de seguridad"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="crear"><button class="btn btn-primary text-white text-nowrap"><i class="mdi mdi-database-plus me-1"></i>Crear copia de seguridad</button></form></div></div></div>
  <div class="col-lg-4"><div class="card card-rounded h-100"><div class="card-body"><h2 class="h6">Política de retención</h2><p class="mb-1"><strong><?=respaldoRetencionDias()?></strong> días</p><p class="mb-0 text-muted">Máximo <?=respaldoMaximoArchivos()?> archivos. El almacenamiento está fuera del directorio público.</p></div></div></div>
</div>
<?php if(!$superadmin):?><div class="alert alert-info"><i class="mdi mdi-shield-lock-outline me-1"></i> Puedes crear, descargar y eliminar copias. La restauración está reservada al Superadministrador.</div><?php endif;?>
<div class="card card-rounded"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Historial</h2><span class="text-muted"><?=number_format($total,0,',','.')?> registros</span></div><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Fecha y hora</th><th>Creada por</th><th>Tipo</th><th>Tamaño</th><th>Contenido</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
<?php foreach($respaldos as $r):$estado=$estados[$r['estado']]??[ucfirst((string)$r['estado']),'secondary'];$disponible=in_array($r['estado'],['disponible','restaurado'],true);?>
<tr><td><time datetime="<?=atenea_e((string)$r['created_at'])?>"><?=atenea_e(date('d/m/Y h:i A',strtotime((string)$r['created_at'])))?></time><?php if($r['restaurado_at']):?><small class="d-block text-muted">Restaurada <?=atenea_e(date('d/m/Y h:i A',strtotime((string)$r['restaurado_at'])))?></small><?php endif;?></td><td><?=atenea_e(trim((string)($r['creador']?:'Proceso del sistema')))?></td><td><?=($r['tipo']==='previo_restauracion')?'Previa a restauración':'Manual'?></td><td><?=atenea_e(formatoTamanoRespaldo($r['tamano_bytes']===null?null:(int)$r['tamano_bytes']))?></td><td><span class="text-nowrap"><?=(int)$r['tablas_incluidas']?> tablas</span><small class="d-block text-muted"><?=number_format((int)$r['filas_incluidas'],0,',','.')?> filas</small></td><td><span class="badge bg-<?=$estado[1]?>"><?=atenea_e($estado[0])?></span><?php if($r['error_sanitizado']):?><small class="d-block text-danger mt-1"><?=atenea_e((string)$r['error_sanitizado'])?></small><?php endif;?></td><td><div class="d-flex gap-1 justify-content-end flex-wrap">
<?php if($disponible):?><form method="post" action="descargar.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><button class="btn btn-sm btn-outline-primary" title="Descargar copia"><i class="mdi mdi-download"></i><span class="visually-hidden">Descargar</span></button></form><?php endif;?>
<?php if($disponible&&$superadmin):?><button type="button" class="btn btn-sm btn-outline-warning js-restaurar" data-id="<?=(int)$r['id']?>" data-fecha="<?=atenea_e(date('d/m/Y h:i A',strtotime((string)$r['created_at'])))?>" title="Restaurar esta copia"><i class="mdi mdi-database-import"></i><span class="visually-hidden">Restaurar</span></button><?php endif;?>
<?php if(!in_array($r['estado'],['creando','restaurando','eliminado'],true)):?><form method="post" action="accion.php" data-atenea-confirm data-atenea-confirm-title="¿Eliminar esta copia?" data-atenea-confirm-message="El archivo dejará de estar disponible para descarga o restauración." data-atenea-confirm-button="Sí, eliminar"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="eliminar"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><button class="btn btn-sm btn-outline-danger" title="Eliminar copia"><i class="mdi mdi-delete-outline"></i><span class="visually-hidden">Eliminar</span></button></form><?php endif;?>
</div></td></tr><?php endforeach;?>
<?php if(!$respaldos):?><tr><td colspan="7"><div class="text-center py-5"><i class="mdi mdi-database-off-outline display-4 text-muted"></i><h3 class="h5 mt-2">Todavía no hay copias</h3><p class="text-muted mb-0">Crea la primera copia para iniciar el historial.</p></div></td></tr><?php endif;?>
</tbody></table></div><?=cmsPaginacionSimple($pagina,$paginas)?></div></div>
<?php if($superadmin):?><div class="modal fade" id="modalRestaurar" tabindex="-1" aria-labelledby="tituloRestaurar" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post" action="accion.php" id="formRestaurar" data-atenea-loading data-atenea-loading-title="Restaurando base de datos"><div class="modal-header"><h2 class="modal-title h5" id="tituloRestaurar">Restaurar copia de seguridad</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body"><div class="alert alert-danger"><strong>Acción crítica.</strong> La base actual será reemplazada. Atenea creará automáticamente una copia previa antes de comenzar.</div><p>Copia seleccionada: <strong data-backup-date></strong></p><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="restaurar"><input type="hidden" name="id" value=""><div class="mb-3"><label class="form-label" for="backup-password">Contraseña actual</label><input class="form-control" id="backup-password" type="password" name="password" autocomplete="current-password" required></div><div class="mb-3"><label class="form-label" for="backup-phrase">Escribe <strong data-backup-phrase></strong></label><input class="form-control" id="backup-phrase" name="frase" autocomplete="off" required></div><div class="form-check"><input class="form-check-input" type="checkbox" value="1" name="confirmar_riesgo" id="confirmar-riesgo" required><label class="form-check-label" for="confirmar-riesgo">Comprendo que la información actual será reemplazada.</label></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-danger">Continuar con la restauración</button></div></form></div></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const modalEl=document.getElementById('modalRestaurar'),form=document.getElementById('formRestaurar'),modal=modalEl&&window.bootstrap?new bootstrap.Modal(modalEl):null;document.querySelectorAll('.js-restaurar').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.id,phrase='RESTAURAR '+id;form.elements.id.value=id;form.elements.password.value='';form.elements.frase.value='';form.elements.confirmar_riesgo.checked=false;modalEl.querySelector('[data-backup-date]').textContent=button.dataset.fecha;modalEl.querySelector('[data-backup-phrase]').textContent=phrase;modal?.show();}));form?.addEventListener('submit',async event=>{if(form.dataset.confirmed==='1')return;event.preventDefault();const ok=window.AteneaAlerts?await AteneaAlerts.confirm({title:'Segunda confirmación',message:'Se creará una copia previa y luego se reemplazará la base de datos actual. No cierres esta ventana.',danger:true,confirmText:'Sí, restaurar ahora'}):confirm('¿Confirmas por segunda vez la restauración?');if(ok){form.dataset.confirmed='1';form.requestSubmit();}});});</script><?php endif;?>
<?php cmsPie();?>
