<?php
declare(strict_types=1);require_once dirname(__DIR__,2).'/includes/comunicacion_centro.php';require_once dirname(__DIR__,2).'/includes/json_response.php';
if(!usuarioAutenticado())responderJsonErrorAtenea('AUTH_REQUIRED','Inicia sesión para utilizar el chat.',401);$pdo=obtenerConexion();$actor=(int)$_SESSION['usuario_id'];
try{
 if(($_SERVER['REQUEST_METHOD']??'GET')==='GET'){$accion=(string)($_GET['accion']??'mensajes');if($accion==='conversaciones')responderJsonExitoAtenea(['conversaciones'=>conversacionesChatAtenea($pdo,$actor,trim((string)($_GET['q']??'')))]);$id=filter_var($_GET['id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;if(!$id||!chatParticipa($pdo,$id,$actor))responderJsonErrorAtenea('CHAT_FORBIDDEN','No tienes acceso a esta conversación.',403);$antes=filter_var($_GET['antes']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:null;$despues=filter_var($_GET['despues']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:null;marcarChatEntregadoAtenea($pdo,$id,$actor);if(!$antes)marcarChatLeido($pdo,$id,$actor);$mensajes=mensajesChatAtenea($pdo,$id,$actor,$antes,$despues,40);responderJsonExitoAtenea(['mensajes'=>$mensajes,'hay_mas'=>!$despues&&count($mensajes)===40,'primero_id'=>$mensajes?(int)$mensajes[0]['id']:0,'ultimo_id'=>$mensajes?(int)$mensajes[array_key_last($mensajes)]['id']:0]);}
 if(!validarTokenCsrf((string)($_POST['csrf_token']??'')))responderJsonErrorAtenea('CSRF_EXPIRED','La sesión del formulario venció.',419);$accion=(string)($_POST['accion']??'enviar');
 if($accion==='enviar'){$id=filter_var($_POST['conversacion_id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$respuesta=filter_var($_POST['respuesta_a_id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:null;$adjunto=null;try{$adjunto=guardarAdjuntoComunicacion('adjunto','chat/'.$id);$mensajeId=enviarMensajeChat($pdo,$id,$actor,(string)($_POST['mensaje']??''),$respuesta,$adjunto,(string)($_POST['idempotency_key']??''));}catch(Throwable$e){if($adjunto&&($archivo=rutaPrivadaComunicacion($adjunto['relpath'])))@unlink($archivo);throw$e;}$mensajes=mensajesChatAtenea($pdo,$id,$actor,null,$mensajeId-1,2);$enviado=null;foreach($mensajes as$m)if((int)$m['id']===$mensajeId)$enviado=$m;responderJsonExitoAtenea(['mensaje'=>$enviado],201);}
 if($accion==='eliminar'){$mensajeId=filter_var($_POST['mensaje_id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;eliminarMensajeChatAtenea($pdo,$mensajeId,$actor);responderJsonExitoAtenea(['mensaje_id'=>$mensajeId]);}
 if($accion==='reportar'){$mensajeId=filter_var($_POST['mensaje_id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$q=$pdo->prepare('SELECT conversacion_id,remitente_id FROM chat_mensajes WHERE id=:id AND estado=\'activo\'');$q->execute(['id'=>$mensajeId]);$m=$q->fetch();if(!$m||!chatParticipa($pdo,(int)$m['conversacion_id'],$actor)||(int)$m['remitente_id']===$actor)throw new DomainException('No puedes reportar este mensaje.');$pdo->prepare("INSERT IGNORE INTO chat_reportes(mensaje_id,reportado_por,motivo) VALUES(:m,:u,'Contenido reportado por participante')")->execute(['m'=>$mensajeId,'u'=>$actor]);crearNotificacionAtenea(['rol'=>'admin','tipo'=>'chat_reportado','categoria'=>'comunicaciones','nivel'=>'advertencia','titulo'=>'Mensaje de chat reportado','descripcion'=>'Hay un mensaje pendiente de moderación.','url'=>atenea_url('src/dashboard/comunicaciones/moderacion.php'),'idempotency_key'=>'chat:reporte:'.$mensajeId],$pdo);responderJsonExitoAtenea(['mensaje_id'=>$mensajeId]);}
 responderJsonErrorAtenea('CHAT_ACTION_INVALID','La acción solicitada no es válida.',400);
}catch(Throwable$e){responderJsonErrorAtenea('CHAT_ERROR',$e instanceof DomainException?$e->getMessage():'No fue posible completar la operación.',$e instanceof DomainException?422:500);}
