<?php
declare(strict_types=1);require_once dirname(__DIR__,2).'/includes/comunicacion_layout.php';$pdo=obtenerConexion();$actor=(int)$_SESSION['usuario_id'];$id=filter_var($_GET['id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$conversaciones=conversacionesChatAtenea($pdo,$actor);if(!$id&&$conversaciones)$id=(int)$conversaciones[0]['id'];if($id&&!chatParticipa($pdo,$id,$actor))mostrarPaginaErrorAtenea(403);$seleccionada=null;foreach($conversaciones as$c)if((int)$c['id']===$id){$seleccionada=$c;break;}
comunicacionCabecera('Chat interno','chat','Conversaciones privadas según tus relaciones académicas y administrativas.');comunicacionNav('chat');?><link rel="stylesheet" href="<?=atenea_url('src/comunicaciones/assets/chat-modern.css')?>">
<div class="chat-shell<?=$id?' has-selection':''?>" data-chat-app data-api="<?=atenea_url('src/comunicaciones/chat-api.php')?>" data-conversation="<?=$id?>" data-csrf="<?=atenea_e(obtenerTokenCsrf())?>">
<aside class="chat-sidebar"><div class="chat-sidebar-header"><div><span>Mensajería</span><h1>Conversaciones</h1></div><a class="chat-new" href="<?=atenea_url('src/comunicaciones/agenda.php')?>" aria-label="Nueva conversación" title="Nueva conversación"><i class="bi bi-pencil-square"></i></a></div><label class="chat-search"><i class="bi bi-search" aria-hidden="true"></i><span class="visually-hidden">Buscar conversaciones</span><input type="search" placeholder="Buscar conversaciones" data-chat-search autocomplete="off"></label><div class="chat-conversation-list" data-conversation-list>
<?php foreach($conversaciones as$c):?><a class="chat-conversation<?=$id===(int)$c['id']?' is-active':''?>" href="?id=<?=$c['id']?>" data-conversation-item data-id="<?=$c['id']?>" data-name="<?=atenea_e(mb_strtolower($c['contacto']))?>"><span class="chat-avatar"><img src="<?=atenea_e($c['avatar'])?>" alt="Foto de <?=atenea_e($c['contacto'])?>"><?php if($c['no_leidos']):?><span class="chat-unread-dot" aria-hidden="true"></span><?php endif;?></span><span class="chat-conversation-copy"><span class="chat-conversation-top"><strong><?=atenea_e($c['contacto'])?></strong><time><?=atenea_e($c['ultimo_mensaje_at']?date('H:i',strtotime($c['ultimo_mensaje_at'])):'')?></time></span><span class="chat-conversation-bottom"><span><?=atenea_e((string)($c['ultimo']?:$c['rol_etiqueta']))?></span><?php if($c['no_leidos']):?><b aria-label="<?=$c['no_leidos']?> mensajes no leídos"><?=$c['no_leidos']?></b><?php endif;?></span></span></a><?php endforeach;?>
<?php if(!$conversaciones):?><div class="chat-list-empty"><i class="bi bi-chat-square-text"></i><strong>No tienes conversaciones</strong><p>Abre un chat desde la agenda con una persona autorizada.</p><a href="<?=atenea_url('src/comunicaciones/agenda.php')?>">Ir a la agenda</a></div><?php endif;?></div><div class="chat-role-note"><i class="bi bi-shield-check"></i><span>Solo aparecen personas relacionadas contigo por rol, curso o administración.</span></div></aside>
<section class="chat-panel"><?php if($seleccionada):?><header class="chat-panel-header"><button class="chat-mobile-back" type="button" data-chat-back aria-label="Volver a conversaciones"><i class="bi bi-arrow-left"></i></button><img src="<?=atenea_e($seleccionada['avatar'])?>" alt="Foto de <?=atenea_e($seleccionada['contacto'])?>"><div><h2><?=atenea_e($seleccionada['contacto'])?></h2><span><?=atenea_e($seleccionada['rol_etiqueta'])?></span></div><button class="chat-header-search" type="button" data-message-search-toggle aria-label="Buscar en esta conversación"><i class="bi bi-search"></i></button></header><div class="chat-message-search" data-message-search hidden><i class="bi bi-search"></i><input type="search" placeholder="Buscar en esta conversación" data-message-search-input><button type="button" data-message-search-close aria-label="Cerrar búsqueda"><i class="bi bi-x-lg"></i></button></div>
<div class="chat-messages" data-chat-messages aria-live="polite" aria-busy="true"><button class="chat-load-older" type="button" data-load-older hidden>Cargar mensajes anteriores</button><div class="chat-loading"><span class="spinner-border" aria-hidden="true"></span><span>Cargando conversación…</span></div></div>
<div class="chat-reply-preview" data-reply-preview hidden><i class="bi bi-reply"></i><div><strong data-reply-author></strong><span data-reply-text></span></div><button type="button" data-reply-cancel aria-label="Cancelar respuesta"><i class="bi bi-x"></i></button></div><div class="chat-attachment-preview" data-attachment-preview hidden><div data-file-preview></div><button type="button" data-file-cancel aria-label="Quitar archivo"><i class="bi bi-x"></i></button></div>
<form class="chat-composer" data-chat-form enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="enviar"><input type="hidden" name="conversacion_id" value="<?=$id?>"><input type="hidden" name="respuesta_a_id" value="" data-reply-id><input type="hidden" name="idempotency_key" value="" data-idempotency><label class="chat-attach" title="Adjuntar archivo"><span class="visually-hidden">Adjuntar archivo</span><i class="bi bi-paperclip"></i><input type="file" name="adjunto" accept=".jpg,.jpeg,.png,.webp,.pdf,.doc,.docx,.txt" data-chat-file></label><textarea name="mensaje" maxlength="5000" rows="1" placeholder="Escribe un mensaje" aria-label="Mensaje" data-chat-input></textarea><button class="chat-send" type="submit" aria-label="Enviar mensaje"><i class="bi bi-send-fill" data-send-icon></i><span class="spinner-border spinner-border-sm" data-send-loading hidden></span></button></form><div class="chat-composer-help">Enter para enviar · Shift + Enter para una nueva línea · máximo 10 MB</div>
<?php else:?><div class="chat-panel-empty"><span><i class="bi bi-chat-heart"></i></span><h2>Selecciona una conversación</h2><p>Elige una persona de la lista o abre un nuevo chat desde la agenda.</p></div><?php endif;?></section></div>
<script src="<?=atenea_url('src/comunicaciones/assets/chat-modern.js')?>" defer></script><?php comunicacionPie();
