<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/comunicacion_layout.php';
$pdo=obtenerConexion();$actor=(int)$_SESSION['usuario_id'];$id=filter_var($_GET['id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$buscar=trim((string)($_GET['q']??''));
$q=$pdo->prepare("SELECT c.id,c.ultimo_mensaje_at,CONCAT(u.nombre,' ',u.apellido) contacto,u.rol,(SELECT contenido FROM chat_mensajes m WHERE m.conversacion_id=c.id AND m.estado='activo' ORDER BY m.id DESC LIMIT 1) ultimo,(SELECT COUNT(*) FROM chat_mensajes m LEFT JOIN chat_lecturas l ON l.mensaje_id=m.id AND l.usuario_id=:u1 WHERE m.conversacion_id=c.id AND m.remitente_id<>:u2 AND l.mensaje_id IS NULL) no_leidos FROM chat_conversaciones c JOIN chat_participantes p ON p.conversacion_id=c.id AND p.usuario_id=:u3 JOIN chat_participantes po ON po.conversacion_id=c.id AND po.usuario_id<>:u4 JOIN usuarios u ON u.id=po.usuario_id WHERE c.estado='activa' ORDER BY c.ultimo_mensaje_at DESC,c.id DESC");$q->execute(['u1'=>$actor,'u2'=>$actor,'u3'=>$actor,'u4'=>$actor]);$conversaciones=$q->fetchAll();if(!$id&&$conversaciones)$id=(int)$conversaciones[0]['id'];if($id&&!chatParticipa($pdo,$id,$actor)){http_response_code(403);exit('Conversación no autorizada.');}
$mensajes=[];$contacto='Selecciona una conversación';if($id){marcarChatLeido($pdo,$id,$actor);$q=$pdo->prepare("SELECT m.id,m.remitente_id,m.contenido,m.estado,m.created_at,CONCAT(u.nombre,' ',u.apellido) remitente FROM chat_mensajes m JOIN usuarios u ON u.id=m.remitente_id WHERE m.conversacion_id=:c AND (:vacio='' OR m.contenido LIKE :buscar) ORDER BY m.id DESC LIMIT 100");$q->execute(['c'=>$id,'vacio'=>$buscar,'buscar'=>'%'.$buscar.'%']);$mensajes=array_reverse($q->fetchAll());foreach($conversaciones as$c)if((int)$c['id']===$id)$contacto=$c['contacto'];}
comunicacionCabecera('Chat interno','chat','Mensajería privada de Atenea con actualización periódica.');comunicacionNav('chat');?>
<div class="row"><div class="col-lg-4"><div class="card card-rounded mb-3"><div class="card-body"><div class="list-group">
<?php foreach($conversaciones as$c):?><a class="list-group-item list-group-item-action <?=$id===(int)$c['id']?'active':''?>" href="?id=<?=$c['id']?>"><strong><?=atenea_e($c['contacto'])?></strong><?php if($c['no_leidos']):?><span class="badge bg-danger float-end"><?=$c['no_leidos']?></span><?php endif;?><small class="d-block text-truncate"><?=atenea_e((string)$c['ultimo'])?></small></a><?php endforeach;?><?php if(!$conversaciones):?><p class="text-muted">Abre un chat desde la agenda.</p><?php endif;?></div></div></div></div>
<div class="col-lg-8"><?php if($id):?><div class="card card-rounded"><div class="card-header"><h1 class="h5 mb-0"><?=atenea_e($contacto)?></h1></div><div class="card-body"><form class="mb-3"><input type="hidden" name="id" value="<?=$id?>"><input class="form-control" name="q" value="<?=atenea_e($buscar)?>" placeholder="Buscar en la conversación"></form><div id="chat-mensajes" style="max-height:480px;overflow:auto">
<?php foreach($mensajes as$m):$propio=(int)$m['remitente_id']===$actor;?><div class="p-3 mb-2 rounded <?=$propio?'bg-primary text-white ms-5':'bg-light me-5'?>"><strong><?=atenea_e($m['remitente'])?></strong><p class="mb-1" style="white-space:pre-wrap"><?=atenea_e($m['estado']==='activo'?$m['contenido']:'[Mensaje moderado]')?></p><small><?=atenea_e($m['created_at'])?></small><?php if(!$propio):?><form class="d-inline" method="post" action="chat-reporte.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="mensaje_id" value="<?=$m['id']?>"><button class="btn btn-sm btn-link">Reportar</button></form><?php endif;?></div><?php endforeach;?></div>
<form class="mt-3" method="post" action="chat-enviar.php"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="conversacion_id" value="<?=$id?>"><div class="input-group"><textarea class="form-control" name="mensaje" maxlength="5000" rows="2" required placeholder="Escribe un mensaje sin HTML"></textarea><button class="btn btn-primary">Enviar</button></div></form></div></div>
<script>let ultimo=0;setInterval(async()=>{if(document.hidden)return;const r=await fetch('chat-api.php?id=<?=$id?>',{credentials:'same-origin'});if(r.ok){const d=await r.json();if(ultimo&&d.ultimo_id>ultimo)location.reload();ultimo=d.ultimo_id;}},5000);</script><?php endif;?></div></div><?php comunicacionPie();
