<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/comunicacion_centro.php';
require_once dirname(__DIR__,2).'/includes/mailer.php';
exigirAutenticacion();
exigirComunicacionHibridaAtenea(true);
if(($_SERVER['REQUEST_METHOD']??'')!=='POST'||!validarTokenCsrf((string)($_POST['csrf_token']??''))){http_response_code(400);exit;}
$pdo=obtenerConexion();$actor=(int)$_SESSION['usuario_id'];$destino=(int)($_POST['destinatario_id']??0);$hilo=(int)($_POST['hilo_id']??0);$asunto=trim(strip_tags((string)($_POST['asunto']??'')));$texto=textoChatSeguro((string)($_POST['mensaje']??''));$adj=null;$ruta=null;
try{
 if(!contactoComunicacionPermitido($pdo,$actor,$destino))throw new DomainException('Destinatario no autorizado.');if($asunto===''||mb_strlen($asunto)>190||preg_match('/[\r\n]/',$asunto)||$texto==='')throw new DomainException('Asunto o mensaje inválido.');
 $yo=comunicacionUsuario($pdo,$actor);$contacto=comunicacionUsuario($pdo,$destino);$adj=guardarAdjuntoComunicacion('adjunto','correo');$ruta=$adj?rutaPrivadaComunicacion($adj['relpath']):null;$pdo->beginTransaction();
 if($hilo){$q=$pdo->prepare('SELECT 1 FROM correo_centro_hilos h JOIN correo_centro_mensajes m ON m.hilo_id=h.id WHERE h.id=:h AND (m.autor_usuario_id=:u OR h.usuario_relacionado_id=:u2) LIMIT 1');$q->execute(['h'=>$hilo,'u'=>$actor,'u2'=>$actor]);if(!$q->fetchColumn())throw new DomainException('El hilo no te pertenece.');$pdo->prepare('UPDATE correo_centro_hilos SET ultimo_mensaje_at=NOW() WHERE id=:h')->execute(['h'=>$hilo]);}
 else{$q=$pdo->prepare('INSERT INTO correo_centro_hilos(asunto,usuario_relacionado_id,ultimo_mensaje_at) VALUES(:a,:u,NOW())');$q->execute(['a'=>$asunto,'u'=>$destino]);$hilo=(int)$pdo->lastInsertId();}
 $q=$pdo->prepare("INSERT INTO correo_centro_mensajes(hilo_id,direccion,autor_usuario_id,remitente,destinatario,reply_to,asunto,contenido_texto,estado,enviado_recibido_at) VALUES(:h,'salida',:u,:remitente,:destino,:reply,:asunto,:mensaje,'pendiente',NOW())");$q->execute(['h'=>$hilo,'u'=>$actor,'remitente'=>MailConfig::fromEmail(),'destino'=>$contacto['correo'],'reply'=>$yo['correo'],'asunto'=>$asunto,'mensaje'=>$texto]);$mid=(int)$pdo->lastInsertId();
 if($adj)$pdo->prepare('INSERT INTO correo_centro_adjuntos(mensaje_id,archivo_relpath,archivo_nombre,archivo_mime,archivo_tamano) VALUES(:m,:r,:n,:mime,:t)')->execute(['m'=>$mid,'r'=>$adj['relpath'],'n'=>$adj['nombre'],'mime'=>$adj['mime'],'t'=>$adj['tamano']]);$pdo->commit();
 $html='<div style="font-family:Arial"><h2>'.atenea_e($asunto).'</h2><p>'.nl2br(atenea_e($texto)).'</p></div>';$clave='centro-correo:'.$mid;
 try{enviarCorreoAtenea($contacto['correo'],trim($contacto['nombre'].' '.$contacto['apellido']),$asunto,$html,$texto,['tipo'=>'centro_comunicaciones','categoria'=>'comunicaciones','usuario_id'=>$destino,'reply_to'=>$yo['correo'],'reply_to_name'=>trim($yo['nombre'].' '.$yo['apellido']),'idempotency_key'=>$clave,'attachments'=>$ruta?[['path'=>$ruta,'name'=>$adj['nombre']]]:[]]);$q=$pdo->prepare('SELECT estado FROM correo_envios WHERE idempotency_key=:k');$q->execute(['k'=>$clave]);$estadoCola=(string)$q->fetchColumn();crearNotificacionAtenea(['usuario_id'=>$destino,'created_by'=>$actor,'tipo'=>'correo_plataforma','categoria'=>'comunicaciones','nivel'=>'informacion','titulo'=>'Correo registrado desde Atenea','descripcion'=>$asunto,'url'=>atenea_url('src/comunicaciones/correo.php?vista=entrada'),'idempotency_key'=>'centro:correo:'.$mid],$pdo);$_SESSION['portal_flash']=['tipo'=>'success','mensaje'=>$estadoCola==='cancelado'?'Correo guardado sin entrega porque el modo de pruebas está activo.':'Correo guardado y añadido a la cola.'];}
 catch(Throwable $e){$pdo->prepare("UPDATE correo_centro_mensajes SET estado='fallido',error_sanitizado=:e WHERE id=:id")->execute(['e'=>sanitizarErrorCorreoAtenea($e),'id'=>$mid]);$_SESSION['portal_flash']=['tipo'=>'danger','mensaje'=>'El correo quedó registrado, pero no pudo añadirse a la cola.'];}
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();if($ruta&&is_file($ruta))unlink($ruta);$_SESSION['portal_flash']=['tipo'=>'danger','mensaje'=>$e instanceof DomainException?$e->getMessage():'No fue posible registrar el correo.'];}
header('Location:'.atenea_url('src/comunicaciones/correo.php?vista=enviados'));exit;
