<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/comunicacion_layout.php';
$pdo=obtenerConexion();$actor=(int)$_SESSION['usuario_id'];$vista=in_array($_GET['vista']??'',['entrada','enviados','no-leidos'],true)?$_GET['vista']:'entrada';$buscar=mb_substr(trim((string)($_GET['q']??'')),0,190);$yo=comunicacionUsuario($pdo,$actor);$esAdmin=esAdministracionComunicacionAtenea();
$where=$vista==='enviados'?($esAdmin?"m.direccion='salida'":"m.direccion='salida' AND m.autor_usuario_id=:u"):($esAdmin?"m.direccion='entrada'":"m.direccion='entrada' AND (h.usuario_relacionado_id=:u OR m.destinatario=:correo)");$p=[];if(!$esAdmin)$p['u']=$actor;if($vista!=='enviados'&&!$esAdmin)$p['correo']=$yo['correo'];if($vista==='no-leidos')$where.=' AND m.leido_at IS NULL';if($buscar!==''){$where.=' AND (m.asunto LIKE :q1 OR m.contenido_texto LIKE :q2 OR m.remitente LIKE :q3 OR m.destinatario LIKE :q4)';$p['q1']=$p['q2']=$p['q3']=$p['q4']='%'.$buscar.'%';}
$q=$pdo->prepare("SELECT m.*,h.asunto hilo_asunto,(SELECT COUNT(*) FROM correo_centro_adjuntos a WHERE a.mensaje_id=m.id) adjuntos FROM correo_centro_mensajes m JOIN correo_centro_hilos h ON h.id=m.hilo_id WHERE $where ORDER BY m.enviado_recibido_at DESC LIMIT 200");$q->execute($p);$mensajes=$q->fetchAll();comunicacionCabecera($vista==='enviados'?'Correos enviados':'Bandeja de entrada',$vista,'Centro de correo institucional.');comunicacionNav($vista);
?>
<div class="card card-rounded"><div class="card-body"><form class="mb-3" role="search"><input type="hidden" name="vista" value="<?=atenea_e($vista)?>"><label class="visually-hidden" for="buscar-correo">Buscar correos</label><input class="form-control" id="buscar-correo" name="q" maxlength="190" value="<?=atenea_e($buscar)?>" placeholder="Buscar por asunto, remitente o contenido"></form><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Asunto</th><th><?=$vista==='enviados'?'Destinatario':'Remitente'?></th><th>Estado</th><th>Fecha</th><th><span class="visually-hidden">Acción</span></th></tr></thead><tbody><?php foreach($mensajes as$m):?><tr><td><?=atenea_e($m['asunto'])?><?=$m['adjuntos']?' 📎':''?><small class="d-block text-muted text-truncate" style="max-width:34rem"><?=atenea_e(mb_strimwidth($m['contenido_texto'],0,100,'…'))?></small></td><td><?=atenea_e($vista==='enviados'?$m['destinatario']:$m['remitente'])?></td><td><?=atenea_e($m['estado'])?></td><td class="text-nowrap"><?=atenea_e($m['enviado_recibido_at'])?></td><td><a class="btn btn-sm btn-outline-primary" href="correo-hilo.php?id=<?=(int)$m['hilo_id']?>">Ver hilo</a></td></tr><?php endforeach;?><?php if(!$mensajes):?><tr><td colspan="5"><div class="text-center py-5"><i class="bi bi-inbox fs-1 text-muted" aria-hidden="true"></i><h2 class="h5 mt-3">No hay correos en esta vista</h2><p class="text-muted mb-0">Los mensajes sincronizados aparecerán aquí.</p></div></td></tr><?php endif;?></tbody></table></div></div></div>
<?php comunicacionPie();
