<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';require_once dirname(__DIR__,3).'/includes/newsletter.php';exigirPermiso('newsletter.manage');
if(($_SERVER['REQUEST_METHOD']??'')!=='POST'||!validarTokenCsrf((string)($_POST['csrf_token']??''))){http_response_code(400);exit;}$pdo=obtenerConexion();$accion=(string)($_POST['accion']??'');$actor=(int)$_SESSION['usuario_id'];$volver='index.php';
try{
 if($accion==='suscriptor_estado'){$id=cmsId($_POST['id']??0);$estado=in_array($_POST['estado']??'',['activo','inactivo'],true)?$_POST['estado']:'';if(!$id||!$estado)throw new DomainException('Solicitud inválida.');$q=$pdo->prepare("UPDATE newsletter_suscriptores SET estado=:estado,fecha_baja=IF(:estado2='inactivo',NOW(),NULL),fecha_suscripcion=IF(:estado3='activo',NOW(),fecha_suscripcion),token_baja=IF(:estado4='activo',:token,token_baja) WHERE id=:id");$q->execute(['estado'=>$estado,'estado2'=>$estado,'estado3'=>$estado,'estado4'=>$estado,'token'=>tokenNewsletterAtenea(),'id'=>$id]);registrarAuditoria(['actor_user_id'=>$actor,'event_type'=>'newsletter.subscriber.status_changed','module'=>'newsletter','entity_type'=>'newsletter_subscriber','entity_id'=>$id,'action'=>'change_status','result'=>'success','description'=>'Estado de suscripción actualizado.','metadata'=>['status'=>$estado]],$pdo);cmsFlash('exito','Estado del suscriptor actualizado.');}
 elseif($accion==='guardar_campana'){$id=cmsId($_POST['id']??0);$nombre=trim((string)($_POST['nombre']??''));$asunto=trim((string)($_POST['asunto']??''));$pre=trim((string)($_POST['preencabezado']??''));$contenido=trim((string)($_POST['contenido']??''));$boton=trim((string)($_POST['texto_boton']??''));$url=trim((string)($_POST['url_destino']??''));$tipo=in_array($_POST['tipo']??'',['promocion','capacitacion','actualizacion','producto','oferta','educativa'],true)?$_POST['tipo']:'actualizacion';$destino=($_POST['destino']??'')==='programada'?'programada':'borrador';$programada=trim((string)($_POST['programada_at']??''))?:date('Y-m-d H:i:s');if($programada)try{$programada=(new DateTimeImmutable($programada))->format('Y-m-d H:i:s');}catch(Throwable){throw new DomainException('Fecha de programación inválida.');}if($nombre===''||mb_strlen($nombre)>180||$asunto===''||mb_strlen($asunto)>190||$contenido===''||mb_strlen($contenido)>100000||($url!==''&&!filter_var($url,FILTER_VALIDATE_URL)))throw new DomainException('Completa nombre, asunto, contenido y una URL pública válida.');$datos=['nombre'=>$nombre,'asunto'=>$asunto,'pre'=>$pre?:null,'contenido'=>$contenido,'boton'=>$boton?:null,'url'=>$url?:null,'tipo'=>$tipo,'estado'=>$destino,'programada'=>$destino==='programada'?$programada:null,'aprobada'=>$destino==='programada'?date('Y-m-d H:i:s'):null,'aprobada_por'=>$destino==='programada'?$actor:null,'actor'=>$actor];
   if($id){$q=$pdo->prepare("UPDATE newsletter_campanas SET nombre=:nombre,asunto=:asunto,preencabezado=:pre,contenido=:contenido,texto_boton=:boton,url_destino=:url,tipo=:tipo,estado=:estado,programada_at=:programada,aprobada_at=:aprobada,aprobada_por=:aprobada_por,actualizada_por=:actor WHERE id=:id AND estado IN('borrador','programada')");$datos['id']=$id;$q->execute($datos);if($q->rowCount()!==1)throw new DomainException('La campaña ya no puede editarse.');}
   else{$q=$pdo->prepare('INSERT INTO newsletter_campanas(nombre,asunto,preencabezado,contenido,texto_boton,url_destino,tipo,estado,programada_at,aprobada_at,aprobada_por,creada_por,actualizada_por) VALUES(:nombre,:asunto,:pre,:contenido,:boton,:url,:tipo,:estado,:programada,:aprobada,:aprobada_por,:actor,:actor2)');$datos['actor2']=$actor;$q->execute($datos);$id=(int)$pdo->lastInsertId();}
   registrarAuditoria(['actor_user_id'=>$actor,'event_type'=>'newsletter.campaign.saved','module'=>'newsletter','entity_type'=>'newsletter_campaign','entity_id'=>$id,'action'=>$destino==='programada'?'approve':'save_draft','result'=>'success','description'=>$destino==='programada'?'Campaña aprobada y programada.':'Borrador de campaña guardado.'],$pdo);cmsFlash('exito',$destino==='programada'?'Campaña aprobada y programada para la cola.':'Borrador guardado.');$volver='campana.php?id='.$id;}
 elseif($accion==='cancelar_campana'){$id=cmsId($_POST['id']??0);cancelarCampanaNewsletterAtenea($id,$actor,$pdo);cmsFlash('exito','Campaña cancelada; no se crearán nuevos envíos.');}
 elseif($accion==='probar_campana'){$id=cmsId($_POST['id']??0);$q=$pdo->prepare('SELECT * FROM newsletter_campanas WHERE id=:id');$q->execute(['id'=>$id]);$c=$q->fetch();if(!$c)throw new DomainException('Campaña no encontrada.');$correo=correoDestinatarioPruebaAtenea();if($correo==='')throw new DomainException('MAIL_TEST_RECIPIENT no está configurado.');$plantilla=renderizarCampanaNewsletterAtenea($c,['token_baja'=>str_repeat('0',64)]);$clave='newsletter-test:'.$id.':'.$actor.':'.bin2hex(random_bytes(8));encolarCorreoAtenea($correo,'Prueba autorizada Atenea','[PRUEBA] '.$plantilla['subject'],$plantilla['html'],$plantilla['text'],['tipo'=>'newsletter_test','categoria'=>'novedades','evento_id'=>$clave,'idempotency_key'=>$clave,'permitir_envio_prueba'=>true]);registrarAuditoria(['actor_user_id'=>$actor,'event_type'=>'newsletter.campaign.test_queued','module'=>'newsletter','entity_type'=>'newsletter_campaign','entity_id'=>$id,'action'=>'test','result'=>'success','description'=>'Se encoló una única prueba al destinatario autorizado.'],$pdo);cmsFlash('exito','Prueba añadida a la cola para el único destinatario autorizado.');$volver='campana.php?id='.$id;}
 elseif($accion==='procesar_cola'){$r=procesarColaNewsletterAtenea(25);registrarAuditoria(['actor_user_id'=>$actor,'event_type'=>'newsletter.queue.manual_batch','module'=>'newsletter','entity_type'=>'newsletter_queue','action'=>'process_batch','result'=>'success','description'=>'Se procesó manualmente un lote limitado de newsletter.','metadata'=>$r],$pdo);cmsFlash('exito','Lote revisado: '.$r['revisados'].'. Encolados: '.$r['encolados'].'. Cancelados por modo de prueba o baja: '.$r['cancelados'].'.');}
 else throw new DomainException('Acción inválida.');
}catch(Throwable$e){error_log('Newsletter dashboard: '.sanitizarErrorCorreoAtenea($e));cmsFlash('error',$e instanceof DomainException?$e->getMessage():'No fue posible completar la operación.');}
header('Location:'.$volver);
