<?php
declare(strict_types=1);

if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
require_once dirname(__DIR__,2).'/includes/conexion.php';
require_once dirname(__DIR__,2).'/includes/config/account_lifecycle.php';
require_once dirname(__DIR__,2).'/includes/audit.php';
require_once dirname(__DIR__,2).'/includes/mailer.php';

$opciones=getopt('', ['apply-notices','apply-deactivate']);$aplicarAvisos=array_key_exists('apply-notices',$opciones);$aplicarDesactivar=array_key_exists('apply-deactivate',$opciones);$config=configuracionCicloCuentasAtenea();$mutar=$aplicarAvisos||$aplicarDesactivar;
if($mutar&&!$config['enabled']){fwrite(STDERR,"ACCOUNT_CLEANUP_ENABLED=false. No se realizaron cambios.\n");exit(2);}
$pdo=obtenerConexion();$sql="SELECT u.id,u.nombre,u.apellido,u.correo,u.rol,u.estado,u.deleted_at,u.retention_hold,u.under_investigation,GREATEST(COALESCE(u.last_activity_at,'1970-01-01'),COALESCE(u.ultimo_acceso,'1970-01-01'),COALESCE(u.updated_at,'1970-01-01'),COALESCE(u.created_at,'1970-01-01'),COALESCE((SELECT MAX(p.created_at) FROM pedidos p WHERE p.usuario_id=u.id),'1970-01-01'),COALESCE((SELECT MAX(a.created_at) FROM audit_logs a WHERE a.actor_user_id=u.id OR a.target_user_id=u.id),'1970-01-01')) inactivity_reference_at FROM usuarios u WHERE u.rol='usuario' AND u.deleted_at IS NULL AND u.retention_hold=0 AND u.under_investigation=0 AND NOT EXISTS(SELECT 1 FROM pedidos p WHERE p.usuario_id=u.id AND p.estado IN ('pendiente','esperando_pago','reembolsado')) AND NOT EXISTS(SELECT 1 FROM admin_notices n WHERE n.user_id=u.id AND n.status IN ('pendiente','visto')) ORDER BY u.id";$usuarios=$pdo->query($sql)->fetchAll();
$ahora=new DateTimeImmutable('now',new DateTimeZone('America/El_Salvador'));$reporte=['mode'=>$mutar?'apply':'dry-run','enabled'=>$config['enabled'],'evaluated'=>count($usuarios),'notice_candidates'=>array_fill_keys(array_map('strval',$config['notice_days']),0),'deactivation_candidates'=>0,'notices_created'=>0,'deactivated'=>0,'errors'=>0];
foreach($usuarios as $usuario){try{$referencia=new DateTimeImmutable((string)$usuario['inactivity_reference_at'],new DateTimeZone('America/El_Salvador'));$umbral=$referencia->modify('+'.$config['inactivity_years'].' years');$dias=(int)$ahora->diff($umbral)->format('%r%a');$ciclo=$umbral->format('Y-m-d');
foreach($config['notice_days'] as $diasAviso){if($dias<=$diasAviso&&$dias>0){$reporte['notice_candidates'][(string)$diasAviso]++;if($aplicarAvisos){$q=$pdo->prepare("INSERT IGNORE INTO account_cleanup_notifications(user_id,notice_days,cycle_key,inactivity_reference_at,status) VALUES(:user,:days,:cycle,:reference,'pendiente')");$q->execute(['user'=>$usuario['id'],'days'=>$diasAviso,'cycle'=>$ciclo,'reference'=>$usuario['inactivity_reference_at']]);if($q->rowCount()){ $nid=(int)$pdo->lastInsertId();try{enviarPlantillaCorreoAtenea('eliminacion_inactividad',(string)$usuario['correo'],trim((string)$usuario['nombre'].' '.(string)$usuario['apellido']),['mensaje'=>'Tu cuenta se aproxima al limite de inactividad. Inicia sesion antes de '.$umbral->format('d/m/Y').' para conservarla activa.'],['usuario_id'=>(int)$usuario['id'],'idempotency_key'=>'cleanup-notice:'.$usuario['id'].':'.$diasAviso.':'.$ciclo]);$pdo->prepare("UPDATE account_cleanup_notifications SET status='enviado',email_sent_at=NOW() WHERE id=:id")->execute(['id'=>$nid]);$reporte['notices_created']++;}catch(Throwable $e){$pdo->prepare("UPDATE account_cleanup_notifications SET status='fallido',error_sanitized=:error WHERE id=:id")->execute(['error'=>sanitizarErrorCorreoAtenea($e),'id'=>$nid]);$reporte['errors']++;}}}}}
if($dias<=0){$reporte['deactivation_candidates']++;if($aplicarDesactivar){$pdo->beginTransaction();$fecha=$ahora->modify('+'.$config['grace_days'].' days')->format('Y-m-d H:i:s');$pdo->prepare("UPDATE usuarios SET estado='inactivo',deleted_at=NOW(),deleted_by=NULL,deletion_reason='Inactividad prolongada',deletion_scheduled_at=:date,session_version=session_version+1 WHERE id=:id AND deleted_at IS NULL")->execute(['date'=>$fecha,'id'=>$usuario['id']]);$pdo->prepare("INSERT INTO user_deletions(user_id,requested_by,reason,status,effective_at) VALUES(:user,NULL,'Inactividad prolongada','periodo_gracia',:date)")->execute(['user'=>$usuario['id'],'date'=>$fecha]);if(!registrarAuditoria(['target_user_id'=>(int)$usuario['id'],'event_type'=>'user.inactivity_deactivated','module'=>'account_lifecycle','entity_type'=>'user','entity_id'=>$usuario['id'],'action'=>'soft_delete','result'=>'success','description'=>'El proceso programado desactivo una cuenta por inactividad prolongada.','metadata'=>['grace_days'=>$config['grace_days']]],$pdo))throw new RuntimeException('No fue posible auditar.');$pdo->commit();$reporte['deactivated']++;}}
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$reporte['errors']++;error_log('Cleanup cuenta #'.(int)$usuario['id'].': '.$e->getMessage());}}
echo json_encode($reporte,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES).PHP_EOL;
