<?php
require_once dirname(__DIR__) . '/includes/cms.php';$pdo=obtenerConexion();$id=cmsId($_GET['id']??$_POST['id']??0);$preSeccion=cmsId($_GET['seccion_id']??0);$f=['id'=>0,'seccion_id'=>$preSeccion,'titulo'=>'','subtitulo'=>'','descripcion'=>'','imagen'=>'','icono'=>'','enlace'=>'','texto_boton'=>'','activo'=>1,'orden'=>0];
if($id){$q=$pdo->prepare('SELECT * FROM elementos_seccion WHERE id=:id');$q->execute(['id'=>$id]);$f=$q->fetch()?:$f;if(!$f['id']){cmsFlash('error','El elemento no existe.');header('Location: index.php');exit;}}
$secciones=$pdo->query('SELECT id,nombre FROM secciones ORDER BY orden,id')->fetchAll();$errores=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!validarTokenCsrf($_POST['csrf_token']??null))$errores[]='El token de seguridad no es válido.';
 $seccionId=cmsId($_POST['seccion_id']??0);$titulo=trim((string)($_POST['titulo']??''));$subtitulo=trim((string)($_POST['subtitulo']??''));$descripcion=trim((string)($_POST['descripcion']??''));$icono=trim((string)($_POST['icono']??''));$enlace=trim((string)($_POST['enlace']??''));$textoBoton=trim((string)($_POST['texto_boton']??''));$orden=(int)($_POST['orden']??0);$activo=isset($_POST['activo'])?1:0;
 if(!$seccionId)$errores[]='Selecciona una sección.';if($titulo===''||mb_strlen($titulo)>255)$errores[]='El título es obligatorio y admite hasta 255 caracteres.';
 if(mb_strlen($subtitulo)>255||mb_strlen($descripcion)>5000||mb_strlen($icono)>100||mb_strlen($textoBoton)>100)$errores[]='Uno de los textos supera la longitud permitida.';
 if($icono!==''&&!preg_match('/^bi-[a-z0-9-]+$/',$icono))$errores[]='El icono debe ser una clase Bootstrap Icons como bi-star.';if(!cmsUrlValida($enlace))$errores[]='El enlace no es válido.';
 $imagen=$f['imagen'];try{$nueva=cmsSubirImagen('imagen');if($nueva)$imagen=$nueva;}catch(RuntimeException $e){$errores[]=$e->getMessage();}
 if(!$errores){try{$pdo->beginTransaction();$datos=['seccion_id'=>$seccionId,'titulo'=>$titulo,'subtitulo'=>$subtitulo,'descripcion'=>$descripcion,'imagen'=>$imagen,'icono'=>$icono,'enlace'=>$enlace,'texto_boton'=>$textoBoton,'activo'=>$activo,'orden'=>$orden];if($id){$datos['id']=$id;$q=$pdo->prepare('UPDATE elementos_seccion SET seccion_id=:seccion_id,titulo=:titulo,subtitulo=:subtitulo,descripcion=:descripcion,imagen=:imagen,icono=:icono,enlace=:enlace,texto_boton=:texto_boton,activo=:activo,orden=:orden WHERE id=:id');}else{$q=$pdo->prepare('INSERT INTO elementos_seccion(seccion_id,titulo,subtitulo,descripcion,imagen,icono,enlace,texto_boton,activo,orden) VALUES(:seccion_id,:titulo,:subtitulo,:descripcion,:imagen,:icono,:enlace,:texto_boton,:activo,:orden)');}$q->execute($datos);$pdo->commit();if($id&&$imagen!==$f['imagen'])cmsEliminarImagenSiNoSeUsa($f['imagen']);cmsFlash('exito','Elemento guardado correctamente.');header('Location: index.php?seccion_id='.$seccionId);exit;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log($e->getMessage());$errores[]='No fue posible guardar el elemento.';}}
 $f=array_merge($f,['seccion_id'=>$seccionId,'titulo'=>$titulo,'subtitulo'=>$subtitulo,'descripcion'=>$descripcion,'imagen'=>$imagen,'icono'=>$icono,'enlace'=>$enlace,'texto_boton'=>$textoBoton,'activo'=>$activo,'orden'=>$orden]);
}
cmsCabecera($id?'Editar elemento':'Agregar elemento','elementos/index.php');?>
<?php foreach($errores as $e):?><div class="alert alert-danger"><?=atenea_e($e)?></div><?php endforeach;?>
<form method="post" enctype="multipart/form-data" class="card card-rounded"><div class="card-header bg-white"><h2 class="card-title mb-1">Contenido del elemento</h2><p class="text-muted mb-0">Los campos marcados con * son obligatorios.</p></div><div class="card-body row g-3"><input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="id" value="<?=$id?>">
<div class="col-md-6"><label class="form-label">Sección <span class="required-mark">*</span></label><select class="form-select" name="seccion_id" required><option value="">Seleccionar</option><?php foreach($secciones as $s):?><option value="<?=$s['id']?>" <?=$f['seccion_id']==$s['id']?'selected':''?>><?=atenea_e($s['nombre'])?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label">Título <span class="required-mark">*</span></label><input class="form-control" name="titulo" maxlength="255" value="<?=atenea_e($f['titulo'])?>" required></div>
<div class="col-md-6"><label class="form-label">Subtítulo o categoría</label><input class="form-control" name="subtitulo" maxlength="255" value="<?=atenea_e((string)$f['subtitulo'])?>"></div><div class="col-md-6"><label class="form-label">Icono Bootstrap</label><input class="form-control" name="icono" maxlength="100" value="<?=atenea_e((string)$f['icono'])?>" placeholder="bi-star"></div><div class="col-12"><label class="form-label">Descripción</label><textarea class="form-control" rows="4" name="descripcion"><?=atenea_e((string)$f['descripcion'])?></textarea></div>
<div class="col-md-6"><label class="form-label">Enlace</label><input class="form-control" name="enlace" maxlength="500" value="<?=atenea_e((string)$f['enlace'])?>"></div><div class="col-md-6"><label class="form-label">Texto del botón</label><input class="form-control" name="texto_boton" maxlength="100" value="<?=atenea_e((string)$f['texto_boton'])?>"></div>
<div class="col-md-6"><label class="form-label">Imagen</label><input class="form-control" type="file" name="imagen" accept=".jpg,.jpeg,.png,.webp"></div><div class="col-md-3"><label class="form-label">Orden</label><input class="form-control" type="number" name="orden" value="<?=(int)$f['orden']?>"></div><div class="col-md-3 d-flex align-items-end"><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="activo" <?=$f['activo']?'checked':''?>><label class="form-check-label">Activo</label></div></div>
<?php if($f['imagen']):?><div class="col-12"><img class="preview-img" src="<?=rutaImagenContenido($f['imagen'])?>" alt="Imagen actual"></div><?php endif;?><div class="col-12"><a class="btn btn-light" href="index.php"><i class="mdi mdi-arrow-left me-1"></i>Volver</a> <a class="btn btn-outline-secondary" href="index.php">Cancelar</a> <button class="btn btn-primary text-white"><i class="mdi mdi-content-save me-1"></i>Guardar cambios</button></div></div></form><?php cmsPie();?>
