<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/cms.php';
require_once dirname(__DIR__,3).'/includes/personalizacion_visual.php';
exigirPermiso('appearance.manage');

$pdo=obtenerConexion();$areas=areasPersonalizacionVisualAtenea();$elementos=elementosPersonalizacionVisualAtenea();$usuario=obtenerUsuarioActual();
$area=(string)($_GET['area']??$_POST['area']??'website');if(!isset($areas[$area]))$area='website';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{
        if(!validarTokenCsrf((string)($_POST['csrf_token']??'')))throw new DomainException('La sesión del formulario venció. Recarga la página.');
        $accion=(string)($_POST['accion']??'publicar');if(!in_array($accion,['publicar','restaurar_original'],true))throw new DomainException('La acción solicitada no es válida.');
        $entrada=obtenerPersonalizacionVisualAtenea($area,$pdo);
        if($accion==='publicar'){
            foreach(array_keys(configuracionVisualOriginalAtenea($area))as$clave){if(array_key_exists($clave,$_POST)&&!in_array($clave,['logo','imagen_fondo','imagen_banner'],true))$entrada[$clave]=$_POST[$clave];}
            foreach(['logo','imagen_fondo','imagen_banner']as$campo){$nueva=subirImagenPersonalizacionVisualAtenea($campo);if($nueva!==null)$entrada[$campo]=$nueva;if(($_POST['quitar_'.$campo]??'')==='1')$entrada[$campo]='';}
        }
        guardarPersonalizacionVisualAtenea($area,$entrada,(int)$usuario['id'],$accion,$pdo);
        registrarAuditoria(['event_type'=>'appearance.'.($accion==='publicar'?'published':'restored'),'module'=>'appearance','entity_type'=>'visual_area','entity_id'=>$area,'action'=>$accion,'description'=>$accion==='publicar'?'Personalización visual publicada.':'Diseño visual original restaurado.','metadata'=>['area'=>$area]],$pdo);
        cmsFlash('success',$accion==='publicar'?'El diseño fue publicado y ya está disponible para los usuarios.':'El diseño original fue restaurado.');header('Location: '.atenea_url('src/dashboard/personalizacion/index.php?area='.rawurlencode($area)));exit;
    }catch(DomainException|RuntimeException $e){cmsFlash('error',$e->getMessage());}
    catch(Throwable $e){error_log('Editor visual Atenea: '.$e->getMessage());cmsFlash('error','No fue posible guardar la personalización. Intenta nuevamente.');}
}
$configuraciones=[];foreach(array_keys($areas)as$clave)$configuraciones[$clave]=obtenerPersonalizacionVisualAtenea($clave,$pdo);
$historial=[];if(tablaPersonalizacionVisualDisponible($pdo)){$historial=$pdo->query("SELECT h.*,TRIM(CONCAT(COALESCE(u.nombre,''),' ',COALESCE(u.apellido,''))) administrador FROM personalizaciones_visuales_historial h LEFT JOIN usuarios u ON u.id=h.realizado_por ORDER BY h.id DESC LIMIT 200")->fetchAll();}
cmsCabecera('Editor visual','personalizacion/index.php','Personaliza los portales de Atenea mediante controles seguros y una vista previa inmediata.');
?>
<link rel="stylesheet" href="<?=atenea_url('src/dashboard/personalizacion/editor.css')?>">
<div class="alert alert-info d-flex align-items-start gap-2" role="status"><i class="mdi mdi-shield-check fs-4"></i><div><strong>Editor protegido.</strong> Solo admite valores visuales e imágenes validadas. No acepta PHP, JavaScript, SQL ni estilos escritos manualmente.</div></div>
<form method="post" enctype="multipart/form-data" id="visualEditorForm" class="visual-editor">
<input type="hidden" name="csrf_token" value="<?=atenea_e(obtenerTokenCsrf())?>"><input type="hidden" name="accion" value="publicar"><input type="hidden" name="area" id="visualAreaHidden" value="<?=atenea_e($area)?>">
<div class="row g-4"><div class="col-xl-4"><section class="card card-rounded visual-controls-card"><div class="card-body">
<label class="form-label fw-bold" for="visualArea">Área a editar</label><select class="form-select mb-3" id="visualArea"><?php foreach($areas as$clave=>$etiqueta):?><option value="<?=atenea_e($clave)?>" <?=$area===$clave?'selected':''?>><?=atenea_e($etiqueta)?></option><?php endforeach;?></select>
<label class="form-label fw-bold" for="visualElement">Elemento</label><select class="form-select mb-4" id="visualElement"><?php foreach($elementos as$clave=>$etiqueta):?><option value="<?=atenea_e($clave)?>"><?=atenea_e($etiqueta)?></option><?php endforeach;?></select>
<div class="visual-control-group" data-control-elements="general"><h2 class="h6">Colores generales</h2><?php foreach(['color_principal'=>'Color principal','color_secundario'=>'Color secundario','color_fondo'=>'Fondo']as$clave=>$etiqueta):?><label class="visual-color-field"><span><?=$etiqueta?></span><input type="color" name="<?=$clave?>" data-setting="<?=$clave?>"></label><?php endforeach;?><label class="form-label mt-3" for="imagen_fondo">Imagen de fondo</label><input class="form-control" id="imagen_fondo" name="imagen_fondo" type="file" accept=".jpg,.jpeg,.png,.webp" data-image-setting="imagen_fondo"><label class="form-check mt-2"><input class="form-check-input" type="checkbox" name="quitar_imagen_fondo" value="1"><span class="form-check-label">Quitar imagen publicada</span></label><label class="form-label mt-3" for="logo">Logo</label><input class="form-control" id="logo" name="logo" type="file" accept=".jpg,.jpeg,.png,.webp" data-image-setting="logo"><label class="form-check mt-2"><input class="form-check-input" type="checkbox" name="quitar_logo" value="1"><span class="form-check-label">Usar logo original</span></label></div>
<div class="visual-control-group" data-control-elements="tipografia" hidden><h2 class="h6">Tipografía</h2><label class="form-label" for="tipografia">Fuente permitida</label><select class="form-select" id="tipografia" name="tipografia" data-setting="tipografia"><?php foreach(fuentesPersonalizacionVisualAtenea()as$fuente):?><option><?=atenea_e($fuente)?></option><?php endforeach;?></select><label class="form-label mt-3" for="tamano_texto">Tamaño base: <output data-output="tamano_texto">16 px</output></label><input class="form-range" id="tamano_texto" name="tamano_texto" type="range" min="12" max="20" data-setting="tamano_texto"><label class="form-label" for="espaciado">Espaciado: <output data-output="espaciado">1</output></label><input class="form-range" id="espaciado" name="espaciado" type="range" min="0.75" max="1.5" step="0.05" data-setting="espaciado"></div>
<div class="visual-control-group" data-control-elements="botones" hidden><h2 class="h6">Botones</h2><label class="visual-color-field"><span>Color de botones</span><input type="color" name="color_botones" data-setting="color_botones"></label></div>
<div class="visual-control-group" data-control-elements="tarjetas" hidden><h2 class="h6">Tarjetas y bordes</h2><label class="form-label" for="tarjetas">Apariencia</label><select class="form-select" id="tarjetas" name="tarjetas" data-setting="tarjetas"><option value="plana">Plana</option><option value="borde">Con borde</option><option value="sombra">Con sombra</option></select><label class="form-label mt-3" for="bordes">Redondeado: <output data-output="bordes">12 px</output></label><input class="form-range" id="bordes" name="bordes" type="range" min="0" max="24" data-setting="bordes"></div>
<?php foreach(['navbar'=>'Navbar','sidebar'=>'Sidebar','footer'=>'Pie de página']as$elemento=>$etiqueta):?><div class="visual-control-group" data-control-elements="<?=$elemento?>" hidden><h2 class="h6"><?=$etiqueta?></h2><label class="visual-color-field"><span>Color de fondo</span><input type="color" name="color_<?=$elemento?>" data-setting="color_<?=$elemento?>"></label></div><?php endforeach;?>
<div class="visual-control-group" data-control-elements="banner" hidden><h2 class="h6">Banner</h2><label class="visual-color-field"><span>Color de fondo</span><input type="color" name="color_banner" data-setting="color_banner"></label><label class="form-label mt-3" for="imagen_banner">Imagen del banner</label><input class="form-control" id="imagen_banner" name="imagen_banner" type="file" accept=".jpg,.jpeg,.png,.webp" data-image-setting="imagen_banner"><label class="form-check mt-2"><input class="form-check-input" type="checkbox" name="quitar_imagen_banner" value="1"><span class="form-check-label">Quitar imagen publicada</span></label></div>
</div></section></div><div class="col-xl-8"><section class="card card-rounded"><div class="card-body"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-1">Vista previa inmediata</h2><p class="small text-muted mb-0">Haz clic en navbar, menú, banner, tarjeta, botón o pie para editarlo.</p></div><span class="badge bg-light text-dark" id="previewAreaLabel"></span></div>
<div class="visual-preview" id="visualPreview" data-preview-target="general" tabindex="0" aria-label="Vista previa del diseño"><header class="preview-navbar" data-preview-target="navbar"><div class="preview-logo" data-preview-target="general"><img alt="Logo de Atenea" id="previewLogo"><strong>Atenea</strong></div><span>Inicio &nbsp; Cursos &nbsp; Perfil</span></header><div class="preview-layout"><aside class="preview-sidebar" data-preview-target="sidebar"><strong>Menú</strong><span>Inicio</span><span>Contenidos</span><span>Mensajes</span></aside><main class="preview-main"><section class="preview-banner" data-preview-target="banner"><small>Bienvenido a</small><h3>Escuela Atenea</h3><p>Formación y bienestar holístico</p></section><div class="preview-grid"><article class="preview-card" data-preview-target="tarjetas"><h4>Contenido destacado</h4><p>Comprueba tipografía, espacios, bordes y contraste.</p><button type="button" class="preview-button" data-preview-target="botones">Acción principal</button></article><article class="preview-card" data-preview-target="tarjetas"><h4>Próxima actividad</h4><p>Los cambios no son públicos hasta guardar.</p></article></div></main></div><footer class="preview-footer" data-preview-target="footer">Atenea Escuela de Naturopatía Holística</footer></div>
</div></section><div class="d-flex flex-wrap gap-2 mt-3"><button class="btn btn-primary" type="submit" data-atenea-loading>Guardar y publicar</button><button class="btn btn-outline-secondary" type="button" id="visualCancel">Cancelar cambios</button><button class="btn btn-outline-danger ms-lg-auto" type="submit" name="accion" value="restaurar_original" data-atenea-confirm="restore" data-atenea-confirm-title="¿Restaurar diseño original?" data-atenea-confirm-message="Se reemplazará la personalización publicada del área seleccionada.">Restaurar diseño original</button></div></div></div></form>
<section class="card card-rounded mt-4"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Historial de cambios: <span id="visualHistoryArea"><?=atenea_e($areas[$area])?></span></h2><span class="text-muted small">Registros recientes</span></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Fecha</th><th>Acción</th><th>Versión</th><th>Administrador</th></tr></thead><tbody id="visualHistoryBody"><?php foreach($historial as$registro):?><tr data-history-area="<?=atenea_e($registro['area'])?>" <?=$registro['area']===$area?'':'hidden'?>> <td><?=atenea_e(date('d/m/Y H:i',strtotime((string)$registro['created_at'])))?></td><td><span class="badge <?=$registro['accion']==='publicar'?'bg-success':'bg-secondary'?>"><?=atenea_e($registro['accion']==='publicar'?'Publicación':'Restauración original')?></span></td><td>v<?=number_format((int)$registro['version'])?></td><td><?=atenea_e($registro['administrador']?:'Cuenta no disponible')?></td></tr><?php endforeach;?><tr id="visualHistoryEmpty"><td colspan="4" class="text-center text-muted py-5">Todavía no hay cambios publicados para esta área.</td></tr></tbody></table></div></div></section>
<script type="application/json" id="visualEditorData"><?=json_encode(['areas'=>$areas,'configuraciones'=>$configuraciones,'baseUrl'=>ATENEA_BASE_URL],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_THROW_ON_ERROR)?></script><script src="<?=atenea_url('src/dashboard/personalizacion/editor.js')?>" defer></script>
<?php cmsPie();
