<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/auth.php';require_once dirname(__DIR__,2).'/includes/audit.php';exigirRol(['usuario']);$retorno=atenea_url('src/estudiantes/perfil.php?completar=1');
if(($_SERVER['REQUEST_METHOD']??'')!=='POST'||!validarTokenCsrf((string)($_POST['csrf_token']??''))){$_SESSION['google_perfil_errores']=['La solicitud expiró. Intenta nuevamente.'];header('Location: '.$retorno);exit;}
$id=(int)$_SESSION['usuario_id'];$perfil=obtenerPerfilUsuario($id);if(!$perfil||empty($perfil['google_id'])||($perfil['perfil_estado']??'completo')!=='pendiente'){header('Location: '.rutaPanelPorRol('usuario'));exit;}
$nombre=trim(strip_tags((string)($_POST['nombre']??'')));$apellido=trim(strip_tags((string)($_POST['apellido']??'')));$fecha=trim((string)($_POST['fecha_nacimiento']??''));$dui=normalizarDui((string)($_POST['dui']??''));$codigo=normalizarCodigoTelefono((string)($_POST['codigo_telefono']??''));$telefono=normalizarTelefono((string)($_POST['telefono']??''));$departamento=filter_var($_POST['departamento_id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$municipio=filter_var($_POST['municipio_id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$distrito=filter_var($_POST['distrito_id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$direccion=trim(strip_tags((string)($_POST['direccion']??'')));$terminos=($_POST['terminos']??'')==='1';$errores=[];
if($nombre===''||mb_strlen($nombre)>100)$errores[]='Ingresa nombres válidos.';if($apellido===''||mb_strlen($apellido)>100)$errores[]='Ingresa apellidos válidos.';if(!fechaNacimientoValida($fecha))$errores[]='Ingresa una fecha de nacimiento válida.';if(!$dui)$errores[]='El DUI debe usar el formato 00000000-0.';if(!telefonoValido($codigo,$telefono))$errores[]='Ingresa un teléfono válido con su prefijo.';if(mb_strlen($direccion)<8||mb_strlen($direccion)>500)$errores[]='Ingresa una dirección completa de 8 a 500 caracteres.';if(!$terminos)$errores[]='Debes aceptar los términos y condiciones.';
$datos=['nombre'=>$nombre,'apellido'=>$apellido,'fecha_nacimiento'=>$fecha,'dui'=>$dui?:'','codigo_telefono'=>$codigo,'telefono'=>$telefono,'departamento_id'=>$departamento,'municipio_id'=>$municipio,'distrito_id'=>$distrito,'direccion'=>$direccion];
try{$pdo=obtenerConexion();if(!$departamento||!$municipio||!$distrito||!ubicacionValida($pdo,$departamento,$municipio,$distrito))$errores[]='Selecciona un departamento, municipio y distrito válidos.';if($dui){$q=$pdo->prepare('SELECT id FROM usuarios WHERE dui=:dui AND id<>:id LIMIT 1');$q->execute(['dui'=>$dui,'id'=>$id]);if($q->fetch())$errores[]='Ese DUI ya está registrado.';}if($errores){$_SESSION['google_perfil_errores']=array_values(array_unique($errores));$_SESSION['google_perfil_datos']=$datos;header('Location: '.$retorno);exit;}$pdo->beginTransaction();$q=$pdo->prepare("UPDATE usuarios SET nombre=:nombre,apellido=:apellido,fecha_nacimiento=:fecha,dui=:dui,codigo_telefono=:codigo,telefono=:telefono,departamento_id=:departamento,municipio_id=:municipio,distrito_id=:distrito,direccion=:direccion,terminos_aceptados_at=NOW(),perfil_estado='completo',last_activity_at=NOW() WHERE id=:id AND perfil_estado='pendiente'");$q->execute(['nombre'=>$nombre,'apellido'=>$apellido,'fecha'=>$fecha,'dui'=>$dui,'codigo'=>$codigo,'telefono'=>$telefono,'departamento'=>$departamento,'municipio'=>$municipio,'distrito'=>$distrito,'direccion'=>$direccion,'id'=>$id]);if($q->rowCount()!==1)throw new RuntimeException('El perfil ya fue procesado.');registrarAuditoria(['actor_user_id'=>$id,'target_user_id'=>$id,'event_type'=>'auth.google_profile_completed','module'=>'auth','entity_type'=>'user','entity_id'=>$id,'action'=>'complete_profile','result'=>'success','description'=>'Se completó el perfil obligatorio de una cuenta registrada con Google.'],$pdo);$pdo->commit();$actualizado=obtenerPerfilUsuario($id);if(!$actualizado||!datosPerfilCompletos($actualizado))throw new RuntimeException('El perfil no quedó completo.');iniciarSesionUsuario($actualizado);unset($_SESSION['google_perfil_errores'],$_SESSION['google_perfil_datos']);$_SESSION['portal_flash']=['tipo'=>'success','titulo'=>'Perfil completado','mensaje'=>'Tu cuenta ya está habilitada.'];header('Location: '.atenea_url('src/estudiantes/index.php'));exit;}catch(Throwable$e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();error_log('Completar perfil Google Atenea: '.$e->getMessage());$_SESSION['google_perfil_errores']=['No fue posible completar el perfil. Intenta nuevamente.'];$_SESSION['google_perfil_datos']=$datos;header('Location: '.$retorno);exit;}
