<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/auth.php';
require_once dirname(__DIR__,2).'/includes/audit.php';
if(($_SERVER['REQUEST_METHOD']??'')!=='POST'){header('Location: '.atenea_url('src/login/sign-in.php'));exit;}
$now=time();$tries=array_values(array_filter(is_array($_SESSION['login_intentos']??null)?$_SESSION['login_intentos']:[],fn($t)=>is_int($t)&&$t>$now-300));
if(count($tries)>=5){registrarAuditoria(['event_type'=>'auth.login_rate_limited','module'=>'auth','action'=>'login','result'=>'blocked','description'=>'Se bloqueo temporalmente un inicio de sesion por exceso de intentos.']);$_SESSION['mensaje_auth']='Demasiados intentos. Espera unos minutos antes de volver a intentarlo.';header('Location: '.atenea_url('src/login/sign-in.php'));exit;}
$correo=strtolower(trim((string)($_POST['correo']??'')));$password=(string)($_POST['password']??'');$_SESSION['login_correo']=substr($correo,0,190);
if(!validarTokenCsrf(isset($_POST['csrf_token'])?(string)$_POST['csrf_token']:null)){registrarAuditoria(['event_type'=>'auth.login_failed','module'=>'auth','action'=>'login','result'=>'failure','description'=>'Fallo un inicio de sesion por token CSRF invalido.']);$_SESSION['mensaje_auth']='La solicitud expiro. Intenta nuevamente.';header('Location: '.atenea_url('src/login/sign-in.php'));exit;}
try{$pdo=obtenerConexion();$q=$pdo->prepare('SELECT id,nombre,apellido,correo,password,rol,foto,estado,deleted_at,session_version,fecha_nacimiento,dui,codigo_telefono,telefono,departamento_id,municipio_id,distrito_id FROM usuarios WHERE correo=:correo LIMIT 1');$q->execute(['correo'=>$correo]);$u=$q->fetch();
$hash=is_array($u)?(string)($u['password']??''):'';$legacy=$hash!==''&&preg_match('/^[a-f0-9]{40}$/i',$hash)===1;$passwordValido=$legacy?hash_equals(strtolower($hash),sha1($password)):($hash!==''&&password_verify($password,$hash));
$ok=is_array($u)&&$u['estado']==='activo'&&empty($u['deleted_at'])&&$passwordValido;
if(!$ok){$tries[]=$now;$_SESSION['login_intentos']=$tries;registrarAuditoria(['target_user_id'=>is_array($u)?(int)$u['id']:null,'event_type'=>'auth.login_failed','module'=>'auth','entity_type'=>is_array($u)?'user':null,'entity_id'=>is_array($u)?(int)$u['id']:null,'action'=>'login','result'=>'failure','description'=>'Fallo un inicio de sesion por credenciales o estado de cuenta no validos.']);$_SESSION['mensaje_auth']='El correo o la contrasena no son correctos.';header('Location: '.atenea_url('src/login/sign-in.php'));exit;}
$pdo->beginTransaction();$nuevoHash=$legacy||password_needs_rehash($hash,PASSWORD_DEFAULT)?password_hash($password,PASSWORD_DEFAULT):null;$sql='UPDATE usuarios SET ultimo_acceso=NOW(),last_activity_at=NOW()'.($nuevoHash!==null?',password=:password':'').' WHERE id=:id';$params=['id'=>(int)$u['id']];if($nuevoHash!==null)$params['password']=$nuevoHash;$pdo->prepare($sql)->execute($params);registrarAuditoria(['actor_user_id'=>(int)$u['id'],'target_user_id'=>(int)$u['id'],'event_type'=>'auth.login_success','module'=>'auth','entity_type'=>'user','entity_id'=>(int)$u['id'],'action'=>'login','result'=>'success','description'=>'Inicio de sesion exitoso.','metadata'=>['credential_upgraded'=>$nuevoHash!==null]],$pdo);$pdo->commit();
iniciarSesionUsuario($u);redirigirPorRol((string)$u['rol']);
}catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();error_log('Login Atenea: '.$e->getMessage());$_SESSION['mensaje_auth']='No fue posible iniciar sesion en este momento.';header('Location: '.atenea_url('src/login/sign-in.php'));exit;}
