<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/includes/auth.php';
require_once dirname(__DIR__,2).'/includes/audit.php';
require_once dirname(__DIR__,2).'/includes/notificaciones.php';
require_once dirname(__DIR__,2).'/includes/mailer.php';
require_once dirname(__DIR__,2).'/includes/carrito.php';
if(($_SERVER['REQUEST_METHOD']??'')!=='POST'){header('Location:'.atenea_url('src/login/sign-in.php'));exit;}
$now=time();$tries=array_values(array_filter(is_array($_SESSION['login_intentos']??null)?$_SESSION['login_intentos']:[],fn($t)=>is_int($t)&&$t>$now-300));
if(count($tries)>=5){registrarAuditoria(['event_type'=>'auth.login_rate_limited','module'=>'auth','action'=>'login','result'=>'blocked','description'=>'Se bloqueó temporalmente un inicio de sesión por exceso de intentos.']);$_SESSION['mensaje_auth']='Demasiados intentos. Espera unos minutos antes de volver a intentarlo.';header('Location:'.atenea_url('src/login/sign-in.php'));exit;}
$correo=strtolower(trim((string)($_POST['correo']??'')));$password=(string)($_POST['password']??'');$recordar=($_POST['recordar']??'')==='1';$_SESSION['login_correo']=mb_substr($correo,0,190);
if(!validarTokenCsrf((string)($_POST['csrf_token']??''))){registrarAuditoria(['event_type'=>'auth.login_failed','module'=>'auth','action'=>'login','result'=>'failure','description'=>'Falló un inicio de sesión por token CSRF inválido.']);$_SESSION['mensaje_auth']='La solicitud expiró. Intenta nuevamente.';header('Location:'.atenea_url('src/login/sign-in.php'));exit;}
try{
 $pdo=obtenerConexion();$q=$pdo->prepare('SELECT id,nombre,apellido,correo,password,google_id,proveedor,rol,foto,estado,deleted_at,session_version,perfil_estado,terminos_aceptados_at,fecha_nacimiento,dui,codigo_telefono,telefono,departamento_id,municipio_id,distrito_id,direccion FROM usuarios WHERE correo=:correo LIMIT 1');$q->execute(['correo'=>$correo]);$u=$q->fetch();$hash=is_array($u)?(string)($u['password']??''):'';$legacy=$hash!==''&&preg_match('/^[a-f0-9]{40}$/i',$hash)===1;$passwordValido=$legacy?hash_equals(strtolower($hash),sha1($password)):password_verify($password,$hash!==''?$hash:'$2y$10$0mWZJk3w6oPqQHPZo0XgDOZP4V6Q4oC6XfQyTnP5Zx.PJQpvE4XXK');$ok=is_array($u)&&$u['estado']==='activo'&&empty($u['deleted_at'])&&$passwordValido;
 if(!$ok){$tries[]=$now;$_SESSION['login_intentos']=$tries;registrarAuditoria(['target_user_id'=>is_array($u)?(int)$u['id']:null,'event_type'=>'auth.login_failed','module'=>'auth','entity_type'=>is_array($u)?'user':null,'entity_id'=>is_array($u)?(int)$u['id']:null,'action'=>'login','result'=>'failure','description'=>'Falló un inicio de sesión por credenciales o estado de cuenta no válidos.']);
  if(is_array($u)&&count($tries)===3){$evento='seguridad:intentos-login:'.$u['id'].':'.date('YmdHi',(int)(floor($now/300)*300));crearNotificacionAtenea(['usuario_id'=>(int)$u['id'],'tipo'=>'inicio_sesion_sospechoso','categoria'=>'seguridad','nivel'=>'advertencia','titulo'=>'Detectamos intentos de acceso','descripcion'=>'Se registraron varios intentos fallidos recientes. Si no fuiste tú, cambia tu contraseña.','url'=>atenea_url('src/login/forgot-password.php'),'idempotency_key'=>$evento],$pdo);$html='<div style="font-family:Arial,sans-serif"><h2>Alerta de seguridad</h2><p>Detectamos varios intentos fallidos recientes para acceder a tu cuenta Atenea.</p><p>Si no reconoces esta actividad, cambia tu contraseña.</p></div>';enviarCorreoAtenea((string)$u['correo'],trim($u['nombre'].' '.$u['apellido']),'Alerta de seguridad de tu cuenta Atenea',$html,'Detectamos varios intentos fallidos recientes. Si no reconoces esta actividad, cambia tu contraseña.',['tipo'=>'inicio_sesion_sospechoso','categoria'=>'seguridad','usuario_id'=>(int)$u['id'],'evento_id'=>$evento,'idempotency_key'=>$evento]);}
  $_SESSION['mensaje_auth']='El correo o la contraseña no son correctos.';header('Location:'.atenea_url('src/login/sign-in.php'));exit;}
 $pdo->beginTransaction();$nuevoHash=$legacy||password_needs_rehash($hash,PASSWORD_DEFAULT)?password_hash($password,PASSWORD_DEFAULT):null;$sql='UPDATE usuarios SET ultimo_acceso=NOW(),last_activity_at=NOW()'.($nuevoHash!==null?',password=:password':'').' WHERE id=:id';$params=['id'=>(int)$u['id']];if($nuevoHash!==null)$params['password']=$nuevoHash;$pdo->prepare($sql)->execute($params);
 $pendiente=is_array($_SESSION['google_vinculacion_pendiente']??null)?$_SESSION['google_vinculacion_pendiente']:null;if($pendiente&&(int)($pendiente['expira']??0)>=time()&&hash_equals((string)$u['correo'],(string)($pendiente['correo']??''))){$google=(string)($pendiente['google_id']??'');$q=$pdo->prepare('SELECT id FROM usuarios WHERE google_id=:g AND id<>:id LIMIT 1');$q->execute(['g'=>$google,'id'=>$u['id']]);if($google!==''&&!$q->fetch()){$pdo->prepare("UPDATE usuarios SET google_id=:g,proveedor='mixto',email_verificado=1 WHERE id=:id")->execute(['g'=>$google,'id'=>$u['id']]);$u['google_id']=$google;$u['proveedor']='mixto';registrarAuditoria(['actor_user_id'=>(int)$u['id'],'target_user_id'=>(int)$u['id'],'event_type'=>'auth.google_linked_after_password','module'=>'auth','entity_type'=>'user','entity_id'=>(int)$u['id'],'action'=>'link','result'=>'success','description'=>'Se vinculó Google después de validar la contraseña local.'],$pdo);}}
 unset($_SESSION['google_vinculacion_pendiente']);registrarAuditoria(['actor_user_id'=>(int)$u['id'],'target_user_id'=>(int)$u['id'],'event_type'=>'auth.login_success','module'=>'auth','entity_type'=>'user','entity_id'=>(int)$u['id'],'action'=>'login','result'=>'success','description'=>'Inicio de sesión exitoso.','metadata'=>['credential_upgraded'=>$nuevoHash!==null]],$pdo);$pdo->commit();iniciarSesionUsuario($u);if($recordar)crearTokenRecuerdoAtenea($pdo,(int)$u['id'],(int)$u['session_version']);else revocarTokenRecuerdoActualAtenea($pdo);if((string)$u['rol']==='usuario')try{sincronizarCarritoInvitadoAtenea($pdo,(int)$u['id']);}catch(Throwable $syncError){error_log('Sincronización de carrito Atenea: '.$syncError->getMessage());}redirigirPorRol((string)$u['rol']);
}catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();registrarFalloGlobalAtenea($e,500);$_SESSION['mensaje_auth']='No fue posible iniciar sesión en este momento.';header('Location:'.atenea_url('src/login/sign-in.php'));exit;}
